/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "IdealFluid_CTS_lib.h"


void Tij_IF_CTS_psi6E(Patch_T *const patch)
{
  if (!IsItNSPatch(patch))
    return;
  const unsigned nn = patch->nn;
  unsigned ijk;

  /* declaring: */
  GET_FIELD(enthalpy)
  GET_FIELD(eta)
  GET_FIELD(u0)
  GET_FIELD(psi)
  GET_FIELD(rho0)
  PREP_FIELD(_E)


  EoS_T *eos = initialize_EoS();
  for(ijk = 0; ijk < nn; ++ijk)
  {
    eos->h   = enthalpy[ijk];
    double p = eos->pressure(eos);
    double alpha = 
eta[ijk]/psi[ijk];

    double psi6 = 
pow(psi[ijk], 6);

    double Ebar = 
psi6*(pow(alpha, 2)*enthalpy[ijk]*rho0[ijk]*pow(u0[ijk], 2) -
p);

  _E[ijk] = Ebar;
  }
  free_EoS(eos);
}
