/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "Tij_header.h"


void Tij_NS_IF_XCTS_gConf_derives(Patch_T *const patch);
void Tij_NS_IF_XCTS_gConf_derives(Patch_T *const patch)
{


  /* declaring: */
  dField_di(denthalpy_D2);
  dField_di(denthalpy_D0);
  dField_di(denthalpy_D1);
  dField_di(du0_D0);
  dField_di(du0_D1);
  dField_di(du0_D2);
  dField_di(drho0_D2);
  dField_di(drho0_D0);
  dField_di(drho0_D1);


}
