/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "Tij_header.h"


void Tij_IF_CTS_nonflat_derives(Patch_T *const patch);
void Tij_IF_CTS_nonflat_derives(Patch_T *const patch)
{


  /* declaring: */
  partial_derivative(denthalpy_D2)
  partial_derivative(denthalpy_D0)
  partial_derivative(denthalpy_D1)
  partial_derivative(du0_D0)
  partial_derivative(du0_D1)
  partial_derivative(du0_D2)
  partial_derivative(drho0_D2)
  partial_derivative(drho0_D0)
  partial_derivative(drho0_D1)


}
