/*
  These C codes generated by Cpi version 3.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "poisson0_headers.h"
#include "maths_equation_solvings_lib.h"
#include "poisson0_equations_lib.h"


void *eq_alpha(void *vp1,void *vp2)
{
  DDM_SCHUR_EQ_DECLARE
  Uint ijk;/* node index */
  DECLARE_FIELD(alpha)
  double *alpha_xx = Partial_Derivative(alpha,"x,x");
  double *alpha_yy = Partial_Derivative(alpha,"y,y");
  double *alpha_zz = Partial_Derivative(alpha,"z,z");

  DDM_SCHUR_EQ_OPEN

  double x = patch->node[ijk]->x[0];
  double y = patch->node[ijk]->x[1];
  double z = patch->node[ijk]->x[2];
  double F_eq =
alpha_xx[ijk] + alpha_yy[ijk] + alpha_zz[ijk] + 3.0*pow(pow(x, 2) +
pow(y, 2) + pow(z, 2) + 1, -2.5);

  F[schur_ijk] = F_eq;

  DDM_SCHUR_EQ_CLOSE

  free(alpha_xx);
  free(alpha_yy);
  free(alpha_zz);

  return 0;
}
