/*
  These C codes generated by Cpi version 3.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "poisson0_headers.h"
#include "maths_equation_solvings_lib.h"
#include "poisson0_equations_lib.h"


void *bc_alpha(void *vp1,void *vp2)
{
  DDM_SCHUR_BC_DECLARE
  Uint ijk;/* node index */
  READ_v(alpha)
  if (patch->outerB)/* at outer boundary */
  {
  DDM_SCHUR_BC_OPEN
  double x = patch->node[ijk]->x[0];
  double y = patch->node[ijk]->x[1];
  double z = patch->node[ijk]->x[2];
  double outerB_F =
alpha[ijk] - pow(pow(x, 2) + pow(y, 2) + pow(z, 2) + 1, -
0.5);

  schur_F[schur_ijk] = outerB_F;
  DDM_SCHUR_BC_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)/* at inner boundary */
  {
  DDM_SCHUR_BC_OPEN
  double x = patch->node[ijk]->x[0];
  double y = patch->node[ijk]->x[1];
  double z = patch->node[ijk]->x[2];
  double innerB_F =
alpha[ijk] - pow(pow(x, 2) + pow(y, 2) + pow(z, 2) + 1, -
0.5);

  schur_F[schur_ijk] = innerB_F;
  DDM_SCHUR_BC_CLOSE
  }/* end of else if (patch->innerB) */
  return 0;
}
