/*
  These C codes generated by Cpi version 3.0
  Copyright (C) 2019-2023 Alireza Rashti.
*/


#include "adm_header.h"
#include "maths_linear_algebra_lib.h"




#define add_and_alloc_with_stem(xNAME,stem) \
 char field__name__##xNAME[99] = {'\0'};\
 const char *const field__index__##xNAME   = strrchr(#xNAME,'_');\
 if (field__index__##xNAME) {sprintf(field__name__##xNAME,"%s%s",stem,field__index__##xNAME);}\
 else                       {sprintf(field__name__##xNAME,"%s"  ,stem);}\
 add_field(field__name__##xNAME,0,patch,YES);



#define add_field_get_v(name) ADD_AND_ALLOC_FIELD(name); WRITE_v(name);


#define add_dfield_and_get_v(name) ADD_FIELD(name); dField_di(name); READ_v_UNUSED(name);

#define Compute_Christoffel(name)  \
  Christoffel_symbol_3d(patch,"adm_ig","dadm_g","Gamma");


extern fFunc_adm_update_adm_KIJ_T (*adm_update_adm_KIJ_patch);
void adm_ham_and_mom_from_scratch(Patch_T *const patch,
        const char *const Ham,const char *const Mom);

void adm_ham_and_mom_from_scratch(Patch_T *const patch,
        const char *const Ham,const char *const Mom)
{

  adm_update_adm_KIJ_patch(patch);
  adm_update_adm_g_patch(patch);

{
    READ_v(adm_g_D2D2)
    READ_v(adm_g_D0D2)
    READ_v(adm_g_D0D0)
    READ_v(adm_g_D0D1)
    READ_v(adm_g_D1D2)
    READ_v(adm_g_D1D1)

    add_field_get_v(adm_ig_U2U2)
    add_field_get_v(adm_ig_U0U2)
    add_field_get_v(adm_ig_U0U0)
    add_field_get_v(adm_ig_U0U1)
    add_field_get_v(adm_ig_U1U2)
    add_field_get_v(adm_ig_U1U1)

    FOR_ALL_ijk
    {
      Matrix_Inverse_3x3_Symmetric_Field(adm_g,D,adm_ig,U,ijk);
    }
}

  REALLOC_v_WRITE_v_STEM(ham,Ham)
  REALLOC_v_WRITE_v_STEM(mom_U0,Mom)
  REALLOC_v_WRITE_v_STEM(mom_U1,Mom)
  REALLOC_v_WRITE_v_STEM(mom_U2,Mom)
  READ_v(adm_KIJ_U0U0)
  READ_v(adm_KIJ_U0U1)
  READ_v(adm_KIJ_U0U2)
  READ_v(adm_KIJ_U1U1)
  READ_v(adm_KIJ_U1U2)
  READ_v(adm_KIJ_U2U2)
  add_dfield_and_get_v(dadm_KIJ_U0U0D0)
  add_dfield_and_get_v(dadm_KIJ_U0U0D1)
  add_dfield_and_get_v(dadm_KIJ_U0U0D2)
  add_dfield_and_get_v(dadm_KIJ_U0U1D0)
  add_dfield_and_get_v(dadm_KIJ_U0U1D1)
  add_dfield_and_get_v(dadm_KIJ_U0U1D2)
  add_dfield_and_get_v(dadm_KIJ_U0U2D0)
  add_dfield_and_get_v(dadm_KIJ_U0U2D1)
  add_dfield_and_get_v(dadm_KIJ_U0U2D2)
  add_dfield_and_get_v(dadm_KIJ_U1U1D0)
  add_dfield_and_get_v(dadm_KIJ_U1U1D1)
  add_dfield_and_get_v(dadm_KIJ_U1U1D2)
  add_dfield_and_get_v(dadm_KIJ_U1U2D0)
  add_dfield_and_get_v(dadm_KIJ_U1U2D1)
  add_dfield_and_get_v(dadm_KIJ_U1U2D2)
  add_dfield_and_get_v(dadm_KIJ_U2U2D0)
  add_dfield_and_get_v(dadm_KIJ_U2U2D1)
  add_dfield_and_get_v(dadm_KIJ_U2U2D2)
  READ_v(psi)
  READ_v(adm_g_D0D0)
  READ_v(adm_g_D0D1)
  READ_v(adm_g_D0D2)
  READ_v(adm_g_D1D1)
  READ_v(adm_g_D1D2)
  READ_v(adm_g_D2D2)
  add_dfield_and_get_v(dadm_g_D0D0D0)
  add_dfield_and_get_v(dadm_g_D0D0D1)
  add_dfield_and_get_v(dadm_g_D0D0D2)
  add_dfield_and_get_v(dadm_g_D0D1D0)
  add_dfield_and_get_v(dadm_g_D0D1D1)
  add_dfield_and_get_v(dadm_g_D0D1D2)
  add_dfield_and_get_v(dadm_g_D0D2D0)
  add_dfield_and_get_v(dadm_g_D0D2D1)
  add_dfield_and_get_v(dadm_g_D0D2D2)
  add_dfield_and_get_v(dadm_g_D1D1D0)
  add_dfield_and_get_v(dadm_g_D1D1D1)
  add_dfield_and_get_v(dadm_g_D1D1D2)
  add_dfield_and_get_v(dadm_g_D1D2D0)
  add_dfield_and_get_v(dadm_g_D1D2D1)
  add_dfield_and_get_v(dadm_g_D1D2D2)
  add_dfield_and_get_v(dadm_g_D2D2D0)
  add_dfield_and_get_v(dadm_g_D2D2D1)
  add_dfield_and_get_v(dadm_g_D2D2D2)
  READ_v(adm_ig_U0U0)
  READ_v(adm_ig_U0U1)
  READ_v(adm_ig_U0U2)
  READ_v(adm_ig_U1U1)
  READ_v(adm_ig_U1U2)
  READ_v(adm_ig_U2U2)
  add_and_alloc_with_stem(add_Gamma_U0D0D0,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U0D0D1,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U0D0D2,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U0D1D0,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U0D1D1,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U0D1D2,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U0D2D0,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U0D2D1,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U0D2D2,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U1D0D0,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U1D0D1,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U1D0D2,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U1D1D0,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U1D1D1,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U1D1D2,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U1D2D0,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U1D2D1,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U1D2D2,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U2D0D0,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U2D0D1,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U2D0D2,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U2D1D0,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U2D1D1,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U2D1D2,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U2D2D0,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U2D2D1,"Gamma")
  add_and_alloc_with_stem(add_Gamma_U2D2D2,"Gamma")
  Compute_Christoffel(compute_Gamma)
  READ_v(Gamma_U0D0D0)
  READ_v(Gamma_U0D0D1)
  READ_v(Gamma_U0D0D2)
  READ_v(Gamma_U0D1D1)
  READ_v(Gamma_U0D1D2)
  READ_v(Gamma_U0D2D2)
  READ_v(Gamma_U1D0D0)
  READ_v(Gamma_U1D0D1)
  READ_v(Gamma_U1D0D2)
  READ_v(Gamma_U1D1D1)
  READ_v(Gamma_U1D1D2)
  READ_v(Gamma_U1D2D2)
  READ_v(Gamma_U2D0D0)
  READ_v(Gamma_U2D0D1)
  READ_v(Gamma_U2D0D2)
  READ_v(Gamma_U2D1D1)
  READ_v(Gamma_U2D1D2)
  READ_v(Gamma_U2D2D2)
  add_dfield_and_get_v(dGamma_U0D0D0D0)
  add_dfield_and_get_v(dGamma_U0D0D0D1)
  add_dfield_and_get_v(dGamma_U0D0D0D2)
  add_dfield_and_get_v(dGamma_U0D0D1D0)
  add_dfield_and_get_v(dGamma_U0D0D1D1)
  add_dfield_and_get_v(dGamma_U0D0D1D2)
  add_dfield_and_get_v(dGamma_U0D0D2D0)
  add_dfield_and_get_v(dGamma_U0D0D2D1)
  add_dfield_and_get_v(dGamma_U0D0D2D2)
  add_dfield_and_get_v(dGamma_U0D1D1D0)
  add_dfield_and_get_v(dGamma_U0D1D1D1)
  add_dfield_and_get_v(dGamma_U0D1D1D2)
  add_dfield_and_get_v(dGamma_U0D1D2D0)
  add_dfield_and_get_v(dGamma_U0D1D2D1)
  add_dfield_and_get_v(dGamma_U0D1D2D2)
  add_dfield_and_get_v(dGamma_U0D2D2D0)
  add_dfield_and_get_v(dGamma_U0D2D2D1)
  add_dfield_and_get_v(dGamma_U0D2D2D2)
  add_dfield_and_get_v(dGamma_U1D0D0D0)
  add_dfield_and_get_v(dGamma_U1D0D0D1)
  add_dfield_and_get_v(dGamma_U1D0D0D2)
  add_dfield_and_get_v(dGamma_U1D0D1D0)
  add_dfield_and_get_v(dGamma_U1D0D1D1)
  add_dfield_and_get_v(dGamma_U1D0D1D2)
  add_dfield_and_get_v(dGamma_U1D0D2D0)
  add_dfield_and_get_v(dGamma_U1D0D2D1)
  add_dfield_and_get_v(dGamma_U1D0D2D2)
  add_dfield_and_get_v(dGamma_U1D1D1D0)
  add_dfield_and_get_v(dGamma_U1D1D1D1)
  add_dfield_and_get_v(dGamma_U1D1D1D2)
  add_dfield_and_get_v(dGamma_U1D1D2D0)
  add_dfield_and_get_v(dGamma_U1D1D2D1)
  add_dfield_and_get_v(dGamma_U1D1D2D2)
  add_dfield_and_get_v(dGamma_U1D2D2D0)
  add_dfield_and_get_v(dGamma_U1D2D2D1)
  add_dfield_and_get_v(dGamma_U1D2D2D2)
  add_dfield_and_get_v(dGamma_U2D0D0D0)
  add_dfield_and_get_v(dGamma_U2D0D0D1)
  add_dfield_and_get_v(dGamma_U2D0D0D2)
  add_dfield_and_get_v(dGamma_U2D0D1D0)
  add_dfield_and_get_v(dGamma_U2D0D1D1)
  add_dfield_and_get_v(dGamma_U2D0D1D2)
  add_dfield_and_get_v(dGamma_U2D0D2D0)
  add_dfield_and_get_v(dGamma_U2D0D2D1)
  add_dfield_and_get_v(dGamma_U2D0D2D2)
  add_dfield_and_get_v(dGamma_U2D1D1D0)
  add_dfield_and_get_v(dGamma_U2D1D1D1)
  add_dfield_and_get_v(dGamma_U2D1D1D2)
  add_dfield_and_get_v(dGamma_U2D1D2D0)
  add_dfield_and_get_v(dGamma_U2D1D2D1)
  add_dfield_and_get_v(dGamma_U2D1D2D2)
  add_dfield_and_get_v(dGamma_U2D2D2D0)
  add_dfield_and_get_v(dGamma_U2D2D2D1)
  add_dfield_and_get_v(dGamma_U2D2D2D2)
  READ_v(EConfP)
  READ_v(EConfC)
  READ_v(JConfP_U0)
  READ_v(JConfP_U1)
  READ_v(JConfP_U2)
  READ_v(JConfC)
  READ_v(trK)
  READ_v(dtrK_D0)
  READ_v(dtrK_D1)
  READ_v(dtrK_D2)

FOR_ALL_ijk
{

  double psim6 =
pow(psi[ijk], -6);

  double Jp_U0 =
JConfP_U0[ijk]*psim6;

  double Jp_U1 =
JConfP_U1[ijk]*psim6;

  double Jp_U2 =
JConfP_U2[ijk]*psim6;

  double Ep =
EConfP[ijk]*psim6;

  double Ric1_D0D0 =
dGamma_U0D0D0D0[ijk] + dGamma_U1D0D0D1[ijk] + dGamma_U2D0D0D2[ijk];

  double Ric1_D0D1 =
dGamma_U0D0D1D0[ijk] + dGamma_U1D0D1D1[ijk] + dGamma_U2D0D1D2[ijk];

  double Ric1_D0D2 =
dGamma_U0D0D2D0[ijk] + dGamma_U1D0D2D1[ijk] + dGamma_U2D0D2D2[ijk];

  double Ric1_D1D1 =
dGamma_U0D1D1D0[ijk] + dGamma_U1D1D1D1[ijk] + dGamma_U2D1D1D2[ijk];

  double Ric1_D1D2 =
dGamma_U0D1D2D0[ijk] + dGamma_U1D1D2D1[ijk] + dGamma_U2D1D2D2[ijk];

  double Ric1_D2D2 =
dGamma_U0D2D2D0[ijk] + dGamma_U1D2D2D1[ijk] + dGamma_U2D2D2D2[ijk];

  double Ric2_D0D0 =
-dGamma_U0D0D0D0[ijk] - dGamma_U1D0D1D0[ijk] - dGamma_U2D0D2D0[ijk];

  double Ric2_D0D1 =
-dGamma_U0D0D0D1[ijk] - dGamma_U1D0D1D1[ijk] - dGamma_U2D0D2D1[ijk];

  double Ric2_D0D2 =
-dGamma_U0D0D0D2[ijk] - dGamma_U1D0D1D2[ijk] - dGamma_U2D0D2D2[ijk];

  double Ric2_D1D1 =
-dGamma_U0D0D1D1[ijk] - dGamma_U1D1D1D1[ijk] - dGamma_U2D1D2D1[ijk];

  double Ric2_D1D2 =
-dGamma_U0D0D1D2[ijk] - dGamma_U1D1D1D2[ijk] - dGamma_U2D1D2D2[ijk];

  double Ric2_D2D2 =
-dGamma_U0D0D2D2[ijk] - dGamma_U1D1D2D2[ijk] - dGamma_U2D2D2D2[ijk];

  double Ric3_D0D0 =
pow(Gamma_U0D0D0[ijk], 2) + Gamma_U0D0D0[ijk]*Gamma_U1D0D1[ijk] +
Gamma_U0D0D0[ijk]*Gamma_U2D0D2[ijk] + Gamma_U0D0D1[ijk]*
Gamma_U1D0D0[ijk] + Gamma_U0D0D2[ijk]*Gamma_U2D0D0[ijk] +
Gamma_U1D0D0[ijk]*Gamma_U1D1D1[ijk] + Gamma_U1D0D0[ijk]*
Gamma_U2D1D2[ijk] + Gamma_U1D1D2[ijk]*Gamma_U2D0D0[ijk] +
Gamma_U2D0D0[ijk]*Gamma_U2D2D2[ijk];

  double Ric3_D0D1 =
Gamma_U0D0D0[ijk]*Gamma_U0D0D1[ijk] + 2.0*Gamma_U0D0D1[ijk]*
Gamma_U1D0D1[ijk] + Gamma_U0D0D1[ijk]*Gamma_U2D0D2[ijk] +
Gamma_U0D0D2[ijk]*Gamma_U2D0D1[ijk] + Gamma_U1D0D1[ijk]*
Gamma_U1D1D1[ijk] + Gamma_U1D0D1[ijk]*Gamma_U2D1D2[ijk] +
Gamma_U1D1D2[ijk]*Gamma_U2D0D1[ijk] + Gamma_U2D0D1[ijk]*
Gamma_U2D2D2[ijk];

  double Ric3_D0D2 =
Gamma_U0D0D0[ijk]*Gamma_U0D0D2[ijk] + Gamma_U0D0D1[ijk]*
Gamma_U1D0D2[ijk] + Gamma_U0D0D2[ijk]*Gamma_U1D0D1[ijk] + 2.0*
Gamma_U0D0D2[ijk]*Gamma_U2D0D2[ijk] + Gamma_U1D0D2[ijk]*
Gamma_U1D1D1[ijk] + Gamma_U1D0D2[ijk]*Gamma_U2D1D2[ijk] +
Gamma_U1D1D2[ijk]*Gamma_U2D0D2[ijk] + Gamma_U2D0D2[ijk]*
Gamma_U2D2D2[ijk];

  double Ric3_D1D1 =
Gamma_U0D0D0[ijk]*Gamma_U0D1D1[ijk] + Gamma_U0D0D1[ijk]*
Gamma_U1D1D1[ijk] + Gamma_U0D0D2[ijk]*Gamma_U2D1D1[ijk] +
Gamma_U0D1D1[ijk]*Gamma_U1D0D1[ijk] + Gamma_U0D1D1[ijk]*
Gamma_U2D0D2[ijk] + pow(Gamma_U1D1D1[ijk], 2) + Gamma_U1D1D1[ijk]*
Gamma_U2D1D2[ijk] + Gamma_U1D1D2[ijk]*Gamma_U2D1D1[ijk] +
Gamma_U2D1D1[ijk]*Gamma_U2D2D2[ijk];

  double Ric3_D1D2 =
Gamma_U0D0D0[ijk]*Gamma_U0D1D2[ijk] + Gamma_U0D0D1[ijk]*
Gamma_U1D1D2[ijk] + Gamma_U0D0D2[ijk]*Gamma_U2D1D2[ijk] +
Gamma_U0D1D2[ijk]*Gamma_U1D0D1[ijk] + Gamma_U0D1D2[ijk]*
Gamma_U2D0D2[ijk] + Gamma_U1D1D1[ijk]*Gamma_U1D1D2[ijk] + 2.0*
Gamma_U1D1D2[ijk]*Gamma_U2D1D2[ijk] + Gamma_U2D1D2[ijk]*
Gamma_U2D2D2[ijk];

  double Ric3_D2D2 =
Gamma_U0D0D0[ijk]*Gamma_U0D2D2[ijk] + Gamma_U0D0D1[ijk]*
Gamma_U1D2D2[ijk] + Gamma_U0D0D2[ijk]*Gamma_U2D2D2[ijk] +
Gamma_U0D2D2[ijk]*Gamma_U1D0D1[ijk] + Gamma_U0D2D2[ijk]*
Gamma_U2D0D2[ijk] + Gamma_U1D1D1[ijk]*Gamma_U1D2D2[ijk] +
Gamma_U1D1D2[ijk]*Gamma_U2D2D2[ijk] + Gamma_U1D2D2[ijk]*
Gamma_U2D1D2[ijk] + pow(Gamma_U2D2D2[ijk], 2);

  double Ric4_D0D0 =
-pow(Gamma_U0D0D0[ijk], 2) - 2.0*Gamma_U0D0D1[ijk]*Gamma_U1D0D0[ijk] -
2.0*Gamma_U0D0D2[ijk]*Gamma_U2D0D0[ijk] - pow(Gamma_U1D0D1[ijk], 2) -
2.0*Gamma_U1D0D2[ijk]*Gamma_U2D0D1[ijk] - pow(Gamma_U2D0D2[ijk], 2);

  double Ric4_D0D1 =
-Gamma_U0D0D0[ijk]*Gamma_U0D0D1[ijk] - Gamma_U0D0D1[ijk]*
Gamma_U1D0D1[ijk] - Gamma_U0D0D2[ijk]*Gamma_U2D0D1[ijk] -
Gamma_U0D1D1[ijk]*Gamma_U1D0D0[ijk] - Gamma_U0D1D2[ijk]*
Gamma_U2D0D0[ijk] - Gamma_U1D0D1[ijk]*Gamma_U1D1D1[ijk] -
Gamma_U1D0D2[ijk]*Gamma_U2D1D1[ijk] - Gamma_U1D1D2[ijk]*
Gamma_U2D0D1[ijk] - Gamma_U2D0D2[ijk]*Gamma_U2D1D2[ijk];

  double Ric4_D0D2 =
-Gamma_U0D0D0[ijk]*Gamma_U0D0D2[ijk] - Gamma_U0D0D1[ijk]*
Gamma_U1D0D2[ijk] - Gamma_U0D0D2[ijk]*Gamma_U2D0D2[ijk] -
Gamma_U0D1D2[ijk]*Gamma_U1D0D0[ijk] - Gamma_U0D2D2[ijk]*
Gamma_U2D0D0[ijk] - Gamma_U1D0D1[ijk]*Gamma_U1D1D2[ijk] -
Gamma_U1D0D2[ijk]*Gamma_U2D1D2[ijk] - Gamma_U1D2D2[ijk]*
Gamma_U2D0D1[ijk] - Gamma_U2D0D2[ijk]*Gamma_U2D2D2[ijk];

  double Ric4_D1D1 =
-pow(Gamma_U0D0D1[ijk], 2) - 2.0*Gamma_U0D1D1[ijk]*Gamma_U1D0D1[ijk] -
2.0*Gamma_U0D1D2[ijk]*Gamma_U2D0D1[ijk] - pow(Gamma_U1D1D1[ijk], 2) -
2.0*Gamma_U1D1D2[ijk]*Gamma_U2D1D1[ijk] - pow(Gamma_U2D1D2[ijk], 2);

  double Ric4_D1D2 =
-Gamma_U0D0D1[ijk]*Gamma_U0D0D2[ijk] - Gamma_U0D1D1[ijk]*
Gamma_U1D0D2[ijk] - Gamma_U0D1D2[ijk]*Gamma_U1D0D1[ijk] -
Gamma_U0D1D2[ijk]*Gamma_U2D0D2[ijk] - Gamma_U0D2D2[ijk]*
Gamma_U2D0D1[ijk] - Gamma_U1D1D1[ijk]*Gamma_U1D1D2[ijk] -
Gamma_U1D1D2[ijk]*Gamma_U2D1D2[ijk] - Gamma_U1D2D2[ijk]*
Gamma_U2D1D1[ijk] - Gamma_U2D1D2[ijk]*Gamma_U2D2D2[ijk];

  double Ric4_D2D2 =
-pow(Gamma_U0D0D2[ijk], 2) - 2.0*Gamma_U0D1D2[ijk]*Gamma_U1D0D2[ijk] -
2.0*Gamma_U0D2D2[ijk]*Gamma_U2D0D2[ijk] - pow(Gamma_U1D1D2[ijk], 2) -
2.0*Gamma_U1D2D2[ijk]*Gamma_U2D1D2[ijk] - pow(Gamma_U2D2D2[ijk], 2);

  double Ric_D0D0 =
Ric1_D0D0 + Ric2_D0D0 + Ric3_D0D0 + Ric4_D0D0;

  double Ric_D0D1 =
Ric1_D0D1 + Ric2_D0D1 + Ric3_D0D1 + Ric4_D0D1;

  double Ric_D0D2 =
Ric1_D0D2 + Ric2_D0D2 + Ric3_D0D2 + Ric4_D0D2;

  double Ric_D1D1 =
Ric1_D1D1 + Ric2_D1D1 + Ric3_D1D1 + Ric4_D1D1;

  double Ric_D1D2 =
Ric1_D1D2 + Ric2_D1D2 + Ric3_D1D2 + Ric4_D1D2;

  double Ric_D2D2 =
Ric1_D2D2 + Ric2_D2D2 + Ric3_D2D2 + Ric4_D2D2;

  double R =
Ric_D0D0*adm_ig_U0U0[ijk] + 2.0*Ric_D0D1*adm_ig_U0U1[ijk] + 2.0*
Ric_D0D2*adm_ig_U0U2[ijk] + Ric_D1D1*adm_ig_U1U1[ijk] + 2.0*Ric_D1D2*
adm_ig_U1U2[ijk] + Ric_D2D2*adm_ig_U2U2[ijk];

  double KijKij =
pow(adm_KIJ_U0U0[ijk], 2)*pow(adm_g_D0D0[ijk], 2) + 4.0*
adm_KIJ_U0U0[ijk]*adm_KIJ_U0U1[ijk]*adm_g_D0D0[ijk]*adm_g_D0D1[ijk] +
4.0*adm_KIJ_U0U0[ijk]*adm_KIJ_U0U2[ijk]*adm_g_D0D0[ijk]*
adm_g_D0D2[ijk] + 2.0*adm_KIJ_U0U0[ijk]*adm_KIJ_U1U1[ijk]*
pow(adm_g_D0D1[ijk], 2) + 4.0*adm_KIJ_U0U0[ijk]*adm_KIJ_U1U2[ijk]*
adm_g_D0D1[ijk]*adm_g_D0D2[ijk] + 2.0*adm_KIJ_U0U0[ijk]*
adm_KIJ_U2U2[ijk]*pow(adm_g_D0D2[ijk], 2) + 2.0*pow(adm_KIJ_U0U1[ijk], 2)*
adm_g_D0D0[ijk]*adm_g_D1D1[ijk] + 2.0*pow(adm_KIJ_U0U1[ijk], 2)*
pow(adm_g_D0D1[ijk], 2) + 4.0*adm_KIJ_U0U1[ijk]*adm_KIJ_U0U2[ijk]*
adm_g_D0D0[ijk]*adm_g_D1D2[ijk] + 4.0*adm_KIJ_U0U1[ijk]*
adm_KIJ_U0U2[ijk]*adm_g_D0D1[ijk]*adm_g_D0D2[ijk] + 4.0*
adm_KIJ_U0U1[ijk]*adm_KIJ_U1U1[ijk]*adm_g_D0D1[ijk]*adm_g_D1D1[ijk] +
4.0*adm_KIJ_U0U1[ijk]*adm_KIJ_U1U2[ijk]*adm_g_D0D1[ijk]*
adm_g_D1D2[ijk] + 4.0*adm_KIJ_U0U1[ijk]*adm_KIJ_U1U2[ijk]*
adm_g_D0D2[ijk]*adm_g_D1D1[ijk] + 4.0*adm_KIJ_U0U1[ijk]*
adm_KIJ_U2U2[ijk]*adm_g_D0D2[ijk]*adm_g_D1D2[ijk] + 2.0*
pow(adm_KIJ_U0U2[ijk], 2)*adm_g_D0D0[ijk]*adm_g_D2D2[ijk] + 2.0*
pow(adm_KIJ_U0U2[ijk], 2)*pow(adm_g_D0D2[ijk], 2) + 4.0*
adm_KIJ_U0U2[ijk]*adm_KIJ_U1U1[ijk]*adm_g_D0D1[ijk]*adm_g_D1D2[ijk] +
4.0*adm_KIJ_U0U2[ijk]*adm_KIJ_U1U2[ijk]*adm_g_D0D1[ijk]*
adm_g_D2D2[ijk] + 4.0*adm_KIJ_U0U2[ijk]*adm_KIJ_U1U2[ijk]*
adm_g_D0D2[ijk]*adm_g_D1D2[ijk] + 4.0*adm_KIJ_U0U2[ijk]*
adm_KIJ_U2U2[ijk]*adm_g_D0D2[ijk]*adm_g_D2D2[ijk] + pow(adm_KIJ_U1U1[ijk], 2)*
pow(adm_g_D1D1[ijk], 2) + 4.0*adm_KIJ_U1U1[ijk]*adm_KIJ_U1U2[ijk]*
adm_g_D1D1[ijk]*adm_g_D1D2[ijk] + 2.0*adm_KIJ_U1U1[ijk]*
adm_KIJ_U2U2[ijk]*pow(adm_g_D1D2[ijk], 2) + 2.0*pow(adm_KIJ_U1U2[ijk], 2)*
adm_g_D1D1[ijk]*adm_g_D2D2[ijk] + 2.0*pow(adm_KIJ_U1U2[ijk], 2)*
pow(adm_g_D1D2[ijk], 2) + 4.0*adm_KIJ_U1U2[ijk]*adm_KIJ_U2U2[ijk]*
adm_g_D1D2[ijk]*adm_g_D2D2[ijk] + pow(adm_KIJ_U2U2[ijk], 2)*
pow(adm_g_D2D2[ijk], 2);

  double DjKij_U0 =
2.0*Gamma_U0D0D0[ijk]*adm_KIJ_U0U0[ijk] + 3.0*Gamma_U0D0D1[ijk]*
adm_KIJ_U0U1[ijk] + 3.0*Gamma_U0D0D2[ijk]*adm_KIJ_U0U2[ijk] +
Gamma_U0D1D1[ijk]*adm_KIJ_U1U1[ijk] + 2.0*Gamma_U0D1D2[ijk]*
adm_KIJ_U1U2[ijk] + Gamma_U0D2D2[ijk]*adm_KIJ_U2U2[ijk] +
Gamma_U1D0D1[ijk]*adm_KIJ_U0U0[ijk] + Gamma_U1D1D1[ijk]*
adm_KIJ_U0U1[ijk] + Gamma_U1D1D2[ijk]*adm_KIJ_U0U2[ijk] +
Gamma_U2D0D2[ijk]*adm_KIJ_U0U0[ijk] + Gamma_U2D1D2[ijk]*
adm_KIJ_U0U1[ijk] + Gamma_U2D2D2[ijk]*adm_KIJ_U0U2[ijk] +
dadm_KIJ_U0U0D0[ijk] + dadm_KIJ_U0U1D1[ijk] + dadm_KIJ_U0U2D2[ijk];

  double DjKij_U1 =
Gamma_U0D0D0[ijk]*adm_KIJ_U0U1[ijk] + Gamma_U0D0D1[ijk]*
adm_KIJ_U1U1[ijk] + Gamma_U0D0D2[ijk]*adm_KIJ_U1U2[ijk] +
Gamma_U1D0D0[ijk]*adm_KIJ_U0U0[ijk] + 3.0*Gamma_U1D0D1[ijk]*
adm_KIJ_U0U1[ijk] + 2.0*Gamma_U1D0D2[ijk]*adm_KIJ_U0U2[ijk] + 2.0*
Gamma_U1D1D1[ijk]*adm_KIJ_U1U1[ijk] + 3.0*Gamma_U1D1D2[ijk]*
adm_KIJ_U1U2[ijk] + Gamma_U1D2D2[ijk]*adm_KIJ_U2U2[ijk] +
Gamma_U2D0D2[ijk]*adm_KIJ_U0U1[ijk] + Gamma_U2D1D2[ijk]*
adm_KIJ_U1U1[ijk] + Gamma_U2D2D2[ijk]*adm_KIJ_U1U2[ijk] +
dadm_KIJ_U0U1D0[ijk] + dadm_KIJ_U1U1D1[ijk] + dadm_KIJ_U1U2D2[ijk];

  double DjKij_U2 =
Gamma_U0D0D0[ijk]*adm_KIJ_U0U2[ijk] + Gamma_U0D0D1[ijk]*
adm_KIJ_U1U2[ijk] + Gamma_U0D0D2[ijk]*adm_KIJ_U2U2[ijk] +
Gamma_U1D0D1[ijk]*adm_KIJ_U0U2[ijk] + Gamma_U1D1D1[ijk]*
adm_KIJ_U1U2[ijk] + Gamma_U1D1D2[ijk]*adm_KIJ_U2U2[ijk] +
Gamma_U2D0D0[ijk]*adm_KIJ_U0U0[ijk] + 2.0*Gamma_U2D0D1[ijk]*
adm_KIJ_U0U1[ijk] + 3.0*Gamma_U2D0D2[ijk]*adm_KIJ_U0U2[ijk] +
Gamma_U2D1D1[ijk]*adm_KIJ_U1U1[ijk] + 3.0*Gamma_U2D1D2[ijk]*
adm_KIJ_U1U2[ijk] + 2.0*Gamma_U2D2D2[ijk]*adm_KIJ_U2U2[ijk] +
dadm_KIJ_U0U2D0[ijk] + dadm_KIJ_U1U2D1[ijk] + dadm_KIJ_U2U2D2[ijk];

  double Ham_Constraint =
EConfC[ijk]*(-KijKij + R + pow(trK[ijk], 2)) - 16*M_PI*
Ep;

  double Mom_constraint_U0 =
-JConfC[ijk]*(-DjKij_U0 + adm_ig_U0U0[ijk]*dtrK_D0[ijk] +
adm_ig_U0U1[ijk]*dtrK_D1[ijk] + adm_ig_U0U2[ijk]*dtrK_D2[ijk]) - 8*M_PI*
Jp_U0;

  double Mom_constraint_U1 =
-JConfC[ijk]*(-DjKij_U1 + adm_ig_U0U1[ijk]*dtrK_D0[ijk] +
adm_ig_U1U1[ijk]*dtrK_D1[ijk] + adm_ig_U1U2[ijk]*dtrK_D2[ijk]) - 8*M_PI*
Jp_U1;

  double Mom_constraint_U2 =
-JConfC[ijk]*(-DjKij_U2 + adm_ig_U0U2[ijk]*dtrK_D0[ijk] +
adm_ig_U1U2[ijk]*dtrK_D1[ijk] + adm_ig_U2U2[ijk]*dtrK_D2[ijk]) - 8*M_PI*
Jp_U2;


  mom_U0[ijk] = Mom_constraint_U0;
  mom_U1[ijk] = Mom_constraint_U1;
  mom_U2[ijk] = Mom_constraint_U2;
  ham[ijk] = Ham_Constraint;
}

remove_field_regex(patch,"^adm_ig_U.+");
remove_field_regex(patch,"^dadm_g_D.+");
remove_field_regex(patch,"^dadm_KIJ_U.+");
remove_field_regex(patch,"^Gamma_U.+");
remove_field_regex(patch,"^dGamma_U.+");
}
