/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "adm_header.h"


void adm_update_AConfIJ_SCTT_MConfIJ0(Patch_T *const patch);

void adm_update_AConfIJ_SCTT_MConfIJ0(Patch_T *const patch)
{


  /* declaring: */
  REALLOC_v_WRITE_v(AConfIJ_U0U1)
  REALLOC_v_WRITE_v(AConfIJ_U0U0)
  REALLOC_v_WRITE_v(AConfIJ_U0U2)
  REALLOC_v_WRITE_v(AConfIJ_U2U2)
  REALLOC_v_WRITE_v(AConfIJ_U1U1)
  REALLOC_v_WRITE_v(AConfIJ_U1U2)
  REALLOC_v_WRITE_v(AConfIJ2)
  READ_v(beta_U1)
  READ_v(beta_U0)
  READ_v(beta_U2)
  READ_v(dbeta_U1D0)
  READ_v(dbeta_U2D2)
  READ_v(dbeta_U2D0)
  READ_v(dbeta_U2D1)
  READ_v(dbeta_U0D0)
  READ_v(dbeta_U1D1)
  READ_v(dbeta_U0D1)
  READ_v(dbeta_U0D2)
  READ_v(dbeta_U1D2)
  READ_v(gConf_D0D2)
  READ_v(gConf_D0D0)
  READ_v(gConf_D0D1)
  READ_v(gConf_D1D2)
  READ_v(gConf_D1D1)
  READ_v(gConf_D2D2)
  READ_v(ChrisConf_U1D0D0)
  READ_v(ChrisConf_U0D2D2)
  READ_v(ChrisConf_U1D0D2)
  READ_v(ChrisConf_U2D2D2)
  READ_v(ChrisConf_U2D1D1)
  READ_v(ChrisConf_U2D0D0)
  READ_v(ChrisConf_U1D1D1)
  READ_v(ChrisConf_U0D1D1)
  READ_v(ChrisConf_U0D1D2)
  READ_v(ChrisConf_U1D1D2)
  READ_v(ChrisConf_U0D0D1)
  READ_v(ChrisConf_U0D0D0)
  READ_v(ChrisConf_U2D0D1)
  READ_v(ChrisConf_U0D0D2)
  READ_v(ChrisConf_U2D1D2)
  READ_v(ChrisConf_U1D2D2)
  READ_v(ChrisConf_U2D0D2)
  READ_v(ChrisConf_U1D0D1)
  READ_v(igConf_U2U2)
  READ_v(igConf_U1U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)


FOR_ALL_ijk
{
  double _DB_UU_U1U2 = 
igConf_U0U1[ijk]*(ChrisConf_U2D0D0[ijk]*beta_U0[ijk] + 
ChrisConf_U2D0D1[ijk]*beta_U1[ijk] + ChrisConf_U2D0D2[ijk]*
beta_U2[ijk] + dbeta_U2D0[ijk]) + igConf_U1U1[ijk]*(ChrisConf_U2D0D1[ijk]*
beta_U0[ijk] + ChrisConf_U2D1D1[ijk]*beta_U1[ijk] + ChrisConf_U2D1D2[ijk]*
beta_U2[ijk] + dbeta_U2D1[ijk]) + igConf_U1U2[ijk]*(ChrisConf_U2D0D2[ijk]*
beta_U0[ijk] + ChrisConf_U2D1D2[ijk]*beta_U1[ijk] + ChrisConf_U2D2D2[ijk]*
beta_U2[ijk] + dbeta_U2D2[ijk]);

  double _DB_UU_U1U1 = 
igConf_U0U1[ijk]*(ChrisConf_U1D0D0[ijk]*beta_U0[ijk] + 
ChrisConf_U1D0D1[ijk]*beta_U1[ijk] + ChrisConf_U1D0D2[ijk]*
beta_U2[ijk] + dbeta_U1D0[ijk]) + igConf_U1U1[ijk]*(ChrisConf_U1D0D1[ijk]*
beta_U0[ijk] + ChrisConf_U1D1D1[ijk]*beta_U1[ijk] + ChrisConf_U1D1D2[ijk]*
beta_U2[ijk] + dbeta_U1D1[ijk]) + igConf_U1U2[ijk]*(ChrisConf_U1D0D2[ijk]*
beta_U0[ijk] + ChrisConf_U1D1D2[ijk]*beta_U1[ijk] + ChrisConf_U1D2D2[ijk]*
beta_U2[ijk] + dbeta_U1D2[ijk]);

  double _DB_UU_U1U0 = 
igConf_U0U1[ijk]*(ChrisConf_U0D0D0[ijk]*beta_U0[ijk] + 
ChrisConf_U0D0D1[ijk]*beta_U1[ijk] + ChrisConf_U0D0D2[ijk]*
beta_U2[ijk] + dbeta_U0D0[ijk]) + igConf_U1U1[ijk]*(ChrisConf_U0D0D1[ijk]*
beta_U0[ijk] + ChrisConf_U0D1D1[ijk]*beta_U1[ijk] + ChrisConf_U0D1D2[ijk]*
beta_U2[ijk] + dbeta_U0D1[ijk]) + igConf_U1U2[ijk]*(ChrisConf_U0D0D2[ijk]*
beta_U0[ijk] + ChrisConf_U0D1D2[ijk]*beta_U1[ijk] + ChrisConf_U0D2D2[ijk]*
beta_U2[ijk] + dbeta_U0D2[ijk]);

  double _DB_UU_U0U2 = 
igConf_U0U0[ijk]*(ChrisConf_U2D0D0[ijk]*beta_U0[ijk] + 
ChrisConf_U2D0D1[ijk]*beta_U1[ijk] + ChrisConf_U2D0D2[ijk]*
beta_U2[ijk] + dbeta_U2D0[ijk]) + igConf_U0U1[ijk]*(ChrisConf_U2D0D1[ijk]*
beta_U0[ijk] + ChrisConf_U2D1D1[ijk]*beta_U1[ijk] + ChrisConf_U2D1D2[ijk]*
beta_U2[ijk] + dbeta_U2D1[ijk]) + igConf_U0U2[ijk]*(ChrisConf_U2D0D2[ijk]*
beta_U0[ijk] + ChrisConf_U2D1D2[ijk]*beta_U1[ijk] + ChrisConf_U2D2D2[ijk]*
beta_U2[ijk] + dbeta_U2D2[ijk]);

  double _DB_UU_U0U0 = 
igConf_U0U0[ijk]*(ChrisConf_U0D0D0[ijk]*beta_U0[ijk] + 
ChrisConf_U0D0D1[ijk]*beta_U1[ijk] + ChrisConf_U0D0D2[ijk]*
beta_U2[ijk] + dbeta_U0D0[ijk]) + igConf_U0U1[ijk]*(ChrisConf_U0D0D1[ijk]*
beta_U0[ijk] + ChrisConf_U0D1D1[ijk]*beta_U1[ijk] + ChrisConf_U0D1D2[ijk]*
beta_U2[ijk] + dbeta_U0D1[ijk]) + igConf_U0U2[ijk]*(ChrisConf_U0D0D2[ijk]*
beta_U0[ijk] + ChrisConf_U0D1D2[ijk]*beta_U1[ijk] + ChrisConf_U0D2D2[ijk]*
beta_U2[ijk] + dbeta_U0D2[ijk]);

  double _DB_UU_U0U1 = 
igConf_U0U0[ijk]*(ChrisConf_U1D0D0[ijk]*beta_U0[ijk] + 
ChrisConf_U1D0D1[ijk]*beta_U1[ijk] + ChrisConf_U1D0D2[ijk]*
beta_U2[ijk] + dbeta_U1D0[ijk]) + igConf_U0U1[ijk]*(ChrisConf_U1D0D1[ijk]*
beta_U0[ijk] + ChrisConf_U1D1D1[ijk]*beta_U1[ijk] + ChrisConf_U1D1D2[ijk]*
beta_U2[ijk] + dbeta_U1D1[ijk]) + igConf_U0U2[ijk]*(ChrisConf_U1D0D2[ijk]*
beta_U0[ijk] + ChrisConf_U1D1D2[ijk]*beta_U1[ijk] + ChrisConf_U1D2D2[ijk]*
beta_U2[ijk] + dbeta_U1D2[ijk]);

  double _DB_UU_U2U0 = 
igConf_U0U2[ijk]*(ChrisConf_U0D0D0[ijk]*beta_U0[ijk] + 
ChrisConf_U0D0D1[ijk]*beta_U1[ijk] + ChrisConf_U0D0D2[ijk]*
beta_U2[ijk] + dbeta_U0D0[ijk]) + igConf_U1U2[ijk]*(ChrisConf_U0D0D1[ijk]*
beta_U0[ijk] + ChrisConf_U0D1D1[ijk]*beta_U1[ijk] + ChrisConf_U0D1D2[ijk]*
beta_U2[ijk] + dbeta_U0D1[ijk]) + igConf_U2U2[ijk]*(ChrisConf_U0D0D2[ijk]*
beta_U0[ijk] + ChrisConf_U0D1D2[ijk]*beta_U1[ijk] + ChrisConf_U0D2D2[ijk]*
beta_U2[ijk] + dbeta_U0D2[ijk]);

  double _DB_UU_U2U1 = 
igConf_U0U2[ijk]*(ChrisConf_U1D0D0[ijk]*beta_U0[ijk] + 
ChrisConf_U1D0D1[ijk]*beta_U1[ijk] + ChrisConf_U1D0D2[ijk]*
beta_U2[ijk] + dbeta_U1D0[ijk]) + igConf_U1U2[ijk]*(ChrisConf_U1D0D1[ijk]*
beta_U0[ijk] + ChrisConf_U1D1D1[ijk]*beta_U1[ijk] + ChrisConf_U1D1D2[ijk]*
beta_U2[ijk] + dbeta_U1D1[ijk]) + igConf_U2U2[ijk]*(ChrisConf_U1D0D2[ijk]*
beta_U0[ijk] + ChrisConf_U1D1D2[ijk]*beta_U1[ijk] + ChrisConf_U1D2D2[ijk]*
beta_U2[ijk] + dbeta_U1D2[ijk]);

  double _DB_UU_U2U2 = 
igConf_U0U2[ijk]*(ChrisConf_U2D0D0[ijk]*beta_U0[ijk] + 
ChrisConf_U2D0D1[ijk]*beta_U1[ijk] + ChrisConf_U2D0D2[ijk]*
beta_U2[ijk] + dbeta_U2D0[ijk]) + igConf_U1U2[ijk]*(ChrisConf_U2D0D1[ijk]*
beta_U0[ijk] + ChrisConf_U2D1D1[ijk]*beta_U1[ijk] + ChrisConf_U2D1D2[ijk]*
beta_U2[ijk] + dbeta_U2D1[ijk]) + igConf_U2U2[ijk]*(ChrisConf_U2D0D2[ijk]*
beta_U0[ijk] + ChrisConf_U2D1D2[ijk]*beta_U1[ijk] + ChrisConf_U2D2D2[ijk]*
beta_U2[ijk] + dbeta_U2D2[ijk]);

  double _A_UUij_U2U2 = 
-0.66666666666666663*_DB_UU_U0U0*gConf_D0D0[ijk]*igConf_U2U2[ijk] - 
0.66666666666666663*_DB_UU_U0U1*gConf_D0D1[ijk]*igConf_U2U2[ijk] - 
0.66666666666666663*_DB_UU_U0U2*gConf_D0D2[ijk]*igConf_U2U2[ijk] - 
0.66666666666666663*_DB_UU_U1U0*gConf_D0D1[ijk]*igConf_U2U2[ijk] - 
0.66666666666666663*_DB_UU_U1U1*gConf_D1D1[ijk]*igConf_U2U2[ijk] - 
0.66666666666666663*_DB_UU_U1U2*gConf_D1D2[ijk]*igConf_U2U2[ijk] - 
0.66666666666666663*_DB_UU_U2U0*gConf_D0D2[ijk]*igConf_U2U2[ijk] - 
0.66666666666666663*_DB_UU_U2U1*gConf_D1D2[ijk]*igConf_U2U2[ijk] - 
0.66666666666666663*_DB_UU_U2U2*gConf_D2D2[ijk]*igConf_U2U2[ijk] + 2*
_DB_UU_U2U2;

  double _A_UUij_U1U2 = 
-0.66666666666666663*_DB_UU_U0U0*gConf_D0D0[ijk]*igConf_U1U2[ijk] - 
0.66666666666666663*_DB_UU_U0U1*gConf_D0D1[ijk]*igConf_U1U2[ijk] - 
0.66666666666666663*_DB_UU_U0U2*gConf_D0D2[ijk]*igConf_U1U2[ijk] - 
0.66666666666666663*_DB_UU_U1U0*gConf_D0D1[ijk]*igConf_U1U2[ijk] - 
0.66666666666666663*_DB_UU_U1U1*gConf_D1D1[ijk]*igConf_U1U2[ijk] - 
0.66666666666666663*_DB_UU_U1U2*gConf_D1D2[ijk]*igConf_U1U2[ijk] + 
_DB_UU_U1U2 - 0.66666666666666663*_DB_UU_U2U0*gConf_D0D2[ijk]*
igConf_U1U2[ijk] - 0.66666666666666663*_DB_UU_U2U1*gConf_D1D2[ijk]*
igConf_U1U2[ijk] + _DB_UU_U2U1 - 0.66666666666666663*_DB_UU_U2U2*
gConf_D2D2[ijk]*igConf_U1U2[ijk];

  double _A_UUij_U1U1 = 
-0.66666666666666663*_DB_UU_U0U0*gConf_D0D0[ijk]*igConf_U1U1[ijk] - 
0.66666666666666663*_DB_UU_U0U1*gConf_D0D1[ijk]*igConf_U1U1[ijk] - 
0.66666666666666663*_DB_UU_U0U2*gConf_D0D2[ijk]*igConf_U1U1[ijk] - 
0.66666666666666663*_DB_UU_U1U0*gConf_D0D1[ijk]*igConf_U1U1[ijk] - 
0.66666666666666663*_DB_UU_U1U1*gConf_D1D1[ijk]*igConf_U1U1[ijk] + 2*
_DB_UU_U1U1 - 0.66666666666666663*_DB_UU_U1U2*gConf_D1D2[ijk]*
igConf_U1U1[ijk] - 0.66666666666666663*_DB_UU_U2U0*gConf_D0D2[ijk]*
igConf_U1U1[ijk] - 0.66666666666666663*_DB_UU_U2U1*gConf_D1D2[ijk]*
igConf_U1U1[ijk] - 0.66666666666666663*_DB_UU_U2U2*gConf_D2D2[ijk]*
igConf_U1U1[ijk];

  double _A_UUij_U0U2 = 
-0.66666666666666663*_DB_UU_U0U0*gConf_D0D0[ijk]*igConf_U0U2[ijk] - 
0.66666666666666663*_DB_UU_U0U1*gConf_D0D1[ijk]*igConf_U0U2[ijk] - 
0.66666666666666663*_DB_UU_U0U2*gConf_D0D2[ijk]*igConf_U0U2[ijk] + 
_DB_UU_U0U2 - 0.66666666666666663*_DB_UU_U1U0*gConf_D0D1[ijk]*
igConf_U0U2[ijk] - 0.66666666666666663*_DB_UU_U1U1*gConf_D1D1[ijk]*
igConf_U0U2[ijk] - 0.66666666666666663*_DB_UU_U1U2*gConf_D1D2[ijk]*
igConf_U0U2[ijk] - 0.66666666666666663*_DB_UU_U2U0*gConf_D0D2[ijk]*
igConf_U0U2[ijk] + _DB_UU_U2U0 - 0.66666666666666663*_DB_UU_U2U1*
gConf_D1D2[ijk]*igConf_U0U2[ijk] - 0.66666666666666663*_DB_UU_U2U2*
gConf_D2D2[ijk]*igConf_U0U2[ijk];

  double _A_UUij_U0U1 = 
-0.66666666666666663*_DB_UU_U0U0*gConf_D0D0[ijk]*igConf_U0U1[ijk] - 
0.66666666666666663*_DB_UU_U0U1*gConf_D0D1[ijk]*igConf_U0U1[ijk] + 
_DB_UU_U0U1 - 0.66666666666666663*_DB_UU_U0U2*gConf_D0D2[ijk]*
igConf_U0U1[ijk] - 0.66666666666666663*_DB_UU_U1U0*gConf_D0D1[ijk]*
igConf_U0U1[ijk] + _DB_UU_U1U0 - 0.66666666666666663*_DB_UU_U1U1*
gConf_D1D1[ijk]*igConf_U0U1[ijk] - 0.66666666666666663*_DB_UU_U1U2*
gConf_D1D2[ijk]*igConf_U0U1[ijk] - 0.66666666666666663*_DB_UU_U2U0*
gConf_D0D2[ijk]*igConf_U0U1[ijk] - 0.66666666666666663*_DB_UU_U2U1*
gConf_D1D2[ijk]*igConf_U0U1[ijk] - 0.66666666666666663*_DB_UU_U2U2*
gConf_D2D2[ijk]*igConf_U0U1[ijk];

  double _A_UUij_U0U0 = 
-0.66666666666666663*_DB_UU_U0U0*gConf_D0D0[ijk]*igConf_U0U0[ijk] + 2*
_DB_UU_U0U0 - 0.66666666666666663*_DB_UU_U0U1*gConf_D0D1[ijk]*
igConf_U0U0[ijk] - 0.66666666666666663*_DB_UU_U0U2*gConf_D0D2[ijk]*
igConf_U0U0[ijk] - 0.66666666666666663*_DB_UU_U1U0*gConf_D0D1[ijk]*
igConf_U0U0[ijk] - 0.66666666666666663*_DB_UU_U1U1*gConf_D1D1[ijk]*
igConf_U0U0[ijk] - 0.66666666666666663*_DB_UU_U1U2*gConf_D1D2[ijk]*
igConf_U0U0[ijk] - 0.66666666666666663*_DB_UU_U2U0*gConf_D0D2[ijk]*
igConf_U0U0[ijk] - 0.66666666666666663*_DB_UU_U2U1*gConf_D1D2[ijk]*
igConf_U0U0[ijk] - 0.66666666666666663*_DB_UU_U2U2*gConf_D2D2[ijk]*
igConf_U0U0[ijk];

  double _AijAij = 
pow(_A_UUij_U0U0, 2)*pow(gConf_D0D0[ijk], 2) + 4.0*_A_UUij_U0U0*
_A_UUij_U0U1*gConf_D0D0[ijk]*gConf_D0D1[ijk] + 4.0*_A_UUij_U0U0*
_A_UUij_U0U2*gConf_D0D0[ijk]*gConf_D0D2[ijk] + 2.0*_A_UUij_U0U0*
_A_UUij_U1U1*pow(gConf_D0D1[ijk], 2) + 4.0*_A_UUij_U0U0*_A_UUij_U1U2*
gConf_D0D1[ijk]*gConf_D0D2[ijk] + 2.0*_A_UUij_U0U0*_A_UUij_U2U2*
pow(gConf_D0D2[ijk], 2) + 2.0*pow(_A_UUij_U0U1, 2)*gConf_D0D0[ijk]*
gConf_D1D1[ijk] + 2.0*pow(_A_UUij_U0U1, 2)*pow(gConf_D0D1[ijk], 2) +
4.0*_A_UUij_U0U1*_A_UUij_U0U2*gConf_D0D0[ijk]*gConf_D1D2[ijk] + 4.0*
_A_UUij_U0U1*_A_UUij_U0U2*gConf_D0D1[ijk]*gConf_D0D2[ijk] + 4.0*
_A_UUij_U0U1*_A_UUij_U1U1*gConf_D0D1[ijk]*gConf_D1D1[ijk] + 4.0*
_A_UUij_U0U1*_A_UUij_U1U2*gConf_D0D1[ijk]*gConf_D1D2[ijk] + 4.0*
_A_UUij_U0U1*_A_UUij_U1U2*gConf_D0D2[ijk]*gConf_D1D1[ijk] + 4.0*
_A_UUij_U0U1*_A_UUij_U2U2*gConf_D0D2[ijk]*gConf_D1D2[ijk] + 2.0*
pow(_A_UUij_U0U2, 2)*gConf_D0D0[ijk]*gConf_D2D2[ijk] + 2.0*
pow(_A_UUij_U0U2, 2)*pow(gConf_D0D2[ijk], 2) + 4.0*_A_UUij_U0U2*
_A_UUij_U1U1*gConf_D0D1[ijk]*gConf_D1D2[ijk] + 4.0*_A_UUij_U0U2*
_A_UUij_U1U2*gConf_D0D1[ijk]*gConf_D2D2[ijk] + 4.0*_A_UUij_U0U2*
_A_UUij_U1U2*gConf_D0D2[ijk]*gConf_D1D2[ijk] + 4.0*_A_UUij_U0U2*
_A_UUij_U2U2*gConf_D0D2[ijk]*gConf_D2D2[ijk] + pow(_A_UUij_U1U1, 2)*
pow(gConf_D1D1[ijk], 2) + 4.0*_A_UUij_U1U1*_A_UUij_U1U2*gConf_D1D1[ijk]*
gConf_D1D2[ijk] + 2.0*_A_UUij_U1U1*_A_UUij_U2U2*pow(gConf_D1D2[ijk], 2) +
2.0*pow(_A_UUij_U1U2, 2)*gConf_D1D1[ijk]*gConf_D2D2[ijk] + 2.0*
pow(_A_UUij_U1U2, 2)*pow(gConf_D1D2[ijk], 2) + 4.0*_A_UUij_U1U2*
_A_UUij_U2U2*gConf_D1D2[ijk]*gConf_D2D2[ijk] + pow(_A_UUij_U2U2, 2)*
pow(gConf_D2D2[ijk], 2);


  /* populating: */
  AConfIJ_U0U1[ijk] = _A_UUij_U0U1;
  AConfIJ_U0U0[ijk] = _A_UUij_U0U0;
  AConfIJ_U0U2[ijk] = _A_UUij_U0U2;
  AConfIJ_U2U2[ijk] = _A_UUij_U2U2;
  AConfIJ_U1U1[ijk] = _A_UUij_U1U1;
  AConfIJ_U1U2[ijk] = _A_UUij_U1U2;
AConfIJ2[ijk] = _AijAij;
}
  dField_di(dAConfIJ_U2U2D2);
  dField_di(dAConfIJ_U2U2D0);
  dField_di(dAConfIJ_U2U2D1);
  dField_di(dAConfIJ_U1U1D2);
  dField_di(dAConfIJ_U1U1D0);
  dField_di(dAConfIJ_U1U1D1);
  dField_di(dAConfIJ_U0U0D2);
  dField_di(dAConfIJ_U0U0D0);
  dField_di(dAConfIJ_U0U0D1);
  dField_di(dAConfIJ_U0U1D2);
  dField_di(dAConfIJ_U0U1D1);
  dField_di(dAConfIJ_U0U1D0);
  dField_di(dAConfIJ_U1U2D1);
  dField_di(dAConfIJ_U1U2D0);
  dField_di(dAConfIJ_U1U2D2);
  dField_di(dAConfIJ_U0U2D0);
  dField_di(dAConfIJ_U0U2D1);
  dField_di(dAConfIJ_U0U2D2);
}
