/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "adm_header.h"
void adm_update_adm_KIJ_useAIJ(Patch_T *const patch);
void adm_update_adm_KIJ_useAIJ(Patch_T *const patch)
{

  /* declaring: */
  REALLOC_v_WRITE_v(adm_KIJ_U0U2)
  REALLOC_v_WRITE_v(adm_KIJ_U0U0)
  REALLOC_v_WRITE_v(adm_KIJ_U0U1)
  REALLOC_v_WRITE_v(adm_KIJ_U1U2)
  REALLOC_v_WRITE_v(adm_KIJ_U1U1)
  REALLOC_v_WRITE_v(adm_KIJ_U2U2)
  READ_v(AConfIJ_U0U1)
  READ_v(AConfIJ_U0U0)
  READ_v(AConfIJ_U0U2)
  READ_v(AConfIJ_U2U2)
  READ_v(AConfIJ_U1U1)
  READ_v(AConfIJ_U1U2)
  READ_v(psi)
  READ_v(trK)
  READ_v(igConf_U2U2)
  READ_v(igConf_U1U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)


FOR_ALL_ijk
{
  double psim10 = 
pow(psi[ijk], -10);

  double psim4 = 
pow(psi[ijk], -4);

  double KIJ_U0U1 = 
AConfIJ_U0U1[ijk]*psim10 + (1.0/3.0)*igConf_U0U1[ijk]*psim4*
trK[ijk];

  double KIJ_U0U0 = 
AConfIJ_U0U0[ijk]*psim10 + (1.0/3.0)*igConf_U0U0[ijk]*psim4*
trK[ijk];

  double KIJ_U0U2 = 
AConfIJ_U0U2[ijk]*psim10 + (1.0/3.0)*igConf_U0U2[ijk]*psim4*
trK[ijk];

  double KIJ_U2U2 = 
AConfIJ_U2U2[ijk]*psim10 + (1.0/3.0)*igConf_U2U2[ijk]*psim4*
trK[ijk];

  double KIJ_U1U1 = 
AConfIJ_U1U1[ijk]*psim10 + (1.0/3.0)*igConf_U1U1[ijk]*psim4*
trK[ijk];

  double KIJ_U1U2 = 
AConfIJ_U1U2[ijk]*psim10 + (1.0/3.0)*igConf_U1U2[ijk]*psim4*
trK[ijk];


  /* populating: */
  adm_KIJ_U0U2[ijk] = KIJ_U0U2;
  adm_KIJ_U0U0[ijk] = KIJ_U0U0;
  adm_KIJ_U0U1[ijk] = KIJ_U0U1;
  adm_KIJ_U1U2[ijk] = KIJ_U1U2;
  adm_KIJ_U1U1[ijk] = KIJ_U1U1;
  adm_KIJ_U2U2[ijk] = KIJ_U2U2;
}
}
