/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "adm_header.h"
void adm_update_adm_Kij(Patch_T *const patch);
void adm_update_adm_Kij(Patch_T *const patch)
{

  /* declaring: */
  REALLOC_v_WRITE_v(adm_Kij_D2D2)
  REALLOC_v_WRITE_v(adm_Kij_D0D2)
  REALLOC_v_WRITE_v(adm_Kij_D1D2)
  REALLOC_v_WRITE_v(adm_Kij_D0D0)
  REALLOC_v_WRITE_v(adm_Kij_D0D1)
  REALLOC_v_WRITE_v(adm_Kij_D1D1)
  READ_v(beta_U1)
  READ_v(beta_U0)
  READ_v(beta_U2)
  READ_v(dbeta_U1D0)
  READ_v(dbeta_U2D2)
  READ_v(dbeta_U2D0)
  READ_v(dbeta_U2D1)
  READ_v(dbeta_U0D0)
  READ_v(dbeta_U1D1)
  READ_v(dbeta_U0D1)
  READ_v(dbeta_U0D2)
  READ_v(dbeta_U1D2)
  READ_v(psi)
  READ_v(eta)
  READ_v(trK)
  READ_v(gConf_D0D2)
  READ_v(gConf_D0D0)
  READ_v(gConf_D0D1)
  READ_v(gConf_D1D2)
  READ_v(gConf_D1D1)
  READ_v(gConf_D2D2)
  READ_v(ChrisConf_U1D0D0)
  READ_v(ChrisConf_U0D2D2)
  READ_v(ChrisConf_U1D0D2)
  READ_v(ChrisConf_U2D2D2)
  READ_v(ChrisConf_U2D1D1)
  READ_v(ChrisConf_U2D0D0)
  READ_v(ChrisConf_U1D1D1)
  READ_v(ChrisConf_U0D1D1)
  READ_v(ChrisConf_U0D1D2)
  READ_v(ChrisConf_U1D1D2)
  READ_v(ChrisConf_U0D0D1)
  READ_v(ChrisConf_U0D0D0)
  READ_v(ChrisConf_U2D0D1)
  READ_v(ChrisConf_U0D0D2)
  READ_v(ChrisConf_U2D1D2)
  READ_v(ChrisConf_U1D2D2)
  READ_v(ChrisConf_U2D0D2)
  READ_v(ChrisConf_U1D0D1)


    unsigned nn = patch->nn;
    unsigned ijk;
    for(ijk = 0; ijk < nn; ++ijk)
    {
    double psi4 = 
pow(psi[ijk], 4);

    double _DB_UD_U2D0 = 
ChrisConf_U2D0D0[ijk]*beta_U0[ijk] + ChrisConf_U2D0D1[ijk]*
beta_U1[ijk] + ChrisConf_U2D0D2[ijk]*beta_U2[ijk] + 
dbeta_U2D0[ijk];

    double _DB_UD_U2D1 = 
ChrisConf_U2D0D1[ijk]*beta_U0[ijk] + ChrisConf_U2D1D1[ijk]*
beta_U1[ijk] + ChrisConf_U2D1D2[ijk]*beta_U2[ijk] + 
dbeta_U2D1[ijk];

    double _DB_UD_U2D2 = 
ChrisConf_U2D0D2[ijk]*beta_U0[ijk] + ChrisConf_U2D1D2[ijk]*
beta_U1[ijk] + ChrisConf_U2D2D2[ijk]*beta_U2[ijk] + 
dbeta_U2D2[ijk];

    double _DB_UD_U0D2 = 
ChrisConf_U0D0D2[ijk]*beta_U0[ijk] + ChrisConf_U0D1D2[ijk]*
beta_U1[ijk] + ChrisConf_U0D2D2[ijk]*beta_U2[ijk] + 
dbeta_U0D2[ijk];

    double _DB_UD_U0D0 = 
ChrisConf_U0D0D0[ijk]*beta_U0[ijk] + ChrisConf_U0D0D1[ijk]*
beta_U1[ijk] + ChrisConf_U0D0D2[ijk]*beta_U2[ijk] + 
dbeta_U0D0[ijk];

    double _DB_UD_U0D1 = 
ChrisConf_U0D0D1[ijk]*beta_U0[ijk] + ChrisConf_U0D1D1[ijk]*
beta_U1[ijk] + ChrisConf_U0D1D2[ijk]*beta_U2[ijk] + 
dbeta_U0D1[ijk];

    double _DB_UD_U1D2 = 
ChrisConf_U1D0D2[ijk]*beta_U0[ijk] + ChrisConf_U1D1D2[ijk]*
beta_U1[ijk] + ChrisConf_U1D2D2[ijk]*beta_U2[ijk] + 
dbeta_U1D2[ijk];

    double _DB_UD_U1D1 = 
ChrisConf_U1D0D1[ijk]*beta_U0[ijk] + ChrisConf_U1D1D1[ijk]*
beta_U1[ijk] + ChrisConf_U1D1D2[ijk]*beta_U2[ijk] + 
dbeta_U1D1[ijk];

    double _DB_UD_U1D0 = 
ChrisConf_U1D0D0[ijk]*beta_U0[ijk] + ChrisConf_U1D0D1[ijk]*
beta_U1[ijk] + ChrisConf_U1D0D2[ijk]*beta_U2[ijk] + 
dbeta_U1D0[ijk];

    double _LV_DD_D0D0 = 
2.0*_DB_UD_U0D0*gConf_D0D0[ijk] + 2.0*_DB_UD_U1D0*gConf_D0D1[ijk] + 
2.0*_DB_UD_U2D0*gConf_D0D2[ijk] - 0.66666666666666663*gConf_D0D0[ijk]*
(_DB_UD_U0D0 + _DB_UD_U1D1 + _DB_UD_U2D2);

    double _LV_DD_D1D1 = 
2.0*_DB_UD_U0D1*gConf_D0D1[ijk] + 2.0*_DB_UD_U1D1*gConf_D1D1[ijk] + 
2.0*_DB_UD_U2D1*gConf_D1D2[ijk] - 0.66666666666666663*gConf_D1D1[ijk]*
(_DB_UD_U0D0 + _DB_UD_U1D1 + _DB_UD_U2D2);

    double _LV_DD_D0D1 = 
0.33333333333333331*_DB_UD_U0D0*gConf_D0D1[ijk] + _DB_UD_U0D1*
gConf_D0D0[ijk] + _DB_UD_U1D0*gConf_D1D1[ijk] + 0.33333333333333331*
_DB_UD_U1D1*gConf_D0D1[ijk] + _DB_UD_U2D0*gConf_D1D2[ijk] + 
_DB_UD_U2D1*gConf_D0D2[ijk] - 0.66666666666666663*_DB_UD_U2D2*
gConf_D0D1[ijk];

    double _LV_DD_D0D2 = 
0.33333333333333331*_DB_UD_U0D0*gConf_D0D2[ijk] + _DB_UD_U0D2*
gConf_D0D0[ijk] + _DB_UD_U1D0*gConf_D1D2[ijk] - 0.66666666666666663*
_DB_UD_U1D1*gConf_D0D2[ijk] + _DB_UD_U1D2*gConf_D0D1[ijk] + 
_DB_UD_U2D0*gConf_D2D2[ijk] + 0.33333333333333331*_DB_UD_U2D2*
gConf_D0D2[ijk];

    double _LV_DD_D1D2 = 
-0.66666666666666663*_DB_UD_U0D0*gConf_D1D2[ijk] + _DB_UD_U0D1*
gConf_D0D2[ijk] + _DB_UD_U0D2*gConf_D0D1[ijk] + 0.33333333333333331*
_DB_UD_U1D1*gConf_D1D2[ijk] + _DB_UD_U1D2*gConf_D1D1[ijk] + 
_DB_UD_U2D1*gConf_D2D2[ijk] + 0.33333333333333331*_DB_UD_U2D2*
gConf_D1D2[ijk];

    double _LV_DD_D2D2 = 
2.0*_DB_UD_U0D2*gConf_D0D2[ijk] + 2.0*_DB_UD_U1D2*gConf_D1D2[ijk] + 
2.0*_DB_UD_U2D2*gConf_D2D2[ijk] - 0.66666666666666663*gConf_D2D2[ijk]*
(_DB_UD_U0D0 + _DB_UD_U1D1 + _DB_UD_U2D2);

    double K_DDij_D2D2 = 
psi4*((1.0/2.0)*_LV_DD_D2D2*psi[ijk]/eta[ijk] + 0.33333333333333331*
gConf_D2D2[ijk]*trK[ijk]);

    double K_DDij_D1D1 = 
psi4*((1.0/2.0)*_LV_DD_D1D1*psi[ijk]/eta[ijk] + 0.33333333333333331*
gConf_D1D1[ijk]*trK[ijk]);

    double K_DDij_D0D1 = 
psi4*((1.0/2.0)*_LV_DD_D0D1*psi[ijk]/eta[ijk] + 0.33333333333333331*
gConf_D0D1[ijk]*trK[ijk]);

    double K_DDij_D0D0 = 
psi4*((1.0/2.0)*_LV_DD_D0D0*psi[ijk]/eta[ijk] + 0.33333333333333331*
gConf_D0D0[ijk]*trK[ijk]);

    double K_DDij_D1D2 = 
psi4*((1.0/2.0)*_LV_DD_D1D2*psi[ijk]/eta[ijk] + 0.33333333333333331*
gConf_D1D2[ijk]*trK[ijk]);

    double K_DDij_D0D2 = 
psi4*((1.0/2.0)*_LV_DD_D0D2*psi[ijk]/eta[ijk] + 0.33333333333333331*
gConf_D0D2[ijk]*trK[ijk]);


    /* populating: */
    adm_Kij_D2D2[ijk] = K_DDij_D2D2;
    adm_Kij_D0D2[ijk] = K_DDij_D0D2;
    adm_Kij_D1D2[ijk] = K_DDij_D1D2;
    adm_Kij_D0D0[ijk] = K_DDij_D0D0;
    adm_Kij_D0D1[ijk] = K_DDij_D0D1;
    adm_Kij_D1D1[ijk] = K_DDij_D1D1;
    }/*end of for(ijk = 0; ijk < nn; ++ijk)*/
}
