/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


/* det(g_{ij} dx^i/dN0 dx^j/dN2) */
#include "core_lib.h"
#include "maths_calculus_lib.h"
#include "coordinates_lib.h"
double det_h_xyzN0N2_Cheb_Ext(Patch_T *const patch,const Integration_T *const I,const unsigned ijk);
double det_h_xyzN0N2_Cheb_Ext(Patch_T *const patch,const Integration_T *const I,const unsigned ijk)
{

  /* declaring: */


  const double *const g_D0D0 = I->g00;
  const double *const g_D0D1 = I->g01;
  const double *const g_D0D2 = I->g02;
  const double *const g_D1D1 = I->g11;
  const double *const g_D1D2 = I->g12;
  const double *const g_D2D2 = I->g22;
  const double dx_dN0_U0 = dq2_dq1(patch,_x_,_N0_,ijk);
  const double dx_dN0_U1 = dq2_dq1(patch,_y_,_N0_,ijk);
  const double dx_dN0_U2 = dq2_dq1(patch,_z_,_N0_,ijk);
  const double dx_dN2_U0 = dq2_dq1(patch,_x_,_N2_,ijk);
  const double dx_dN2_U1 = dq2_dq1(patch,_y_,_N2_,ijk);
  const double dx_dN2_U2 = dq2_dq1(patch,_z_,_N2_,ijk);


  double h00 = 
pow(dx_dN0_U0, 2)*g_D0D0[ijk] + 2.0*dx_dN0_U0*dx_dN0_U1*g_D0D1[ijk] +
2.0*dx_dN0_U0*dx_dN0_U2*g_D0D2[ijk] + pow(dx_dN0_U1, 2)*g_D1D1[ijk] +
2.0*dx_dN0_U1*dx_dN0_U2*g_D1D2[ijk] + pow(dx_dN0_U2, 2)*
g_D2D2[ijk];

  double h01 = 
dx_dN0_U0*dx_dN2_U0*g_D0D0[ijk] + dx_dN0_U0*dx_dN2_U1*g_D0D1[ijk] +
dx_dN0_U0*dx_dN2_U2*g_D0D2[ijk] + dx_dN0_U1*dx_dN2_U0*g_D0D1[ijk] +
dx_dN0_U1*dx_dN2_U1*g_D1D1[ijk] + dx_dN0_U1*dx_dN2_U2*g_D1D2[ijk] +
dx_dN0_U2*dx_dN2_U0*g_D0D2[ijk] + dx_dN0_U2*dx_dN2_U1*g_D1D2[ijk] +
dx_dN0_U2*dx_dN2_U2*g_D2D2[ijk];

  double h10 = 
h01;

  double h11 = 
pow(dx_dN2_U0, 2)*g_D0D0[ijk] + 2.0*dx_dN2_U0*dx_dN2_U1*g_D0D1[ijk] +
2.0*dx_dN2_U0*dx_dN2_U2*g_D0D2[ijk] + pow(dx_dN2_U1, 2)*g_D1D1[ijk] +
2.0*dx_dN2_U1*dx_dN2_U2*g_D1D2[ijk] + pow(dx_dN2_U2, 2)*
g_D2D2[ijk];

  double h = 
h00*h11 - h01*h10;

  return h;
}
