/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "dg_header.h"

#define STR_LEN (99)


#define dChristoffel(x) indx = strrchr(#x,'_'); sprintf(fname,"%s%s",dChris,indx); \
    partial_derivative(patch->fields[Ind(fname)]);


void dChristoffel_symbol_3d(Patch_T *const patch,const char *const dChris);
void dChristoffel_symbol_3d(Patch_T *const patch,const char *const dChris)
{
char fname[STR_LEN] = {'\0'};
const char *indx = 0;

  /* declaring: */
  dChristoffel(dChris_U1D0D0D1)
  dChristoffel(dChris_U0D1D1D0)
  dChristoffel(dChris_U1D0D0D2)
  dChristoffel(dChris_U1D0D0D0)
  dChristoffel(dChris_U2D1D1D2)
  dChristoffel(dChris_U2D1D1D0)
  dChristoffel(dChris_U2D1D1D1)
  dChristoffel(dChris_U0D1D1D2)
  dChristoffel(dChris_U2D0D0D1)
  dChristoffel(dChris_U2D1D2D1)
  dChristoffel(dChris_U2D1D2D0)
  dChristoffel(dChris_U2D1D2D2)
  dChristoffel(dChris_U0D2D2D0)
  dChristoffel(dChris_U0D2D2D1)
  dChristoffel(dChris_U0D2D2D2)
  dChristoffel(dChris_U2D0D2D1)
  dChristoffel(dChris_U1D2D2D1)
  dChristoffel(dChris_U1D2D2D0)
  dChristoffel(dChris_U1D2D2D2)
  dChristoffel(dChris_U2D0D2D2)
  dChristoffel(dChris_U0D0D0D0)
  dChristoffel(dChris_U0D0D0D1)
  dChristoffel(dChris_U0D0D0D2)
  dChristoffel(dChris_U1D1D2D2)
  dChristoffel(dChris_U2D0D0D2)
  dChristoffel(dChris_U2D0D2D0)
  dChristoffel(dChris_U0D0D2D2)
  dChristoffel(dChris_U0D1D1D1)
  dChristoffel(dChris_U0D0D2D0)
  dChristoffel(dChris_U0D0D2D1)
  dChristoffel(dChris_U2D2D2D1)
  dChristoffel(dChris_U2D0D1D2)
  dChristoffel(dChris_U2D0D1D1)
  dChristoffel(dChris_U2D0D1D0)
  dChristoffel(dChris_U1D1D2D0)
  dChristoffel(dChris_U0D0D1D1)
  dChristoffel(dChris_U0D0D1D0)
  dChristoffel(dChris_U2D2D2D0)
  dChristoffel(dChris_U0D0D1D2)
  dChristoffel(dChris_U0D1D2D2)
  dChristoffel(dChris_U0D1D2D1)
  dChristoffel(dChris_U0D1D2D0)
  dChristoffel(dChris_U1D0D1D0)
  dChristoffel(dChris_U1D0D1D1)
  dChristoffel(dChris_U1D0D1D2)
  dChristoffel(dChris_U1D1D2D1)
  dChristoffel(dChris_U2D2D2D2)
  dChristoffel(dChris_U1D1D1D1)
  dChristoffel(dChris_U1D1D1D0)
  dChristoffel(dChris_U1D1D1D2)
  dChristoffel(dChris_U2D0D0D0)
  dChristoffel(dChris_U1D0D2D2)
  dChristoffel(dChris_U1D0D2D1)
  dChristoffel(dChris_U1D0D2D0)


}
