/*
  These C codes generated by Cpi version 3.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_curve_exc_T2_ddm_jacobian_bc_alphaPsi(void *vp1,void *vp2);
void *eq_XCTS_curve_exc_T2_ddm_jacobian_bc_alphaPsi(void *vp1,void *vp2)
{
  DDM_SCHUR_JACOBIAN_BC_DECLARE
  Uint ijk,lmn;/* for Jacobian entries J[ijk][lmn] */
  const double kd[2] = {0.,1.};/* Kronecker delta */

  Header_Jacobian
  Init_Jacobian(JalphaPsi_D0)
  Init_Jacobian(JalphaPsi_D1)
  Init_Jacobian(JalphaPsi_D2)
  READ_v(bh_sConf_U0)
  READ_v(bh_sConf_U1)
  READ_v(bh_sConf_U2)
  if (patch->outerB)
  {
  DDM_SCHUR_JACOBIAN_BC_Bpart_OPEN

  double outerB_Bpart =
kd[ijk==lmn];

  B[schur_r][schur_c] = outerB_Bpart;

  DDM_SCHUR_JACOBIAN_BC_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_BC_Epart_OPEN

  double outerB_Epart =
0;

  E_Trans[schur_c][schur_r] = outerB_Epart;

  DDM_SCHUR_JACOBIAN_BC_Epart_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)
  {
  DDM_SCHUR_JACOBIAN_BC_Bpart_OPEN

  double JalphaPsi_D0 = d2f_dxdu_Jacobian(patch,0,ijk,lmn,JalphaPsi_D0);
  double JalphaPsi_D1 = d2f_dxdu_Jacobian(patch,1,ijk,lmn,JalphaPsi_D1);
  double JalphaPsi_D2 = d2f_dxdu_Jacobian(patch,2,ijk,lmn,JalphaPsi_D2);
  double innerB_Bpart =
JalphaPsi_D0*bh_sConf_U0[ijk] + JalphaPsi_D1*bh_sConf_U1[ijk] +
JalphaPsi_D2*bh_sConf_U2[ijk];

  B[schur_r][schur_c] = innerB_Bpart;

  DDM_SCHUR_JACOBIAN_BC_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_BC_Epart_OPEN

  double JalphaPsi_D0 = d2f_dxdu_Jacobian(patch,0,ijk,lmn,JalphaPsi_D0);
  double JalphaPsi_D1 = d2f_dxdu_Jacobian(patch,1,ijk,lmn,JalphaPsi_D1);
  double JalphaPsi_D2 = d2f_dxdu_Jacobian(patch,2,ijk,lmn,JalphaPsi_D2);
  double innerB_Epart =
JalphaPsi_D0*bh_sConf_U0[ijk] + JalphaPsi_D1*bh_sConf_U1[ijk] +
JalphaPsi_D2*bh_sConf_U2[ijk];

  E_Trans[schur_c][schur_r] = innerB_Epart;

  DDM_SCHUR_JACOBIAN_BC_Epart_CLOSE

  }/* end of else if (patch->innerB) */


  Free_Jacobian(JalphaPsi_D0)
  Free_Jacobian(JalphaPsi_D1)
  Free_Jacobian(JalphaPsi_D2)
  Footer_Jacobian

  return 0;
}
