/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_curve_Wolf_ddm_jacobian_bc_phi(void *vp1,void *vp2);
void *eq_XCTS_curve_Wolf_ddm_jacobian_bc_phi(void *vp1,void *vp2)
{
  DDM_SCHUR_JACOBIAN_BC_DECLARE
  Uint ijk,lmn;/* for Jacobian entries J[ijk][lmn] */

  /* declaring: */
  JACOBIAN_DERIVATIVE(Jphi_D1)
  JACOBIAN_DERIVATIVE(Jphi_D0)
  JACOBIAN_DERIVATIVE(Jphi_D2)
  READ_v(drho0_D2)
  READ_v(drho0_D0)
  READ_v(drho0_D1)
  READ_v(psi)
  READ_v(igConf_U2U2)
  READ_v(igConf_U1U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)


  if (patch->outerB)
  {
  DDM_SCHUR_JACOBIAN_BC_Bpart_OPEN

  double outerB_Bpart = 
1.0*(Jphi_D0(j_Jphi_D0,ijk,lmn)*drho0_D0[ijk]*igConf_U0U0[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*drho0_D1[ijk]*igConf_U0U1[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*drho0_D2[ijk]*igConf_U0U2[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*drho0_D0[ijk]*igConf_U0U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*drho0_D1[ijk]*igConf_U1U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*drho0_D2[ijk]*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*drho0_D0[ijk]*igConf_U0U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*drho0_D1[ijk]*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*drho0_D2[ijk]*igConf_U2U2[ijk])/
pow(psi[ijk], 4);

  B[i][j] = outerB_Bpart;

  DDM_SCHUR_JACOBIAN_BC_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_BC_Epart_OPEN

  double outerB_Epart = 
1.0*(Jphi_D0(j_Jphi_D0,ijk,lmn)*drho0_D0[ijk]*igConf_U0U0[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*drho0_D1[ijk]*igConf_U0U1[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*drho0_D2[ijk]*igConf_U0U2[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*drho0_D0[ijk]*igConf_U0U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*drho0_D1[ijk]*igConf_U1U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*drho0_D2[ijk]*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*drho0_D0[ijk]*igConf_U0U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*drho0_D1[ijk]*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*drho0_D2[ijk]*igConf_U2U2[ijk])/
pow(psi[ijk], 4);

  E_Trans[j][i] = outerB_Epart;

  DDM_SCHUR_JACOBIAN_BC_Epart_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)
  {
  DDM_SCHUR_JACOBIAN_BC_Bpart_OPEN

  double innerB_Bpart = 
0;

  B[i][j] = innerB_Bpart;

  DDM_SCHUR_JACOBIAN_BC_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_BC_Epart_OPEN

  double innerB_Epart = 
0;

  E_Trans[j][i] = innerB_Epart;

  DDM_SCHUR_JACOBIAN_BC_Epart_CLOSE

  }/* end of else if (patch->innerB) */

  return 0;
}
