/*
  These C codes generated by Cpi version 3.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_curve_T1_ddm_jacobian_eq_phi(void *vp1,void *vp2);
void *eq_XCTS_curve_T1_ddm_jacobian_eq_phi(void *vp1,void *vp2)
{
  DDM_SCHUR_JACOBIAN_EQ_DECLARE
  Uint ijk,lmn;/* for Jacobian entries J[ijk][lmn] */


  Header_Jacobian
  EQ_Def_Param_Prefix_Char
  EQ_Set_Prefix("NS")

  Init_Jacobian(Jphi_D0)
  Init_Jacobian(Jphi_D1)
  Init_Jacobian(Jphi_D2)
  Init_Jacobian(JJphi_D0D0)
  Init_Jacobian(JJphi_D0D1)
  Init_Jacobian(JJphi_D0D2)
  Init_Jacobian(JJphi_D1D1)
  Init_Jacobian(JJphi_D1D2)
  Init_Jacobian(JJphi_D2D2)
  READ_v(enthalpy)
  READ_v(denthalpy_D0)
  READ_v(denthalpy_D1)
  READ_v(denthalpy_D2)
  READ_v(rho0)
  READ_v(drho0_D0)
  READ_v(drho0_D1)
  READ_v(drho0_D2)
  READ_v(alphaPsi)
  READ_v(dalphaPsi_D0)
  READ_v(dalphaPsi_D1)
  READ_v(dalphaPsi_D2)
  READ_v(psi)
  READ_v(dpsi_D0)
  READ_v(dpsi_D1)
  READ_v(dpsi_D2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U1U2)
  READ_v(igConf_U2U2)
  READ_v(ChrisConf_U0D0D0)
  READ_v(ChrisConf_U0D0D1)
  READ_v(ChrisConf_U0D0D2)
  READ_v(ChrisConf_U0D1D1)
  READ_v(ChrisConf_U0D1D2)
  READ_v(ChrisConf_U0D2D2)
  READ_v(ChrisConf_U1D0D0)
  READ_v(ChrisConf_U1D0D1)
  READ_v(ChrisConf_U1D0D2)
  READ_v(ChrisConf_U1D1D1)
  READ_v(ChrisConf_U1D1D2)
  READ_v(ChrisConf_U1D2D2)
  READ_v(ChrisConf_U2D0D0)
  READ_v(ChrisConf_U2D0D1)
  READ_v(ChrisConf_U2D0D2)
  READ_v(ChrisConf_U2D1D1)
  READ_v(ChrisConf_U2D1D2)
  READ_v(ChrisConf_U2D2D2)
  const double rhoc = Pgetd(EQ_PrefixIt("rho0_center"));
  const double e    = Pgetd(EQ_PrefixIt("Eq_phi_polish"));
  const double att  = e*rhoc;
  DDM_SCHUR_JACOBIAN_EQ_Bpart_OPEN

  double Jphi_D0 = d2f_dxdu_Jacobian(patch,0,ijk,lmn,Jphi_D0);
  double Jphi_D1 = d2f_dxdu_Jacobian(patch,1,ijk,lmn,Jphi_D1);
  double Jphi_D2 = d2f_dxdu_Jacobian(patch,2,ijk,lmn,Jphi_D2);
  double JJphi_D0D0 = d3f_dx2du_Jacobian(patch,0,ijk,lmn,JJphi_D0D0);
  double JJphi_D0D1 = d3f_dx2du_Jacobian(patch,1,ijk,lmn,JJphi_D0D1);
  double JJphi_D0D2 = d3f_dx2du_Jacobian(patch,2,ijk,lmn,JJphi_D0D2);
  double JJphi_D1D1 = d3f_dx2du_Jacobian(patch,3,ijk,lmn,JJphi_D1D1);
  double JJphi_D1D2 = d3f_dx2du_Jacobian(patch,4,ijk,lmn,JJphi_D1D2);
  double JJphi_D2D2 = d3f_dx2du_Jacobian(patch,5,ijk,lmn,JJphi_D2D2);
  double dLn_of_psi_b_U0 =
dpsi_D0[ijk]/psi[ijk];

  double dLn_of_psi_b_U1 =
dpsi_D1[ijk]/psi[ijk];

  double dLn_of_psi_b_U2 =
dpsi_D2[ijk]/psi[ijk];

  double dLn_of_alpha_b_U0 =
-dLn_of_psi_b_U0 + dalphaPsi_D0[ijk]/alphaPsi[ijk];

  double dLn_of_alpha_b_U1 =
-dLn_of_psi_b_U1 + dalphaPsi_D1[ijk]/alphaPsi[ijk];

  double dLn_of_alpha_b_U2 =
-dLn_of_psi_b_U2 + dalphaPsi_D2[ijk]/alphaPsi[ijk];

  double dLn_of_enthalpy_b_U0 =
denthalpy_D0[ijk]/enthalpy[ijk];

  double dLn_of_enthalpy_b_U1 =
denthalpy_D1[ijk]/enthalpy[ijk];

  double dLn_of_enthalpy_b_U2 =
denthalpy_D2[ijk]/enthalpy[ijk];

  double polish_b =
att*pow(rho0[ijk]/rhoc - 1, 4);

  double t1_b =
-(polish_b + rho0[ijk])*(igConf_U0U0[ijk]*(ChrisConf_U0D0D0[ijk]*
Jphi_D0 + ChrisConf_U1D0D0[ijk]*Jphi_D1 + ChrisConf_U2D0D0[ijk]*
Jphi_D2 - JJphi_D0D0) + 2.0*igConf_U0U1[ijk]*(ChrisConf_U0D0D1[ijk]*
Jphi_D0 + ChrisConf_U1D0D1[ijk]*Jphi_D1 + ChrisConf_U2D0D1[ijk]*
Jphi_D2 - JJphi_D0D1) + 2.0*igConf_U0U2[ijk]*(ChrisConf_U0D0D2[ijk]*
Jphi_D0 + ChrisConf_U1D0D2[ijk]*Jphi_D1 + ChrisConf_U2D0D2[ijk]*
Jphi_D2 - JJphi_D0D2) + igConf_U1U1[ijk]*(ChrisConf_U0D1D1[ijk]*
Jphi_D0 + ChrisConf_U1D1D1[ijk]*Jphi_D1 + ChrisConf_U2D1D1[ijk]*
Jphi_D2 - JJphi_D1D1) + 2.0*igConf_U1U2[ijk]*(ChrisConf_U0D1D2[ijk]*
Jphi_D0 + ChrisConf_U1D1D2[ijk]*Jphi_D1 + ChrisConf_U2D1D2[ijk]*
Jphi_D2 - JJphi_D1D2) + igConf_U2U2[ijk]*(ChrisConf_U0D2D2[ijk]*
Jphi_D0 + ChrisConf_U1D2D2[ijk]*Jphi_D1 + ChrisConf_U2D2D2[ijk]*
Jphi_D2 - JJphi_D2D2));

  double t2_b =
Jphi_D0*igConf_U0U0[ijk]*(drho0_D0[ijk] + rho0[ijk]*(dLn_of_alpha_b_U0 -
dLn_of_enthalpy_b_U0 + 2*dLn_of_psi_b_U0)) + Jphi_D0*igConf_U0U1[ijk]*
(drho0_D1[ijk] + rho0[ijk]*(dLn_of_alpha_b_U1 - dLn_of_enthalpy_b_U1 +
2*dLn_of_psi_b_U1)) + Jphi_D0*igConf_U0U2[ijk]*(drho0_D2[ijk] +
rho0[ijk]*(dLn_of_alpha_b_U2 - dLn_of_enthalpy_b_U2 + 2*
dLn_of_psi_b_U2)) + Jphi_D1*igConf_U0U1[ijk]*(drho0_D0[ijk] + rho0[ijk]*
(dLn_of_alpha_b_U0 - dLn_of_enthalpy_b_U0 + 2*dLn_of_psi_b_U0)) +
Jphi_D1*igConf_U1U1[ijk]*(drho0_D1[ijk] + rho0[ijk]*(dLn_of_alpha_b_U1 -
dLn_of_enthalpy_b_U1 + 2*dLn_of_psi_b_U1)) + Jphi_D1*igConf_U1U2[ijk]*
(drho0_D2[ijk] + rho0[ijk]*(dLn_of_alpha_b_U2 - dLn_of_enthalpy_b_U2 +
2*dLn_of_psi_b_U2)) + Jphi_D2*igConf_U0U2[ijk]*(drho0_D0[ijk] +
rho0[ijk]*(dLn_of_alpha_b_U0 - dLn_of_enthalpy_b_U0 + 2*
dLn_of_psi_b_U0)) + Jphi_D2*igConf_U1U2[ijk]*(drho0_D1[ijk] + rho0[ijk]*
(dLn_of_alpha_b_U1 - dLn_of_enthalpy_b_U1 + 2*dLn_of_psi_b_U1)) +
Jphi_D2*igConf_U2U2[ijk]*(drho0_D2[ijk] + rho0[ijk]*(dLn_of_alpha_b_U2 -
dLn_of_enthalpy_b_U2 + 2*dLn_of_psi_b_U2));

  double Bpart_ =
t1_b + t2_b;

  B[schur_ijk][schur_c] = Bpart_;

  DDM_SCHUR_JACOBIAN_EQ_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_EQ_Epart_OPEN

  double Jphi_D0 = d2f_dxdu_Jacobian(patch,0,ijk,lmn,Jphi_D0);
  double Jphi_D1 = d2f_dxdu_Jacobian(patch,1,ijk,lmn,Jphi_D1);
  double Jphi_D2 = d2f_dxdu_Jacobian(patch,2,ijk,lmn,Jphi_D2);
  double JJphi_D0D0 = d3f_dx2du_Jacobian(patch,0,ijk,lmn,JJphi_D0D0);
  double JJphi_D0D1 = d3f_dx2du_Jacobian(patch,1,ijk,lmn,JJphi_D0D1);
  double JJphi_D0D2 = d3f_dx2du_Jacobian(patch,2,ijk,lmn,JJphi_D0D2);
  double JJphi_D1D1 = d3f_dx2du_Jacobian(patch,3,ijk,lmn,JJphi_D1D1);
  double JJphi_D1D2 = d3f_dx2du_Jacobian(patch,4,ijk,lmn,JJphi_D1D2);
  double JJphi_D2D2 = d3f_dx2du_Jacobian(patch,5,ijk,lmn,JJphi_D2D2);
  double dLn_of_psi_e_U0 =
dpsi_D0[ijk]/psi[ijk];

  double dLn_of_psi_e_U1 =
dpsi_D1[ijk]/psi[ijk];

  double dLn_of_psi_e_U2 =
dpsi_D2[ijk]/psi[ijk];

  double dLn_of_alpha_e_U0 =
-dLn_of_psi_e_U0 + dalphaPsi_D0[ijk]/alphaPsi[ijk];

  double dLn_of_alpha_e_U1 =
-dLn_of_psi_e_U1 + dalphaPsi_D1[ijk]/alphaPsi[ijk];

  double dLn_of_alpha_e_U2 =
-dLn_of_psi_e_U2 + dalphaPsi_D2[ijk]/alphaPsi[ijk];

  double dLn_of_enthalpy_e_U0 =
denthalpy_D0[ijk]/enthalpy[ijk];

  double dLn_of_enthalpy_e_U1 =
denthalpy_D1[ijk]/enthalpy[ijk];

  double dLn_of_enthalpy_e_U2 =
denthalpy_D2[ijk]/enthalpy[ijk];

  double polish_e =
att*pow(rho0[ijk]/rhoc - 1, 4);

  double t1_e =
-(polish_e + rho0[ijk])*(igConf_U0U0[ijk]*(ChrisConf_U0D0D0[ijk]*
Jphi_D0 + ChrisConf_U1D0D0[ijk]*Jphi_D1 + ChrisConf_U2D0D0[ijk]*
Jphi_D2 - JJphi_D0D0) + 2.0*igConf_U0U1[ijk]*(ChrisConf_U0D0D1[ijk]*
Jphi_D0 + ChrisConf_U1D0D1[ijk]*Jphi_D1 + ChrisConf_U2D0D1[ijk]*
Jphi_D2 - JJphi_D0D1) + 2.0*igConf_U0U2[ijk]*(ChrisConf_U0D0D2[ijk]*
Jphi_D0 + ChrisConf_U1D0D2[ijk]*Jphi_D1 + ChrisConf_U2D0D2[ijk]*
Jphi_D2 - JJphi_D0D2) + igConf_U1U1[ijk]*(ChrisConf_U0D1D1[ijk]*
Jphi_D0 + ChrisConf_U1D1D1[ijk]*Jphi_D1 + ChrisConf_U2D1D1[ijk]*
Jphi_D2 - JJphi_D1D1) + 2.0*igConf_U1U2[ijk]*(ChrisConf_U0D1D2[ijk]*
Jphi_D0 + ChrisConf_U1D1D2[ijk]*Jphi_D1 + ChrisConf_U2D1D2[ijk]*
Jphi_D2 - JJphi_D1D2) + igConf_U2U2[ijk]*(ChrisConf_U0D2D2[ijk]*
Jphi_D0 + ChrisConf_U1D2D2[ijk]*Jphi_D1 + ChrisConf_U2D2D2[ijk]*
Jphi_D2 - JJphi_D2D2));

  double t2_e =
Jphi_D0*igConf_U0U0[ijk]*(drho0_D0[ijk] + rho0[ijk]*(dLn_of_alpha_e_U0 -
dLn_of_enthalpy_e_U0 + 2*dLn_of_psi_e_U0)) + Jphi_D0*igConf_U0U1[ijk]*
(drho0_D1[ijk] + rho0[ijk]*(dLn_of_alpha_e_U1 - dLn_of_enthalpy_e_U1 +
2*dLn_of_psi_e_U1)) + Jphi_D0*igConf_U0U2[ijk]*(drho0_D2[ijk] +
rho0[ijk]*(dLn_of_alpha_e_U2 - dLn_of_enthalpy_e_U2 + 2*
dLn_of_psi_e_U2)) + Jphi_D1*igConf_U0U1[ijk]*(drho0_D0[ijk] + rho0[ijk]*
(dLn_of_alpha_e_U0 - dLn_of_enthalpy_e_U0 + 2*dLn_of_psi_e_U0)) +
Jphi_D1*igConf_U1U1[ijk]*(drho0_D1[ijk] + rho0[ijk]*(dLn_of_alpha_e_U1 -
dLn_of_enthalpy_e_U1 + 2*dLn_of_psi_e_U1)) + Jphi_D1*igConf_U1U2[ijk]*
(drho0_D2[ijk] + rho0[ijk]*(dLn_of_alpha_e_U2 - dLn_of_enthalpy_e_U2 +
2*dLn_of_psi_e_U2)) + Jphi_D2*igConf_U0U2[ijk]*(drho0_D0[ijk] +
rho0[ijk]*(dLn_of_alpha_e_U0 - dLn_of_enthalpy_e_U0 + 2*
dLn_of_psi_e_U0)) + Jphi_D2*igConf_U1U2[ijk]*(drho0_D1[ijk] + rho0[ijk]*
(dLn_of_alpha_e_U1 - dLn_of_enthalpy_e_U1 + 2*dLn_of_psi_e_U1)) +
Jphi_D2*igConf_U2U2[ijk]*(drho0_D2[ijk] + rho0[ijk]*(dLn_of_alpha_e_U2 -
dLn_of_enthalpy_e_U2 + 2*dLn_of_psi_e_U2));

  double Epart_ =
t1_e + t2_e;

  E_Trans[schur_c][schur_ijk] = Epart_;

  DDM_SCHUR_JACOBIAN_EQ_Epart_CLOSE

  if(patch->grid->kind != Grid_SplitCubedSpherical_BHNS &&
     patch->grid->kind != Grid_SplitCubedSpherical_NSNS &&
     patch->grid->kind != Grid_SplitCubedSpherical_SNS)
    Error0("For this grid you need to figure out where to set phi = 0.\n");


  if(IsItCovering(patch,"left_central_box") || IsItCovering(patch,"right_central_box"))
  {
    const double Att_Con_Num = 1E-5;
    const double NS_center[3] = {Pgetd(EQ_PrefixIt("center_x")),
                                 Pgetd(EQ_PrefixIt("center_y")),
                                 Pgetd(EQ_PrefixIt("center_z"))};
    double X[3] = {0};

    if (X_of_x(X,NS_center,patch))
    {
      fdInterp_dfs_T *const dInterp_df = get_dInterp_df(patch,0,"none");
      const Uint nn = patch->nn;
      double *d_df = alloc_double(nn);
      for (ijk = 0; ijk < nn; ++ijk)
        d_df[ijk] = dInterp_df(patch,X,ijk,0);

      DDM_SCHUR_JACOBIAN_EQ_Bpart_OPEN
      	 B[schur_ijk][schur_c] += Att_Con_Num*d_df[lmn];
      DDM_SCHUR_JACOBIAN_EQ_Bpart_CLOSE

      DDM_SCHUR_JACOBIAN_EQ_Epart_OPEN
        E_Trans[schur_c][schur_ijk] += Att_Con_Num*d_df[lmn];
      DDM_SCHUR_JACOBIAN_EQ_Epart_CLOSE
      free(d_df);
    }
  }

  Free_Jacobian(Jphi_D0)
  Free_Jacobian(Jphi_D1)
  Free_Jacobian(Jphi_D2)
  Free_Jacobian(JJphi_D0D0)
  Free_Jacobian(JJphi_D0D1)
  Free_Jacobian(JJphi_D0D2)
  Free_Jacobian(JJphi_D1D1)
  Free_Jacobian(JJphi_D1D2)
  Free_Jacobian(JJphi_D2D2)
  Footer_Jacobian

  return 0;
}
