/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_curve_exc_T2_ddm_jacobian_bc_alphaPsi(void *vp1,void *vp2);
void *eq_XCTS_curve_exc_T2_ddm_jacobian_bc_alphaPsi(void *vp1,void *vp2)
{
  DDM_SCHUR_JACOBIAN_BC_DECLARE
  Uint ijk,lmn;/* for Jacobian entries J[ijk][lmn] */
  const double kd[2] = {0.,1.};/* Kronecker delta */

  /* declaring: */
  Init_Jacobian(JalphaPsi_D1)
  Init_Jacobian(JalphaPsi_D0)
  Init_Jacobian(JalphaPsi_D2)
  READ_v(bh_sConf_U1)
  READ_v(bh_sConf_U0)
  READ_v(bh_sConf_U2)


  if (patch->outerB)
  {
  DDM_SCHUR_JACOBIAN_BC_Bpart_OPEN

  double outerB_Bpart = 
kd[ijk==lmn];

  B[i][j] = outerB_Bpart;

  DDM_SCHUR_JACOBIAN_BC_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_BC_Epart_OPEN

  double outerB_Epart = 
0;

  E_Trans[j][i] = outerB_Epart;

  DDM_SCHUR_JACOBIAN_BC_Epart_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)
  {
  DDM_SCHUR_JACOBIAN_BC_Bpart_OPEN

  double innerB_Bpart = 
JalphaPsi_D0(j_JalphaPsi_D0,ijk,lmn)*bh_sConf_U0[ijk] +
JalphaPsi_D1(j_JalphaPsi_D1,ijk,lmn)*bh_sConf_U1[ijk] +
JalphaPsi_D2(j_JalphaPsi_D2,ijk,lmn)*bh_sConf_U2[ijk];

  B[i][j] = innerB_Bpart;

  DDM_SCHUR_JACOBIAN_BC_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_BC_Epart_OPEN

  double innerB_Epart = 
JalphaPsi_D0(j_JalphaPsi_D0,ijk,lmn)*bh_sConf_U0[ijk] +
JalphaPsi_D1(j_JalphaPsi_D1,ijk,lmn)*bh_sConf_U1[ijk] +
JalphaPsi_D2(j_JalphaPsi_D2,ijk,lmn)*bh_sConf_U2[ijk];

  E_Trans[j][i] = innerB_Epart;

  DDM_SCHUR_JACOBIAN_BC_Epart_CLOSE

  }/* end of else if (patch->innerB) */

  return 0;
}
