/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_curve_exc_Nmnn_ddm_bc_alphaPsi(void *vp1,void *vp2);
void *eq_XCTS_curve_exc_Nmnn_ddm_bc_alphaPsi(void *vp1,void *vp2)
{
  DDM_SCHUR_BC_DECLARE
  Uint ijk;/* node index */

  /* declaring: */
  READ_v(alphaPsi)
  READ_v(dalphaPsi_D2)
  READ_v(dalphaPsi_D1)
  READ_v(dalphaPsi_D0)
  READ_v(psi)
  READ_v(dpsi_D0)
  READ_v(dpsi_D1)
  READ_v(dpsi_D2)


  if (patch->outerB)/* at outer boundary */
  {
  DDM_SCHUR_BC_OPEN

  double outerB_F = 
alphaPsi[ijk] - 1;

  F[map[ijk]] = outerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)/* at inner boundary */
  {
  EQ_Def_Param_Prefix_Char
  EQ_Set_Prefix("BH")
  const double BH_center[3] = {Pgetd(EQ_PrefixIt("center_x")),
                               Pgetd(EQ_PrefixIt("center_y")),
                               Pgetd(EQ_PrefixIt("center_z"))};

  DDM_SCHUR_BC_OPEN


 double x_U0 = patch->node[ijk]->x[0] - BH_center[0];
 double x_U1 = patch->node[ijk]->x[1] - BH_center[1];
 double x_U2 = patch->node[ijk]->x[2] - BH_center[2];
 double dalpha_dr = 
-x_U0*(alphaPsi[ijk]*dpsi_D0[ijk] - dalphaPsi_D0[ijk]*psi[ijk]) - x_U1*
(alphaPsi[ijk]*dpsi_D1[ijk] - dalphaPsi_D1[ijk]*psi[ijk]) - x_U2*
(alphaPsi[ijk]*dpsi_D2[ijk] - dalphaPsi_D2[ijk]*psi[ijk]);

 double innerB_F = 
dalpha_dr;

  F[map[ijk]] = innerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of else if (patch->innerB) */
  return 0;
}
