/*
  These C codes generated by Cpi version 3.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_flat_exc_T1_ddm_jacobian_eq_B0_U0(void *vp1,void *vp2);
void *eq_XCTS_flat_exc_T1_ddm_jacobian_eq_B0_U0(void *vp1,void *vp2)
{
  DDM_SCHUR_JACOBIAN_EQ_DECLARE
  Uint ijk,lmn;/* for Jacobian entries J[ijk][lmn] */

  Header_Jacobian
  Init_Jacobian(JB0_D0)
  Init_Jacobian(JB0_D1)
  Init_Jacobian(JB0_D2)
  Init_Jacobian(JJB0_D0D0)
  Init_Jacobian(JJB0_D0D1)
  Init_Jacobian(JJB0_D0D2)
  Init_Jacobian(JJB0_D1D1)
  Init_Jacobian(JJB0_D1D2)
  Init_Jacobian(JJB0_D2D2)
  READ_v(psi)
  READ_v_UNUSED(dpsi_D0)
  READ_v_UNUSED(dpsi_D1)
  READ_v_UNUSED(dpsi_D2)
  READ_v(alphaPsi)
  READ_v_UNUSED(dalphaPsi_D0)
  READ_v_UNUSED(dalphaPsi_D1)
  READ_v_UNUSED(dalphaPsi_D2)
  READ_v_UNUSED(igConf_U0U0)
  READ_v_UNUSED(igConf_U0U1)
  READ_v_UNUSED(igConf_U0U2)
  READ_v_UNUSED(igConf_U1U1)
  READ_v_UNUSED(igConf_U1U2)
  READ_v_UNUSED(igConf_U2U2)
  DDM_SCHUR_JACOBIAN_EQ_Bpart_OPEN

  double JB0_D0 = d2f_dxdu_Jacobian(patch,0,ijk,lmn,JB0_D0);
  double JB0_D1 = d2f_dxdu_Jacobian(patch,1,ijk,lmn,JB0_D1);
  double JB0_D2 = d2f_dxdu_Jacobian(patch,2,ijk,lmn,JB0_D2);
  double JJB0_D0D0 = d3f_dx2du_Jacobian(patch,0,ijk,lmn,JJB0_D0D0);
  double JJB0_D0D1 = d3f_dx2du_Jacobian(patch,1,ijk,lmn,JJB0_D0D1);
  double JJB0_D0D2 = d3f_dx2du_Jacobian(patch,2,ijk,lmn,JJB0_D0D2);
  double JJB0_D1D1 = d3f_dx2du_Jacobian(patch,3,ijk,lmn,JJB0_D1D1);
  double JJB0_D1D2 = d3f_dx2du_Jacobian(patch,4,ijk,lmn,JJB0_D1D2);
  double JJB0_D2D2 = d3f_dx2du_Jacobian(patch,5,ijk,lmn,JJB0_D2D2);
  double dLnOf_alpha_B_U0 =
-7*dpsi_D0[ijk]/psi[ijk] + dalphaPsi_D0[ijk]/alphaPsi[ijk];

  double dLnOf_alpha_B_U1 =
-7*dpsi_D1[ijk]/psi[ijk] + dalphaPsi_D1[ijk]/alphaPsi[ijk];

  double dLnOf_alpha_B_U2 =
-7*dpsi_D2[ijk]/psi[ijk] + dalphaPsi_D2[ijk]/alphaPsi[ijk];

  double t1_B_U0 =
JJB0_D0D0*igConf_U0U0[ijk] + 2.0*JJB0_D0D1*igConf_U0U1[ijk] + 2.0*
JJB0_D0D2*igConf_U0U2[ijk] + JJB0_D1D1*igConf_U1U1[ijk] + 2.0*JJB0_D1D2*
igConf_U1U2[ijk] + JJB0_D2D2*igConf_U2U2[ijk];



  double t2_B_U0 =
0.33333333333333331*JJB0_D0D0*igConf_U0U0[ijk] + 0.33333333333333331*
JJB0_D0D1*igConf_U0U1[ijk] + 0.33333333333333331*JJB0_D0D2*
igConf_U0U2[ijk];



  double t3_B_U0 =
0.66666666666666663*JB0_D0*(dLnOf_alpha_B_U0*igConf_U0U0[ijk] +
dLnOf_alpha_B_U1*igConf_U0U1[ijk] + dLnOf_alpha_B_U2*
igConf_U0U2[ijk]);



  double t4_B_U0 =
-JB0_D0*dLnOf_alpha_B_U0*igConf_U0U0[ijk] - JB0_D0*dLnOf_alpha_B_U1*
igConf_U0U1[ijk] - JB0_D0*dLnOf_alpha_B_U2*igConf_U0U2[ijk] - JB0_D1*
dLnOf_alpha_B_U0*igConf_U0U1[ijk] - JB0_D1*dLnOf_alpha_B_U1*
igConf_U1U1[ijk] - JB0_D1*dLnOf_alpha_B_U2*igConf_U1U2[ijk] - JB0_D2*
dLnOf_alpha_B_U0*igConf_U0U2[ijk] - JB0_D2*dLnOf_alpha_B_U1*
igConf_U1U2[ijk] - JB0_D2*dLnOf_alpha_B_U2*igConf_U2U2[ijk];



  double t5_B_U0 =
-dLnOf_alpha_B_U0*(JB0_D0*igConf_U0U0[ijk] + JB0_D1*igConf_U0U1[ijk] +
JB0_D2*igConf_U0U2[ijk]);



  double Bpart_U0 =
t1_B_U0 + t2_B_U0 + t3_B_U0 + t4_B_U0 + t5_B_U0;



  B[schur_ijk][schur_lmn] = Bpart_U0;

  DDM_SCHUR_JACOBIAN_EQ_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_EQ_Epart_OPEN

  double JB0_D0 = d2f_dxdu_Jacobian(patch,0,ijk,lmn,JB0_D0);
  double JB0_D1 = d2f_dxdu_Jacobian(patch,1,ijk,lmn,JB0_D1);
  double JB0_D2 = d2f_dxdu_Jacobian(patch,2,ijk,lmn,JB0_D2);
  double JJB0_D0D0 = d3f_dx2du_Jacobian(patch,0,ijk,lmn,JJB0_D0D0);
  double JJB0_D0D1 = d3f_dx2du_Jacobian(patch,1,ijk,lmn,JJB0_D0D1);
  double JJB0_D0D2 = d3f_dx2du_Jacobian(patch,2,ijk,lmn,JJB0_D0D2);
  double JJB0_D1D1 = d3f_dx2du_Jacobian(patch,3,ijk,lmn,JJB0_D1D1);
  double JJB0_D1D2 = d3f_dx2du_Jacobian(patch,4,ijk,lmn,JJB0_D1D2);
  double JJB0_D2D2 = d3f_dx2du_Jacobian(patch,5,ijk,lmn,JJB0_D2D2);
  double dLnOf_alpha_E_U0 =
-7*dpsi_D0[ijk]/psi[ijk] + dalphaPsi_D0[ijk]/alphaPsi[ijk];

  double dLnOf_alpha_E_U1 =
-7*dpsi_D1[ijk]/psi[ijk] + dalphaPsi_D1[ijk]/alphaPsi[ijk];

  double dLnOf_alpha_E_U2 =
-7*dpsi_D2[ijk]/psi[ijk] + dalphaPsi_D2[ijk]/alphaPsi[ijk];

  double t1_E_U0 =
JJB0_D0D0*igConf_U0U0[ijk] + 2.0*JJB0_D0D1*igConf_U0U1[ijk] + 2.0*
JJB0_D0D2*igConf_U0U2[ijk] + JJB0_D1D1*igConf_U1U1[ijk] + 2.0*JJB0_D1D2*
igConf_U1U2[ijk] + JJB0_D2D2*igConf_U2U2[ijk];



  double t2_E_U0 =
0.33333333333333331*JJB0_D0D0*igConf_U0U0[ijk] + 0.33333333333333331*
JJB0_D0D1*igConf_U0U1[ijk] + 0.33333333333333331*JJB0_D0D2*
igConf_U0U2[ijk];



  double t3_E_U0 =
0.66666666666666663*JB0_D0*(dLnOf_alpha_E_U0*igConf_U0U0[ijk] +
dLnOf_alpha_E_U1*igConf_U0U1[ijk] + dLnOf_alpha_E_U2*
igConf_U0U2[ijk]);



  double t4_E_U0 =
-JB0_D0*dLnOf_alpha_E_U0*igConf_U0U0[ijk] - JB0_D0*dLnOf_alpha_E_U1*
igConf_U0U1[ijk] - JB0_D0*dLnOf_alpha_E_U2*igConf_U0U2[ijk] - JB0_D1*
dLnOf_alpha_E_U0*igConf_U0U1[ijk] - JB0_D1*dLnOf_alpha_E_U1*
igConf_U1U1[ijk] - JB0_D1*dLnOf_alpha_E_U2*igConf_U1U2[ijk] - JB0_D2*
dLnOf_alpha_E_U0*igConf_U0U2[ijk] - JB0_D2*dLnOf_alpha_E_U1*
igConf_U1U2[ijk] - JB0_D2*dLnOf_alpha_E_U2*igConf_U2U2[ijk];



  double t5_E_U0 =
-dLnOf_alpha_E_U0*(JB0_D0*igConf_U0U0[ijk] + JB0_D1*igConf_U0U1[ijk] +
JB0_D2*igConf_U0U2[ijk]);



  double Epart_U0 =
t1_E_U0 + t2_E_U0 + t3_E_U0 + t4_E_U0 + t5_E_U0;



  E_Trans[schur_lmn][schur_ijk] = Epart_U0;

  DDM_SCHUR_JACOBIAN_EQ_Epart_CLOSE


  Free_Jacobian(JB0_D0)
  Free_Jacobian(JB0_D1)
  Free_Jacobian(JB0_D2)
  Free_Jacobian(JJB0_D0D0)
  Free_Jacobian(JJB0_D0D1)
  Free_Jacobian(JJB0_D0D2)
  Free_Jacobian(JJB0_D1D1)
  Free_Jacobian(JJB0_D1D2)
  Free_Jacobian(JJB0_D2D2)
  Footer_Jacobian

  return 0;
}
