/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_curve_T1_ddm_jacobian_eq_phi(void *vp1,void *vp2);
void *eq_XCTS_curve_T1_ddm_jacobian_eq_phi(void *vp1,void *vp2)
{
  DDM_SCHUR_JACOBIAN_EQ_DECLARE
  Uint ijk,lmn;/* for Jacobian entries J[ijk][lmn] */

  EQ_Def_Param_Prefix_Char
  EQ_Set_Prefix("NS")


  /* declaring: */
  JACOBIAN_DERIVATIVE(Jphi_D1)
  JACOBIAN_DERIVATIVE(Jphi_D0)
  JACOBIAN_DERIVATIVE(Jphi_D2)
  JACOBIAN_DERIVATIVE(JJphi_D1D2)
  JACOBIAN_DERIVATIVE(JJphi_D1D1)
  JACOBIAN_DERIVATIVE(JJphi_D0D2)
  JACOBIAN_DERIVATIVE(JJphi_D0D0)
  JACOBIAN_DERIVATIVE(JJphi_D0D1)
  JACOBIAN_DERIVATIVE(JJphi_D2D2)
  READ_v(enthalpy)
  READ_v(denthalpy_D2)
  READ_v(denthalpy_D0)
  READ_v(denthalpy_D1)
  READ_v(rho0)
  READ_v(drho0_D2)
  READ_v(drho0_D0)
  READ_v(drho0_D1)
  READ_v(alphaPsi)
  READ_v(dalphaPsi_D2)
  READ_v(dalphaPsi_D1)
  READ_v(dalphaPsi_D0)
  READ_v(psi)
  READ_v(dpsi_D0)
  READ_v(dpsi_D1)
  READ_v(dpsi_D2)
  READ_v(igConf_U2U2)
  READ_v(igConf_U1U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)
  READ_v(ChrisConf_U1D0D0)
  READ_v(ChrisConf_U0D2D2)
  READ_v(ChrisConf_U1D0D2)
  READ_v(ChrisConf_U2D2D2)
  READ_v(ChrisConf_U2D1D1)
  READ_v(ChrisConf_U2D0D0)
  READ_v(ChrisConf_U1D1D1)
  READ_v(ChrisConf_U0D1D1)
  READ_v(ChrisConf_U0D1D2)
  READ_v(ChrisConf_U1D1D2)
  READ_v(ChrisConf_U0D0D1)
  READ_v(ChrisConf_U0D0D0)
  READ_v(ChrisConf_U2D0D1)
  READ_v(ChrisConf_U0D0D2)
  READ_v(ChrisConf_U2D1D2)
  READ_v(ChrisConf_U1D2D2)
  READ_v(ChrisConf_U2D0D2)
  READ_v(ChrisConf_U1D0D1)


  const double rhoc = Pgetd(EQ_PrefixIt("rho_center"));
  const double e    = Pgetd(EQ_PrefixIt("Eq_phi_polish"));
  const double att  = e*rhoc;
  DDM_SCHUR_JACOBIAN_EQ_Bpart_OPEN

  double dLn_of_alpha_b__U2 = 
-dpsi_D2[ijk]/psi[ijk] + dalphaPsi_D2[ijk]/alphaPsi[ijk];

  double dLn_of_alpha_b__U1 = 
-dpsi_D1[ijk]/psi[ijk] + dalphaPsi_D1[ijk]/alphaPsi[ijk];

  double dLn_of_alpha_b__U0 = 
-dpsi_D0[ijk]/psi[ijk] + dalphaPsi_D0[ijk]/alphaPsi[ijk];

  double dLn_of_enthalpy_b__U1 = 
denthalpy_D1[ijk]/enthalpy[ijk];

  double dLn_of_enthalpy_b__U0 = 
denthalpy_D0[ijk]/enthalpy[ijk];

  double dLn_of_enthalpy_b__U2 = 
denthalpy_D2[ijk]/enthalpy[ijk];

  double dLns0_b__U2 = 
drho0_D2[ijk] + rho0[ijk]*(dLn_of_alpha_b__U2 - dLn_of_enthalpy_b__U2);

  double dLns0_b__U0 = 
drho0_D0[ijk] + rho0[ijk]*(dLn_of_alpha_b__U0 - dLn_of_enthalpy_b__U0);

  double dLns0_b__U1 = 
drho0_D1[ijk] + rho0[ijk]*(dLn_of_alpha_b__U1 - dLn_of_enthalpy_b__U1);

  double t1_b_ = 
1.0*(Jphi_D0(j_Jphi_D0,ijk,lmn)*dLns0_b__U0*igConf_U0U0[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*dLns0_b__U1*igConf_U0U1[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*dLns0_b__U2*igConf_U0U2[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dLns0_b__U0*igConf_U0U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dLns0_b__U1*igConf_U1U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dLns0_b__U2*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dLns0_b__U0*igConf_U0U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dLns0_b__U1*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dLns0_b__U2*igConf_U2U2[ijk])/
pow(psi[ijk], 4);

  double t2_b_ = 
2.0*(Jphi_D0(j_Jphi_D0,ijk,lmn)*dpsi_D0[ijk]*igConf_U0U0[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*dpsi_D1[ijk]*igConf_U0U1[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*dpsi_D2[ijk]*igConf_U0U2[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dpsi_D0[ijk]*igConf_U0U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dpsi_D1[ijk]*igConf_U1U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dpsi_D2[ijk]*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dpsi_D0[ijk]*igConf_U0U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dpsi_D1[ijk]*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dpsi_D2[ijk]*igConf_U2U2[ijk])/
pow(psi[ijk], 5);

  double t3_b_ = 
-(igConf_U0U0[ijk]*(ChrisConf_U0D0D0[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D0D0[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D0D0[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D0D0(j_JJphi_D0D0,ijk,lmn)) + 2.0*
igConf_U0U1[ijk]*(ChrisConf_U0D0D1[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D0D1[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D0D1[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D0D1(j_JJphi_D0D1,ijk,lmn)) + 2.0*
igConf_U0U2[ijk]*(ChrisConf_U0D0D2[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D0D2[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D0D2[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D0D2(j_JJphi_D0D2,ijk,lmn)) +
igConf_U1U1[ijk]*(ChrisConf_U0D1D1[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D1D1[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D1D1[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D1D1(j_JJphi_D1D1,ijk,lmn)) + 2.0*
igConf_U1U2[ijk]*(ChrisConf_U0D1D2[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D1D2[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D1D2[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D1D2(j_JJphi_D1D2,ijk,lmn)) +
igConf_U2U2[ijk]*(ChrisConf_U0D2D2[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D2D2[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D2D2[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D2D2(j_JJphi_D2D2,ijk,lmn)))/
pow(psi[ijk], 4);

  double Bpart_ = 
att*t3_b_*pow(rho0[ijk]/rhoc - 1, 4) + rho0[ijk]*(t2_b_ + t3_b_) +
t1_b_;

  B[i][j] = Bpart_;

  DDM_SCHUR_JACOBIAN_EQ_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_EQ_Epart_OPEN

  double dLn_of_alpha_e__U0 = 
-dpsi_D0[ijk]/psi[ijk] + dalphaPsi_D0[ijk]/alphaPsi[ijk];

  double dLn_of_alpha_e__U1 = 
-dpsi_D1[ijk]/psi[ijk] + dalphaPsi_D1[ijk]/alphaPsi[ijk];

  double dLn_of_alpha_e__U2 = 
-dpsi_D2[ijk]/psi[ijk] + dalphaPsi_D2[ijk]/alphaPsi[ijk];

  double dLn_of_enthalpy_e__U2 = 
denthalpy_D2[ijk]/enthalpy[ijk];

  double dLn_of_enthalpy_e__U0 = 
denthalpy_D0[ijk]/enthalpy[ijk];

  double dLn_of_enthalpy_e__U1 = 
denthalpy_D1[ijk]/enthalpy[ijk];

  double dLns0_e__U1 = 
drho0_D1[ijk] + rho0[ijk]*(dLn_of_alpha_e__U1 - dLn_of_enthalpy_e__U1);

  double dLns0_e__U0 = 
drho0_D0[ijk] + rho0[ijk]*(dLn_of_alpha_e__U0 - dLn_of_enthalpy_e__U0);

  double dLns0_e__U2 = 
drho0_D2[ijk] + rho0[ijk]*(dLn_of_alpha_e__U2 - dLn_of_enthalpy_e__U2);

  double t1_e_ = 
1.0*(Jphi_D0(j_Jphi_D0,ijk,lmn)*dLns0_e__U0*igConf_U0U0[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*dLns0_e__U1*igConf_U0U1[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*dLns0_e__U2*igConf_U0U2[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dLns0_e__U0*igConf_U0U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dLns0_e__U1*igConf_U1U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dLns0_e__U2*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dLns0_e__U0*igConf_U0U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dLns0_e__U1*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dLns0_e__U2*igConf_U2U2[ijk])/
pow(psi[ijk], 4);

  double t2_e_ = 
2.0*(Jphi_D0(j_Jphi_D0,ijk,lmn)*dpsi_D0[ijk]*igConf_U0U0[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*dpsi_D1[ijk]*igConf_U0U1[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*dpsi_D2[ijk]*igConf_U0U2[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dpsi_D0[ijk]*igConf_U0U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dpsi_D1[ijk]*igConf_U1U1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*dpsi_D2[ijk]*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dpsi_D0[ijk]*igConf_U0U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dpsi_D1[ijk]*igConf_U1U2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*dpsi_D2[ijk]*igConf_U2U2[ijk])/
pow(psi[ijk], 5);

  double t3_e_ = 
-(igConf_U0U0[ijk]*(ChrisConf_U0D0D0[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D0D0[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D0D0[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D0D0(j_JJphi_D0D0,ijk,lmn)) + 2.0*
igConf_U0U1[ijk]*(ChrisConf_U0D0D1[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D0D1[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D0D1[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D0D1(j_JJphi_D0D1,ijk,lmn)) + 2.0*
igConf_U0U2[ijk]*(ChrisConf_U0D0D2[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D0D2[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D0D2[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D0D2(j_JJphi_D0D2,ijk,lmn)) +
igConf_U1U1[ijk]*(ChrisConf_U0D1D1[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D1D1[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D1D1[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D1D1(j_JJphi_D1D1,ijk,lmn)) + 2.0*
igConf_U1U2[ijk]*(ChrisConf_U0D1D2[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D1D2[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D1D2[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D1D2(j_JJphi_D1D2,ijk,lmn)) +
igConf_U2U2[ijk]*(ChrisConf_U0D2D2[ijk]*Jphi_D0(j_Jphi_D0,ijk,lmn) +
ChrisConf_U1D2D2[ijk]*Jphi_D1(j_Jphi_D1,ijk,lmn) + ChrisConf_U2D2D2[ijk]*
Jphi_D2(j_Jphi_D2,ijk,lmn) - JJphi_D2D2(j_JJphi_D2D2,ijk,lmn)))/
pow(psi[ijk], 4);

  double Epart_ = 
att*t3_e_*pow(rho0[ijk]/rhoc - 1, 4) + rho0[ijk]*(t2_e_ + t3_e_) +
t1_e_;

  E_Trans[j][i] = Epart_;

  DDM_SCHUR_JACOBIAN_EQ_Epart_CLOSE

  if(patch->grid->kind != Grid_SplitCubedSpherical_BHNS &&
     patch->grid->kind != Grid_SplitCubedSpherical_NSNS &&
     patch->grid->kind != Grid_SplitCubedSpherical_SNS)
    Error0("For this grid you need to figure out where to set phi = 0.\n");


  if(IsItCovering(patch,"left_central_box") || IsItCovering(patch,"right_central_box"))
  {
    const double Att_Con_Num = 1E-5;
    const double NS_center[3] = {Pgetd(EQ_PrefixIt("center_x")),
                                 Pgetd(EQ_PrefixIt("center_y")),
                                 Pgetd(EQ_PrefixIt("center_z"))};
    double X[3] = {0};

    if (X_of_x(X,NS_center,patch))
    {
      fdInterp_dfs_T *const dInterp_df = get_dInterp_df(patch,0,"none");
      const Uint nn = patch->nn;
      double *d_df = alloc_double(nn);
      for (ijk = 0; ijk < nn; ++ijk)
        d_df[ijk] = dInterp_df(patch,X,ijk,0);

      for (i = 0; i < Ni; ++i)
      {
        for (j = 0; j < Nj; ++j)
        {
         lmn = node[j];
         B[i][j] += Att_Con_Num*d_df[lmn];
        }
      }

      if (S->NI)/* if there is any interface points then E is needed */
      {
        E_Trans = S->E_Trans->reg->A;
        for (k = K0; k < Nk; ++k)
        {
          lmn = node[k];
          j = k-K0;
          for (i = 0; i < Ni; ++i)
          {
            E_Trans[j][i] += Att_Con_Num*d_df[lmn];
          }
        }
      }/* end of if (S->NI) */
      free(d_df);
    }
  }
  return 0;
}
