/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_curve_exc_KS_ddm_bc_B0_U2(void *vp1,void *vp2);
void *eq_XCTS_curve_exc_KS_ddm_bc_B0_U2(void *vp1,void *vp2)
{
  DDM_SCHUR_BC_DECLARE
  Uint ijk;/* node index */

  /* declaring: */
  READ_v(B0_U2)
  READ_v(B1_U2)
  READ_v(psi)
  READ_v(alphaPsi)
  READ_v(bh_sConf_U2)


  if (patch->outerB)/* at outer boundary */
  {
  EQ_Def_Param_Prefix_Char
  EQ_Set_Prefix("BH")

  const double v2_boost = Pgetd(EQ_PrefixIt("boost_z"));
  DDM_SCHUR_BC_OPEN

  double outerB_F = 
B0_U2[ijk] - v2_boost;

  F[map[ijk]] = outerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)/* at inner boundary */
  {
  EQ_Def_Param_Prefix_Char
  EQ_Set_Prefix("BH")

  const double BH_center_x = Pgetd(EQ_PrefixIt("center_x"));
  const double BH_center_y = Pgetd(EQ_PrefixIt("center_y"));
  const double BH_Omega_U0 = Pgetd(EQ_PrefixIt("Omega_x"));
  const double BH_Omega_U1 = Pgetd(EQ_PrefixIt("Omega_y"));

  DDM_SCHUR_BC_OPEN

  double alpha = 
alphaPsi[ijk]/psi[ijk];

  double S_U2 = 
bh_sConf_U2[ijk]/pow(psi[ijk], 2);

  double x = patch->node[ijk]->x[0]-BH_center_x;
  double y = patch->node[ijk]->x[1]-BH_center_y;
  double OmegaXr_U2 = 
BH_Omega_U0*y - BH_Omega_U1*x;

  double innerB_F = 
B0_U2[ijk] + B1_U2[ijk] - OmegaXr_U2 - S_U2*alpha;

  F[map[ijk]] = innerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of else if (patch->innerB) */
  return 0;
}
