/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_curve_Wolf_ddm_bc_phi(void *vp1,void *vp2);
void *eq_XCTS_curve_Wolf_ddm_bc_phi(void *vp1,void *vp2)
{
  DDM_SCHUR_BC_DECLARE
  Uint ijk;/* node index */

  /* declaring: */
  READ_v(dphi_D2)
  READ_v(dphi_D1)
  READ_v(dphi_D0)
  READ_v(W_U1)
  READ_v(W_U0)
  READ_v(W_U2)
  READ_v(enthalpy)
  READ_v(drho0_D2)
  READ_v(drho0_D0)
  READ_v(drho0_D1)
  READ_v(u0)
  READ_v(psi)
  READ_v(beta_U1)
  READ_v(beta_U0)
  READ_v(beta_U2)
  READ_v(igConf_U2U2)
  READ_v(igConf_U1U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)


  if (patch->outerB)/* at outer boundary */
  {
  DDM_SCHUR_BC_OPEN

  double outerB_F = 
1.0*(dphi_D0[ijk]*drho0_D0[ijk]*igConf_U0U0[ijk] + dphi_D0[ijk]*
drho0_D1[ijk]*igConf_U0U1[ijk] + dphi_D0[ijk]*drho0_D2[ijk]*
igConf_U0U2[ijk] + dphi_D1[ijk]*drho0_D0[ijk]*igConf_U0U1[ijk] +
dphi_D1[ijk]*drho0_D1[ijk]*igConf_U1U1[ijk] + dphi_D1[ijk]*
drho0_D2[ijk]*igConf_U1U2[ijk] + dphi_D2[ijk]*drho0_D0[ijk]*
igConf_U0U2[ijk] + dphi_D2[ijk]*drho0_D1[ijk]*igConf_U1U2[ijk] +
dphi_D2[ijk]*drho0_D2[ijk]*igConf_U2U2[ijk] + pow(psi[ijk], 4)*
(W_U0[ijk]*drho0_D0[ijk] + W_U1[ijk]*drho0_D1[ijk] + W_U2[ijk]*
drho0_D2[ijk] - enthalpy[ijk]*u0[ijk]*(beta_U0[ijk]*drho0_D0[ijk] +
beta_U1[ijk]*drho0_D1[ijk] + beta_U2[ijk]*drho0_D2[ijk])))/
pow(psi[ijk], 4);

  F[map[ijk]] = outerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)/* at inner boundary */
  {
  DDM_SCHUR_BC_OPEN

  double innerB_F = 
0;

  F[map[ijk]] = innerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of else if (patch->innerB) */
  return 0;
}
