/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_curve_T2_ddm_eq_phi(void *vp1,void *vp2);
void *eq_XCTS_curve_T2_ddm_eq_phi(void *vp1,void *vp2)
{
  DDM_SCHUR_EQ_DECLARE
  Uint ijk;/* node index */

  EQ_Def_Param_Prefix_Char
  EQ_Set_Prefix("NS")


  /* declaring: */
  READ_v(dphi_D2)
  READ_v(dphi_D1)
  READ_v(dphi_D0)
  READ_v(ddphi_D2D2)
  READ_v(ddphi_D1D2)
  READ_v(ddphi_D1D1)
  READ_v(ddphi_D0D2)
  READ_v(ddphi_D0D0)
  READ_v(ddphi_D0D1)
  READ_v(W_U1)
  READ_v(W_U0)
  READ_v(W_U2)
  READ_v(enthalpy)
  READ_v(denthalpy_D2)
  READ_v(denthalpy_D0)
  READ_v(denthalpy_D1)
  READ_v(rho0)
  READ_v(drho0_D2)
  READ_v(drho0_D0)
  READ_v(drho0_D1)
  READ_v(u0)
  READ_v(du0_D0)
  READ_v(du0_D1)
  READ_v(du0_D2)
  READ_v(alphaPsi)
  READ_v(dalphaPsi_D2)
  READ_v(dalphaPsi_D1)
  READ_v(dalphaPsi_D0)
  READ_v(psi)
  READ_v(dpsi_D0)
  READ_v(dpsi_D1)
  READ_v(dpsi_D2)
  READ_v(trK)
  READ_v(beta_U1)
  READ_v(beta_U0)
  READ_v(beta_U2)
  READ_v(dbeta_U1D0)
  READ_v(dbeta_U2D2)
  READ_v(dbeta_U2D0)
  READ_v(dbeta_U2D1)
  READ_v(dbeta_U0D0)
  READ_v(dbeta_U1D1)
  READ_v(dbeta_U0D1)
  READ_v(dbeta_U0D2)
  READ_v(dbeta_U1D2)
  READ_v(igConf_U2U2)
  READ_v(igConf_U1U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)
  READ_v(ChrisConf_U1D0D0)
  READ_v(ChrisConf_U0D2D2)
  READ_v(ChrisConf_U1D0D2)
  READ_v(ChrisConf_U2D2D2)
  READ_v(ChrisConf_U2D1D1)
  READ_v(ChrisConf_U2D0D0)
  READ_v(ChrisConf_U1D1D1)
  READ_v(ChrisConf_U0D1D1)
  READ_v(ChrisConf_U0D1D2)
  READ_v(ChrisConf_U1D1D2)
  READ_v(ChrisConf_U0D0D1)
  READ_v(ChrisConf_U0D0D0)
  READ_v(ChrisConf_U2D0D1)
  READ_v(ChrisConf_U0D0D2)
  READ_v(ChrisConf_U2D1D2)
  READ_v(ChrisConf_U1D2D2)
  READ_v(ChrisConf_U2D0D2)
  READ_v(ChrisConf_U1D0D1)


  const double rhoc = Pgetd(EQ_PrefixIt("rho_center"));
  const double e    = Pgetd(EQ_PrefixIt("Eq_phi_polish"));
  const double att  = e*rhoc;
  DDM_SCHUR_EQ_OPEN

  double dLn_of_psi_U0 = 
dpsi_D0[ijk]/psi[ijk];

  double dLn_of_psi_U1 = 
dpsi_D1[ijk]/psi[ijk];

  double dLn_of_psi_U2 = 
dpsi_D2[ijk]/psi[ijk];

  double dLn_of_alpha_U2 = 
-dLn_of_psi_U2 + dalphaPsi_D2[ijk]/alphaPsi[ijk];

  double dLn_of_alpha_U0 = 
-dLn_of_psi_U0 + dalphaPsi_D0[ijk]/alphaPsi[ijk];

  double dLn_of_alpha_U1 = 
-dLn_of_psi_U1 + dalphaPsi_D1[ijk]/alphaPsi[ijk];

  double dLn_of_enthalpy_U0 = 
denthalpy_D0[ijk]/enthalpy[ijk];

  double dLn_of_enthalpy_U1 = 
denthalpy_D1[ijk]/enthalpy[ijk];

  double dLn_of_enthalpy_U2 = 
denthalpy_D2[ijk]/enthalpy[ijk];

  double dLn_of_u0_U2 = 
du0_D2[ijk]/u0[ijk];

  double dLn_of_u0_U0 = 
du0_D0[ijk]/u0[ijk];

  double dLn_of_u0_U1 = 
du0_D1[ijk]/u0[ijk];

  double psi4 = 
pow(psi[ijk], 4);

  double alpha = 
alphaPsi[ijk]/psi[ijk];

  double polish = 
att*pow(rho0[ijk]/rhoc - 1, 4);

  double hxu0xpsi4 = 
enthalpy[ijk]*psi4*u0[ijk];

  double DiBi = 
ChrisConf_U0D0D0[ijk]*beta_U0[ijk] + ChrisConf_U0D0D1[ijk]*
beta_U1[ijk] + ChrisConf_U0D0D2[ijk]*beta_U2[ijk] + ChrisConf_U1D0D1[ijk]*
beta_U0[ijk] + ChrisConf_U1D1D1[ijk]*beta_U1[ijk] + ChrisConf_U1D1D2[ijk]*
beta_U2[ijk] + ChrisConf_U2D0D2[ijk]*beta_U0[ijk] + ChrisConf_U2D1D2[ijk]*
beta_U1[ijk] + ChrisConf_U2D2D2[ijk]*beta_U2[ijk] + 6.0*beta_U0[ijk]*
dLn_of_psi_U0 + 6.0*beta_U1[ijk]*dLn_of_psi_U1 + 6.0*beta_U2[ijk]*
dLn_of_psi_U2 + dbeta_U0D0[ijk] + dbeta_U1D1[ijk] + dbeta_U2D2[ijk];

  double t1 = 
-igConf_U0U0[ijk]*(ChrisConf_U0D0D0[ijk]*dphi_D0[ijk] +
ChrisConf_U1D0D0[ijk]*dphi_D1[ijk] + ChrisConf_U2D0D0[ijk]*
dphi_D2[ijk] - ddphi_D0D0[ijk]) - 2.0*igConf_U0U1[ijk]*
(ChrisConf_U0D0D1[ijk]*dphi_D0[ijk] + ChrisConf_U1D0D1[ijk]*
dphi_D1[ijk] + ChrisConf_U2D0D1[ijk]*dphi_D2[ijk] - ddphi_D0D1[ijk]) -
2.0*igConf_U0U2[ijk]*(ChrisConf_U0D0D2[ijk]*dphi_D0[ijk] +
ChrisConf_U1D0D2[ijk]*dphi_D1[ijk] + ChrisConf_U2D0D2[ijk]*
dphi_D2[ijk] - ddphi_D0D2[ijk]) - igConf_U1U1[ijk]*(ChrisConf_U0D1D1[ijk]*
dphi_D0[ijk] + ChrisConf_U1D1D1[ijk]*dphi_D1[ijk] + ChrisConf_U2D1D1[ijk]*
dphi_D2[ijk] - ddphi_D1D1[ijk]) - 2.0*igConf_U1U2[ijk]*
(ChrisConf_U0D1D2[ijk]*dphi_D0[ijk] + ChrisConf_U1D1D2[ijk]*
dphi_D1[ijk] + ChrisConf_U2D1D2[ijk]*dphi_D2[ijk] - ddphi_D1D2[ijk]) -
igConf_U2U2[ijk]*(ChrisConf_U0D2D2[ijk]*dphi_D0[ijk] +
ChrisConf_U1D2D2[ijk]*dphi_D1[ijk] + ChrisConf_U2D2D2[ijk]*
dphi_D2[ijk] - ddphi_D2D2[ijk]);

  double t2 = 
dphi_D0[ijk]*igConf_U0U0[ijk]*(dLn_of_alpha_U0 - dLn_of_enthalpy_U0 +
2.0*dLn_of_psi_U0) + dphi_D0[ijk]*igConf_U0U1[ijk]*(dLn_of_alpha_U1 -
dLn_of_enthalpy_U1 + 2.0*dLn_of_psi_U1) + dphi_D0[ijk]*igConf_U0U2[ijk]*
(dLn_of_alpha_U2 - dLn_of_enthalpy_U2 + 2.0*dLn_of_psi_U2) +
dphi_D1[ijk]*igConf_U0U1[ijk]*(dLn_of_alpha_U0 - dLn_of_enthalpy_U0 +
2.0*dLn_of_psi_U0) + dphi_D1[ijk]*igConf_U1U1[ijk]*(dLn_of_alpha_U1 -
dLn_of_enthalpy_U1 + 2.0*dLn_of_psi_U1) + dphi_D1[ijk]*igConf_U1U2[ijk]*
(dLn_of_alpha_U2 - dLn_of_enthalpy_U2 + 2.0*dLn_of_psi_U2) +
dphi_D2[ijk]*igConf_U0U2[ijk]*(dLn_of_alpha_U0 - dLn_of_enthalpy_U0 +
2.0*dLn_of_psi_U0) + dphi_D2[ijk]*igConf_U1U2[ijk]*(dLn_of_alpha_U1 -
dLn_of_enthalpy_U1 + 2.0*dLn_of_psi_U1) + dphi_D2[ijk]*igConf_U2U2[ijk]*
(dLn_of_alpha_U2 - dLn_of_enthalpy_U2 + 2.0*dLn_of_psi_U2);

  double t3 = 
psi4*(W_U0[ijk]*(ChrisConf_U0D0D0[ijk] + ChrisConf_U1D0D1[ijk] +
ChrisConf_U2D0D2[ijk] + dLn_of_alpha_U0 - dLn_of_enthalpy_U0 + 6*
dLn_of_psi_U0) + W_U1[ijk]*(ChrisConf_U0D0D1[ijk] + ChrisConf_U1D1D1[ijk] +
ChrisConf_U2D1D2[ijk] + dLn_of_alpha_U1 - dLn_of_enthalpy_U1 + 6*
dLn_of_psi_U1) + W_U2[ijk]*(ChrisConf_U0D0D2[ijk] + ChrisConf_U1D1D2[ijk] +
ChrisConf_U2D2D2[ijk] + dLn_of_alpha_U2 - dLn_of_enthalpy_U2 + 6*
dLn_of_psi_U2));

  double t4 = 
-hxu0xpsi4*(beta_U0[ijk]*(dLn_of_alpha_U0 + dLn_of_u0_U0) +
beta_U1[ijk]*(dLn_of_alpha_U1 + dLn_of_u0_U1) + beta_U2[ijk]*
(dLn_of_alpha_U2 + dLn_of_u0_U2));

  double t5 = 
-DiBi*hxu0xpsi4;

  double t6_U2 = 
W_U2[ijk]*psi4 - beta_U2[ijk]*hxu0xpsi4 + dphi_D0[ijk]*
igConf_U0U2[ijk] + dphi_D1[ijk]*igConf_U1U2[ijk] + dphi_D2[ijk]*
igConf_U2U2[ijk];

  double t6_U1 = 
W_U1[ijk]*psi4 - beta_U1[ijk]*hxu0xpsi4 + dphi_D0[ijk]*
igConf_U0U1[ijk] + dphi_D1[ijk]*igConf_U1U1[ijk] + dphi_D2[ijk]*
igConf_U1U2[ijk];

  double t6_U0 = 
W_U0[ijk]*psi4 - beta_U0[ijk]*hxu0xpsi4 + dphi_D0[ijk]*
igConf_U0U0[ijk] + dphi_D1[ijk]*igConf_U0U1[ijk] + dphi_D2[ijk]*
igConf_U0U2[ijk];

  double F_eq = 
drho0_D0[ijk]*t6_U0 + drho0_D1[ijk]*t6_U1 + drho0_D2[ijk]*t6_U2 +
polish*t1 + rho0[ijk]*(t1 + t2 + t3 + t4 + t5);

  F[n] = F_eq;

  DDM_SCHUR_EQ_CLOSE

  if(patch->grid->kind != Grid_SplitCubedSpherical_BHNS &&
     patch->grid->kind != Grid_SplitCubedSpherical_NSNS &&
     patch->grid->kind != Grid_SplitCubedSpherical_SNS)
    Error0("For this grid you need to figure out where to set phi = 0.\n");


  if(IsItCovering(patch,"left_central_box") || IsItCovering(patch,"right_central_box"))
  {
    const double Att_Con_Num = 1E-5;
    const double NS_center[3] = {Pgetd(EQ_PrefixIt("center_x")),
                                 Pgetd(EQ_PrefixIt("center_y")),
                                 Pgetd(EQ_PrefixIt("center_z"))};
    double interp;
    double X[3] = {0};

    if (X_of_x(X,NS_center,patch))
    {
      Interpolation_T *interp_phi0 = init_interpolation();
      interp_phi0->field = patch->fields[Ind("phi")];
      interp_phi0->X = X[0];
      interp_phi0->Y = X[1];
      interp_phi0->Z = X[2];
      interp_phi0->XYZ_dir_flag = 1;
      plan_interpolation(interp_phi0);
      interp = execute_interpolation(interp_phi0);
      free_interpolation(interp_phi0);
      for (n = 0; n < N; ++n)
	 F[n] += Att_Con_Num*interp;
   }
   
  }
  return 0;
}
