/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "eq_header.h"
#include "maths_equation_solvings_lib.h"

void *eq_XCTS_curve_exc_KS_ddm_eq_psi(void *vp1,void *vp2);
void *eq_XCTS_curve_exc_KS_ddm_eq_psi(void *vp1,void *vp2)
{
  DDM_SCHUR_EQ_DECLARE
  Uint ijk;/* node index */

  /* declaring: */
  READ_v(psi)
  READ_v(dpsi_D0)
  READ_v(dpsi_D1)
  READ_v(dpsi_D2)
  READ_v(ddpsi_D2D2)
  READ_v(ddpsi_D0D0)
  READ_v(ddpsi_D0D1)
  READ_v(ddpsi_D1D1)
  READ_v(ddpsi_D1D2)
  READ_v(ddpsi_D0D2)
  READ_v(trRicciConf)
  READ_v(trK)
  READ_v(AConfIJ2)
  READ_v(EConf)
  READ_v(igConf_U2U2)
  READ_v(igConf_U1U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)
  READ_v(ChrisConf_U1D0D0)
  READ_v(ChrisConf_U0D2D2)
  READ_v(ChrisConf_U1D0D2)
  READ_v(ChrisConf_U2D2D2)
  READ_v(ChrisConf_U2D1D1)
  READ_v(ChrisConf_U2D0D0)
  READ_v(ChrisConf_U1D1D1)
  READ_v(ChrisConf_U0D1D1)
  READ_v(ChrisConf_U0D1D2)
  READ_v(ChrisConf_U1D1D2)
  READ_v(ChrisConf_U0D0D1)
  READ_v(ChrisConf_U0D0D0)
  READ_v(ChrisConf_U2D0D1)
  READ_v(ChrisConf_U0D0D2)
  READ_v(ChrisConf_U2D1D2)
  READ_v(ChrisConf_U1D2D2)
  READ_v(ChrisConf_U2D0D2)
  READ_v(ChrisConf_U1D0D1)


  DDM_SCHUR_EQ_OPEN

  double psi4 = 
pow(psi[ijk], 4);

  double aij2 = 
AConfIJ2[ijk]/psi4;

  double F_eq = 
-ChrisConf_U0D0D0[ijk]*dpsi_D0[ijk]*igConf_U0U0[ijk] - 2.0*
ChrisConf_U0D0D1[ijk]*dpsi_D0[ijk]*igConf_U0U1[ijk] - 2.0*
ChrisConf_U0D0D2[ijk]*dpsi_D0[ijk]*igConf_U0U2[ijk] -
ChrisConf_U0D1D1[ijk]*dpsi_D0[ijk]*igConf_U1U1[ijk] - 2.0*
ChrisConf_U0D1D2[ijk]*dpsi_D0[ijk]*igConf_U1U2[ijk] -
ChrisConf_U0D2D2[ijk]*dpsi_D0[ijk]*igConf_U2U2[ijk] -
ChrisConf_U1D0D0[ijk]*dpsi_D1[ijk]*igConf_U0U0[ijk] - 2.0*
ChrisConf_U1D0D1[ijk]*dpsi_D1[ijk]*igConf_U0U1[ijk] - 2.0*
ChrisConf_U1D0D2[ijk]*dpsi_D1[ijk]*igConf_U0U2[ijk] -
ChrisConf_U1D1D1[ijk]*dpsi_D1[ijk]*igConf_U1U1[ijk] - 2.0*
ChrisConf_U1D1D2[ijk]*dpsi_D1[ijk]*igConf_U1U2[ijk] -
ChrisConf_U1D2D2[ijk]*dpsi_D1[ijk]*igConf_U2U2[ijk] -
ChrisConf_U2D0D0[ijk]*dpsi_D2[ijk]*igConf_U0U0[ijk] - 2.0*
ChrisConf_U2D0D1[ijk]*dpsi_D2[ijk]*igConf_U0U1[ijk] - 2.0*
ChrisConf_U2D0D2[ijk]*dpsi_D2[ijk]*igConf_U0U2[ijk] -
ChrisConf_U2D1D1[ijk]*dpsi_D2[ijk]*igConf_U1U1[ijk] - 2.0*
ChrisConf_U2D1D2[ijk]*dpsi_D2[ijk]*igConf_U1U2[ijk] -
ChrisConf_U2D2D2[ijk]*dpsi_D2[ijk]*igConf_U2U2[ijk] + 2*M_PI*EConf[ijk]/
psi[ijk] + (1.0/8.0)*aij2/pow(psi[ijk], 3) + ddpsi_D0D0[ijk]*
igConf_U0U0[ijk] + 2.0*ddpsi_D0D1[ijk]*igConf_U0U1[ijk] + 2.0*
ddpsi_D0D2[ijk]*igConf_U0U2[ijk] + ddpsi_D1D1[ijk]*igConf_U1U1[ijk] +
2.0*ddpsi_D1D2[ijk]*igConf_U1U2[ijk] + ddpsi_D2D2[ijk]*
igConf_U2U2[ijk] - 1.0/12.0*psi[ijk]*psi4*pow(trK[ijk], 2) - 1.0/8.0*
psi[ijk]*trRicciConf[ijk];

  F[n] = F_eq;

  DDM_SCHUR_EQ_CLOSE

  return 0;
}
