int make_patches(Grid_T *const grid);
int realize_geometry(Grid_T *const grid);
int X_of_x(double *const X,const double *const x,const Patch_T *const patch);
double *make_collocation_1d(const Patch_T *const patch,const unsigned dir,const double min,const double max);
double x_coord(const unsigned i,const Patch_T *const patch);
double y_coord(const unsigned i,const Patch_T *const patch);
double z_coord(const unsigned i,const Patch_T *const patch);
double X_coord(const unsigned i,const Patch_T *const patch);
double Y_coord(const unsigned i,const Patch_T *const patch);
double Z_coord(const unsigned i,const Patch_T *const patch);
double dq2_dq1(const Patch_T *const patch,const dq2_dq1_T q2_e, const dq2_dq1_T q1_e,const unsigned q2, const unsigned q1);
