int make_patches(Grid_T *const grid);
int realize_geometry(Grid_T *const grid);
int X_of_x(double *const X,const double *const x,const Patch_T *const patch);
double x_coord(const unsigned i,const Patch_T *const patch);
double y_coord(const unsigned i,const Patch_T *const patch);
double z_coord(const unsigned i,const Patch_T *const patch);
double X_coord(const unsigned i,const Patch_T *const patch);
double Y_coord(const unsigned i,const Patch_T *const patch);
double Z_coord(const unsigned i,const Patch_T *const patch);
double dq2_dq1(const Patch_T *const patch,const Dd_T q2_e, const Dd_T q1_e,const unsigned p);
double JT_Cartesian_patch(const Patch_T *const patch,const Dd_T q2_e, const Dd_T q1_e,const unsigned p);
double *normal_vec(Point_T *const point);
double General2ChebyshevExtrema(const double X,const unsigned dir,const Patch_T *const patch);
