void *alloc_parameter(Parameter_T ***const mem);
void *alloc_project(Project_T ***const mem);
void *alloc_grid(void);
void alloc_patches(Grid_T *const grid);
void alloc_nodes(Grid_T *const grid);
void *alloc_point(const unsigned s);
void alloc_interface(Patch_T *const patch);
void *alloc_sFunc_PtoV(sFunc_PtoV_T ***const mem);
void *alloc_needle(void);
Field_T *alloc_field(const Grid_T *const grid);
double *alloc_double(const unsigned N);
void free_needle(Needle_T *needle);
void free_2d(void *mem0);
void free_matrix(void *mem, const unsigned long c);
void free_points(Grid_T *const grid);
void free_func_PtoV(sFunc_PtoV_T **func);
void free_field(Field_T *f);
