void *alloc_parameter(Parameter_T ***mem);
void *alloc_project(Project_T ***mem);
void *alloc_grid(void);
void alloc_patches(Grid_T *grid);
void alloc_nodes(Grid_T *grid);
void alloc_point(Patch_T *patch);
void *alloc_interface(Patch_T *patch);
void *alloc_sFunc_PtoV(sFunc_PtoV_T ***mem);
void free_2d(void *mem0);
void free_matrix(void *mem, long int c);
