#define TEST_START test_start(__FILE__,__LINE__);

void test_start(const char *const file,const int line);
unsigned countf(void *const p);
void init_func_PtoV(sFunc_PtoV_T ***const func);
void add_func_PtoV(sFunc_PtoV_T ***const func,void (*f)(Patch_T *const patch),const char *const task,const Coord_T coord);
void run_func_PtoV(sFunc_PtoV_T **const func,const char *const task,Patch_T *const patch);
Collocation_T get_collocation(const char *const coll);
Coord_T find_coord(const char *const coordsys);
Basis_T get_basis(const char *const basis);
void IJK(const unsigned l, const unsigned *const n, unsigned *const i, unsigned *const j, unsigned *const k);
unsigned L(const unsigned *const n, const unsigned i, const unsigned j, const unsigned k);
unsigned I(const unsigned l, const unsigned *const n);
unsigned J(const unsigned l, const unsigned *const n);
unsigned K(const unsigned l, const unsigned *const n);
int IsOnEdge(const unsigned *const n,const unsigned p);
int IsOnFace(const double *const x, const Patch_T *const patch,unsigned *const f);
SubFace_T *get_paired_subface(const SubFace_T *const sub);
unsigned total_nodes_grid(const Grid_T *const grid);
unsigned total_nodes_patch(const Patch_T *const patch);
void init_func_Grid2Pdouble(sFunc_Grid2Pdouble_T ***const func);
void add_func_Grid2Pdouble(sFunc_Grid2Pdouble_T ***const func,double *(*f)(Grid_T *const grid),const char *const name);
sFunc_Grid2Pdouble_T *get_func_Grid2Pdouble(const char *const name,sFunc_Grid2Pdouble_T **const func);