/*
  These C codes generated by Cpi version 3.0
  Copyright (C) 2019-2023 Alireza Rashti.
*/


#include "obs_header.h"

#define add_and_get_field(name) \
  if (_Ind(#name) < 0) \
  {ADD_AND_ALLOC_FIELD(name);} \
  WRITE_v(name);


void obs_Rc_NS(Observe_T *const obs);
void obs_Rc_NS(Observe_T *const obs)
{
  Physics_T *const phys = obs->phys;
  double *const Rc      = obs->ret;
  Grid_T *const grid    = phys->grid;
  const char *const region = Ftype("NS");
  const double Madm = Getd("ADM_mass");
  const double x_CM = sysGetd("x_CM");
  const double y_CM = sysGetd("y_CM");
  const double z_CM = sysGetd("z_CM");
  Uint p;

  Rc[0] = 0;
  Rc[1] = 0;
  Rc[2] = 0;
  FOR_ALL_PATCHES(p,grid)
  {
    Patch_T *patch = grid->patch[p];
    if (!IsItCovering(patch,region))
      continue;

  READ_v(dpsi_D0)
  READ_v(dpsi_D1)
  READ_v(dpsi_D2)
  READ_v(ddpsi_D0D0)
  READ_v(ddpsi_D0D1)
  READ_v(ddpsi_D0D2)
  READ_v(ddpsi_D1D1)
  READ_v(ddpsi_D1D2)
  READ_v(ddpsi_D2D2)
  READ_v(gConf_D0D0)
  READ_v(gConf_D0D1)
  READ_v(gConf_D0D2)
  READ_v(gConf_D1D1)
  READ_v(gConf_D1D2)
  READ_v(gConf_D2D2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U1U2)
  READ_v(igConf_U2U2)
  READ_v(ChrisConf_U0D0D0)
  READ_v(ChrisConf_U0D0D1)
  READ_v(ChrisConf_U0D0D2)
  READ_v(ChrisConf_U0D1D1)
  READ_v(ChrisConf_U0D1D2)
  READ_v(ChrisConf_U0D2D2)
  READ_v(ChrisConf_U1D0D0)
  READ_v(ChrisConf_U1D0D1)
  READ_v(ChrisConf_U1D0D2)
  READ_v(ChrisConf_U1D1D1)
  READ_v(ChrisConf_U1D1D2)
  READ_v(ChrisConf_U1D2D2)
  READ_v(ChrisConf_U2D0D0)
  READ_v(ChrisConf_U2D0D1)
  READ_v(ChrisConf_U2D0D2)
  READ_v(ChrisConf_U2D1D1)
  READ_v(ChrisConf_U2D1D2)
  READ_v(ChrisConf_U2D2D2)
    Uint nn  = patch->nn;
    Uint ijk;

    ADD_FIELD(Rc_integrandx)
    ADD_FIELD(Rc_integrandy)
    ADD_FIELD(Rc_integrandz)
    {
    REALLOC_v_WRITE_v(Rc_integrandx)
    REALLOC_v_WRITE_v(Rc_integrandy)
    REALLOC_v_WRITE_v(Rc_integrandz)
    for (ijk = 0; ijk < nn; ++ijk)
    {
    double D2psi =
-ChrisConf_U0D0D0[ijk]*dpsi_D0[ijk]*igConf_U0U0[ijk] - 2.0*
ChrisConf_U0D0D1[ijk]*dpsi_D0[ijk]*igConf_U0U1[ijk] - 2.0*
ChrisConf_U0D0D2[ijk]*dpsi_D0[ijk]*igConf_U0U2[ijk] -
ChrisConf_U0D1D1[ijk]*dpsi_D0[ijk]*igConf_U1U1[ijk] - 2.0*
ChrisConf_U0D1D2[ijk]*dpsi_D0[ijk]*igConf_U1U2[ijk] -
ChrisConf_U0D2D2[ijk]*dpsi_D0[ijk]*igConf_U2U2[ijk] -
ChrisConf_U1D0D0[ijk]*dpsi_D1[ijk]*igConf_U0U0[ijk] - 2.0*
ChrisConf_U1D0D1[ijk]*dpsi_D1[ijk]*igConf_U0U1[ijk] - 2.0*
ChrisConf_U1D0D2[ijk]*dpsi_D1[ijk]*igConf_U0U2[ijk] -
ChrisConf_U1D1D1[ijk]*dpsi_D1[ijk]*igConf_U1U1[ijk] - 2.0*
ChrisConf_U1D1D2[ijk]*dpsi_D1[ijk]*igConf_U1U2[ijk] -
ChrisConf_U1D2D2[ijk]*dpsi_D1[ijk]*igConf_U2U2[ijk] -
ChrisConf_U2D0D0[ijk]*dpsi_D2[ijk]*igConf_U0U0[ijk] - 2.0*
ChrisConf_U2D0D1[ijk]*dpsi_D2[ijk]*igConf_U0U1[ijk] - 2.0*
ChrisConf_U2D0D2[ijk]*dpsi_D2[ijk]*igConf_U0U2[ijk] -
ChrisConf_U2D1D1[ijk]*dpsi_D2[ijk]*igConf_U1U1[ijk] - 2.0*
ChrisConf_U2D1D2[ijk]*dpsi_D2[ijk]*igConf_U1U2[ijk] -
ChrisConf_U2D2D2[ijk]*dpsi_D2[ijk]*igConf_U2U2[ijk] + ddpsi_D0D0[ijk]*
igConf_U0U0[ijk] + 2.0*ddpsi_D0D1[ijk]*igConf_U0U1[ijk] + 2.0*
ddpsi_D0D2[ijk]*igConf_U0U2[ijk] + ddpsi_D1D1[ijk]*igConf_U1U1[ijk] +
2.0*ddpsi_D1D2[ijk]*igConf_U1U2[ijk] + ddpsi_D2D2[ijk]*
igConf_U2U2[ijk];

    double x = patch->node[ijk]->x[0];
    double y = patch->node[ijk]->x[1];
    double z = patch->node[ijk]->x[2];
    Rc_integrandx[ijk] = D2psi*(x-x_CM);
    Rc_integrandy[ijk] = D2psi*(y-y_CM);
    Rc_integrandz[ijk] = D2psi*(z-z_CM);
    }
    }
    DECLARE_FIELD(Rc_integrandx)
    DECLARE_FIELD(Rc_integrandy)
    DECLARE_FIELD(Rc_integrandz)
    Integration_T *I = init_integration();
    I->type = "Integral{f(x)dV},Spectral";
    I->g00 = gConf_D0D0;
    I->g01 = gConf_D0D1;
    I->g02 = gConf_D0D2;
    I->g11 = gConf_D1D1;
    I->g12 = gConf_D1D2;
    I->g22 = gConf_D2D2;
    I->Spectral->f = Rc_integrandx;
    plan_integration(I);
    Rc[0] += execute_integration(I);
    I->Spectral->f = Rc_integrandy;
    plan_integration(I);
    Rc[1] += execute_integration(I);
    I->Spectral->f = Rc_integrandz;
    plan_integration(I);
    Rc[2] += execute_integration(I);
    free_integration(I);
    REMOVE_FIELD(Rc_integrandx)
    REMOVE_FIELD(Rc_integrandy)
    REMOVE_FIELD(Rc_integrandz)
  }

  Rc[0] /= (-2*M_PI*Madm);
  Rc[1] /= (-2*M_PI*Madm);
  Rc[2] /= (-2*M_PI*Madm);
}
