/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2021 Alireza Rashti.
*/


#include "obs_header.h"


#define add_and_get_field(name) \
  if (_Ind(#name) < 0) \
  {ADD_AND_ALLOC_FIELD(name);} \
  WRITE_v(name);


void obs_ADM_P_Stokes_SV_constraint(Observe_T *const obs);
void obs_ADM_P_Stokes_SV_constraint(Observe_T *const obs)
{
  struct items_S **adm = obs->items;
  const Uint N = obs->Nitems;
  Uint p;

  for(p = 0; p < N; ++p)
  {
  Patch_T *patch = adm[p]->patch;
  Uint nn = patch->nn;
  Uint ijk;

  /* declaring: */
  READ_v(AConfIJ_U0U1)
  READ_v(AConfIJ_U0U0)
  READ_v(AConfIJ_U0U2)
  READ_v(AConfIJ_U2U2)
  READ_v(AConfIJ_U1U1)
  READ_v(AConfIJ_U1U2)
  READ_v(gConf_D0D2)
  READ_v(gConf_D0D0)
  READ_v(gConf_D0D1)
  READ_v(gConf_D1D2)
  READ_v(gConf_D1D1)
  READ_v(gConf_D2D2)
  READ_v(igConf_U2U2)
  READ_v(igConf_U1U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)
  READ_v(ChrisConf_U1D0D0)
  READ_v(ChrisConf_U0D2D2)
  READ_v(ChrisConf_U1D0D2)
  READ_v(ChrisConf_U2D2D2)
  READ_v(ChrisConf_U2D1D1)
  READ_v(ChrisConf_U2D0D0)
  READ_v(ChrisConf_U1D1D1)
  READ_v(ChrisConf_U0D1D1)
  READ_v(ChrisConf_U0D1D2)
  READ_v(ChrisConf_U1D1D2)
  READ_v(ChrisConf_U0D0D1)
  READ_v(ChrisConf_U0D0D0)
  READ_v(ChrisConf_U2D0D1)
  READ_v(ChrisConf_U0D0D2)
  READ_v(ChrisConf_U2D1D2)
  READ_v(ChrisConf_U1D2D2)
  READ_v(ChrisConf_U2D0D2)
  READ_v(ChrisConf_U1D0D1)
  READ_v(psi)
  READ_v(dpsi_D0)
  READ_v(dpsi_D1)
  READ_v(dpsi_D2)
  READ_v(trK)
  add_and_get_field(obs__Ps_D0)
  add_and_get_field(obs__Ps_D1)
  add_and_get_field(obs__Ps_D2)
  add_and_get_field(obs__Pv_D2)
  add_and_get_field(obs__Pv_D1)
  add_and_get_field(obs__Pv_D0)


  if (adm[p]->surface_integration_flg)
  {

      const double *n_U0 = adm[p]->n_U0;
      const double *n_U1 = adm[p]->n_U1;
      const double *n_U2 = adm[p]->n_U2;

      for (ijk = 0; ijk < nn; ++ijk)
      {
      double psi4 = 
pow(psi[ijk], 4);

      double psim2 = 
pow(psi[ijk], -2);

      double Ps_D2 = 
-n_U0[ijk]*(0.66666666666666663*gConf_D0D2[ijk]*psi4*trK[ijk] - psim2*
(AConfIJ_U0U0[ijk]*gConf_D0D0[ijk]*gConf_D0D2[ijk] + AConfIJ_U0U1[ijk]*
gConf_D0D0[ijk]*gConf_D1D2[ijk] + AConfIJ_U0U1[ijk]*gConf_D0D1[ijk]*
gConf_D0D2[ijk] + AConfIJ_U0U2[ijk]*gConf_D0D0[ijk]*gConf_D2D2[ijk] + 
AConfIJ_U0U2[ijk]*pow(gConf_D0D2[ijk], 2) + AConfIJ_U1U1[ijk]*
gConf_D0D1[ijk]*gConf_D1D2[ijk] + AConfIJ_U1U2[ijk]*gConf_D0D1[ijk]*
gConf_D2D2[ijk] + AConfIJ_U1U2[ijk]*gConf_D0D2[ijk]*gConf_D1D2[ijk] + 
AConfIJ_U2U2[ijk]*gConf_D0D2[ijk]*gConf_D2D2[ijk])) - n_U1[ijk]*
(0.66666666666666663*gConf_D1D2[ijk]*psi4*trK[ijk] - psim2*
(AConfIJ_U0U0[ijk]*gConf_D0D1[ijk]*gConf_D0D2[ijk] + AConfIJ_U0U1[ijk]*
gConf_D0D1[ijk]*gConf_D1D2[ijk] + AConfIJ_U0U1[ijk]*gConf_D0D2[ijk]*
gConf_D1D1[ijk] + AConfIJ_U0U2[ijk]*gConf_D0D1[ijk]*gConf_D2D2[ijk] + 
AConfIJ_U0U2[ijk]*gConf_D0D2[ijk]*gConf_D1D2[ijk] + AConfIJ_U1U1[ijk]*
gConf_D1D1[ijk]*gConf_D1D2[ijk] + AConfIJ_U1U2[ijk]*gConf_D1D1[ijk]*
gConf_D2D2[ijk] + AConfIJ_U1U2[ijk]*pow(gConf_D1D2[ijk], 2) + 
AConfIJ_U2U2[ijk]*gConf_D1D2[ijk]*gConf_D2D2[ijk])) - n_U2[ijk]*
(0.66666666666666663*gConf_D2D2[ijk]*psi4*trK[ijk] - psim2*
(AConfIJ_U0U0[ijk]*pow(gConf_D0D2[ijk], 2) + 2.0*AConfIJ_U0U1[ijk]*
gConf_D0D2[ijk]*gConf_D1D2[ijk] + 2.0*AConfIJ_U0U2[ijk]*gConf_D0D2[ijk]*
gConf_D2D2[ijk] + AConfIJ_U1U1[ijk]*pow(gConf_D1D2[ijk], 2) + 2.0*
AConfIJ_U1U2[ijk]*gConf_D1D2[ijk]*gConf_D2D2[ijk] + AConfIJ_U2U2[ijk]*
pow(gConf_D2D2[ijk], 2)));

      double Ps_D1 = 
-n_U0[ijk]*(0.66666666666666663*gConf_D0D1[ijk]*psi4*trK[ijk] - psim2*
(AConfIJ_U0U0[ijk]*gConf_D0D0[ijk]*gConf_D0D1[ijk] + AConfIJ_U0U1[ijk]*
gConf_D0D0[ijk]*gConf_D1D1[ijk] + AConfIJ_U0U1[ijk]*
pow(gConf_D0D1[ijk], 2) + AConfIJ_U0U2[ijk]*gConf_D0D0[ijk]*
gConf_D1D2[ijk] + AConfIJ_U0U2[ijk]*gConf_D0D1[ijk]*gConf_D0D2[ijk] + 
AConfIJ_U1U1[ijk]*gConf_D0D1[ijk]*gConf_D1D1[ijk] + AConfIJ_U1U2[ijk]*
gConf_D0D1[ijk]*gConf_D1D2[ijk] + AConfIJ_U1U2[ijk]*gConf_D0D2[ijk]*
gConf_D1D1[ijk] + AConfIJ_U2U2[ijk]*gConf_D0D2[ijk]*gConf_D1D2[ijk])) - 
n_U1[ijk]*(0.66666666666666663*gConf_D1D1[ijk]*psi4*trK[ijk] - psim2*
(AConfIJ_U0U0[ijk]*pow(gConf_D0D1[ijk], 2) + 2.0*AConfIJ_U0U1[ijk]*
gConf_D0D1[ijk]*gConf_D1D1[ijk] + 2.0*AConfIJ_U0U2[ijk]*gConf_D0D1[ijk]*
gConf_D1D2[ijk] + AConfIJ_U1U1[ijk]*pow(gConf_D1D1[ijk], 2) + 2.0*
AConfIJ_U1U2[ijk]*gConf_D1D1[ijk]*gConf_D1D2[ijk] + AConfIJ_U2U2[ijk]*
pow(gConf_D1D2[ijk], 2))) - n_U2[ijk]*(0.66666666666666663*
gConf_D1D2[ijk]*psi4*trK[ijk] - psim2*(AConfIJ_U0U0[ijk]*
gConf_D0D1[ijk]*gConf_D0D2[ijk] + AConfIJ_U0U1[ijk]*gConf_D0D1[ijk]*
gConf_D1D2[ijk] + AConfIJ_U0U1[ijk]*gConf_D0D2[ijk]*gConf_D1D1[ijk] + 
AConfIJ_U0U2[ijk]*gConf_D0D1[ijk]*gConf_D2D2[ijk] + AConfIJ_U0U2[ijk]*
gConf_D0D2[ijk]*gConf_D1D2[ijk] + AConfIJ_U1U1[ijk]*gConf_D1D1[ijk]*
gConf_D1D2[ijk] + AConfIJ_U1U2[ijk]*gConf_D1D1[ijk]*gConf_D2D2[ijk] + 
AConfIJ_U1U2[ijk]*pow(gConf_D1D2[ijk], 2) + AConfIJ_U2U2[ijk]*
gConf_D1D2[ijk]*gConf_D2D2[ijk]));

      double Ps_D0 = 
-n_U0[ijk]*(0.66666666666666663*gConf_D0D0[ijk]*psi4*trK[ijk] - psim2*
(AConfIJ_U0U0[ijk]*pow(gConf_D0D0[ijk], 2) + 2.0*AConfIJ_U0U1[ijk]*
gConf_D0D0[ijk]*gConf_D0D1[ijk] + 2.0*AConfIJ_U0U2[ijk]*gConf_D0D0[ijk]*
gConf_D0D2[ijk] + AConfIJ_U1U1[ijk]*pow(gConf_D0D1[ijk], 2) + 2.0*
AConfIJ_U1U2[ijk]*gConf_D0D1[ijk]*gConf_D0D2[ijk] + AConfIJ_U2U2[ijk]*
pow(gConf_D0D2[ijk], 2))) - n_U1[ijk]*(0.66666666666666663*
gConf_D0D1[ijk]*psi4*trK[ijk] - psim2*(AConfIJ_U0U0[ijk]*
gConf_D0D0[ijk]*gConf_D0D1[ijk] + AConfIJ_U0U1[ijk]*gConf_D0D0[ijk]*
gConf_D1D1[ijk] + AConfIJ_U0U1[ijk]*pow(gConf_D0D1[ijk], 2) + 
AConfIJ_U0U2[ijk]*gConf_D0D0[ijk]*gConf_D1D2[ijk] + AConfIJ_U0U2[ijk]*
gConf_D0D1[ijk]*gConf_D0D2[ijk] + AConfIJ_U1U1[ijk]*gConf_D0D1[ijk]*
gConf_D1D1[ijk] + AConfIJ_U1U2[ijk]*gConf_D0D1[ijk]*gConf_D1D2[ijk] + 
AConfIJ_U1U2[ijk]*gConf_D0D2[ijk]*gConf_D1D1[ijk] + AConfIJ_U2U2[ijk]*
gConf_D0D2[ijk]*gConf_D1D2[ijk])) - n_U2[ijk]*(0.66666666666666663*
gConf_D0D2[ijk]*psi4*trK[ijk] - psim2*(AConfIJ_U0U0[ijk]*
gConf_D0D0[ijk]*gConf_D0D2[ijk] + AConfIJ_U0U1[ijk]*gConf_D0D0[ijk]*
gConf_D1D2[ijk] + AConfIJ_U0U1[ijk]*gConf_D0D1[ijk]*gConf_D0D2[ijk] + 
AConfIJ_U0U2[ijk]*gConf_D0D0[ijk]*gConf_D2D2[ijk] + AConfIJ_U0U2[ijk]*
pow(gConf_D0D2[ijk], 2) + AConfIJ_U1U1[ijk]*gConf_D0D1[ijk]*
gConf_D1D2[ijk] + AConfIJ_U1U2[ijk]*gConf_D0D1[ijk]*gConf_D2D2[ijk] + 
AConfIJ_U1U2[ijk]*gConf_D0D2[ijk]*gConf_D1D2[ijk] + AConfIJ_U2U2[ijk]*
gConf_D0D2[ijk]*gConf_D2D2[ijk]));


      /* populating: */
      obs__Ps_D0[ijk] = Ps_D0;
      obs__Ps_D1[ijk] = Ps_D1;
      obs__Ps_D2[ijk] = Ps_D2;
      }
  }
  else
  {
      for (ijk = 0; ijk < nn; ++ijk)
      {
      double psim2_ = 
pow(psi[ijk], -2);

      double psi4_ = 
pow(psi[ijk], 4);

      double psim4_ = 
1.0/psi4_;

      double dLnpsi_D0 = 
dpsi_D0[ijk]/psi[ijk];

      double dLnpsi_D1 = 
dpsi_D1[ijk]/psi[ijk];

      double dLnpsi_D2 = 
dpsi_D2[ijk]/psi[ijk];

      double c_U0D2D2 = 
-2.0*gConf_D2D2[ijk]*(dLnpsi_D0*igConf_U0U0[ijk] + dLnpsi_D1*
igConf_U0U1[ijk] + dLnpsi_D2*igConf_U0U2[ijk]);

      double c_U1D2D2 = 
-2.0*gConf_D2D2[ijk]*(dLnpsi_D0*igConf_U0U1[ijk] + dLnpsi_D1*
igConf_U1U1[ijk] + dLnpsi_D2*igConf_U1U2[ijk]);

      double c_U0D0D1 = 
-2.0*dLnpsi_D0*gConf_D0D1[ijk]*igConf_U0U0[ijk] - 2.0*dLnpsi_D1*
gConf_D0D1[ijk]*igConf_U0U1[ijk] + 2.0*dLnpsi_D1 - 2.0*dLnpsi_D2*
gConf_D0D1[ijk]*igConf_U0U2[ijk];

      double c_U2D1D2 = 
-2.0*dLnpsi_D0*gConf_D1D2[ijk]*igConf_U0U2[ijk] - 2.0*dLnpsi_D1*
gConf_D1D2[ijk]*igConf_U1U2[ijk] + 2.0*dLnpsi_D1 - 2.0*dLnpsi_D2*
gConf_D1D2[ijk]*igConf_U2U2[ijk];

      double c_U0D0D0 = 
-2.0*dLnpsi_D0*gConf_D0D0[ijk]*igConf_U0U0[ijk] + 4.0*dLnpsi_D0 - 2.0*
dLnpsi_D1*gConf_D0D0[ijk]*igConf_U0U1[ijk] - 2.0*dLnpsi_D2*
gConf_D0D0[ijk]*igConf_U0U2[ijk];

      double c_U2D0D1 = 
-2.0*gConf_D0D1[ijk]*(dLnpsi_D0*igConf_U0U2[ijk] + dLnpsi_D1*
igConf_U1U2[ijk] + dLnpsi_D2*igConf_U2U2[ijk]);

      double c_U2D1D1 = 
-2.0*gConf_D1D1[ijk]*(dLnpsi_D0*igConf_U0U2[ijk] + dLnpsi_D1*
igConf_U1U2[ijk] + dLnpsi_D2*igConf_U2U2[ijk]);

      double c_U1D1D1 = 
-2.0*dLnpsi_D0*gConf_D1D1[ijk]*igConf_U0U1[ijk] - 2.0*dLnpsi_D1*
gConf_D1D1[ijk]*igConf_U1U1[ijk] + 4.0*dLnpsi_D1 - 2.0*dLnpsi_D2*
gConf_D1D1[ijk]*igConf_U1U2[ijk];

      double c_U0D1D1 = 
-2.0*gConf_D1D1[ijk]*(dLnpsi_D0*igConf_U0U0[ijk] + dLnpsi_D1*
igConf_U0U1[ijk] + dLnpsi_D2*igConf_U0U2[ijk]);

      double c_U0D1D2 = 
-2.0*gConf_D1D2[ijk]*(dLnpsi_D0*igConf_U0U0[ijk] + dLnpsi_D1*
igConf_U0U1[ijk] + dLnpsi_D2*igConf_U0U2[ijk]);

      double c_U1D1D2 = 
-2.0*dLnpsi_D0*gConf_D1D2[ijk]*igConf_U0U1[ijk] - 2.0*dLnpsi_D1*
gConf_D1D2[ijk]*igConf_U1U1[ijk] - 2.0*dLnpsi_D2*gConf_D1D2[ijk]*
igConf_U1U2[ijk] + 2.0*dLnpsi_D2;

      double c_U2D0D2 = 
-2.0*dLnpsi_D0*gConf_D0D2[ijk]*igConf_U0U2[ijk] + 2.0*dLnpsi_D0 - 2.0*
dLnpsi_D1*gConf_D0D2[ijk]*igConf_U1U2[ijk] - 2.0*dLnpsi_D2*
gConf_D0D2[ijk]*igConf_U2U2[ijk];

      double c_U2D0D0 = 
-2.0*gConf_D0D0[ijk]*(dLnpsi_D0*igConf_U0U2[ijk] + dLnpsi_D1*
igConf_U1U2[ijk] + dLnpsi_D2*igConf_U2U2[ijk]);

      double c_U0D0D2 = 
-2.0*dLnpsi_D0*gConf_D0D2[ijk]*igConf_U0U0[ijk] - 2.0*dLnpsi_D1*
gConf_D0D2[ijk]*igConf_U0U1[ijk] - 2.0*dLnpsi_D2*gConf_D0D2[ijk]*
igConf_U0U2[ijk] + 2.0*dLnpsi_D2;

      double c_U1D0D0 = 
-2.0*gConf_D0D0[ijk]*(dLnpsi_D0*igConf_U0U1[ijk] + dLnpsi_D1*
igConf_U1U1[ijk] + dLnpsi_D2*igConf_U1U2[ijk]);

      double c_U1D0D1 = 
-2.0*dLnpsi_D0*gConf_D0D1[ijk]*igConf_U0U1[ijk] + 2.0*dLnpsi_D0 - 2.0*
dLnpsi_D1*gConf_D0D1[ijk]*igConf_U1U1[ijk] - 2.0*dLnpsi_D2*
gConf_D0D1[ijk]*igConf_U1U2[ijk];

      double c_U1D0D2 = 
-2.0*gConf_D0D2[ijk]*(dLnpsi_D0*igConf_U0U1[ijk] + dLnpsi_D1*
igConf_U1U1[ijk] + dLnpsi_D2*igConf_U1U2[ijk]);

      double c_U2D2D2 = 
-2.0*dLnpsi_D0*gConf_D2D2[ijk]*igConf_U0U2[ijk] - 2.0*dLnpsi_D1*
gConf_D2D2[ijk]*igConf_U1U2[ijk] - 2.0*dLnpsi_D2*gConf_D2D2[ijk]*
igConf_U2U2[ijk] + 4.0*dLnpsi_D2;

      double Gamma_U1D0D0 = 
ChrisConf_U1D0D0[ijk] + c_U1D0D0;

      double Gamma_U0D2D2 = 
ChrisConf_U0D2D2[ijk] + c_U0D2D2;

      double Gamma_U1D0D2 = 
ChrisConf_U1D0D2[ijk] + c_U1D0D2;

      double Gamma_U2D2D2 = 
ChrisConf_U2D2D2[ijk] + c_U2D2D2;

      double Gamma_U1D0D1 = 
ChrisConf_U1D0D1[ijk] + c_U1D0D1;

      double Gamma_U1D2D2 = 
ChrisConf_U1D2D2[ijk] + c_U1D2D2;

      double Gamma_U0D0D2 = 
ChrisConf_U0D0D2[ijk] + c_U0D0D2;

      double Gamma_U2D0D1 = 
ChrisConf_U2D0D1[ijk] + c_U2D0D1;

      double Gamma_U2D1D2 = 
ChrisConf_U2D1D2[ijk] + c_U2D1D2;

      double Gamma_U2D0D2 = 
ChrisConf_U2D0D2[ijk] + c_U2D0D2;

      double Gamma_U0D0D1 = 
ChrisConf_U0D0D1[ijk] + c_U0D0D1;

      double Gamma_U2D0D0 = 
ChrisConf_U2D0D0[ijk] + c_U2D0D0;

      double Gamma_U0D0D0 = 
ChrisConf_U0D0D0[ijk] + c_U0D0D0;

      double Gamma_U1D1D1 = 
ChrisConf_U1D1D1[ijk] + c_U1D1D1;

      double Gamma_U0D1D1 = 
ChrisConf_U0D1D1[ijk] + c_U0D1D1;

      double Gamma_U0D1D2 = 
ChrisConf_U0D1D2[ijk] + c_U0D1D2;

      double Gamma_U1D1D2 = 
ChrisConf_U1D1D2[ijk] + c_U1D1D2;

      double Gamma_U2D1D1 = 
ChrisConf_U2D1D1[ijk] + c_U2D1D1;

      double mom_D2D2 = 
-0.66666666666666663*gConf_D2D2[ijk]*psi4_*trK[ijk] + psim2_*
(AConfIJ_U0U0[ijk]*pow(gConf_D0D2[ijk], 2) + 2.0*AConfIJ_U0U1[ijk]*
gConf_D0D2[ijk]*gConf_D1D2[ijk] + 2.0*AConfIJ_U0U2[ijk]*gConf_D0D2[ijk]*
gConf_D2D2[ijk] + AConfIJ_U1U1[ijk]*pow(gConf_D1D2[ijk], 2) + 2.0*
AConfIJ_U1U2[ijk]*gConf_D1D2[ijk]*gConf_D2D2[ijk] + AConfIJ_U2U2[ijk]*
pow(gConf_D2D2[ijk], 2));

      double mom_D1D1 = 
-0.66666666666666663*gConf_D1D1[ijk]*psi4_*trK[ijk] + psim2_*
(AConfIJ_U0U0[ijk]*pow(gConf_D0D1[ijk], 2) + 2.0*AConfIJ_U0U1[ijk]*
gConf_D0D1[ijk]*gConf_D1D1[ijk] + 2.0*AConfIJ_U0U2[ijk]*gConf_D0D1[ijk]*
gConf_D1D2[ijk] + AConfIJ_U1U1[ijk]*pow(gConf_D1D1[ijk], 2) + 2.0*
AConfIJ_U1U2[ijk]*gConf_D1D1[ijk]*gConf_D1D2[ijk] + AConfIJ_U2U2[ijk]*
pow(gConf_D1D2[ijk], 2));

      double mom_D1D2 = 
-0.66666666666666663*gConf_D1D2[ijk]*psi4_*trK[ijk] + psim2_*
(AConfIJ_U0U0[ijk]*gConf_D0D1[ijk]*gConf_D0D2[ijk] + AConfIJ_U0U1[ijk]*
gConf_D0D1[ijk]*gConf_D1D2[ijk] + AConfIJ_U0U1[ijk]*gConf_D0D2[ijk]*
gConf_D1D1[ijk] + AConfIJ_U0U2[ijk]*gConf_D0D1[ijk]*gConf_D2D2[ijk] + 
AConfIJ_U0U2[ijk]*gConf_D0D2[ijk]*gConf_D1D2[ijk] + AConfIJ_U1U1[ijk]*
gConf_D1D1[ijk]*gConf_D1D2[ijk] + AConfIJ_U1U2[ijk]*gConf_D1D1[ijk]*
gConf_D2D2[ijk] + AConfIJ_U1U2[ijk]*pow(gConf_D1D2[ijk], 2) + 
AConfIJ_U2U2[ijk]*gConf_D1D2[ijk]*gConf_D2D2[ijk]);

      double mom_D0D0 = 
-0.66666666666666663*gConf_D0D0[ijk]*psi4_*trK[ijk] + psim2_*
(AConfIJ_U0U0[ijk]*pow(gConf_D0D0[ijk], 2) + 2.0*AConfIJ_U0U1[ijk]*
gConf_D0D0[ijk]*gConf_D0D1[ijk] + 2.0*AConfIJ_U0U2[ijk]*gConf_D0D0[ijk]*
gConf_D0D2[ijk] + AConfIJ_U1U1[ijk]*pow(gConf_D0D1[ijk], 2) + 2.0*
AConfIJ_U1U2[ijk]*gConf_D0D1[ijk]*gConf_D0D2[ijk] + AConfIJ_U2U2[ijk]*
pow(gConf_D0D2[ijk], 2));

      double mom_D0D1 = 
-0.66666666666666663*gConf_D0D1[ijk]*psi4_*trK[ijk] + psim2_*
(AConfIJ_U0U0[ijk]*gConf_D0D0[ijk]*gConf_D0D1[ijk] + AConfIJ_U0U1[ijk]*
gConf_D0D0[ijk]*gConf_D1D1[ijk] + AConfIJ_U0U1[ijk]*
pow(gConf_D0D1[ijk], 2) + AConfIJ_U0U2[ijk]*gConf_D0D0[ijk]*
gConf_D1D2[ijk] + AConfIJ_U0U2[ijk]*gConf_D0D1[ijk]*gConf_D0D2[ijk] + 
AConfIJ_U1U1[ijk]*gConf_D0D1[ijk]*gConf_D1D1[ijk] + AConfIJ_U1U2[ijk]*
gConf_D0D1[ijk]*gConf_D1D2[ijk] + AConfIJ_U1U2[ijk]*gConf_D0D2[ijk]*
gConf_D1D1[ijk] + AConfIJ_U2U2[ijk]*gConf_D0D2[ijk]*
gConf_D1D2[ijk]);

      double mom_D0D2 = 
-0.66666666666666663*gConf_D0D2[ijk]*psi4_*trK[ijk] + psim2_*
(AConfIJ_U0U0[ijk]*gConf_D0D0[ijk]*gConf_D0D2[ijk] + AConfIJ_U0U1[ijk]*
gConf_D0D0[ijk]*gConf_D1D2[ijk] + AConfIJ_U0U1[ijk]*gConf_D0D1[ijk]*
gConf_D0D2[ijk] + AConfIJ_U0U2[ijk]*gConf_D0D0[ijk]*gConf_D2D2[ijk] + 
AConfIJ_U0U2[ijk]*pow(gConf_D0D2[ijk], 2) + AConfIJ_U1U1[ijk]*
gConf_D0D1[ijk]*gConf_D1D2[ijk] + AConfIJ_U1U2[ijk]*gConf_D0D1[ijk]*
gConf_D2D2[ijk] + AConfIJ_U1U2[ijk]*gConf_D0D2[ijk]*gConf_D1D2[ijk] + 
AConfIJ_U2U2[ijk]*gConf_D0D2[ijk]*gConf_D2D2[ijk]);

      double Pv_D0 = 
psim4_*(Gamma_U0D0D0*igConf_U0U0[ijk]*mom_D0D0 + Gamma_U0D0D0*
igConf_U0U1[ijk]*mom_D0D1 + Gamma_U0D0D0*igConf_U0U2[ijk]*mom_D0D2 + 
Gamma_U0D0D1*igConf_U0U1[ijk]*mom_D0D0 + Gamma_U0D0D1*igConf_U1U1[ijk]*
mom_D0D1 + Gamma_U0D0D1*igConf_U1U2[ijk]*mom_D0D2 + Gamma_U0D0D2*
igConf_U0U2[ijk]*mom_D0D0 + Gamma_U0D0D2*igConf_U1U2[ijk]*mom_D0D1 + 
Gamma_U0D0D2*igConf_U2U2[ijk]*mom_D0D2 + Gamma_U1D0D0*igConf_U0U0[ijk]*
mom_D0D1 + Gamma_U1D0D0*igConf_U0U1[ijk]*mom_D1D1 + Gamma_U1D0D0*
igConf_U0U2[ijk]*mom_D1D2 + Gamma_U1D0D1*igConf_U0U1[ijk]*mom_D0D1 + 
Gamma_U1D0D1*igConf_U1U1[ijk]*mom_D1D1 + Gamma_U1D0D1*igConf_U1U2[ijk]*
mom_D1D2 + Gamma_U1D0D2*igConf_U0U2[ijk]*mom_D0D1 + Gamma_U1D0D2*
igConf_U1U2[ijk]*mom_D1D1 + Gamma_U1D0D2*igConf_U2U2[ijk]*mom_D1D2 + 
Gamma_U2D0D0*igConf_U0U0[ijk]*mom_D0D2 + Gamma_U2D0D0*igConf_U0U1[ijk]*
mom_D1D2 + Gamma_U2D0D0*igConf_U0U2[ijk]*mom_D2D2 + Gamma_U2D0D1*
igConf_U0U1[ijk]*mom_D0D2 + Gamma_U2D0D1*igConf_U1U1[ijk]*mom_D1D2 + 
Gamma_U2D0D1*igConf_U1U2[ijk]*mom_D2D2 + Gamma_U2D0D2*igConf_U0U2[ijk]*
mom_D0D2 + Gamma_U2D0D2*igConf_U1U2[ijk]*mom_D1D2 + Gamma_U2D0D2*
igConf_U2U2[ijk]*mom_D2D2);

      double Pv_D1 = 
psim4_*(Gamma_U0D0D1*igConf_U0U0[ijk]*mom_D0D0 + Gamma_U0D0D1*
igConf_U0U1[ijk]*mom_D0D1 + Gamma_U0D0D1*igConf_U0U2[ijk]*mom_D0D2 + 
Gamma_U0D1D1*igConf_U0U1[ijk]*mom_D0D0 + Gamma_U0D1D1*igConf_U1U1[ijk]*
mom_D0D1 + Gamma_U0D1D1*igConf_U1U2[ijk]*mom_D0D2 + Gamma_U0D1D2*
igConf_U0U2[ijk]*mom_D0D0 + Gamma_U0D1D2*igConf_U1U2[ijk]*mom_D0D1 + 
Gamma_U0D1D2*igConf_U2U2[ijk]*mom_D0D2 + Gamma_U1D0D1*igConf_U0U0[ijk]*
mom_D0D1 + Gamma_U1D0D1*igConf_U0U1[ijk]*mom_D1D1 + Gamma_U1D0D1*
igConf_U0U2[ijk]*mom_D1D2 + Gamma_U1D1D1*igConf_U0U1[ijk]*mom_D0D1 + 
Gamma_U1D1D1*igConf_U1U1[ijk]*mom_D1D1 + Gamma_U1D1D1*igConf_U1U2[ijk]*
mom_D1D2 + Gamma_U1D1D2*igConf_U0U2[ijk]*mom_D0D1 + Gamma_U1D1D2*
igConf_U1U2[ijk]*mom_D1D1 + Gamma_U1D1D2*igConf_U2U2[ijk]*mom_D1D2 + 
Gamma_U2D0D1*igConf_U0U0[ijk]*mom_D0D2 + Gamma_U2D0D1*igConf_U0U1[ijk]*
mom_D1D2 + Gamma_U2D0D1*igConf_U0U2[ijk]*mom_D2D2 + Gamma_U2D1D1*
igConf_U0U1[ijk]*mom_D0D2 + Gamma_U2D1D1*igConf_U1U1[ijk]*mom_D1D2 + 
Gamma_U2D1D1*igConf_U1U2[ijk]*mom_D2D2 + Gamma_U2D1D2*igConf_U0U2[ijk]*
mom_D0D2 + Gamma_U2D1D2*igConf_U1U2[ijk]*mom_D1D2 + Gamma_U2D1D2*
igConf_U2U2[ijk]*mom_D2D2);

      double Pv_D2 = 
psim4_*(Gamma_U0D0D2*igConf_U0U0[ijk]*mom_D0D0 + Gamma_U0D0D2*
igConf_U0U1[ijk]*mom_D0D1 + Gamma_U0D0D2*igConf_U0U2[ijk]*mom_D0D2 + 
Gamma_U0D1D2*igConf_U0U1[ijk]*mom_D0D0 + Gamma_U0D1D2*igConf_U1U1[ijk]*
mom_D0D1 + Gamma_U0D1D2*igConf_U1U2[ijk]*mom_D0D2 + Gamma_U0D2D2*
igConf_U0U2[ijk]*mom_D0D0 + Gamma_U0D2D2*igConf_U1U2[ijk]*mom_D0D1 + 
Gamma_U0D2D2*igConf_U2U2[ijk]*mom_D0D2 + Gamma_U1D0D2*igConf_U0U0[ijk]*
mom_D0D1 + Gamma_U1D0D2*igConf_U0U1[ijk]*mom_D1D1 + Gamma_U1D0D2*
igConf_U0U2[ijk]*mom_D1D2 + Gamma_U1D1D2*igConf_U0U1[ijk]*mom_D0D1 + 
Gamma_U1D1D2*igConf_U1U1[ijk]*mom_D1D1 + Gamma_U1D1D2*igConf_U1U2[ijk]*
mom_D1D2 + Gamma_U1D2D2*igConf_U0U2[ijk]*mom_D0D1 + Gamma_U1D2D2*
igConf_U1U2[ijk]*mom_D1D1 + Gamma_U1D2D2*igConf_U2U2[ijk]*mom_D1D2 + 
Gamma_U2D0D2*igConf_U0U0[ijk]*mom_D0D2 + Gamma_U2D0D2*igConf_U0U1[ijk]*
mom_D1D2 + Gamma_U2D0D2*igConf_U0U2[ijk]*mom_D2D2 + Gamma_U2D1D2*
igConf_U0U1[ijk]*mom_D0D2 + Gamma_U2D1D2*igConf_U1U1[ijk]*mom_D1D2 + 
Gamma_U2D1D2*igConf_U1U2[ijk]*mom_D2D2 + Gamma_U2D2D2*igConf_U0U2[ijk]*
mom_D0D2 + Gamma_U2D2D2*igConf_U1U2[ijk]*mom_D1D2 + Gamma_U2D2D2*
igConf_U2U2[ijk]*mom_D2D2);


      /* populating: */
      obs__Pv_D2[ijk] = Pv_D2;
      obs__Pv_D1[ijk] = Pv_D1;
      obs__Pv_D0[ijk] = Pv_D0;
      }
  }
  }

  obs->ret[0] = obs_integral_SV
                 (obs,"obs__Ps_D0","obs__Pv_D0",'+','+')/(8*M_PI);
  obs->ret[1] = obs_integral_SV
                 (obs,"obs__Ps_D1","obs__Pv_D1",'+','+')/(8*M_PI);
  obs->ret[2] = obs_integral_SV
                 (obs,"obs__Ps_D2","obs__Pv_D2",'+','+')/(8*M_PI);

  for(p = 0; p < N; ++p)
  {
    Patch_T *patch = adm[p]->patch;
    remove_field_regex(patch,"^obs__Ps_D.$");
    remove_field_regex(patch,"^obs__Pv_D.$");
  }

}
