/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "obs_header.h"

#define add_and_get_field(name) \
  if (_Ind(#name) < 0) \
  {ADD_AND_ALLOC_FIELD(name);} \
  WRITE_v(name);


double obs_ADM_mass_SV_isotropic(Observe_T *const obs);
double obs_ADM_mass_SV_isotropic(Observe_T *const obs)
{
  double adm_mass = 0;
  struct items_S **adm = obs->items;
  const Uint N = obs->Nitems;
  const double CutOff = 1E8;
  Uint p;

  for(p = 0; p < N; ++p)
  {
  Patch_T *patch = adm[p]->patch;


  /* declaring: */
  READ_v(dpsi_D0)
  READ_v(dpsi_D1)
  READ_v(dpsi_D2)
  READ_v(ddpsi_D2D2)
  READ_v(ddpsi_D0D0)
  READ_v(ddpsi_D0D1)
  READ_v(ddpsi_D1D1)
  READ_v(ddpsi_D1D2)
  READ_v(ddpsi_D0D2)
  READ_v(igConf_U2U2)
  READ_v(igConf_U1U2)
  READ_v(igConf_U1U1)
  READ_v(igConf_U0U2)
  READ_v(igConf_U0U0)
  READ_v(igConf_U0U1)
  READ_v(ChrisConf_U1D0D0)
  READ_v(ChrisConf_U0D2D2)
  READ_v(ChrisConf_U1D0D2)
  READ_v(ChrisConf_U2D2D2)
  READ_v(ChrisConf_U2D1D1)
  READ_v(ChrisConf_U2D0D0)
  READ_v(ChrisConf_U1D1D1)
  READ_v(ChrisConf_U0D1D1)
  READ_v(ChrisConf_U0D1D2)
  READ_v(ChrisConf_U1D1D2)
  READ_v(ChrisConf_U0D0D1)
  READ_v(ChrisConf_U0D0D0)
  READ_v(ChrisConf_U2D0D1)
  READ_v(ChrisConf_U0D0D2)
  READ_v(ChrisConf_U2D1D2)
  READ_v(ChrisConf_U1D2D2)
  READ_v(ChrisConf_U2D0D2)
  READ_v(ChrisConf_U1D0D1)


    Uint nn = patch->nn;
    Uint ijk;

    if (adm[p]->surface_integration_flg)
    {
      ADD_FIELD(ADM_mass_integrand_S)
      {
      const double *n_U0 = adm[p]->n_U0;
      const double *n_U1 = adm[p]->n_U1;
      const double *n_U2 = adm[p]->n_U2;
      REALLOC_v_WRITE_v(ADM_mass_integrand_S)
      for (ijk = 0; ijk < nn; ++ijk)
      {
      double M_s = 
dpsi_D0[ijk]*n_U0[ijk] + dpsi_D1[ijk]*n_U1[ijk] + dpsi_D2[ijk]*
n_U2[ijk];

      ADM_mass_integrand_S[ijk] = M_s;
      }
      }
      DECLARE_FIELD(ADM_mass_integrand_S)
      Integration_T *I = init_integration();
      I->type = "Integral{f(x)dS},Spectral";
      I->Spectral->f = ADM_mass_integrand_S;
      I->g00 = adm[p]->g00;
      I->g01 = adm[p]->g01;
      I->g02 = adm[p]->g02;
      I->g11 = adm[p]->g11;
      I->g12 = adm[p]->g12;
      I->g22 = adm[p]->g22;
      I->Spectral->X_surface = adm[p]->X_surface;
      I->Spectral->Y_surface = adm[p]->Y_surface;
      I->Spectral->Z_surface = adm[p]->Z_surface;
      I->Spectral->I         = adm[p]->I;
      I->Spectral->J         = adm[p]->J;
      I->Spectral->K         = adm[p]->K;
      plan_integration(I);
      adm_mass += execute_integration(I);
      free_integration(I);
      REMOVE_FIELD(ADM_mass_integrand_S)
    }
    else
    {
      ADD_FIELD(ADM_mass_integrand_V)
      {
      REALLOC_v_WRITE_v(ADM_mass_integrand_V)
      for (ijk = 0; ijk < nn; ++ijk)
      {
      DEF_RELATIVE_x
      DEF_RELATIVE_y
      DEF_RELATIVE_z
      DEF_RELATIVE_r
      double att = r > CutOff ? 0:1;
      double M_v = 
-ChrisConf_U0D0D0[ijk]*dpsi_D0[ijk]*igConf_U0U0[ijk] - 2.0*
ChrisConf_U0D0D1[ijk]*dpsi_D0[ijk]*igConf_U0U1[ijk] - 2.0*
ChrisConf_U0D0D2[ijk]*dpsi_D0[ijk]*igConf_U0U2[ijk] -
ChrisConf_U0D1D1[ijk]*dpsi_D0[ijk]*igConf_U1U1[ijk] - 2.0*
ChrisConf_U0D1D2[ijk]*dpsi_D0[ijk]*igConf_U1U2[ijk] -
ChrisConf_U0D2D2[ijk]*dpsi_D0[ijk]*igConf_U2U2[ijk] -
ChrisConf_U1D0D0[ijk]*dpsi_D1[ijk]*igConf_U0U0[ijk] - 2.0*
ChrisConf_U1D0D1[ijk]*dpsi_D1[ijk]*igConf_U0U1[ijk] - 2.0*
ChrisConf_U1D0D2[ijk]*dpsi_D1[ijk]*igConf_U0U2[ijk] -
ChrisConf_U1D1D1[ijk]*dpsi_D1[ijk]*igConf_U1U1[ijk] - 2.0*
ChrisConf_U1D1D2[ijk]*dpsi_D1[ijk]*igConf_U1U2[ijk] -
ChrisConf_U1D2D2[ijk]*dpsi_D1[ijk]*igConf_U2U2[ijk] -
ChrisConf_U2D0D0[ijk]*dpsi_D2[ijk]*igConf_U0U0[ijk] - 2.0*
ChrisConf_U2D0D1[ijk]*dpsi_D2[ijk]*igConf_U0U1[ijk] - 2.0*
ChrisConf_U2D0D2[ijk]*dpsi_D2[ijk]*igConf_U0U2[ijk] -
ChrisConf_U2D1D1[ijk]*dpsi_D2[ijk]*igConf_U1U1[ijk] - 2.0*
ChrisConf_U2D1D2[ijk]*dpsi_D2[ijk]*igConf_U1U2[ijk] -
ChrisConf_U2D2D2[ijk]*dpsi_D2[ijk]*igConf_U2U2[ijk] + ddpsi_D0D0[ijk]*
igConf_U0U0[ijk] + 2.0*ddpsi_D0D1[ijk]*igConf_U0U1[ijk] + 2.0*
ddpsi_D0D2[ijk]*igConf_U0U2[ijk] + ddpsi_D1D1[ijk]*igConf_U1U1[ijk] +
2.0*ddpsi_D1D2[ijk]*igConf_U1U2[ijk] + ddpsi_D2D2[ijk]*
igConf_U2U2[ijk];

      ADM_mass_integrand_V[ijk] = M_v*att;
      }
      }
      DECLARE_FIELD(ADM_mass_integrand_V)
      Integration_T *I = init_integration();
      I->type = "Integral{f(x)dV},Spectral";
      I->Spectral->f = ADM_mass_integrand_V;
      I->g00 = adm[p]->g00;
      I->g01 = adm[p]->g01;
      I->g02 = adm[p]->g02;
      I->g11 = adm[p]->g11;
      I->g12 = adm[p]->g12;
      I->g22 = adm[p]->g22;
      plan_integration(I);
      adm_mass += execute_integration(I);
      free_integration(I);
      REMOVE_FIELD(ADM_mass_integrand_V)
    }

  }
  adm_mass /= (-2*M_PI);
  return adm_mass;
}
