/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "fd_header.h"


void fd_add_fields_RicciConf(Grid_T *const grid);
void fd_add_fields_RicciConf(Grid_T *const grid)
{
 Uint p;
 FOR_ALL_PATCHES(p,grid)
 {
 Patch_T *patch = grid->patch[p];


  /* declaring: */
  ADD_AND_ALLOC_FIELD(trRicciConf)
  ADD_AND_ALLOC_FIELD(RicciConf_D0D1)
  ADD_AND_ALLOC_FIELD(RicciConf_D0D0)
  ADD_AND_ALLOC_FIELD(RicciConf_D0D2)
  ADD_AND_ALLOC_FIELD(RicciConf_D1D1)
  ADD_AND_ALLOC_FIELD(RicciConf_D1D2)
  ADD_AND_ALLOC_FIELD(RicciConf_D2D2)


 }
}
