/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "bbn_headers.h"

#define declare_and_remove_field(name) \
 DECLARE_FIELD(name); REMOVE_FIELD(name);

void bbn_rm_1st_2nd_derivatives_conformal_metric(Patch_T *const patch);
void bbn_rm_1st_2nd_derivatives_conformal_metric(Patch_T *const patch)
{

  /* declaring: */
  declare_and_remove_field(_dgamma_D0D2D1)
  declare_and_remove_field(_dgamma_D0D0D1)
  declare_and_remove_field(_dgamma_D1D2D2)
  declare_and_remove_field(_dgamma_D1D1D0)
  declare_and_remove_field(_dgamma_D0D1D1)
  declare_and_remove_field(_dgamma_D2D2D0)
  declare_and_remove_field(_dgamma_D2D2D2)
  declare_and_remove_field(_dgamma_D0D1D0)
  declare_and_remove_field(_dgamma_D0D0D0)
  declare_and_remove_field(_dgamma_D1D1D1)
  declare_and_remove_field(_dgamma_D1D2D1)
  declare_and_remove_field(_dgamma_D0D1D2)
  declare_and_remove_field(_dgamma_D2D2D1)
  declare_and_remove_field(_dgamma_D1D1D2)
  declare_and_remove_field(_dgamma_D0D0D2)
  declare_and_remove_field(_dgamma_D0D2D2)
  declare_and_remove_field(_dgamma_D0D2D0)
  declare_and_remove_field(_dgamma_D1D2D0)
  declare_and_remove_field(_ddgamma_D1D1D0D2)
  declare_and_remove_field(_ddgamma_D1D2D1D0)
  declare_and_remove_field(_ddgamma_D0D1D1D2)
  declare_and_remove_field(_ddgamma_D0D1D2D0)
  declare_and_remove_field(_ddgamma_D0D0D0D0)
  declare_and_remove_field(_ddgamma_D0D2D2D0)
  declare_and_remove_field(_ddgamma_D2D2D0D1)
  declare_and_remove_field(_ddgamma_D1D2D0D1)
  declare_and_remove_field(_ddgamma_D2D2D2D0)
  declare_and_remove_field(_ddgamma_D1D1D0D1)
  declare_and_remove_field(_ddgamma_D2D2D0D0)
  declare_and_remove_field(_ddgamma_D0D2D2D2)
  declare_and_remove_field(_ddgamma_D1D2D0D2)
  declare_and_remove_field(_ddgamma_D0D2D0D1)
  declare_and_remove_field(_ddgamma_D0D1D2D2)
  declare_and_remove_field(_ddgamma_D0D2D1D1)
  declare_and_remove_field(_ddgamma_D1D2D1D2)
  declare_and_remove_field(_ddgamma_D0D0D2D0)
  declare_and_remove_field(_ddgamma_D0D0D1D1)
  declare_and_remove_field(_ddgamma_D0D1D0D1)
  declare_and_remove_field(_ddgamma_D1D1D1D2)
  declare_and_remove_field(_ddgamma_D0D2D1D0)
  declare_and_remove_field(_ddgamma_D1D1D2D0)
  declare_and_remove_field(_ddgamma_D1D2D2D0)
  declare_and_remove_field(_ddgamma_D1D1D2D2)
  declare_and_remove_field(_ddgamma_D1D2D1D1)
  declare_and_remove_field(_ddgamma_D0D0D0D2)
  declare_and_remove_field(_ddgamma_D0D0D1D0)
  declare_and_remove_field(_ddgamma_D0D0D1D2)
  declare_and_remove_field(_ddgamma_D1D1D1D0)
  declare_and_remove_field(_ddgamma_D1D2D2D1)
  declare_and_remove_field(_ddgamma_D0D1D1D0)
  declare_and_remove_field(_ddgamma_D1D2D2D2)
  declare_and_remove_field(_ddgamma_D2D2D1D2)
  declare_and_remove_field(_ddgamma_D2D2D2D1)
  declare_and_remove_field(_ddgamma_D0D0D2D2)
  declare_and_remove_field(_ddgamma_D0D2D2D1)
  declare_and_remove_field(_ddgamma_D0D1D0D0)
  declare_and_remove_field(_ddgamma_D1D1D1D1)
  declare_and_remove_field(_ddgamma_D0D1D2D1)
  declare_and_remove_field(_ddgamma_D0D0D2D1)
  declare_and_remove_field(_ddgamma_D1D1D0D0)
  declare_and_remove_field(_ddgamma_D0D2D0D0)
  declare_and_remove_field(_ddgamma_D0D2D0D2)
  declare_and_remove_field(_ddgamma_D0D2D1D2)
  declare_and_remove_field(_ddgamma_D0D1D1D1)
  declare_and_remove_field(_ddgamma_D2D2D0D2)
  declare_and_remove_field(_ddgamma_D1D2D0D0)
  declare_and_remove_field(_ddgamma_D2D2D1D1)
  declare_and_remove_field(_ddgamma_D0D1D0D2)
  declare_and_remove_field(_ddgamma_D0D0D0D1)
  declare_and_remove_field(_ddgamma_D2D2D2D2)
  declare_and_remove_field(_ddgamma_D1D1D2D1)
  declare_and_remove_field(_ddgamma_D2D2D1D0)


}
