/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"
#include "maths_equation_solvings_lib.h"
#include "bbn_XCTS_equations_lib.h"


void *bbn_jacobian_bc_psi(void *vp1,void *vp2)
{
  DDM_SCHUR_JACOBIAN_BC_DECLARE
  unsigned ijk,lmn;/* for Jacobian entries J[ijk][lmn] */
  const double kd[2] = {0.,1.};/* Kronecker delta */

  /* declaring: */
  READ_v(psi)
  READ_v(K)
  READ_v_UNUSED(_A_UiUj_U2U2)
  READ_v_UNUSED(_A_UiUj_U1U2)
  READ_v_UNUSED(_A_UiUj_U1U1)
  READ_v_UNUSED(_A_UiUj_U0U2)
  READ_v_UNUSED(_A_UiUj_U0U1)
  READ_v_UNUSED(_A_UiUj_U0U0)
  READ_v_UNUSED(_gamma_D2D2)
  READ_v_UNUSED(_gamma_D0D2)
  READ_v_UNUSED(_gamma_D0D0)
  READ_v_UNUSED(_gamma_D0D1)
  READ_v_UNUSED(_gamma_D1D2)
  READ_v_UNUSED(_gamma_D1D1)
  READ_v_IF_ON_HORIZON(_HS_U2)
  READ_v_IF_ON_HORIZON(_HS_U0)
  READ_v_IF_ON_HORIZON(_HS_U1)
  READ_v_IF_ON_HORIZON(_dHS_U2D0)
  READ_v_IF_ON_HORIZON(_dHS_U2D1)
  READ_v_IF_ON_HORIZON(_dHS_U0D1)
  READ_v_IF_ON_HORIZON(_dHS_U2D2)
  READ_v_IF_ON_HORIZON(_dHS_U0D0)
  READ_v_IF_ON_HORIZON(_dHS_U1D2)
  READ_v_IF_ON_HORIZON(_dHS_U0D2)
  READ_v_IF_ON_HORIZON(_dHS_U1D0)
  READ_v_IF_ON_HORIZON(_dHS_U1D1)
  JACOBIAN_DERIVATIVE(Jpsi_D2)
  JACOBIAN_DERIVATIVE(Jpsi_D0)
  JACOBIAN_DERIVATIVE(Jpsi_D1)
  READ_v_UNUSED(_Gamma_U2D1D1)
  READ_v_UNUSED(_Gamma_U2D1D2)
  READ_v_UNUSED(_Gamma_U0D1D1)
  READ_v_UNUSED(_Gamma_U2D0D2)
  READ_v_UNUSED(_Gamma_U2D2D2)
  READ_v_UNUSED(_Gamma_U0D1D2)
  READ_v_UNUSED(_Gamma_U0D0D2)
  READ_v_UNUSED(_Gamma_U0D0D1)
  READ_v_UNUSED(_Gamma_U0D0D0)
  READ_v_UNUSED(_Gamma_U1D2D2)
  READ_v_UNUSED(_Gamma_U2D0D1)
  READ_v_UNUSED(_Gamma_U0D2D2)
  READ_v_UNUSED(_Gamma_U2D0D0)
  READ_v_UNUSED(_Gamma_U1D0D2)
  READ_v_UNUSED(_Gamma_U1D1D2)
  READ_v_UNUSED(_Gamma_U1D0D0)
  READ_v_UNUSED(_Gamma_U1D0D1)
  READ_v_UNUSED(_Gamma_U1D1D1)


  if (patch->outerB)
  {
  DDM_SCHUR_JACOBIAN_BC_Bpart_OPEN

  double outerB_Bpart = 
kd[ijk==lmn];

  B[i][j] = outerB_Bpart;

  DDM_SCHUR_JACOBIAN_BC_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_BC_Epart_OPEN

  double outerB_Epart = 
0;

  E_Trans[j][i] = outerB_Epart;

  DDM_SCHUR_JACOBIAN_BC_Epart_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)
  {
  DDM_SCHUR_JACOBIAN_BC_Bpart_OPEN

  double _DiHSi_b = 
_Gamma_U0D0D0[ijk]*_HS_U0[ijk] + _Gamma_U0D0D1[ijk]*_HS_U1[ijk] +
_Gamma_U0D0D2[ijk]*_HS_U2[ijk] + _Gamma_U1D0D1[ijk]*_HS_U0[ijk] +
_Gamma_U1D1D1[ijk]*_HS_U1[ijk] + _Gamma_U1D1D2[ijk]*_HS_U2[ijk] +
_Gamma_U2D0D2[ijk]*_HS_U0[ijk] + _Gamma_U2D1D2[ijk]*_HS_U1[ijk] +
_Gamma_U2D2D2[ijk]*_HS_U2[ijk] + _dHS_U0D0[ijk] + _dHS_U1D1[ijk] +
_dHS_U2D2[ijk];

  double B_t1 = 
0;

  double innerB_Bpart = 
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_HS_U0[ijk] + Jpsi_D1(j_Jpsi_D1,ijk,lmn)*
_HS_U1[ijk] + Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_HS_U2[ijk] - 1.0/4.0*
kd[ijk==lmn]*(4*B_t1 + 2*K[ijk]*pow(psi[ijk], 2) - _DiHSi_b);

  B[i][j] = innerB_Bpart;

  DDM_SCHUR_JACOBIAN_BC_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_BC_Epart_OPEN

  double _DiHSi_e = 
_Gamma_U0D0D0[ijk]*_HS_U0[ijk] + _Gamma_U0D0D1[ijk]*_HS_U1[ijk] +
_Gamma_U0D0D2[ijk]*_HS_U2[ijk] + _Gamma_U1D0D1[ijk]*_HS_U0[ijk] +
_Gamma_U1D1D1[ijk]*_HS_U1[ijk] + _Gamma_U1D1D2[ijk]*_HS_U2[ijk] +
_Gamma_U2D0D2[ijk]*_HS_U0[ijk] + _Gamma_U2D1D2[ijk]*_HS_U1[ijk] +
_Gamma_U2D2D2[ijk]*_HS_U2[ijk] + _dHS_U0D0[ijk] + _dHS_U1D1[ijk] +
_dHS_U2D2[ijk];

  double E_t1 = 
0;

  double innerB_Epart = 
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_HS_U0[ijk] + Jpsi_D1(j_Jpsi_D1,ijk,lmn)*
_HS_U1[ijk] + Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_HS_U2[ijk] - 1.0/4.0*
kd[ijk==lmn]*(4*E_t1 + 2*K[ijk]*pow(psi[ijk], 2) - _DiHSi_e);

  E_Trans[j][i] = innerB_Epart;

  DDM_SCHUR_JACOBIAN_BC_Epart_CLOSE

  }/* end of else if (patch->innerB) */

  return 0;
}
