/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"
#include "maths_equation_solvings_lib.h"
#include "bbn_XCTS_equations_lib.h"


void *bbn_bc_Beta_U1(void *vp1,void *vp2)
{
  DDM_SCHUR_BC_DECLARE
  unsigned ijk;/* node index */

  /* declaring: */
  READ_v(B0_U1)
  READ_v(B1_U1)
  READ_v(psi)
  READ_v(eta)
  READ_v_IF_ON_HORIZON(_HS_U1)


  const double BH_center_x = Pgetd_E("BH_center_x");
  const double BH_Omega_U2 = Pgetd_E("BH_Omega_U2");
  const double v1_boost    = Pgetd_E("v*_boost_y");
  if (patch->outerB)/* at outer boundary */
  {
  DDM_SCHUR_BC_OPEN

  double outerB_F = 
B0_U1[ijk] - v1_boost;

  F[map[ijk]] = outerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)/* at inner boundary */
  {
  DDM_SCHUR_BC_OPEN

  double alpha = 
eta[ijk]/psi[ijk];

  double S_U1 = 
_HS_U1[ijk]/pow(psi[ijk], 2);

  double x = patch->node[ijk]->x[0]-BH_center_x;
  double OmegaXr_U1 = 
BH_Omega_U2*x;

  double innerB_F = 
B0_U1[ijk] + B1_U1[ijk] - OmegaXr_U1 - S_U1*alpha;

  F[map[ijk]] = innerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of else if (patch->innerB) */
  return 0;
}
