/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"
#include "maths_equation_solvings_lib.h"
#include "bbn_XCTS_equations_lib.h"


void *bbn_bc_phi(void *vp1,void *vp2)
{
  DDM_SCHUR_BC_DECLARE
  unsigned ijk;/* node index */

  /* declaring: */
  READ_v_IF_IN_NS(dphi_D2)
  READ_v_IF_IN_NS(dphi_D1)
  READ_v_IF_IN_NS(dphi_D0)
  READ_v_IF_IN_NS(W_U1)
  READ_v_IF_IN_NS(W_U0)
  READ_v_IF_IN_NS(W_U2)
  READ_v_IF_IN_NS(enthalpy)
  READ_v_IF_IN_NS(drho0_D2)
  READ_v_IF_IN_NS(drho0_D0)
  READ_v_IF_IN_NS(drho0_D1)
  READ_v_IF_IN_NS(u0)
  READ_v(psi)
  READ_v(Beta_U1)
  READ_v(Beta_U0)
  READ_v(Beta_U2)
  READ_v(_gammaI_U0U2)
  READ_v(_gammaI_U0U0)
  READ_v(_gammaI_U0U1)
  READ_v(_gammaI_U1U2)
  READ_v(_gammaI_U1U1)
  READ_v(_gammaI_U2U2)


  if (patch->outerB)/* at outer boundary */
  {
  DDM_SCHUR_BC_OPEN

  double outerB_F = 
1.0*(_gammaI_U0U0[ijk]*dphi_D0[ijk]*drho0_D0[ijk] + _gammaI_U0U1[ijk]*
dphi_D0[ijk]*drho0_D1[ijk] + _gammaI_U0U1[ijk]*dphi_D1[ijk]*
drho0_D0[ijk] + _gammaI_U0U2[ijk]*dphi_D0[ijk]*drho0_D2[ijk] +
_gammaI_U0U2[ijk]*dphi_D2[ijk]*drho0_D0[ijk] + _gammaI_U1U1[ijk]*
dphi_D1[ijk]*drho0_D1[ijk] + _gammaI_U1U2[ijk]*dphi_D1[ijk]*
drho0_D2[ijk] + _gammaI_U1U2[ijk]*dphi_D2[ijk]*drho0_D1[ijk] +
_gammaI_U2U2[ijk]*dphi_D2[ijk]*drho0_D2[ijk] + pow(psi[ijk], 4)*
(W_U0[ijk]*drho0_D0[ijk] + W_U1[ijk]*drho0_D1[ijk] + W_U2[ijk]*
drho0_D2[ijk] - enthalpy[ijk]*u0[ijk]*(Beta_U0[ijk]*drho0_D0[ijk] +
Beta_U1[ijk]*drho0_D1[ijk] + Beta_U2[ijk]*drho0_D2[ijk])))/
pow(psi[ijk], 4);

  F[map[ijk]] = outerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)/* at inner boundary */
  {
  DDM_SCHUR_BC_OPEN

  double innerB_F = 
0;

  F[map[ijk]] = innerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of else if (patch->innerB) */
  return 0;
}
