/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"
static void dK_UiUj(Grid_T *const grid);

#define add_field_and_get_field(name) ADD_FIELD(name) PREP_FIELD(name)

void bbn_make_K_UiUj_and_dK_UiUj(Grid_T *const grid)
{
  const unsigned np = grid->np;
  unsigned p;

  OpenMP_Patch_Pragma(omp parallel for)
  for(p = 0; p < np; ++p)
  {
    Patch_T *patch = grid->patch[p];
    unsigned nn = patch->nn;
    unsigned ijk;

    /* declaring: */
    add_field_and_get_field(K_UiUj_U2U2)
    add_field_and_get_field(K_UiUj_U1U2)
    add_field_and_get_field(K_UiUj_U1U1)
    add_field_and_get_field(K_UiUj_U0U2)
    add_field_and_get_field(K_UiUj_U0U1)
    add_field_and_get_field(K_UiUj_U0U0)
    ADD_FIELD(dK_UiUj_U0U0D2)
    ADD_FIELD(dK_UiUj_U0U0D0)
    ADD_FIELD(dK_UiUj_U0U0D1)
    ADD_FIELD(dK_UiUj_U1U1D2)
    ADD_FIELD(dK_UiUj_U1U1D0)
    ADD_FIELD(dK_UiUj_U1U1D1)
    ADD_FIELD(dK_UiUj_U0U2D0)
    ADD_FIELD(dK_UiUj_U0U2D1)
    ADD_FIELD(dK_UiUj_U0U2D2)
    ADD_FIELD(dK_UiUj_U1U2D1)
    ADD_FIELD(dK_UiUj_U1U2D0)
    ADD_FIELD(dK_UiUj_U2U2D0)
    ADD_FIELD(dK_UiUj_U1U2D2)
    ADD_FIELD(dK_UiUj_U2U2D1)
    ADD_FIELD(dK_UiUj_U2U2D2)
    ADD_FIELD(dK_UiUj_U0U1D2)
    ADD_FIELD(dK_UiUj_U0U1D1)
    ADD_FIELD(dK_UiUj_U0U1D0)
    GET_FIELD(_A_UiUj_U2U2)
    GET_FIELD(_A_UiUj_U1U2)
    GET_FIELD(_A_UiUj_U1U1)
    GET_FIELD(_A_UiUj_U0U2)
    GET_FIELD(_A_UiUj_U0U1)
    GET_FIELD(_A_UiUj_U0U0)
    GET_FIELD(psi)
    GET_FIELD(_gammaI_U0U2)
    GET_FIELD(_gammaI_U0U0)
    GET_FIELD(_gammaI_U0U1)
    GET_FIELD(_gammaI_U1U2)
    GET_FIELD(_gammaI_U1U1)
    GET_FIELD(_gammaI_U2U2)
    GET_FIELD(K)


  for(ijk = 0; ijk < nn; ++ijk)
  {
  double psim4 = 
pow(psi[ijk], -4);

  double psim10 = 
pow(psi[ijk], -10);

  double Kij_U0U1 = 
(1.0/3.0)*K[ijk]*_gammaI_U0U1[ijk]*psim4 + _A_UiUj_U0U1[ijk]*
psim10;

  double Kij_U0U0 = 
(1.0/3.0)*K[ijk]*_gammaI_U0U0[ijk]*psim4 + _A_UiUj_U0U0[ijk]*
psim10;

  double Kij_U0U2 = 
(1.0/3.0)*K[ijk]*_gammaI_U0U2[ijk]*psim4 + _A_UiUj_U0U2[ijk]*
psim10;

  double Kij_U2U2 = 
(1.0/3.0)*K[ijk]*_gammaI_U2U2[ijk]*psim4 + _A_UiUj_U2U2[ijk]*
psim10;

  double Kij_U1U1 = 
(1.0/3.0)*K[ijk]*_gammaI_U1U1[ijk]*psim4 + _A_UiUj_U1U1[ijk]*
psim10;

  double Kij_U1U2 = 
(1.0/3.0)*K[ijk]*_gammaI_U1U2[ijk]*psim4 + _A_UiUj_U1U2[ijk]*
psim10;


  /* populating: */
  K_UiUj_U2U2[ijk] = Kij_U2U2;
  K_UiUj_U1U2[ijk] = Kij_U1U2;
  K_UiUj_U1U1[ijk] = Kij_U1U1;
  K_UiUj_U0U2[ijk] = Kij_U0U2;
  K_UiUj_U0U1[ijk] = Kij_U0U1;
  K_UiUj_U0U0[ijk] = Kij_U0U0;
  }
  }
  dK_UiUj(grid);
}

/* calculating the partial derivatives of K_UiUj */
static void dK_UiUj(Grid_T *const grid)
{
  const unsigned np = grid->np;
  unsigned p;

  OpenMP_Patch_Pragma(omp parallel for)
  for(p = 0; p < np; ++p)
  {
    Patch_T *patch = grid->patch[p];

    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U0U0D2)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U0U0D0)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U0U0D1)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U1U1D2)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U1U1D0)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U1U1D1)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U0U2D0)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U0U2D1)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U0U2D2)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U1U2D1)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U1U2D0)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U2U2D0)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U1U2D2)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U2U2D1)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U2U2D2)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U0U1D2)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U0U1D1)
    DECLARE_AND_EMPTY_FIELD(dK_UiUj_U0U1D0)

    DECLARE_FIELD(K_UiUj_U2U2)
    DECLARE_FIELD(K_UiUj_U1U2)
    DECLARE_FIELD(K_UiUj_U1U1)
    DECLARE_FIELD(K_UiUj_U0U2)
    DECLARE_FIELD(K_UiUj_U0U1)
    DECLARE_FIELD(K_UiUj_U0U0)

    dK_UiUj_U0U0D2->v = Partial_Derivative(K_UiUj_U0U0,"z");
    dK_UiUj_U0U0D0->v = Partial_Derivative(K_UiUj_U0U0,"x");
    dK_UiUj_U0U0D1->v = Partial_Derivative(K_UiUj_U0U0,"y");
    dK_UiUj_U1U1D2->v = Partial_Derivative(K_UiUj_U1U1,"z");
    dK_UiUj_U1U1D0->v = Partial_Derivative(K_UiUj_U1U1,"x");
    dK_UiUj_U1U1D1->v = Partial_Derivative(K_UiUj_U1U1,"y");
    dK_UiUj_U0U2D0->v = Partial_Derivative(K_UiUj_U0U2,"x");
    dK_UiUj_U0U2D1->v = Partial_Derivative(K_UiUj_U0U2,"y");
    dK_UiUj_U0U2D2->v = Partial_Derivative(K_UiUj_U0U2,"z");
    dK_UiUj_U1U2D1->v = Partial_Derivative(K_UiUj_U1U2,"y");
    dK_UiUj_U1U2D0->v = Partial_Derivative(K_UiUj_U1U2,"x");
    dK_UiUj_U2U2D0->v = Partial_Derivative(K_UiUj_U2U2,"x");
    dK_UiUj_U1U2D2->v = Partial_Derivative(K_UiUj_U1U2,"z");
    dK_UiUj_U2U2D1->v = Partial_Derivative(K_UiUj_U2U2,"y");
    dK_UiUj_U2U2D2->v = Partial_Derivative(K_UiUj_U2U2,"z");
    dK_UiUj_U0U1D2->v = Partial_Derivative(K_UiUj_U0U1,"z");
    dK_UiUj_U0U1D1->v = Partial_Derivative(K_UiUj_U0U1,"y");
    dK_UiUj_U0U1D0->v = Partial_Derivative(K_UiUj_U0U1,"x");

  }
}

/* free K_UiUj and dK_UiUj */
void bbn_free_K_UiUj_and_dK_UiUj(Grid_T *const grid)
{
  const unsigned np = grid->np;
  unsigned p;

  OpenMP_Patch_Pragma(omp parallel for)
  for(p = 0; p < np; ++p)
  {
    Patch_T *patch = grid->patch[p];

    DECLARE_FIELD(dK_UiUj_U0U0D2)
    DECLARE_FIELD(dK_UiUj_U0U0D0)
    DECLARE_FIELD(dK_UiUj_U0U0D1)
    DECLARE_FIELD(dK_UiUj_U1U1D2)
    DECLARE_FIELD(dK_UiUj_U1U1D0)
    DECLARE_FIELD(dK_UiUj_U1U1D1)
    DECLARE_FIELD(dK_UiUj_U0U2D0)
    DECLARE_FIELD(dK_UiUj_U0U2D1)
    DECLARE_FIELD(dK_UiUj_U0U2D2)
    DECLARE_FIELD(dK_UiUj_U1U2D1)
    DECLARE_FIELD(dK_UiUj_U1U2D0)
    DECLARE_FIELD(dK_UiUj_U2U2D0)
    DECLARE_FIELD(dK_UiUj_U1U2D2)
    DECLARE_FIELD(dK_UiUj_U2U2D1)
    DECLARE_FIELD(dK_UiUj_U2U2D2)
    DECLARE_FIELD(dK_UiUj_U0U1D2)
    DECLARE_FIELD(dK_UiUj_U0U1D1)
    DECLARE_FIELD(dK_UiUj_U0U1D0)

    DECLARE_FIELD(K_UiUj_U2U2)
    DECLARE_FIELD(K_UiUj_U1U2)
    DECLARE_FIELD(K_UiUj_U1U1)
    DECLARE_FIELD(K_UiUj_U0U2)
    DECLARE_FIELD(K_UiUj_U0U1)
    DECLARE_FIELD(K_UiUj_U0U0)

    REMOVE_FIELD(dK_UiUj_U0U0D2)
    REMOVE_FIELD(dK_UiUj_U0U0D0)
    REMOVE_FIELD(dK_UiUj_U0U0D1)
    REMOVE_FIELD(dK_UiUj_U1U1D2)
    REMOVE_FIELD(dK_UiUj_U1U1D0)
    REMOVE_FIELD(dK_UiUj_U1U1D1)
    REMOVE_FIELD(dK_UiUj_U0U2D0)
    REMOVE_FIELD(dK_UiUj_U0U2D1)
    REMOVE_FIELD(dK_UiUj_U0U2D2)
    REMOVE_FIELD(dK_UiUj_U1U2D1)
    REMOVE_FIELD(dK_UiUj_U1U2D0)
    REMOVE_FIELD(dK_UiUj_U2U2D0)
    REMOVE_FIELD(dK_UiUj_U1U2D2)
    REMOVE_FIELD(dK_UiUj_U2U2D1)
    REMOVE_FIELD(dK_UiUj_U2U2D2)
    REMOVE_FIELD(dK_UiUj_U0U1D2)
    REMOVE_FIELD(dK_UiUj_U0U1D1)
    REMOVE_FIELD(dK_UiUj_U0U1D0)

    REMOVE_FIELD(K_UiUj_U2U2)
    REMOVE_FIELD(K_UiUj_U1U2)
    REMOVE_FIELD(K_UiUj_U1U1)
    REMOVE_FIELD(K_UiUj_U0U2)
    REMOVE_FIELD(K_UiUj_U0U1)
    REMOVE_FIELD(K_UiUj_U0U0)

  }
}
