/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "bbn_headers.h"
#define FREE_DATA_OpenMP(x)  _Pragma ( #x )

void bbn_free_data_Gamma(Grid_T *const grid);
void bbn_free_data_Gamma_patch(Patch_T *const patch);
void bbn_free_data_Gamma(Grid_T *const grid)
{
  const unsigned np = grid->np;
  unsigned p;

  FREE_DATA_OpenMP(omp parallel for)
  for(p = 0; p < np; ++p)
  {
    Patch_T *patch = grid->patch[p];
    bbn_1st_derivatives_conformal_metric(patch);
    bbn_free_data_Gamma_patch(patch);
    bbn_free_conformal_metric_derivatives(patch);
  }
}

void bbn_free_data_Gamma_patch(Patch_T *const patch)
{

  /* declaring: */
  READ_v(_gammaI_U0U1)
  READ_v(_gammaI_U1U2)
  READ_v(_gammaI_U1U1)
  READ_v(_gammaI_U0U2)
  READ_v(_gammaI_U2U2)
  READ_v(_gammaI_U0U0)
  READ_v(_dgamma_D1D1D2)
  READ_v(_dgamma_D0D2D2)
  READ_v(_dgamma_D2D2D2)
  READ_v(_dgamma_D0D1D1)
  READ_v(_dgamma_D0D0D1)
  READ_v(_dgamma_D0D0D2)
  READ_v(_dgamma_D1D2D0)
  READ_v(_dgamma_D1D2D2)
  READ_v(_dgamma_D0D2D0)
  READ_v(_dgamma_D1D1D1)
  READ_v(_dgamma_D1D2D1)
  READ_v(_dgamma_D1D1D0)
  READ_v(_dgamma_D0D0D0)
  READ_v(_dgamma_D0D1D2)
  READ_v(_dgamma_D2D2D0)
  READ_v(_dgamma_D2D2D1)
  READ_v(_dgamma_D0D1D0)
  READ_v(_dgamma_D0D2D1)
  REALLOC_v_WRITE_v(_Gamma_U1D1D2)
  REALLOC_v_WRITE_v(_Gamma_U0D1D2)
  REALLOC_v_WRITE_v(_Gamma_U2D2D2)
  REALLOC_v_WRITE_v(_Gamma_U1D1D1)
  REALLOC_v_WRITE_v(_Gamma_U0D0D2)
  REALLOC_v_WRITE_v(_Gamma_U1D0D1)
  REALLOC_v_WRITE_v(_Gamma_U0D2D2)
  REALLOC_v_WRITE_v(_Gamma_U1D0D0)
  REALLOC_v_WRITE_v(_Gamma_U0D1D1)
  REALLOC_v_WRITE_v(_Gamma_U1D2D2)
  REALLOC_v_WRITE_v(_Gamma_U2D1D1)
  REALLOC_v_WRITE_v(_Gamma_U2D0D1)
  REALLOC_v_WRITE_v(_Gamma_U2D1D2)
  REALLOC_v_WRITE_v(_Gamma_U1D0D2)
  REALLOC_v_WRITE_v(_Gamma_U0D0D0)
  REALLOC_v_WRITE_v(_Gamma_U0D0D1)
  REALLOC_v_WRITE_v(_Gamma_U2D0D2)
  REALLOC_v_WRITE_v(_Gamma_U2D0D0)


    const unsigned nn = patch->nn;
    unsigned ijk;
    for(ijk = 0; ijk < nn; ++ijk)
    {
    double GAMMA_U1D2D2 = 
0.5*_dgamma_D2D2D2[ijk]*_gammaI_U1U2[ijk] + 0.5*_gammaI_U0U1[ijk]*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*_gammaI_U1U1[ijk]*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

    double GAMMA_U1D0D0 = 
0.5*_dgamma_D0D0D0[ijk]*_gammaI_U0U1[ijk] - 0.5*_gammaI_U1U1[ijk]*
(_dgamma_D0D0D1[ijk] - 2*_dgamma_D0D1D0[ijk]) - 0.5*_gammaI_U1U2[ijk]*
(_dgamma_D0D0D2[ijk] - 2*_dgamma_D0D2D0[ijk]);

    double GAMMA_U2D1D2 = 
0.5*_dgamma_D1D1D2[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D2D2D1[ijk]*
_gammaI_U2U2[ijk] + 0.5*_gammaI_U0U2[ijk]*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);

    double GAMMA_U2D0D1 = 
0.5*_dgamma_D0D0D1[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D1D1D0[ijk]*
_gammaI_U1U2[ijk] + 0.5*_gammaI_U2U2[ijk]*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

    double GAMMA_U1D1D1 = 
0.5*_dgamma_D1D1D1[ijk]*_gammaI_U1U1[ijk] + 0.5*_gammaI_U0U1[ijk]*(2*
_dgamma_D0D1D1[ijk] - _dgamma_D1D1D0[ijk]) - 0.5*_gammaI_U1U2[ijk]*
(_dgamma_D1D1D2[ijk] - 2*_dgamma_D1D2D1[ijk]);

    double GAMMA_U2D0D0 = 
0.5*_dgamma_D0D0D0[ijk]*_gammaI_U0U2[ijk] - 0.5*_gammaI_U1U2[ijk]*
(_dgamma_D0D0D1[ijk] - 2*_dgamma_D0D1D0[ijk]) - 0.5*_gammaI_U2U2[ijk]*
(_dgamma_D0D0D2[ijk] - 2*_dgamma_D0D2D0[ijk]);

    double GAMMA_U2D2D2 = 
0.5*_dgamma_D2D2D2[ijk]*_gammaI_U2U2[ijk] + 0.5*_gammaI_U0U2[ijk]*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*_gammaI_U1U2[ijk]*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

    double GAMMA_U1D0D1 = 
0.5*_dgamma_D0D0D1[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D1D1D0[ijk]*
_gammaI_U1U1[ijk] + 0.5*_gammaI_U1U2[ijk]*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

    double GAMMA_U0D1D1 = 
0.5*_dgamma_D1D1D1[ijk]*_gammaI_U0U1[ijk] + 0.5*_gammaI_U0U0[ijk]*(2*
_dgamma_D0D1D1[ijk] - _dgamma_D1D1D0[ijk]) - 0.5*_gammaI_U0U2[ijk]*
(_dgamma_D1D1D2[ijk] - 2*_dgamma_D1D2D1[ijk]);

    double GAMMA_U1D1D2 = 
0.5*_dgamma_D1D1D2[ijk]*_gammaI_U1U1[ijk] + 0.5*_dgamma_D2D2D1[ijk]*
_gammaI_U1U2[ijk] + 0.5*_gammaI_U0U1[ijk]*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);

    double GAMMA_U0D0D0 = 
0.5*_dgamma_D0D0D0[ijk]*_gammaI_U0U0[ijk] - 0.5*_gammaI_U0U1[ijk]*
(_dgamma_D0D0D1[ijk] - 2*_dgamma_D0D1D0[ijk]) - 0.5*_gammaI_U0U2[ijk]*
(_dgamma_D0D0D2[ijk] - 2*_dgamma_D0D2D0[ijk]);

    double GAMMA_U2D1D1 = 
0.5*_dgamma_D1D1D1[ijk]*_gammaI_U1U2[ijk] + 0.5*_gammaI_U0U2[ijk]*(2*
_dgamma_D0D1D1[ijk] - _dgamma_D1D1D0[ijk]) - 0.5*_gammaI_U2U2[ijk]*
(_dgamma_D1D1D2[ijk] - 2*_dgamma_D1D2D1[ijk]);

    double GAMMA_U1D0D2 = 
0.5*_dgamma_D0D0D2[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D2D2D0[ijk]*
_gammaI_U1U2[ijk] + 0.5*_gammaI_U1U1[ijk]*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

    double GAMMA_U0D2D2 = 
0.5*_dgamma_D2D2D2[ijk]*_gammaI_U0U2[ijk] + 0.5*_gammaI_U0U0[ijk]*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*_gammaI_U0U1[ijk]*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

    double GAMMA_U2D0D2 = 
0.5*_dgamma_D0D0D2[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D2D2D0[ijk]*
_gammaI_U2U2[ijk] + 0.5*_gammaI_U1U2[ijk]*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

    double GAMMA_U0D0D2 = 
0.5*_dgamma_D0D0D2[ijk]*_gammaI_U0U0[ijk] + 0.5*_dgamma_D2D2D0[ijk]*
_gammaI_U0U2[ijk] + 0.5*_gammaI_U0U1[ijk]*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

    double GAMMA_U0D0D1 = 
0.5*_dgamma_D0D0D1[ijk]*_gammaI_U0U0[ijk] + 0.5*_dgamma_D1D1D0[ijk]*
_gammaI_U0U1[ijk] + 0.5*_gammaI_U0U2[ijk]*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

    double GAMMA_U0D1D2 = 
0.5*_dgamma_D1D1D2[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D2D2D1[ijk]*
_gammaI_U0U2[ijk] + 0.5*_gammaI_U0U0[ijk]*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);


    /* populating: */
    _Gamma_U1D1D2[ijk] = GAMMA_U1D1D2;
    _Gamma_U0D1D2[ijk] = GAMMA_U0D1D2;
    _Gamma_U2D2D2[ijk] = GAMMA_U2D2D2;
    _Gamma_U1D1D1[ijk] = GAMMA_U1D1D1;
    _Gamma_U0D0D2[ijk] = GAMMA_U0D0D2;
    _Gamma_U1D0D1[ijk] = GAMMA_U1D0D1;
    _Gamma_U0D2D2[ijk] = GAMMA_U0D2D2;
    _Gamma_U1D0D0[ijk] = GAMMA_U1D0D0;
    _Gamma_U0D1D1[ijk] = GAMMA_U0D1D1;
    _Gamma_U1D2D2[ijk] = GAMMA_U1D2D2;
    _Gamma_U2D1D1[ijk] = GAMMA_U2D1D1;
    _Gamma_U2D0D1[ijk] = GAMMA_U2D0D1;
    _Gamma_U2D1D2[ijk] = GAMMA_U2D1D2;
    _Gamma_U1D0D2[ijk] = GAMMA_U1D0D2;
    _Gamma_U0D0D0[ijk] = GAMMA_U0D0D0;
    _Gamma_U0D0D1[ijk] = GAMMA_U0D0D1;
    _Gamma_U2D0D2[ijk] = GAMMA_U2D0D2;
    _Gamma_U2D0D0[ijk] = GAMMA_U2D0D0;
    }/*end of for(ijk = 0; ijk < nn; ++ijk)*/
}
