/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"

double bbn_Kommar_mass(Observable_T *const obs);
double bbn_Kommar_mass(Observable_T *const obs)
{
  double Kommar_mass = 0;
  struct items_S **const kommar = obs->items;
  const Uint N = obs->Nitems;
  Uint p;

  for(p = 0; p < N; ++p)
  {
    Patch_T *patch     = kommar[p]->patch;
    const double *n_U0 = kommar[p]->n_U0;
    const double *n_U1 = kommar[p]->n_U1;
    const double *n_U2 = kommar[p]->n_U2;
    Uint nn        = patch->nn;
    Uint ijk;

    ADD_FIELD(Kommar_mass_integrand)


  /* declaring: */
  READ_v(_gamma_D2D2)
  READ_v(_gamma_D0D2)
  READ_v(_gamma_D0D0)
  READ_v(_gamma_D0D1)
  READ_v(_gamma_D1D2)
  READ_v(_gamma_D1D1)
  READ_v(_A_UiUj_U2U2)
  READ_v(_A_UiUj_U1U2)
  READ_v(_A_UiUj_U1U1)
  READ_v(_A_UiUj_U0U2)
  READ_v(_A_UiUj_U0U1)
  READ_v(_A_UiUj_U0U0)
  READ_v(eta)
  READ_v(deta_D0)
  READ_v(deta_D1)
  READ_v(deta_D2)
  READ_v(Beta_U1)
  READ_v(Beta_U0)
  READ_v(Beta_U2)
  READ_v(K)
  READ_v(psi)
  READ_v(dpsi_D0)
  READ_v(dpsi_D1)
  READ_v(dpsi_D2)


{
    REALLOC_v_WRITE_v(Kommar_mass_integrand)
    for(ijk = 0; ijk < nn; ++ijk)
    {
    double psim2 = 
pow(psi[ijk], -2);

    double psi2 = 
pow(psi[ijk], 2);

    double psi4 = 
pow(psi[ijk], 4);

    double dalpha_U1 = 
deta_D1[ijk]/psi[ijk] - dpsi_D1[ijk]*eta[ijk]/psi2;

    double dalpha_U0 = 
deta_D0[ijk]/psi[ijk] - dpsi_D0[ijk]*eta[ijk]/psi2;

    double dalpha_U2 = 
deta_D2[ijk]/psi[ijk] - dpsi_D2[ijk]*eta[ijk]/psi2;

    double K_DD_D1D1 = 
0.33333333333333331*K[ijk]*_gamma_D1D1[ijk]*psi4 + psim2*
(_A_UiUj_U0U0[ijk]*pow(_gamma_D0D1[ijk], 2) + 2.0*_A_UiUj_U0U1[ijk]*
_gamma_D0D1[ijk]*_gamma_D1D1[ijk] + 2.0*_A_UiUj_U0U2[ijk]*
_gamma_D0D1[ijk]*_gamma_D1D2[ijk] + _A_UiUj_U1U1[ijk]*
pow(_gamma_D1D1[ijk], 2) + 2.0*_A_UiUj_U1U2[ijk]*_gamma_D1D1[ijk]*
_gamma_D1D2[ijk] + _A_UiUj_U2U2[ijk]*pow(_gamma_D1D2[ijk], 2));

    double K_DD_D1D2 = 
0.33333333333333331*K[ijk]*_gamma_D1D2[ijk]*psi4 + psim2*
(_A_UiUj_U0U0[ijk]*_gamma_D0D1[ijk]*_gamma_D0D2[ijk] + 
_A_UiUj_U0U1[ijk]*_gamma_D0D1[ijk]*_gamma_D1D2[ijk] + 
_A_UiUj_U0U1[ijk]*_gamma_D0D2[ijk]*_gamma_D1D1[ijk] + 
_A_UiUj_U0U2[ijk]*_gamma_D0D1[ijk]*_gamma_D2D2[ijk] + 
_A_UiUj_U0U2[ijk]*_gamma_D0D2[ijk]*_gamma_D1D2[ijk] + 
_A_UiUj_U1U1[ijk]*_gamma_D1D1[ijk]*_gamma_D1D2[ijk] + 
_A_UiUj_U1U2[ijk]*_gamma_D1D1[ijk]*_gamma_D2D2[ijk] + 
_A_UiUj_U1U2[ijk]*pow(_gamma_D1D2[ijk], 2) + _A_UiUj_U2U2[ijk]*
_gamma_D1D2[ijk]*_gamma_D2D2[ijk]);

    double K_DD_D2D2 = 
0.33333333333333331*K[ijk]*_gamma_D2D2[ijk]*psi4 + psim2*
(_A_UiUj_U0U0[ijk]*pow(_gamma_D0D2[ijk], 2) + 2.0*_A_UiUj_U0U1[ijk]*
_gamma_D0D2[ijk]*_gamma_D1D2[ijk] + 2.0*_A_UiUj_U0U2[ijk]*
_gamma_D0D2[ijk]*_gamma_D2D2[ijk] + _A_UiUj_U1U1[ijk]*
pow(_gamma_D1D2[ijk], 2) + 2.0*_A_UiUj_U1U2[ijk]*_gamma_D1D2[ijk]*
_gamma_D2D2[ijk] + _A_UiUj_U2U2[ijk]*pow(_gamma_D2D2[ijk], 2));

    double K_DD_D0D0 = 
0.33333333333333331*K[ijk]*_gamma_D0D0[ijk]*psi4 + psim2*
(_A_UiUj_U0U0[ijk]*pow(_gamma_D0D0[ijk], 2) + 2.0*_A_UiUj_U0U1[ijk]*
_gamma_D0D0[ijk]*_gamma_D0D1[ijk] + 2.0*_A_UiUj_U0U2[ijk]*
_gamma_D0D0[ijk]*_gamma_D0D2[ijk] + _A_UiUj_U1U1[ijk]*
pow(_gamma_D0D1[ijk], 2) + 2.0*_A_UiUj_U1U2[ijk]*_gamma_D0D1[ijk]*
_gamma_D0D2[ijk] + _A_UiUj_U2U2[ijk]*pow(_gamma_D0D2[ijk], 2));

    double K_DD_D0D1 = 
0.33333333333333331*K[ijk]*_gamma_D0D1[ijk]*psi4 + psim2*
(_A_UiUj_U0U0[ijk]*_gamma_D0D0[ijk]*_gamma_D0D1[ijk] + 
_A_UiUj_U0U1[ijk]*_gamma_D0D0[ijk]*_gamma_D1D1[ijk] + 
_A_UiUj_U0U1[ijk]*pow(_gamma_D0D1[ijk], 2) + _A_UiUj_U0U2[ijk]*
_gamma_D0D0[ijk]*_gamma_D1D2[ijk] + _A_UiUj_U0U2[ijk]*_gamma_D0D1[ijk]*
_gamma_D0D2[ijk] + _A_UiUj_U1U1[ijk]*_gamma_D0D1[ijk]*
_gamma_D1D1[ijk] + _A_UiUj_U1U2[ijk]*_gamma_D0D1[ijk]*
_gamma_D1D2[ijk] + _A_UiUj_U1U2[ijk]*_gamma_D0D2[ijk]*
_gamma_D1D1[ijk] + _A_UiUj_U2U2[ijk]*_gamma_D0D2[ijk]*
_gamma_D1D2[ijk]);

    double K_DD_D0D2 = 
0.33333333333333331*K[ijk]*_gamma_D0D2[ijk]*psi4 + psim2*
(_A_UiUj_U0U0[ijk]*_gamma_D0D0[ijk]*_gamma_D0D2[ijk] + 
_A_UiUj_U0U1[ijk]*_gamma_D0D0[ijk]*_gamma_D1D2[ijk] + 
_A_UiUj_U0U1[ijk]*_gamma_D0D1[ijk]*_gamma_D0D2[ijk] + 
_A_UiUj_U0U2[ijk]*_gamma_D0D0[ijk]*_gamma_D2D2[ijk] + 
_A_UiUj_U0U2[ijk]*pow(_gamma_D0D2[ijk], 2) + _A_UiUj_U1U1[ijk]*
_gamma_D0D1[ijk]*_gamma_D1D2[ijk] + _A_UiUj_U1U2[ijk]*_gamma_D0D1[ijk]*
_gamma_D2D2[ijk] + _A_UiUj_U1U2[ijk]*_gamma_D0D2[ijk]*
_gamma_D1D2[ijk] + _A_UiUj_U2U2[ijk]*_gamma_D0D2[ijk]*
_gamma_D2D2[ijk]);

    double integrand = 
-n_U0[ijk]*(Beta_U0[ijk]*K_DD_D0D0 + Beta_U1[ijk]*K_DD_D0D1 +
Beta_U2[ijk]*K_DD_D0D2 - dalpha_U0) - n_U1[ijk]*(Beta_U0[ijk]*
K_DD_D0D1 + Beta_U1[ijk]*K_DD_D1D1 + Beta_U2[ijk]*K_DD_D1D2 -
dalpha_U1) - n_U2[ijk]*(Beta_U0[ijk]*K_DD_D0D2 + Beta_U1[ijk]*
K_DD_D1D2 + Beta_U2[ijk]*K_DD_D2D2 - dalpha_U2);


      Kommar_mass_integrand[ijk] = integrand;
    }
}

  DECLARE_FIELD(Kommar_mass_integrand)
  Integration_T *I = init_integration();
  I->type = "Integral{f(x)dS},Spectral";
  I->Spectral->f = Kommar_mass_integrand;
  I->g00 = kommar[p]->g00;
  I->g01 = kommar[p]->g01;
  I->g02 = kommar[p]->g02;
  I->g11 = kommar[p]->g11;
  I->g12 = kommar[p]->g12;
  I->g22 = kommar[p]->g22;
  I->Spectral->X_surface = kommar[p]->X_surface;
  I->Spectral->Y_surface = kommar[p]->Y_surface;
  I->Spectral->Z_surface = kommar[p]->Z_surface;
  I->Spectral->I         = kommar[p]->I;
  I->Spectral->J         = kommar[p]->J;
  I->Spectral->K         = kommar[p]->K;
  plan_integration(I);
  Kommar_mass += execute_integration(I);

  free_integration(I);
  REMOVE_FIELD(Kommar_mass_integrand)
  }

  Kommar_mass /= (4*M_PI);
  return Kommar_mass;
}
