/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "bbn_headers.h"
#include "maths_equation_solvings_lib.h"

#define read_2nd_order_derives(name) \
        sprintf(eq_fld_name,"%s_%s",#name,fld_name); \
        const double *const name = patch->pool[Ind(fld_name)]->v;

void *bbn_bhf_eq_Brown(void *vp1,void *vp2);
void *bbn_bhf_eq_Brown(void *vp1,void *vp2)
{
  DDM_SCHUR_EQ_DECLARE
  unsigned ijk;/* node index */
  const Solving_Man_T *const sol = patch->solving_man;
  const char *const fld_name     = sol->field_name[sol->cf];
  char eq_fld_name[100] = {'\0'};


  /* declaring: */
  read_2nd_order_derives(ddB_xx)
  read_2nd_order_derives(ddB_yy)
  read_2nd_order_derives(ddB_zz)


  DDM_SCHUR_EQ_OPEN

  double F_eq = 
ddB_xx[ijk] + ddB_yy[ijk] + ddB_zz[ijk];

  F[n] = F_eq;

  DDM_SCHUR_EQ_CLOSE

  return 0;
}
