/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"
#include "maths_equation_solvings_lib.h"
#include "bbn_XCTS_equations_lib.h"


void *bbn_eq_eta(void *vp1,void *vp2)
{
  DDM_SCHUR_EQ_DECLARE
  unsigned ijk;/* node index */

  /* declaring: */
  READ_v(eta)
  READ_v(deta_D0)
  READ_v(deta_D1)
  READ_v(deta_D2)
  READ_v(ddeta_D2D2)
  READ_v(ddeta_D1D1)
  READ_v(ddeta_D0D1)
  READ_v(ddeta_D0D0)
  READ_v(ddeta_D1D2)
  READ_v(ddeta_D0D2)
  READ_v(psi)
  READ_v(Beta_U1)
  READ_v(Beta_U0)
  READ_v(Beta_U2)
  READ_v(_R)
  READ_v(K)
  READ_v(dK_D2)
  READ_v(dK_D1)
  READ_v(dK_D0)
  READ_v(_Aij2)
  READ_v(_E)
  READ_v(_S)
  READ_v(_gammaI_U0U2)
  READ_v(_gammaI_U0U0)
  READ_v(_gammaI_U0U1)
  READ_v(_gammaI_U1U2)
  READ_v(_gammaI_U1U1)
  READ_v(_gammaI_U2U2)
  READ_v(_Gamma_U2D1D1)
  READ_v(_Gamma_U2D1D2)
  READ_v(_Gamma_U0D1D1)
  READ_v(_Gamma_U2D0D2)
  READ_v(_Gamma_U2D2D2)
  READ_v(_Gamma_U0D1D2)
  READ_v(_Gamma_U0D0D2)
  READ_v(_Gamma_U0D0D1)
  READ_v(_Gamma_U0D0D0)
  READ_v(_Gamma_U1D2D2)
  READ_v(_Gamma_U2D0D1)
  READ_v(_Gamma_U0D2D2)
  READ_v(_Gamma_U2D0D0)
  READ_v(_Gamma_U1D0D2)
  READ_v(_Gamma_U1D1D2)
  READ_v(_Gamma_U1D0D0)
  READ_v(_Gamma_U1D0D1)
  READ_v(_Gamma_U1D1D1)


  DDM_SCHUR_EQ_OPEN

  double psi4 = 
pow(psi[ijk], 4);

  double aij2 = 
_Aij2[ijk]/psi4;

  double F_eq = 
-_gammaI_U0U0[ijk]*(_Gamma_U0D0D0[ijk]*deta_D0[ijk] +
_Gamma_U1D0D0[ijk]*deta_D1[ijk] + _Gamma_U2D0D0[ijk]*deta_D2[ijk] -
ddeta_D0D0[ijk]) - 2.0*_gammaI_U0U1[ijk]*(_Gamma_U0D0D1[ijk]*
deta_D0[ijk] + _Gamma_U1D0D1[ijk]*deta_D1[ijk] + _Gamma_U2D0D1[ijk]*
deta_D2[ijk] - ddeta_D0D1[ijk]) - 2.0*_gammaI_U0U2[ijk]*
(_Gamma_U0D0D2[ijk]*deta_D0[ijk] + _Gamma_U1D0D2[ijk]*deta_D1[ijk] +
_Gamma_U2D0D2[ijk]*deta_D2[ijk] - ddeta_D0D2[ijk]) - _gammaI_U1U1[ijk]*
(_Gamma_U0D1D1[ijk]*deta_D0[ijk] + _Gamma_U1D1D1[ijk]*deta_D1[ijk] +
_Gamma_U2D1D1[ijk]*deta_D2[ijk] - ddeta_D1D1[ijk]) - 2.0*
_gammaI_U1U2[ijk]*(_Gamma_U0D1D2[ijk]*deta_D0[ijk] +
_Gamma_U1D1D2[ijk]*deta_D1[ijk] + _Gamma_U2D1D2[ijk]*deta_D2[ijk] -
ddeta_D1D2[ijk]) - _gammaI_U2U2[ijk]*(_Gamma_U0D2D2[ijk]*deta_D0[ijk] +
_Gamma_U1D2D2[ijk]*deta_D1[ijk] + _Gamma_U2D2D2[ijk]*deta_D2[ijk] -
ddeta_D2D2[ijk]) - eta[ijk]*(0.41666666666666669*pow(K[ijk], 2)*psi4 +
(1.0/8.0)*_R[ijk] + 0.875*aij2/psi4) - 2*M_PI*eta[ijk]*(_E[ijk] + 2*
_S[ijk])/pow(psi[ijk], 2) - psi[ijk]*psi4*(Beta_U0[ijk]*dK_D0[ijk] +
Beta_U1[ijk]*dK_D1[ijk] + Beta_U2[ijk]*dK_D2[ijk]);

  F[n] = F_eq;

  DDM_SCHUR_EQ_CLOSE

  return 0;
}
