/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"
#include "maths_equation_solvings_lib.h"
#include "bbn_XCTS_equations_lib.h"


void *bc_Beta_U2(void *vp1,void *vp2)
{
  DDM_SCHUR_BC_DECLARE
  unsigned ijk;/* node index */

  /* declaring: */
  GET_FIELD(B0_U2)
  GET_FIELD(B1_U2)
  GET_FIELD(psi)
  GET_FIELD(eta)
  GET_FIELD_IF_ON_HORIZON(_HS_U2)


  const double BH_Omega_U0 = GetParameterD_E("BH_mass")*GetParameterD_E("BH_X_U0");
  const double BH_Omega_U1 = GetParameterD_E("BH_mass")*GetParameterD_E("BH_X_U1");
  if (patch->outerB)/* at outer boundary */
  {
  DDM_SCHUR_BC_OPEN

  double outerB_F = 
B0_U2[ijk];

  F[map[ijk]] = outerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)/* at inner boundary */
  {
  DDM_SCHUR_BC_OPEN

  double alpha = 
eta[ijk]/psi[ijk];

  double S_U2 = 
_HS_U2[ijk]/pow(psi[ijk], 2);

  double x = patch->node[ijk]->x[0];
  double y = patch->node[ijk]->x[1];
  double OmegaXr_U2 = 
BH_Omega_U0*y - BH_Omega_U1*x;

  double innerB_F = 
B0_U2[ijk] + B1_U2[ijk] - OmegaXr_U2 - S_U2*alpha;

  F[map[ijk]] = innerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of else if (patch->innerB) */
  return 0;
}
