/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"


#define add_field_and_prep_field(name) ADD_FIELD(name) REALLOC_v_WRITE_v(name)
#define add_field_NoMem_and_declare_field(name) \
 ADD_FIELD(name)  Field_T *const f##name = patch->pool[Ind(#name)];
void bbn_bam_set_bam_fields(Grid_T *const grid)
{
  unsigned p;
  FOR_ALL_PATCHES(p,grid)
  {
  Patch_T *patch = grid->patch[p];
  unsigned nn    = patch->nn;
  unsigned ijk;

  /* declaring: */
  add_field_and_prep_field(bam_alpha)
  add_field_and_prep_field(bam_Beta_U0)
  add_field_and_prep_field(bam_Beta_U1)
  add_field_and_prep_field(bam_Beta_U2)
  add_field_and_prep_field(bam_adm_g_D0D0)
  add_field_and_prep_field(bam_adm_g_D0D1)
  add_field_and_prep_field(bam_adm_g_D0D2)
  add_field_and_prep_field(bam_adm_g_D2D2)
  add_field_and_prep_field(bam_adm_g_D1D1)
  add_field_and_prep_field(bam_adm_g_D1D2)
  add_field_and_prep_field(bam_adm_K_D1D1)
  add_field_and_prep_field(bam_adm_K_D2D2)
  add_field_and_prep_field(bam_adm_K_D0D0)
  add_field_and_prep_field(bam_adm_K_D0D1)
  add_field_and_prep_field(bam_adm_K_D0D2)
  add_field_and_prep_field(bam_adm_K_D1D2)
  add_field_and_prep_field(bam_grhd_v_U0)
  add_field_and_prep_field(bam_grhd_v_U1)
  add_field_and_prep_field(bam_grhd_v_U2)
  READ_v(_A_UiUj_U2U2)
  READ_v(_A_UiUj_U1U2)
  READ_v(_A_UiUj_U1U1)
  READ_v(_A_UiUj_U0U2)
  READ_v(_A_UiUj_U0U1)
  READ_v(_A_UiUj_U0U0)
  READ_v(Beta_U1)
  READ_v(Beta_U0)
  READ_v(Beta_U2)
  READ_v(B1_U0)
  READ_v(B1_U1)
  READ_v(B1_U2)
  READ_v(psi)
  READ_v(eta)
  READ_v(K)
  READ_v(_gamma_D2D2)
  READ_v(_gamma_D0D2)
  READ_v(_gamma_D0D0)
  READ_v(_gamma_D0D1)
  READ_v(_gamma_D1D2)
  READ_v(_gamma_D1D1)
  READ_v(_gammaI_U0U2)
  READ_v(_gammaI_U0U0)
  READ_v(_gammaI_U0U1)
  READ_v(_gammaI_U1U2)
  READ_v(_gammaI_U1U1)
  READ_v(_gammaI_U2U2)


  for(ijk = 0; ijk < nn; ++ijk)
  {
  double temp_bh2_D0D0 = 
1.0;

  double temp_bh2_D2D2 = 
1.0;

  double temp_bh2_D1D2 = 
0;

  double temp_bh2_D0D2 = 
0;

  double temp_bh2_D0D1 = 
0;

  double temp_bh2_D1D1 = 
1.0;

  double temp_bh1_U2 = 
B1_U2[ijk];

  double temp_bh1_U1 = 
B1_U1[ijk];

  double temp_bh1_U0 = 
B1_U0[ijk];

  bam_alpha[ijk] = eta[ijk]/psi[ijk];

  /* populating: */
  bam_Beta_U0[ijk] = temp_bh1_U0;
  bam_Beta_U1[ijk] = temp_bh1_U1;
  bam_Beta_U2[ijk] = temp_bh1_U2;

  /* populating: */
  bam_adm_g_D0D0[ijk] = temp_bh2_D0D0;
  bam_adm_g_D0D1[ijk] = temp_bh2_D0D1;
  bam_adm_g_D0D2[ijk] = temp_bh2_D0D2;
  bam_adm_g_D2D2[ijk] = temp_bh2_D2D2;
  bam_adm_g_D1D1[ijk] = temp_bh2_D1D1;
  bam_adm_g_D1D2[ijk] = temp_bh2_D1D2;

  /* populating: */
  bam_adm_K_D1D1[ijk] = temp_bh2_D1D1;
  bam_adm_K_D2D2[ijk] = temp_bh2_D2D2;
  bam_adm_K_D0D0[ijk] = temp_bh2_D0D0;
  bam_adm_K_D0D1[ijk] = temp_bh2_D0D1;
  bam_adm_K_D0D2[ijk] = temp_bh2_D0D2;
  bam_adm_K_D1D2[ijk] = temp_bh2_D1D2;
  }
  for(ijk = 0; ijk < nn; ++ijk)
  {
  double psi4 = 
pow(psi[ijk], 4);

  double psim4 = 
pow(psi[ijk], -4);

  double psim10 = 
pow(psim4, 2)/pow(psi[ijk], 2);

  bam_alpha[ijk] = eta[ijk]/psi[ijk];
   bam_Beta_U0[ijk] = Beta_U0[ijk];
   bam_Beta_U1[ijk] = Beta_U1[ijk];
   bam_Beta_U2[ijk] = Beta_U2[ijk];
   double adm_g_D0D2 = 
_gamma_D0D2[ijk]*psi4;

   double adm_g_D0D1 = 
_gamma_D0D1[ijk]*psi4;

   double adm_g_D0D0 = 
_gamma_D0D0[ijk]*psi4;

   double adm_g_D1D2 = 
_gamma_D1D2[ijk]*psi4;

   double adm_g_D1D1 = 
_gamma_D1D1[ijk]*psi4;

   double adm_g_D2D2 = 
_gamma_D2D2[ijk]*psi4;


   /* populating: */
   bam_adm_g_D0D0[ijk] = adm_g_D0D0;
   bam_adm_g_D0D1[ijk] = adm_g_D0D1;
   bam_adm_g_D0D2[ijk] = adm_g_D0D2;
   bam_adm_g_D2D2[ijk] = adm_g_D2D2;
   bam_adm_g_D1D1[ijk] = adm_g_D1D1;
   bam_adm_g_D1D2[ijk] = adm_g_D1D2;
   double adm_Kuu_U1U2 = 
(1.0/3.0)*K[ijk]*_gammaI_U1U2[ijk]*psim4 + _A_UiUj_U1U2[ijk]*
psim10;

   double adm_Kuu_U1U1 = 
(1.0/3.0)*K[ijk]*_gammaI_U1U1[ijk]*psim4 + _A_UiUj_U1U1[ijk]*
psim10;

   double adm_Kuu_U0U2 = 
(1.0/3.0)*K[ijk]*_gammaI_U0U2[ijk]*psim4 + _A_UiUj_U0U2[ijk]*
psim10;

   double adm_Kuu_U0U1 = 
(1.0/3.0)*K[ijk]*_gammaI_U0U1[ijk]*psim4 + _A_UiUj_U0U1[ijk]*
psim10;

   double adm_Kuu_U0U0 = 
(1.0/3.0)*K[ijk]*_gammaI_U0U0[ijk]*psim4 + _A_UiUj_U0U0[ijk]*
psim10;

   double adm_Kuu_U2U2 = 
(1.0/3.0)*K[ijk]*_gammaI_U2U2[ijk]*psim4 + _A_UiUj_U2U2[ijk]*
psim10;

   double adm_Kdd_D0D1 = 
adm_Kuu_U0U0*adm_g_D0D0*adm_g_D0D1 + adm_Kuu_U0U1*adm_g_D0D0*
adm_g_D1D1 + adm_Kuu_U0U1*pow(adm_g_D0D1, 2) + adm_Kuu_U0U2*adm_g_D0D0*
adm_g_D1D2 + adm_Kuu_U0U2*adm_g_D0D1*adm_g_D0D2 + adm_Kuu_U1U1*
adm_g_D0D1*adm_g_D1D1 + adm_Kuu_U1U2*adm_g_D0D1*adm_g_D1D2 + 
adm_Kuu_U1U2*adm_g_D0D2*adm_g_D1D1 + adm_Kuu_U2U2*adm_g_D0D2*
adm_g_D1D2;

   double adm_Kdd_D0D0 = 
adm_Kuu_U0U0*pow(adm_g_D0D0, 2) + 2.0*adm_Kuu_U0U1*adm_g_D0D0*
adm_g_D0D1 + 2.0*adm_Kuu_U0U2*adm_g_D0D0*adm_g_D0D2 + adm_Kuu_U1U1*
pow(adm_g_D0D1, 2) + 2.0*adm_Kuu_U1U2*adm_g_D0D1*adm_g_D0D2 + 
adm_Kuu_U2U2*pow(adm_g_D0D2, 2);

   double adm_Kdd_D0D2 = 
adm_Kuu_U0U0*adm_g_D0D0*adm_g_D0D2 + adm_Kuu_U0U1*adm_g_D0D0*
adm_g_D1D2 + adm_Kuu_U0U1*adm_g_D0D1*adm_g_D0D2 + adm_Kuu_U0U2*
adm_g_D0D0*adm_g_D2D2 + adm_Kuu_U0U2*pow(adm_g_D0D2, 2) + adm_Kuu_U1U1*
adm_g_D0D1*adm_g_D1D2 + adm_Kuu_U1U2*adm_g_D0D1*adm_g_D2D2 + 
adm_Kuu_U1U2*adm_g_D0D2*adm_g_D1D2 + adm_Kuu_U2U2*adm_g_D0D2*
adm_g_D2D2;

   double adm_Kdd_D1D1 = 
adm_Kuu_U0U0*pow(adm_g_D0D1, 2) + 2.0*adm_Kuu_U0U1*adm_g_D0D1*
adm_g_D1D1 + 2.0*adm_Kuu_U0U2*adm_g_D0D1*adm_g_D1D2 + adm_Kuu_U1U1*
pow(adm_g_D1D1, 2) + 2.0*adm_Kuu_U1U2*adm_g_D1D1*adm_g_D1D2 + 
adm_Kuu_U2U2*pow(adm_g_D1D2, 2);

   double adm_Kdd_D1D2 = 
adm_Kuu_U0U0*adm_g_D0D1*adm_g_D0D2 + adm_Kuu_U0U1*adm_g_D0D1*
adm_g_D1D2 + adm_Kuu_U0U1*adm_g_D0D2*adm_g_D1D1 + adm_Kuu_U0U2*
adm_g_D0D1*adm_g_D2D2 + adm_Kuu_U0U2*adm_g_D0D2*adm_g_D1D2 + 
adm_Kuu_U1U1*adm_g_D1D1*adm_g_D1D2 + adm_Kuu_U1U2*adm_g_D1D1*
adm_g_D2D2 + adm_Kuu_U1U2*pow(adm_g_D1D2, 2) + adm_Kuu_U2U2*adm_g_D1D2*
adm_g_D2D2;

   double adm_Kdd_D2D2 = 
adm_Kuu_U0U0*pow(adm_g_D0D2, 2) + 2.0*adm_Kuu_U0U1*adm_g_D0D2*
adm_g_D1D2 + 2.0*adm_Kuu_U0U2*adm_g_D0D2*adm_g_D2D2 + adm_Kuu_U1U1*
pow(adm_g_D1D2, 2) + 2.0*adm_Kuu_U1U2*adm_g_D1D2*adm_g_D2D2 + 
adm_Kuu_U2U2*pow(adm_g_D2D2, 2);


   /* populating: */
   bam_adm_K_D1D1[ijk] = adm_Kdd_D1D1;
   bam_adm_K_D2D2[ijk] = adm_Kdd_D2D2;
   bam_adm_K_D0D0[ijk] = adm_Kdd_D0D0;
   bam_adm_K_D0D1[ijk] = adm_Kdd_D0D1;
   bam_adm_K_D0D2[ijk] = adm_Kdd_D0D2;
   bam_adm_K_D1D2[ijk] = adm_Kdd_D1D2;
  }
  for(ijk = 0; ijk < nn; ++ijk)
  {
  }
  }
}
