/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "core_lib.h"
#include "physics_observables_lib.h"
#include "utilities_lib.h"
#include "manifold_lib.h"
#include "maths_general_lib.h"
#include "maths_calculus_lib.h"
#include "fields_lib.h"
#include "bbn_headers.h"

#define declare_and_alloc_xi(name) \
  double *name = alloc_double(nn);

#define add_and_get_field(name) \
  if (_Ind(#name) >= 0)\
  {DECLARE_FIELD(name);REMOVE_FIELD(name);}\
  ADD_FIELD(name);REALLOC_v_WRITE_v(name);


void bbn_populate_spin_integrands_Campanelli(Patch_T *const patch,const double xc[3],const double *const normal[3]);
void bbn_populate_spin_integrands_Campanelli(Patch_T *const patch,const double xc[3],const double *const normal[3])
{
  const double x_c = xc[0];
  const double y_c = xc[1];
  const double z_c = xc[2];
  const unsigned nn = patch->nn;
  unsigned ijk;

  /* declaring: */
  READ_v(_A_UiUj_U1U2)
  READ_v(_A_UiUj_U0U1)
  READ_v(_A_UiUj_U0U2)
  READ_v(_A_UiUj_U1U1)
  READ_v(_A_UiUj_U2U2)
  READ_v(_A_UiUj_U0U0)
  READ_v(_gamma_D0D1)
  READ_v(_gamma_D0D0)
  READ_v(_gamma_D2D2)
  READ_v(_gamma_D0D2)
  READ_v(_gamma_D1D1)
  READ_v(_gamma_D1D2)
  READ_v(psi)
  add_and_get_field(SPIN_integrand_D1)
  add_and_get_field(SPIN_integrand_D2)
  add_and_get_field(SPIN_integrand_D0)
  declare_and_alloc_xi(xi0_U0)
  declare_and_alloc_xi(xi0_U1)
  declare_and_alloc_xi(xi0_U2)
  declare_and_alloc_xi(xi1_U0)
  declare_and_alloc_xi(xi1_U1)
  declare_and_alloc_xi(xi1_U2)
  declare_and_alloc_xi(xi2_U0)
  declare_and_alloc_xi(xi2_U1)
  declare_and_alloc_xi(xi2_U2)



   for(ijk = 0; ijk < nn; ++ijk)
   {
   double x    = patch->node[ijk]->x[0];
   double y    = patch->node[ijk]->x[1];
   double z    = patch->node[ijk]->x[2];
   xi0_U0[ijk] = 0;
   xi0_U1[ijk] = -(z-z_c);
   xi0_U2[ijk] = y-y_c;
   xi1_U0[ijk] = z-z_c;
   xi1_U1[ijk] = 0;
   xi1_U2[ijk] = -(x-x_c);
   xi2_U0[ijk] = -(y-y_c);
   xi2_U1[ijk] = (x-x_c);
   xi2_U2[ijk] = 0;
   }
   const double *const n_U0 = normal[0];
   const double *const n_U1 = normal[1];
   const double *const n_U2 = normal[2];
   for (ijk = 0; ijk < nn; ++ijk)
   {
   double psim2 = 
pow(psi[ijk], -2);

   double Pn_U1 = 
_A_UiUj_U0U1[ijk]*_gamma_D0D0[ijk]*n_U0[ijk] + _A_UiUj_U0U1[ijk]*
_gamma_D0D1[ijk]*n_U1[ijk] + _A_UiUj_U0U1[ijk]*_gamma_D0D2[ijk]*
n_U2[ijk] + _A_UiUj_U1U1[ijk]*_gamma_D0D1[ijk]*n_U0[ijk] + 
_A_UiUj_U1U1[ijk]*_gamma_D1D1[ijk]*n_U1[ijk] + _A_UiUj_U1U1[ijk]*
_gamma_D1D2[ijk]*n_U2[ijk] + _A_UiUj_U1U2[ijk]*_gamma_D0D2[ijk]*
n_U0[ijk] + _A_UiUj_U1U2[ijk]*_gamma_D1D2[ijk]*n_U1[ijk] + 
_A_UiUj_U1U2[ijk]*_gamma_D2D2[ijk]*n_U2[ijk];

   double Pn_U0 = 
_A_UiUj_U0U0[ijk]*_gamma_D0D0[ijk]*n_U0[ijk] + _A_UiUj_U0U0[ijk]*
_gamma_D0D1[ijk]*n_U1[ijk] + _A_UiUj_U0U0[ijk]*_gamma_D0D2[ijk]*
n_U2[ijk] + _A_UiUj_U0U1[ijk]*_gamma_D0D1[ijk]*n_U0[ijk] + 
_A_UiUj_U0U1[ijk]*_gamma_D1D1[ijk]*n_U1[ijk] + _A_UiUj_U0U1[ijk]*
_gamma_D1D2[ijk]*n_U2[ijk] + _A_UiUj_U0U2[ijk]*_gamma_D0D2[ijk]*
n_U0[ijk] + _A_UiUj_U0U2[ijk]*_gamma_D1D2[ijk]*n_U1[ijk] + 
_A_UiUj_U0U2[ijk]*_gamma_D2D2[ijk]*n_U2[ijk];

   double Pn_U2 = 
_A_UiUj_U0U2[ijk]*_gamma_D0D0[ijk]*n_U0[ijk] + _A_UiUj_U0U2[ijk]*
_gamma_D0D1[ijk]*n_U1[ijk] + _A_UiUj_U0U2[ijk]*_gamma_D0D2[ijk]*
n_U2[ijk] + _A_UiUj_U1U2[ijk]*_gamma_D0D1[ijk]*n_U0[ijk] + 
_A_UiUj_U1U2[ijk]*_gamma_D1D1[ijk]*n_U1[ijk] + _A_UiUj_U1U2[ijk]*
_gamma_D1D2[ijk]*n_U2[ijk] + _A_UiUj_U2U2[ijk]*_gamma_D0D2[ijk]*
n_U0[ijk] + _A_UiUj_U2U2[ijk]*_gamma_D1D2[ijk]*n_U1[ijk] + 
_A_UiUj_U2U2[ijk]*_gamma_D2D2[ijk]*n_U2[ijk];

   double xi0P = 
psim2*(Pn_U0*_gamma_D0D0[ijk]*xi0_U0[ijk] + Pn_U0*_gamma_D0D1[ijk]*
xi0_U1[ijk] + Pn_U0*_gamma_D0D2[ijk]*xi0_U2[ijk] + Pn_U1*
_gamma_D0D1[ijk]*xi0_U0[ijk] + Pn_U1*_gamma_D1D1[ijk]*xi0_U1[ijk] +
Pn_U1*_gamma_D1D2[ijk]*xi0_U2[ijk] + Pn_U2*_gamma_D0D2[ijk]*
xi0_U0[ijk] + Pn_U2*_gamma_D1D2[ijk]*xi0_U1[ijk] + Pn_U2*
_gamma_D2D2[ijk]*xi0_U2[ijk]);

   double xi1P = 
psim2*(Pn_U0*_gamma_D0D0[ijk]*xi1_U0[ijk] + Pn_U0*_gamma_D0D1[ijk]*
xi1_U1[ijk] + Pn_U0*_gamma_D0D2[ijk]*xi1_U2[ijk] + Pn_U1*
_gamma_D0D1[ijk]*xi1_U0[ijk] + Pn_U1*_gamma_D1D1[ijk]*xi1_U1[ijk] +
Pn_U1*_gamma_D1D2[ijk]*xi1_U2[ijk] + Pn_U2*_gamma_D0D2[ijk]*
xi1_U0[ijk] + Pn_U2*_gamma_D1D2[ijk]*xi1_U1[ijk] + Pn_U2*
_gamma_D2D2[ijk]*xi1_U2[ijk]);

   double xi2P = 
psim2*(Pn_U0*_gamma_D0D0[ijk]*xi2_U0[ijk] + Pn_U0*_gamma_D0D1[ijk]*
xi2_U1[ijk] + Pn_U0*_gamma_D0D2[ijk]*xi2_U2[ijk] + Pn_U1*
_gamma_D0D1[ijk]*xi2_U0[ijk] + Pn_U1*_gamma_D1D1[ijk]*xi2_U1[ijk] +
Pn_U1*_gamma_D1D2[ijk]*xi2_U2[ijk] + Pn_U2*_gamma_D0D2[ijk]*
xi2_U0[ijk] + Pn_U2*_gamma_D1D2[ijk]*xi2_U1[ijk] + Pn_U2*
_gamma_D2D2[ijk]*xi2_U2[ijk]);

   SPIN_integrand_D0[ijk] = xi0P;
   SPIN_integrand_D1[ijk] = xi1P;
   SPIN_integrand_D2[ijk] = xi2P;
   }

   free(xi0_U0);
   free(xi0_U1);
   free(xi0_U2);
   free(xi1_U0);
   free(xi1_U1);
   free(xi1_U2);
   free(xi2_U0);
   free(xi2_U1);
   free(xi2_U2);

}
