/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"


void bbn_calculate_constraints_2nd(Grid_T *const grid);
void bbn_calculate_constraints_2nd(Grid_T *const grid)
{

  bbn_make_K_UiUj_and_dK_UiUj(grid);
  bbn_make_metric_and_Gamma_and_derivatives(grid);
  const unsigned np = grid->np;
  unsigned p;

  OpenMP_Patch_Pragma(omp parallel for)
  for(p = 0; p < np; ++p)
  {
    Patch_T *patch = grid->patch[p];
    unsigned nn = patch->nn;
    unsigned ijk;

    if(IsItInsideBHPatch(patch))
       continue;


  /* declaring: */
  REALLOC_v_WRITE_v(ham_constraint_2nd)
  REALLOC_v_WRITE_v(mom_constraint_2nd_U1)
  REALLOC_v_WRITE_v(mom_constraint_2nd_U0)
  REALLOC_v_WRITE_v(mom_constraint_2nd_U2)
  READ_v(K_UiUj_U2U2)
  READ_v(K_UiUj_U1U2)
  READ_v(K_UiUj_U1U1)
  READ_v(K_UiUj_U0U2)
  READ_v(K_UiUj_U0U1)
  READ_v(K_UiUj_U0U0)
  READ_v_UNUSED(dK_UiUj_U0U0D2)
  READ_v_UNUSED(dK_UiUj_U0U0D0)
  READ_v_UNUSED(dK_UiUj_U0U0D1)
  READ_v_UNUSED(dK_UiUj_U1U1D2)
  READ_v_UNUSED(dK_UiUj_U1U1D0)
  READ_v_UNUSED(dK_UiUj_U1U1D1)
  READ_v_UNUSED(dK_UiUj_U0U2D0)
  READ_v_UNUSED(dK_UiUj_U0U2D1)
  READ_v_UNUSED(dK_UiUj_U0U2D2)
  READ_v_UNUSED(dK_UiUj_U1U2D1)
  READ_v_UNUSED(dK_UiUj_U1U2D0)
  READ_v_UNUSED(dK_UiUj_U2U2D0)
  READ_v_UNUSED(dK_UiUj_U1U2D2)
  READ_v_UNUSED(dK_UiUj_U2U2D1)
  READ_v_UNUSED(dK_UiUj_U2U2D2)
  READ_v_UNUSED(dK_UiUj_U0U1D2)
  READ_v_UNUSED(dK_UiUj_U0U1D1)
  READ_v_UNUSED(dK_UiUj_U0U1D0)
  READ_v(psi)
  READ_v(gamma_D1D1)
  READ_v(gamma_D0D1)
  READ_v(gamma_D0D2)
  READ_v(gamma_D1D2)
  READ_v(gamma_D0D0)
  READ_v(gamma_D2D2)
  READ_v(gammaI_U2U2)
  READ_v(gammaI_U0U0)
  READ_v(gammaI_U0U1)
  READ_v(gammaI_U0U2)
  READ_v(gammaI_U1U1)
  READ_v(gammaI_U1U2)
  READ_v(Gamma_U1D0D0)
  READ_v(Gamma_U0D2D2)
  READ_v(Gamma_U1D0D2)
  READ_v(Gamma_U2D1D2)
  READ_v(Gamma_U1D0D1)
  READ_v(Gamma_U1D2D2)
  READ_v(Gamma_U2D0D2)
  READ_v(Gamma_U2D0D0)
  READ_v(Gamma_U0D0D1)
  READ_v(Gamma_U0D0D0)
  READ_v(Gamma_U2D0D1)
  READ_v(Gamma_U0D0D2)
  READ_v(Gamma_U2D2D2)
  READ_v(Gamma_U1D1D1)
  READ_v(Gamma_U0D1D1)
  READ_v(Gamma_U0D1D2)
  READ_v(Gamma_U1D1D2)
  READ_v(Gamma_U2D1D1)
  READ_v_UNUSED(dGamma_U1D0D1D2)
  READ_v_UNUSED(dGamma_U1D2D2D2)
  READ_v_UNUSED(dGamma_U1D0D1D0)
  READ_v_UNUSED(dGamma_U1D0D1D1)
  READ_v_UNUSED(dGamma_U2D0D2D2)
  READ_v_UNUSED(dGamma_U2D1D1D2)
  READ_v_UNUSED(dGamma_U2D0D0D1)
  READ_v_UNUSED(dGamma_U1D0D0D2)
  READ_v_UNUSED(dGamma_U1D0D0D1)
  READ_v_UNUSED(dGamma_U1D0D0D0)
  READ_v_UNUSED(dGamma_U1D2D2D1)
  READ_v_UNUSED(dGamma_U1D0D2D1)
  READ_v_UNUSED(dGamma_U1D0D2D0)
  READ_v_UNUSED(dGamma_U1D0D2D2)
  READ_v_UNUSED(dGamma_U0D1D1D2)
  READ_v_UNUSED(dGamma_U0D1D1D0)
  READ_v_UNUSED(dGamma_U0D1D1D1)
  READ_v_UNUSED(dGamma_U2D0D1D2)
  READ_v_UNUSED(dGamma_U0D1D2D1)
  READ_v_UNUSED(dGamma_U0D1D2D0)
  READ_v_UNUSED(dGamma_U0D1D2D2)
  READ_v_UNUSED(dGamma_U2D2D2D0)
  READ_v_UNUSED(dGamma_U2D2D2D1)
  READ_v_UNUSED(dGamma_U2D2D2D2)
  READ_v_UNUSED(dGamma_U1D2D2D0)
  READ_v_UNUSED(dGamma_U0D0D2D0)
  READ_v_UNUSED(dGamma_U0D0D2D1)
  READ_v_UNUSED(dGamma_U0D0D2D2)
  READ_v_UNUSED(dGamma_U2D0D1D0)
  READ_v_UNUSED(dGamma_U1D1D2D0)
  READ_v_UNUSED(dGamma_U1D1D2D1)
  READ_v_UNUSED(dGamma_U1D1D2D2)
  READ_v_UNUSED(dGamma_U1D1D1D1)
  READ_v_UNUSED(dGamma_U0D0D0D2)
  READ_v_UNUSED(dGamma_U2D1D1D1)
  READ_v_UNUSED(dGamma_U0D0D0D0)
  READ_v_UNUSED(dGamma_U0D0D0D1)
  READ_v_UNUSED(dGamma_U2D1D1D0)
  READ_v_UNUSED(dGamma_U0D0D1D2)
  READ_v_UNUSED(dGamma_U0D0D1D1)
  READ_v_UNUSED(dGamma_U0D0D1D0)
  READ_v_UNUSED(dGamma_U0D2D2D2)
  READ_v_UNUSED(dGamma_U1D1D1D2)
  READ_v_UNUSED(dGamma_U0D2D2D0)
  READ_v_UNUSED(dGamma_U0D2D2D1)
  READ_v_UNUSED(dGamma_U2D0D0D2)
  READ_v_UNUSED(dGamma_U2D1D2D2)
  READ_v_UNUSED(dGamma_U2D0D1D1)
  READ_v_UNUSED(dGamma_U2D1D2D0)
  READ_v_UNUSED(dGamma_U2D0D2D0)
  READ_v_UNUSED(dGamma_U2D0D2D1)
  READ_v_UNUSED(dGamma_U1D1D1D0)
  READ_v_UNUSED(dGamma_U2D0D0D0)
  READ_v_UNUSED(dGamma_U2D1D2D1)
  READ_v(_E)
  READ_v(_J_U0)
  READ_v(_J_U1)
  READ_v(_J_U2)
  READ_v(K)
  READ_v(dK_D2)
  READ_v(dK_D1)
  READ_v(dK_D0)


  for(ijk = 0; ijk < nn; ++ijk)
  {
  double psim6 = 
pow(psi[ijk], -6);

  double J_U2 = 
_J_U2[ijk]*psim6;

  double J_U0 = 
_J_U0[ijk]*psim6;

  double J_U1 = 
_J_U1[ijk]*psim6;

  double E = 
_E[ijk]*psim6;

  double Ric1_D0D0 = 
dGamma_U0D0D0D0[ijk] + dGamma_U1D0D0D1[ijk] + dGamma_U2D0D0D2[ijk];

  double Ric1_D2D2 = 
dGamma_U0D2D2D0[ijk] + dGamma_U1D2D2D1[ijk] + dGamma_U2D2D2D2[ijk];

  double Ric1_D1D2 = 
dGamma_U0D1D2D0[ijk] + dGamma_U1D1D2D1[ijk] + dGamma_U2D1D2D2[ijk];

  double Ric1_D0D2 = 
dGamma_U0D0D2D0[ijk] + dGamma_U1D0D2D1[ijk] + dGamma_U2D0D2D2[ijk];

  double Ric1_D0D1 = 
dGamma_U0D0D1D0[ijk] + dGamma_U1D0D1D1[ijk] + dGamma_U2D0D1D2[ijk];

  double Ric1_D1D1 = 
dGamma_U0D1D1D0[ijk] + dGamma_U1D1D1D1[ijk] + dGamma_U2D1D1D2[ijk];

  double Ric2_D2D2 = 
-dGamma_U0D0D2D2[ijk] - dGamma_U1D1D2D2[ijk] - dGamma_U2D2D2D2[ijk];

  double Ric2_D0D0 = 
-dGamma_U0D0D0D0[ijk] - dGamma_U1D0D1D0[ijk] - dGamma_U2D0D2D0[ijk];

  double Ric2_D0D2 = 
-dGamma_U0D0D0D2[ijk] - dGamma_U1D0D1D2[ijk] - dGamma_U2D0D2D2[ijk];

  double Ric2_D1D2 = 
-dGamma_U0D0D1D2[ijk] - dGamma_U1D1D1D2[ijk] - dGamma_U2D1D2D2[ijk];

  double Ric2_D1D1 = 
-dGamma_U0D0D1D1[ijk] - dGamma_U1D1D1D1[ijk] - dGamma_U2D1D2D1[ijk];

  double Ric2_D0D1 = 
-dGamma_U0D0D0D1[ijk] - dGamma_U1D0D1D1[ijk] - dGamma_U2D0D2D1[ijk];

  double Ric3_D1D1 = 
Gamma_U0D0D0[ijk]*Gamma_U0D1D1[ijk] + Gamma_U0D0D1[ijk]*
Gamma_U1D1D1[ijk] + Gamma_U0D0D2[ijk]*Gamma_U2D1D1[ijk] + 
Gamma_U0D1D1[ijk]*Gamma_U1D0D1[ijk] + Gamma_U0D1D1[ijk]*
Gamma_U2D0D2[ijk] + pow(Gamma_U1D1D1[ijk], 2) + Gamma_U1D1D1[ijk]*
Gamma_U2D1D2[ijk] + Gamma_U1D1D2[ijk]*Gamma_U2D1D1[ijk] + 
Gamma_U2D1D1[ijk]*Gamma_U2D2D2[ijk];

  double Ric3_D1D2 = 
Gamma_U0D0D0[ijk]*Gamma_U0D1D2[ijk] + Gamma_U0D0D1[ijk]*
Gamma_U1D1D2[ijk] + Gamma_U0D0D2[ijk]*Gamma_U2D1D2[ijk] + 
Gamma_U0D1D2[ijk]*Gamma_U1D0D1[ijk] + Gamma_U0D1D2[ijk]*
Gamma_U2D0D2[ijk] + Gamma_U1D1D1[ijk]*Gamma_U1D1D2[ijk] + 2.0*
Gamma_U1D1D2[ijk]*Gamma_U2D1D2[ijk] + Gamma_U2D1D2[ijk]*
Gamma_U2D2D2[ijk];

  double Ric3_D0D1 = 
Gamma_U0D0D0[ijk]*Gamma_U0D0D1[ijk] + 2.0*Gamma_U0D0D1[ijk]*
Gamma_U1D0D1[ijk] + Gamma_U0D0D1[ijk]*Gamma_U2D0D2[ijk] + 
Gamma_U0D0D2[ijk]*Gamma_U2D0D1[ijk] + Gamma_U1D0D1[ijk]*
Gamma_U1D1D1[ijk] + Gamma_U1D0D1[ijk]*Gamma_U2D1D2[ijk] + 
Gamma_U1D1D2[ijk]*Gamma_U2D0D1[ijk] + Gamma_U2D0D1[ijk]*
Gamma_U2D2D2[ijk];

  double Ric3_D0D0 = 
pow(Gamma_U0D0D0[ijk], 2) + Gamma_U0D0D0[ijk]*Gamma_U1D0D1[ijk] + 
Gamma_U0D0D0[ijk]*Gamma_U2D0D2[ijk] + Gamma_U0D0D1[ijk]*
Gamma_U1D0D0[ijk] + Gamma_U0D0D2[ijk]*Gamma_U2D0D0[ijk] + 
Gamma_U1D0D0[ijk]*Gamma_U1D1D1[ijk] + Gamma_U1D0D0[ijk]*
Gamma_U2D1D2[ijk] + Gamma_U1D1D2[ijk]*Gamma_U2D0D0[ijk] + 
Gamma_U2D0D0[ijk]*Gamma_U2D2D2[ijk];

  double Ric3_D0D2 = 
Gamma_U0D0D0[ijk]*Gamma_U0D0D2[ijk] + Gamma_U0D0D1[ijk]*
Gamma_U1D0D2[ijk] + Gamma_U0D0D2[ijk]*Gamma_U1D0D1[ijk] + 2.0*
Gamma_U0D0D2[ijk]*Gamma_U2D0D2[ijk] + Gamma_U1D0D2[ijk]*
Gamma_U1D1D1[ijk] + Gamma_U1D0D2[ijk]*Gamma_U2D1D2[ijk] + 
Gamma_U1D1D2[ijk]*Gamma_U2D0D2[ijk] + Gamma_U2D0D2[ijk]*
Gamma_U2D2D2[ijk];

  double Ric3_D2D2 = 
Gamma_U0D0D0[ijk]*Gamma_U0D2D2[ijk] + Gamma_U0D0D1[ijk]*
Gamma_U1D2D2[ijk] + Gamma_U0D0D2[ijk]*Gamma_U2D2D2[ijk] + 
Gamma_U0D2D2[ijk]*Gamma_U1D0D1[ijk] + Gamma_U0D2D2[ijk]*
Gamma_U2D0D2[ijk] + Gamma_U1D1D1[ijk]*Gamma_U1D2D2[ijk] + 
Gamma_U1D1D2[ijk]*Gamma_U2D2D2[ijk] + Gamma_U1D2D2[ijk]*
Gamma_U2D1D2[ijk] + pow(Gamma_U2D2D2[ijk], 2);

  double Ric4_D0D0 = 
-pow(Gamma_U0D0D0[ijk], 2) - 2.0*Gamma_U0D0D1[ijk]*Gamma_U1D0D0[ijk] - 
2.0*Gamma_U0D0D2[ijk]*Gamma_U2D0D0[ijk] - pow(Gamma_U1D0D1[ijk], 2) - 
2.0*Gamma_U1D0D2[ijk]*Gamma_U2D0D1[ijk] - pow(Gamma_U2D0D2[ijk], 2);

  double Ric4_D0D1 = 
-Gamma_U0D0D0[ijk]*Gamma_U0D0D1[ijk] - Gamma_U0D0D1[ijk]*
Gamma_U1D0D1[ijk] - Gamma_U0D0D2[ijk]*Gamma_U2D0D1[ijk] - 
Gamma_U0D1D1[ijk]*Gamma_U1D0D0[ijk] - Gamma_U0D1D2[ijk]*
Gamma_U2D0D0[ijk] - Gamma_U1D0D1[ijk]*Gamma_U1D1D1[ijk] - 
Gamma_U1D0D2[ijk]*Gamma_U2D1D1[ijk] - Gamma_U1D1D2[ijk]*
Gamma_U2D0D1[ijk] - Gamma_U2D0D2[ijk]*Gamma_U2D1D2[ijk];

  double Ric4_D0D2 = 
-Gamma_U0D0D0[ijk]*Gamma_U0D0D2[ijk] - Gamma_U0D0D1[ijk]*
Gamma_U1D0D2[ijk] - Gamma_U0D0D2[ijk]*Gamma_U2D0D2[ijk] - 
Gamma_U0D1D2[ijk]*Gamma_U1D0D0[ijk] - Gamma_U0D2D2[ijk]*
Gamma_U2D0D0[ijk] - Gamma_U1D0D1[ijk]*Gamma_U1D1D2[ijk] - 
Gamma_U1D0D2[ijk]*Gamma_U2D1D2[ijk] - Gamma_U1D2D2[ijk]*
Gamma_U2D0D1[ijk] - Gamma_U2D0D2[ijk]*Gamma_U2D2D2[ijk];

  double Ric4_D1D1 = 
-pow(Gamma_U0D0D1[ijk], 2) - 2.0*Gamma_U0D1D1[ijk]*Gamma_U1D0D1[ijk] - 
2.0*Gamma_U0D1D2[ijk]*Gamma_U2D0D1[ijk] - pow(Gamma_U1D1D1[ijk], 2) - 
2.0*Gamma_U1D1D2[ijk]*Gamma_U2D1D1[ijk] - pow(Gamma_U2D1D2[ijk], 2);

  double Ric4_D1D2 = 
-Gamma_U0D0D1[ijk]*Gamma_U0D0D2[ijk] - Gamma_U0D1D1[ijk]*
Gamma_U1D0D2[ijk] - Gamma_U0D1D2[ijk]*Gamma_U1D0D1[ijk] - 
Gamma_U0D1D2[ijk]*Gamma_U2D0D2[ijk] - Gamma_U0D2D2[ijk]*
Gamma_U2D0D1[ijk] - Gamma_U1D1D1[ijk]*Gamma_U1D1D2[ijk] - 
Gamma_U1D1D2[ijk]*Gamma_U2D1D2[ijk] - Gamma_U1D2D2[ijk]*
Gamma_U2D1D1[ijk] - Gamma_U2D1D2[ijk]*Gamma_U2D2D2[ijk];

  double Ric4_D2D2 = 
-pow(Gamma_U0D0D2[ijk], 2) - 2.0*Gamma_U0D1D2[ijk]*Gamma_U1D0D2[ijk] - 
2.0*Gamma_U0D2D2[ijk]*Gamma_U2D0D2[ijk] - pow(Gamma_U1D1D2[ijk], 2) - 
2.0*Gamma_U1D2D2[ijk]*Gamma_U2D1D2[ijk] - pow(Gamma_U2D2D2[ijk], 2);

  double Ric_D1D1 = 
Ric1_D1D1 + Ric2_D1D1 + Ric3_D1D1 + Ric4_D1D1;

  double Ric_D1D2 = 
Ric1_D1D2 + Ric2_D1D2 + Ric3_D1D2 + Ric4_D1D2;

  double Ric_D2D2 = 
Ric1_D2D2 + Ric2_D2D2 + Ric3_D2D2 + Ric4_D2D2;

  double Ric_D0D1 = 
Ric1_D0D1 + Ric2_D0D1 + Ric3_D0D1 + Ric4_D0D1;

  double Ric_D0D0 = 
Ric1_D0D0 + Ric2_D0D0 + Ric3_D0D0 + Ric4_D0D0;

  double Ric_D0D2 = 
Ric1_D0D2 + Ric2_D0D2 + Ric3_D0D2 + Ric4_D0D2;

  double R = 
Ric_D0D0*gammaI_U0U0[ijk] + 2.0*Ric_D0D1*gammaI_U0U1[ijk] + 2.0*
Ric_D0D2*gammaI_U0U2[ijk] + Ric_D1D1*gammaI_U1U1[ijk] + 2.0*Ric_D1D2*
gammaI_U1U2[ijk] + Ric_D2D2*gammaI_U2U2[ijk];

  double KijKij = 
pow(K_UiUj_U0U0[ijk], 2)*pow(gamma_D0D0[ijk], 2) + 4.0*
K_UiUj_U0U0[ijk]*K_UiUj_U0U1[ijk]*gamma_D0D0[ijk]*gamma_D0D1[ijk] +
4.0*K_UiUj_U0U0[ijk]*K_UiUj_U0U2[ijk]*gamma_D0D0[ijk]*gamma_D0D2[ijk] +
2.0*K_UiUj_U0U0[ijk]*K_UiUj_U1U1[ijk]*pow(gamma_D0D1[ijk], 2) + 4.0*
K_UiUj_U0U0[ijk]*K_UiUj_U1U2[ijk]*gamma_D0D1[ijk]*gamma_D0D2[ijk] +
2.0*K_UiUj_U0U0[ijk]*K_UiUj_U2U2[ijk]*pow(gamma_D0D2[ijk], 2) + 2.0*
pow(K_UiUj_U0U1[ijk], 2)*gamma_D0D0[ijk]*gamma_D1D1[ijk] + 2.0*
pow(K_UiUj_U0U1[ijk], 2)*pow(gamma_D0D1[ijk], 2) + 4.0*
K_UiUj_U0U1[ijk]*K_UiUj_U0U2[ijk]*gamma_D0D0[ijk]*gamma_D1D2[ijk] +
4.0*K_UiUj_U0U1[ijk]*K_UiUj_U0U2[ijk]*gamma_D0D1[ijk]*gamma_D0D2[ijk] +
4.0*K_UiUj_U0U1[ijk]*K_UiUj_U1U1[ijk]*gamma_D0D1[ijk]*gamma_D1D1[ijk] +
4.0*K_UiUj_U0U1[ijk]*K_UiUj_U1U2[ijk]*gamma_D0D1[ijk]*gamma_D1D2[ijk] +
4.0*K_UiUj_U0U1[ijk]*K_UiUj_U1U2[ijk]*gamma_D0D2[ijk]*gamma_D1D1[ijk] +
4.0*K_UiUj_U0U1[ijk]*K_UiUj_U2U2[ijk]*gamma_D0D2[ijk]*gamma_D1D2[ijk] +
2.0*pow(K_UiUj_U0U2[ijk], 2)*gamma_D0D0[ijk]*gamma_D2D2[ijk] + 2.0*
pow(K_UiUj_U0U2[ijk], 2)*pow(gamma_D0D2[ijk], 2) + 4.0*
K_UiUj_U0U2[ijk]*K_UiUj_U1U1[ijk]*gamma_D0D1[ijk]*gamma_D1D2[ijk] +
4.0*K_UiUj_U0U2[ijk]*K_UiUj_U1U2[ijk]*gamma_D0D1[ijk]*gamma_D2D2[ijk] +
4.0*K_UiUj_U0U2[ijk]*K_UiUj_U1U2[ijk]*gamma_D0D2[ijk]*gamma_D1D2[ijk] +
4.0*K_UiUj_U0U2[ijk]*K_UiUj_U2U2[ijk]*gamma_D0D2[ijk]*gamma_D2D2[ijk] +
pow(K_UiUj_U1U1[ijk], 2)*pow(gamma_D1D1[ijk], 2) + 4.0*
K_UiUj_U1U1[ijk]*K_UiUj_U1U2[ijk]*gamma_D1D1[ijk]*gamma_D1D2[ijk] +
2.0*K_UiUj_U1U1[ijk]*K_UiUj_U2U2[ijk]*pow(gamma_D1D2[ijk], 2) + 2.0*
pow(K_UiUj_U1U2[ijk], 2)*gamma_D1D1[ijk]*gamma_D2D2[ijk] + 2.0*
pow(K_UiUj_U1U2[ijk], 2)*pow(gamma_D1D2[ijk], 2) + 4.0*
K_UiUj_U1U2[ijk]*K_UiUj_U2U2[ijk]*gamma_D1D2[ijk]*gamma_D2D2[ijk] +
pow(K_UiUj_U2U2[ijk], 2)*pow(gamma_D2D2[ijk], 2);

  double DjKij_U0 = 
2.0*Gamma_U0D0D0[ijk]*K_UiUj_U0U0[ijk] + 3.0*Gamma_U0D0D1[ijk]*
K_UiUj_U0U1[ijk] + 3.0*Gamma_U0D0D2[ijk]*K_UiUj_U0U2[ijk] + 
Gamma_U0D1D1[ijk]*K_UiUj_U1U1[ijk] + 2.0*Gamma_U0D1D2[ijk]*
K_UiUj_U1U2[ijk] + Gamma_U0D2D2[ijk]*K_UiUj_U2U2[ijk] + 
Gamma_U1D0D1[ijk]*K_UiUj_U0U0[ijk] + Gamma_U1D1D1[ijk]*
K_UiUj_U0U1[ijk] + Gamma_U1D1D2[ijk]*K_UiUj_U0U2[ijk] + 
Gamma_U2D0D2[ijk]*K_UiUj_U0U0[ijk] + Gamma_U2D1D2[ijk]*
K_UiUj_U0U1[ijk] + Gamma_U2D2D2[ijk]*K_UiUj_U0U2[ijk] + 
dK_UiUj_U0U0D0[ijk] + dK_UiUj_U0U1D1[ijk] + dK_UiUj_U0U2D2[ijk];

  double DjKij_U1 = 
Gamma_U0D0D0[ijk]*K_UiUj_U0U1[ijk] + Gamma_U0D0D1[ijk]*
K_UiUj_U1U1[ijk] + Gamma_U0D0D2[ijk]*K_UiUj_U1U2[ijk] + 
Gamma_U1D0D0[ijk]*K_UiUj_U0U0[ijk] + 3.0*Gamma_U1D0D1[ijk]*
K_UiUj_U0U1[ijk] + 2.0*Gamma_U1D0D2[ijk]*K_UiUj_U0U2[ijk] + 2.0*
Gamma_U1D1D1[ijk]*K_UiUj_U1U1[ijk] + 3.0*Gamma_U1D1D2[ijk]*
K_UiUj_U1U2[ijk] + Gamma_U1D2D2[ijk]*K_UiUj_U2U2[ijk] + 
Gamma_U2D0D2[ijk]*K_UiUj_U0U1[ijk] + Gamma_U2D1D2[ijk]*
K_UiUj_U1U1[ijk] + Gamma_U2D2D2[ijk]*K_UiUj_U1U2[ijk] + 
dK_UiUj_U0U1D0[ijk] + dK_UiUj_U1U1D1[ijk] + dK_UiUj_U1U2D2[ijk];

  double DjKij_U2 = 
Gamma_U0D0D0[ijk]*K_UiUj_U0U2[ijk] + Gamma_U0D0D1[ijk]*
K_UiUj_U1U2[ijk] + Gamma_U0D0D2[ijk]*K_UiUj_U2U2[ijk] + 
Gamma_U1D0D1[ijk]*K_UiUj_U0U2[ijk] + Gamma_U1D1D1[ijk]*
K_UiUj_U1U2[ijk] + Gamma_U1D1D2[ijk]*K_UiUj_U2U2[ijk] + 
Gamma_U2D0D0[ijk]*K_UiUj_U0U0[ijk] + 2.0*Gamma_U2D0D1[ijk]*
K_UiUj_U0U1[ijk] + 3.0*Gamma_U2D0D2[ijk]*K_UiUj_U0U2[ijk] + 
Gamma_U2D1D1[ijk]*K_UiUj_U1U1[ijk] + 3.0*Gamma_U2D1D2[ijk]*
K_UiUj_U1U2[ijk] + 2.0*Gamma_U2D2D2[ijk]*K_UiUj_U2U2[ijk] + 
dK_UiUj_U0U2D0[ijk] + dK_UiUj_U1U2D1[ijk] + dK_UiUj_U2U2D2[ijk];

  double Ham_Constraint = 
-16*M_PI*E + pow(K[ijk], 2) - KijKij + R;

  double Mom_constraint_U2 = 
DjKij_U2 - 8*M_PI*J_U2 - dK_D0[ijk]*gammaI_U0U2[ijk] - dK_D1[ijk]*
gammaI_U1U2[ijk] - dK_D2[ijk]*gammaI_U2U2[ijk];

  double Mom_constraint_U0 = 
DjKij_U0 - 8*M_PI*J_U0 - dK_D0[ijk]*gammaI_U0U0[ijk] - dK_D1[ijk]*
gammaI_U0U1[ijk] - dK_D2[ijk]*gammaI_U0U2[ijk];

  double Mom_constraint_U1 = 
DjKij_U1 - 8*M_PI*J_U1 - dK_D0[ijk]*gammaI_U0U1[ijk] - dK_D1[ijk]*
gammaI_U1U1[ijk] - dK_D2[ijk]*gammaI_U1U2[ijk];


  /* populating: */
  mom_constraint_2nd_U1[ijk] = Mom_constraint_U1;
  mom_constraint_2nd_U0[ijk] = Mom_constraint_U0;
  mom_constraint_2nd_U2[ijk] = Mom_constraint_U2;
  ham_constraint_2nd[ijk] = Ham_Constraint;
  }
  }
  bbn_free_metric_and_Gamma_and_derivatives(grid);
  bbn_free_K_UiUj_and_dK_UiUj(grid);
}
