/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"

double force_balance_yCM_root_finder_eq(void *params,const double *const x);
double force_balance_yCM_root_finder_eq(void *params,const double *const x)
{
const struct Force_Balance_RootFinder_S *const par = params;
Patch_T *const patch = par->patch;
const unsigned  nn   = patch->nn;
const double Omega_BHNS = par->Omega_BHNS;
const double Vr         = par->Vr;
const double D          = par->D;
double y_CM             = x[0];
const double *const X   = par->X; 
unsigned ijk;
/* B^1 */
PREP_FIELD(B1_U0)
PREP_FIELD(B1_U1)
PREP_FIELD(B1_U2)
for (ijk = 0; ijk < nn; ++ijk)
{
double x0     = patch->node[ijk]->x[0];
double y0     = patch->node[ijk]->x[1];
B1_U0[ijk] = Omega_BHNS*(-y0+y_CM)+Vr*x0/D;
B1_U1[ijk] = Omega_BHNS*x0+Vr*(y0-y_CM)/D;
B1_U2[ijk] = 0;
}
bbn_update_Beta_U0(patch);
bbn_update_Beta_U1(patch);
bbn_update_Beta_U2(patch);

  /* declaring: */
  GET_FIELD(_gamma_D2D2)
  GET_FIELD(_gamma_D0D2)
  GET_FIELD(_gamma_D0D0)
  GET_FIELD(_gamma_D0D1)
  GET_FIELD(_gamma_D1D2)
  GET_FIELD(_gamma_D1D1)
  GET_FIELD(W_U1)
  GET_FIELD(W_U0)
  GET_FIELD(W_U2)
  GET_FIELD(dphi_D2)
  GET_FIELD(dphi_D1)
  GET_FIELD(dphi_D0)
  GET_FIELD(eta)
  GET_FIELD(Beta_U1)
  GET_FIELD(Beta_U0)
  GET_FIELD(Beta_U2)
  GET_FIELD(psi)
  GET_FIELD(enthalpy)
  GET_FIELD(u0)


ADD_FIELD(GAMMA_rf);
ADD_FIELD(GAMMAt_rf);
ADD_FIELD_NoMem(dGAMMA_D1_rf);
ADD_FIELD_NoMem(dGAMMAt_D1_rf);
DECLARE_FIELD(GAMMA_rf);
DECLARE_FIELD(GAMMAt_rf);
DECLARE_FIELD(dGAMMA_D1_rf);
DECLARE_FIELD(dGAMMAt_D1_rf);
for (ijk = 0; ijk < nn; ++ijk)
{
  double alpha = 
eta[ijk]/psi[ijk];

  double alpha2 = 
pow(alpha, 2);

  double psi4 = 
pow(psi[ijk], 4);

  double t_U0 = 
Beta_U0[ijk] + W_U0[ijk]/(enthalpy[ijk]*u0[ijk]);

  double t_U1 = 
Beta_U1[ijk] + W_U1[ijk]/(enthalpy[ijk]*u0[ijk]);

  double t_U2 = 
Beta_U2[ijk] + W_U2[ijk]/(enthalpy[ijk]*u0[ijk]);

  double t2 = 
psi4*(_gamma_D0D0[ijk]*pow(t_U0, 2) + 2.0*_gamma_D0D1[ijk]*t_U0*t_U1 +
2.0*_gamma_D0D2[ijk]*t_U0*t_U2 + _gamma_D1D1[ijk]*pow(t_U1, 2) + 2.0*
_gamma_D1D2[ijk]*t_U1*t_U2 + _gamma_D2D2[ijk]*pow(t_U2, 2));

  double Gtilda = 
alpha2 - t2;

  double v = 
(pow(alpha, 2)*enthalpy[ijk]*u0[ijk]*(dphi_D0[ijk]*t_U0 + dphi_D1[ijk]*
t_U1 + dphi_D2[ijk]*t_U2) + alpha2*psi4*(pow(W_U0[ijk], 2)*
_gamma_D0D0[ijk] + 2.0*W_U0[ijk]*W_U1[ijk]*_gamma_D0D1[ijk] + 2.0*
W_U0[ijk]*W_U2[ijk]*_gamma_D0D2[ijk] + pow(W_U1[ijk], 2)*
_gamma_D1D1[ijk] + 2.0*W_U1[ijk]*W_U2[ijk]*_gamma_D1D2[ijk] +
pow(W_U2[ijk], 2)*_gamma_D2D2[ijk]))/(pow(alpha, 2)*alpha2*
pow(enthalpy[ijk], 2)*pow(u0[ijk], 2));

  double G = 
-alpha*u0[ijk]*pow((alpha2 - t2)/alpha2, -0.5)*(v -
1);


GAMMA_rf->v[ijk]  = G;
GAMMAt_rf->v[ijk] = Gtilda;
}
dGAMMA_D1_rf->v  = Partial_Derivative(GAMMA_rf,"y");
dGAMMAt_D1_rf->v = Partial_Derivative(GAMMAt_rf,"y");
Interpolation_T *interp_GAMMA   = init_interpolation();
Interpolation_T *interp_GAMMAt  = init_interpolation();
Interpolation_T *interp_dGAMMA  = init_interpolation();
Interpolation_T *interp_dGAMMAt = init_interpolation();

interp_GAMMA->field   = GAMMA_rf;
interp_GAMMAt->field  = GAMMAt_rf;
interp_dGAMMA->field  = dGAMMA_D1_rf;
interp_dGAMMAt->field = dGAMMAt_D1_rf;

interp_GAMMA->X = X[0];
interp_GAMMA->Y = X[1];
interp_GAMMA->Z = X[2];
interp_GAMMA->XYZ_dir_flag = 1;

interp_GAMMAt->X = X[0];
interp_GAMMAt->Y = X[1];
interp_GAMMAt->Z = X[2];
interp_GAMMAt->XYZ_dir_flag = 1;

interp_dGAMMA->X = X[0];
interp_dGAMMA->Y = X[1];
interp_dGAMMA->Z = X[2];
interp_dGAMMA->XYZ_dir_flag = 1;

interp_dGAMMAt->X = X[0];
interp_dGAMMAt->Y = X[1];
interp_dGAMMAt->Z = X[2];
interp_dGAMMAt->XYZ_dir_flag = 1;

plan_interpolation(interp_GAMMA);
plan_interpolation(interp_dGAMMA);
plan_interpolation(interp_GAMMAt);
plan_interpolation(interp_dGAMMAt);
const double g   = execute_interpolation(interp_GAMMA);
const double gt  = execute_interpolation(interp_GAMMAt);
const double dg  = execute_interpolation(interp_dGAMMA);
const double dgt = execute_interpolation(interp_dGAMMAt);

free_interpolation(interp_GAMMA);
free_interpolation(interp_GAMMAt);
free_interpolation(interp_dGAMMA);
free_interpolation(interp_dGAMMAt);

double f = dgt/gt+2*dg/g;
if(!isfinite(f))
  f = 1;

REMOVE_FIELD(GAMMA_rf);
REMOVE_FIELD(GAMMAt_rf);
REMOVE_FIELD(dGAMMA_D1_rf);
REMOVE_FIELD(dGAMMAt_D1_rf);
return f;
}
