/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"

double force_balance_Omega_root_finder_eq(void *params,const double *const x);
double force_balance_Omega_root_finder_eq(void *params,const double *const x)
{
const struct Force_Balance_RootFinder_S *const par = params;
Patch_T *const patch = par->patch;
const unsigned  nn   = patch->nn;
const double Omega_BHNS = x[0];
const double Vr         = par->Vr;
const double D          = par->D;
const double y_CM       = par->y_CM;
const double *const X   = par->X; 
const double dyLnGamma  = par->dyLnGamma;
unsigned ijk;
/* B^1 */
PREP_FIELD(B1_U0)
PREP_FIELD(B1_U1)
PREP_FIELD(B1_U2)
for (ijk = 0; ijk < nn; ++ijk)
{
double x0  = patch->node[ijk]->x[0];
double y0  = patch->node[ijk]->x[1];
B1_U0[ijk] = Omega_BHNS*(-y0+y_CM)+Vr*x0/D;
B1_U1[ijk] = Omega_BHNS*x0+Vr*(y0-y_CM)/D;
B1_U2[ijk] = 0;
}
bbn_update_Beta_U0(patch);
bbn_update_Beta_U1(patch);
bbn_update_Beta_U2(patch);

  /* declaring: */
  GET_FIELD(_gamma_D2D2)
  GET_FIELD(_gamma_D0D2)
  GET_FIELD(_gamma_D0D0)
  GET_FIELD(_gamma_D0D1)
  GET_FIELD(_gamma_D1D2)
  GET_FIELD(_gamma_D1D1)
  GET_FIELD(W_U1)
  GET_FIELD(W_U0)
  GET_FIELD(W_U2)
  GET_FIELD(eta)
  GET_FIELD(Beta_U1)
  GET_FIELD(Beta_U0)
  GET_FIELD(Beta_U2)
  GET_FIELD(psi)
  GET_FIELD(enthalpy)
  GET_FIELD(u0)


ADD_FIELD(Gtilda_rf);
ADD_FIELD_NoMem(dGtilda_D1_rf);
DECLARE_FIELD(Gtilda_rf);
DECLARE_FIELD(dGtilda_D1_rf);
for (ijk = 0; ijk < nn; ++ijk)
{
  double alpha = 
eta[ijk]/psi[ijk];

  double alpha2 = 
pow(alpha, 2);

  double psi4 = 
pow(psi[ijk], 4);

  double t_U0 = 
Beta_U0[ijk] + W_U0[ijk]/(enthalpy[ijk]*u0[ijk]);

  double t_U1 = 
Beta_U1[ijk] + W_U1[ijk]/(enthalpy[ijk]*u0[ijk]);

  double t_U2 = 
Beta_U2[ijk] + W_U2[ijk]/(enthalpy[ijk]*u0[ijk]);

  double t2 = 
psi4*(_gamma_D0D0[ijk]*pow(t_U0, 2) + 2.0*_gamma_D0D1[ijk]*t_U0*t_U1 +
2.0*_gamma_D0D2[ijk]*t_U0*t_U2 + _gamma_D1D1[ijk]*pow(t_U1, 2) + 2.0*
_gamma_D1D2[ijk]*t_U1*t_U2 + _gamma_D2D2[ijk]*pow(t_U2, 2));

  double Gtilda = 
alpha2 - t2;


Gtilda_rf->v[ijk] = Gtilda;
}
dGtilda_D1_rf->v = Partial_Derivative(Gtilda_rf,"y");
Interpolation_T *interp_Gtilda  = init_interpolation();
Interpolation_T *interp_dGtilda = init_interpolation();

interp_Gtilda->field  = Gtilda_rf;
interp_dGtilda->field = dGtilda_D1_rf;

interp_Gtilda->X = X[0];
interp_Gtilda->Y = X[1];
interp_Gtilda->Z = X[2];
interp_Gtilda->XYZ_dir_flag = 1;

interp_dGtilda->X = X[0];
interp_dGtilda->Y = X[1];
interp_dGtilda->Z = X[2];
interp_dGtilda->XYZ_dir_flag = 1;

plan_interpolation(interp_Gtilda);
plan_interpolation(interp_dGtilda);
const double gt  = execute_interpolation(interp_Gtilda);
const double dgt = execute_interpolation(interp_dGtilda);

free_interpolation(interp_Gtilda);
free_interpolation(interp_dGtilda);

const double f = dgt/gt+2*dyLnGamma;
assert(isfinite(f));

REMOVE_FIELD(Gtilda_rf);
REMOVE_FIELD(dGtilda_D1_rf);
return f;
}
