/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "bbn_headers.h"
#include "maths_equation_solvings_lib.h"
void *bbn_bhf_Brown_bc(void *vp1,void *vp2);
void *bbn_bhf_Brown_bc(void *vp1,void *vp2)
{
  DDM_SCHUR_BC_DECLARE
  unsigned ijk;/* node index */
  const Solving_Man_T *const sol = patch->solving_man;
  const char *const fld_name     = sol->field_name[sol->cf];
  char bc_fld_name[100] = {'\0'};

  sprintf(bc_fld_name,"bc_%s",fld_name);
  const double * const v_bc = patch->pool[Ind(bc_fld_name)]->v;

  if (patch->outerB)/* at outer boundary */
  {
  DDM_SCHUR_BC_OPEN

  F[map[ijk]] = v_bc[ijk];

  DDM_SCHUR_BC_CLOSE
  }/* end of if (patch->outerB) */
  else if (patch->innerB)/* at inner boundary */
  {
  DDM_SCHUR_BC_OPEN

  double innerB_F = 
0;

  F[map[ijk]] = innerB_F;

  DDM_SCHUR_BC_CLOSE
  }/* end of else if (patch->innerB) */
  return 0;
}
