/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "bbn_headers.h"
#include "maths_equation_solvings_lib.h"
#include "bbn_XCTS_equations_lib.h"


void *bbn_jacobian_eq_psi(void *vp1,void *vp2)
{
  DDM_SCHUR_JACOBIAN_EQ_DECLARE
  Uint ijk,lmn;/* for Jacobian entries J[ijk][lmn] */
  const double kd[2] = {0.,1.};/* Kronecker delta */

  /* declaring: */
  READ_v(psi)
  READ_v(_R)
  READ_v(K)
  READ_v(_Aij2)
  READ_v(_E)
  READ_v(_gammaI_U1U1)
  READ_v(_gammaI_U0U0)
  READ_v(_gammaI_U2U2)
  READ_v(_gammaI_U0U1)
  READ_v(_gammaI_U1U2)
  READ_v(_gammaI_U0U2)
  READ_v(_Gamma_U0D0D1)
  READ_v(_Gamma_U0D1D1)
  READ_v(_Gamma_U2D1D2)
  READ_v(_Gamma_U1D0D2)
  READ_v(_Gamma_U2D0D1)
  READ_v(_Gamma_U2D0D2)
  READ_v(_Gamma_U0D0D0)
  READ_v(_Gamma_U0D2D2)
  READ_v(_Gamma_U2D1D1)
  READ_v(_Gamma_U2D0D0)
  READ_v(_Gamma_U1D2D2)
  READ_v(_Gamma_U0D1D2)
  READ_v(_Gamma_U1D0D0)
  READ_v(_Gamma_U1D1D1)
  READ_v(_Gamma_U0D0D2)
  READ_v(_Gamma_U1D1D2)
  READ_v(_Gamma_U2D2D2)
  READ_v(_Gamma_U1D0D1)
  JACOBIAN_DERIVATIVE(Jpsi_D2)
  JACOBIAN_DERIVATIVE(Jpsi_D0)
  JACOBIAN_DERIVATIVE(Jpsi_D1)
  JACOBIAN_DERIVATIVE(JJpsi_D1D2)
  JACOBIAN_DERIVATIVE(JJpsi_D0D2)
  JACOBIAN_DERIVATIVE(JJpsi_D0D1)
  JACOBIAN_DERIVATIVE(JJpsi_D1D1)
  JACOBIAN_DERIVATIVE(JJpsi_D2D2)
  JACOBIAN_DERIVATIVE(JJpsi_D0D0)


  DDM_SCHUR_JACOBIAN_EQ_Bpart_OPEN

  double psi4_B = 
pow(psi[ijk], 4);

  double aij2_B = 
_Aij2[ijk]/psi4_B;

  double Bpart = 
JJpsi_D0D0(j_JJpsi_D0D0,ijk,lmn)*_gammaI_U0U0[ijk] + 2.0*
JJpsi_D0D1(j_JJpsi_D0D1,ijk,lmn)*_gammaI_U0U1[ijk] + 2.0*
JJpsi_D0D2(j_JJpsi_D0D2,ijk,lmn)*_gammaI_U0U2[ijk] +
JJpsi_D1D1(j_JJpsi_D1D1,ijk,lmn)*_gammaI_U1U1[ijk] + 2.0*
JJpsi_D1D2(j_JJpsi_D1D2,ijk,lmn)*_gammaI_U1U2[ijk] +
JJpsi_D2D2(j_JJpsi_D2D2,ijk,lmn)*_gammaI_U2U2[ijk] -
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D0D0[ijk]*_gammaI_U0U0[ijk] - 2.0*
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D0D1[ijk]*_gammaI_U0U1[ijk] - 2.0*
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D0D2[ijk]*_gammaI_U0U2[ijk] -
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D1D1[ijk]*_gammaI_U1U1[ijk] - 2.0*
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D1D2[ijk]*_gammaI_U1U2[ijk] -
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D2D2[ijk]*_gammaI_U2U2[ijk] -
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D0D0[ijk]*_gammaI_U0U0[ijk] - 2.0*
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D0D1[ijk]*_gammaI_U0U1[ijk] - 2.0*
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D0D2[ijk]*_gammaI_U0U2[ijk] -
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D1D1[ijk]*_gammaI_U1U1[ijk] - 2.0*
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D1D2[ijk]*_gammaI_U1U2[ijk] -
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D2D2[ijk]*_gammaI_U2U2[ijk] -
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D0D0[ijk]*_gammaI_U0U0[ijk] - 2.0*
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D0D1[ijk]*_gammaI_U0U1[ijk] - 2.0*
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D0D2[ijk]*_gammaI_U0U2[ijk] -
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D1D1[ijk]*_gammaI_U1U1[ijk] - 2.0*
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D1D2[ijk]*_gammaI_U1U2[ijk] -
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D2D2[ijk]*_gammaI_U2U2[ijk] -
kd[ijk==lmn]*((5.0/12.0)*pow(K[ijk], 2)*psi4_B + 2*M_PI*_E[ijk]/
pow(psi[ijk], 2) + (1.0/8.0)*_R[ijk] + 0.875*aij2_B/
psi4_B);

  B[i][j] = Bpart;

  DDM_SCHUR_JACOBIAN_EQ_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_EQ_Epart_OPEN

  double psi4_E = 
pow(psi[ijk], 4);

  double aij2_E = 
_Aij2[ijk]/psi4_E;

  double Epart = 
JJpsi_D0D0(j_JJpsi_D0D0,ijk,lmn)*_gammaI_U0U0[ijk] + 2.0*
JJpsi_D0D1(j_JJpsi_D0D1,ijk,lmn)*_gammaI_U0U1[ijk] + 2.0*
JJpsi_D0D2(j_JJpsi_D0D2,ijk,lmn)*_gammaI_U0U2[ijk] +
JJpsi_D1D1(j_JJpsi_D1D1,ijk,lmn)*_gammaI_U1U1[ijk] + 2.0*
JJpsi_D1D2(j_JJpsi_D1D2,ijk,lmn)*_gammaI_U1U2[ijk] +
JJpsi_D2D2(j_JJpsi_D2D2,ijk,lmn)*_gammaI_U2U2[ijk] -
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D0D0[ijk]*_gammaI_U0U0[ijk] - 2.0*
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D0D1[ijk]*_gammaI_U0U1[ijk] - 2.0*
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D0D2[ijk]*_gammaI_U0U2[ijk] -
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D1D1[ijk]*_gammaI_U1U1[ijk] - 2.0*
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D1D2[ijk]*_gammaI_U1U2[ijk] -
Jpsi_D0(j_Jpsi_D0,ijk,lmn)*_Gamma_U0D2D2[ijk]*_gammaI_U2U2[ijk] -
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D0D0[ijk]*_gammaI_U0U0[ijk] - 2.0*
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D0D1[ijk]*_gammaI_U0U1[ijk] - 2.0*
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D0D2[ijk]*_gammaI_U0U2[ijk] -
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D1D1[ijk]*_gammaI_U1U1[ijk] - 2.0*
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D1D2[ijk]*_gammaI_U1U2[ijk] -
Jpsi_D1(j_Jpsi_D1,ijk,lmn)*_Gamma_U1D2D2[ijk]*_gammaI_U2U2[ijk] -
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D0D0[ijk]*_gammaI_U0U0[ijk] - 2.0*
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D0D1[ijk]*_gammaI_U0U1[ijk] - 2.0*
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D0D2[ijk]*_gammaI_U0U2[ijk] -
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D1D1[ijk]*_gammaI_U1U1[ijk] - 2.0*
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D1D2[ijk]*_gammaI_U1U2[ijk] -
Jpsi_D2(j_Jpsi_D2,ijk,lmn)*_Gamma_U2D2D2[ijk]*_gammaI_U2U2[ijk] -
kd[ijk==lmn]*((5.0/12.0)*pow(K[ijk], 2)*psi4_E + 2*M_PI*_E[ijk]/
pow(psi[ijk], 2) + (1.0/8.0)*_R[ijk] + 0.875*aij2_E/
psi4_E);

  E_Trans[j][i] = Epart;

  DDM_SCHUR_JACOBIAN_EQ_Epart_CLOSE

  return 0;
}
