/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"


void bbn_calculate_constraints_1st(Grid_T *const grid);
void bbn_calculate_constraints_1st(Grid_T *const grid)
{
  const unsigned np = grid->np;
  unsigned p;

  OpenMP_Patch_Pragma(omp parallel for)
  for(p = 0; p < np; ++p)
  {
    Patch_T *patch = grid->patch[p];
    unsigned nn = patch->nn;
    unsigned ijk;
  {
  /* add fields for derivative of the conformal metric */
  DECLARE_FIELD(_gammaI_U2U2)
  DECLARE_FIELD(_gammaI_U0U2)
  DECLARE_FIELD(_gammaI_U0U0)
  DECLARE_FIELD(_gammaI_U0U1)
  DECLARE_FIELD(_gammaI_U1U2)
  DECLARE_FIELD(_gammaI_U1U1)

  ADD_FIELD_NoMem(_dgammaI_U0U0D1)
  ADD_FIELD_NoMem(_dgammaI_U0U0D0)
  ADD_FIELD_NoMem(_dgammaI_U2U2D2)
  ADD_FIELD_NoMem(_dgammaI_U0U0D2)
  ADD_FIELD_NoMem(_dgammaI_U0U2D1)
  ADD_FIELD_NoMem(_dgammaI_U1U1D0)
  ADD_FIELD_NoMem(_dgammaI_U1U1D2)
  ADD_FIELD_NoMem(_dgammaI_U2U2D0)
  ADD_FIELD_NoMem(_dgammaI_U2U2D1)
  ADD_FIELD_NoMem(_dgammaI_U0U1D0)
  ADD_FIELD_NoMem(_dgammaI_U0U1D1)
  ADD_FIELD_NoMem(_dgammaI_U0U1D2)
  ADD_FIELD_NoMem(_dgammaI_U0U2D0)
  ADD_FIELD_NoMem(_dgammaI_U1U1D1)
  ADD_FIELD_NoMem(_dgammaI_U1U2D1)
  ADD_FIELD_NoMem(_dgammaI_U1U2D2)
  ADD_FIELD_NoMem(_dgammaI_U1U2D0)
  ADD_FIELD_NoMem(_dgammaI_U0U2D2)

  DECLARE_FIELD(_dgammaI_U0U0D0)
  DECLARE_FIELD(_dgammaI_U2U2D2)
  DECLARE_FIELD(_dgammaI_U0U1D0)
  DECLARE_FIELD(_dgammaI_U0U1D1)
  DECLARE_FIELD(_dgammaI_U0U2D0)
  DECLARE_FIELD(_dgammaI_U1U1D1)
  DECLARE_FIELD(_dgammaI_U1U2D1)
  DECLARE_FIELD(_dgammaI_U1U2D2)
  DECLARE_FIELD(_dgammaI_U0U2D2)

  /* filling the values */
  _dgammaI_U0U0D0->v = Partial_Derivative(_gammaI_U0U0,"x");
  _dgammaI_U1U2D2->v = Partial_Derivative(_gammaI_U1U2,"z");
  _dgammaI_U0U1D1->v = Partial_Derivative(_gammaI_U0U1,"y");
  _dgammaI_U0U1D0->v = Partial_Derivative(_gammaI_U0U1,"x");
  _dgammaI_U0U2D2->v = Partial_Derivative(_gammaI_U0U2,"z");
  _dgammaI_U1U2D1->v = Partial_Derivative(_gammaI_U1U2,"y");
  _dgammaI_U0U2D0->v = Partial_Derivative(_gammaI_U0U2,"x");
  _dgammaI_U2U2D2->v = Partial_Derivative(_gammaI_U2U2,"z");
  _dgammaI_U1U1D1->v = Partial_Derivative(_gammaI_U1U1,"y");
  }

  {

  /* declaring: */
  PREP_FIELD(ham_constraint_1st)
  PREP_FIELD(mom_constraint_1st_U1)
  PREP_FIELD(mom_constraint_1st_U0)
  PREP_FIELD(mom_constraint_1st_U2)
  GET_FIELD(_A_UiUj_U2U2)
  GET_FIELD(_A_UiUj_U1U2)
  GET_FIELD(_A_UiUj_U1U1)
  GET_FIELD(_A_UiUj_U0U2)
  GET_FIELD(_A_UiUj_U0U1)
  GET_FIELD(_A_UiUj_U0U0)
  GET_FIELD_UNUSED(_dA_UiUj_U2U2D2)
  GET_FIELD_UNUSED(_dA_UiUj_U2U2D0)
  GET_FIELD_UNUSED(_dA_UiUj_U2U2D1)
  GET_FIELD_UNUSED(_dA_UiUj_U1U1D2)
  GET_FIELD_UNUSED(_dA_UiUj_U1U1D0)
  GET_FIELD_UNUSED(_dA_UiUj_U1U1D1)
  GET_FIELD_UNUSED(_dA_UiUj_U0U0D2)
  GET_FIELD_UNUSED(_dA_UiUj_U0U0D0)
  GET_FIELD_UNUSED(_dA_UiUj_U0U0D1)
  GET_FIELD_UNUSED(_dA_UiUj_U0U1D2)
  GET_FIELD_UNUSED(_dA_UiUj_U0U1D1)
  GET_FIELD_UNUSED(_dA_UiUj_U0U1D0)
  GET_FIELD_UNUSED(_dA_UiUj_U1U2D1)
  GET_FIELD_UNUSED(_dA_UiUj_U1U2D0)
  GET_FIELD_UNUSED(_dA_UiUj_U1U2D2)
  GET_FIELD_UNUSED(_dA_UiUj_U0U2D0)
  GET_FIELD_UNUSED(_dA_UiUj_U0U2D1)
  GET_FIELD_UNUSED(_dA_UiUj_U0U2D2)
  GET_FIELD(psi)
  GET_FIELD(dpsi_D0)
  GET_FIELD(dpsi_D1)
  GET_FIELD(dpsi_D2)
  GET_FIELD(ddpsi_D2D2)
  GET_FIELD(ddpsi_D0D0)
  GET_FIELD(ddpsi_D0D1)
  GET_FIELD(ddpsi_D1D1)
  GET_FIELD(ddpsi_D1D2)
  GET_FIELD(ddpsi_D0D2)
  GET_FIELD(_gamma_D2D2)
  GET_FIELD(_gamma_D0D2)
  GET_FIELD(_gamma_D0D0)
  GET_FIELD(_gamma_D0D1)
  GET_FIELD(_gamma_D1D2)
  GET_FIELD(_gamma_D1D1)
  GET_FIELD(_gammaI_U0U2)
  GET_FIELD(_gammaI_U0U0)
  GET_FIELD(_gammaI_U0U1)
  GET_FIELD(_gammaI_U1U2)
  GET_FIELD(_gammaI_U1U1)
  GET_FIELD(_gammaI_U2U2)
  GET_FIELD_UNUSED(_dgammaI_U2U2D0)
  GET_FIELD_UNUSED(_dgammaI_U0U1D2)
  GET_FIELD_UNUSED(_dgammaI_U0U2D0)
  GET_FIELD_UNUSED(_dgammaI_U0U1D0)
  GET_FIELD_UNUSED(_dgammaI_U0U1D1)
  GET_FIELD_UNUSED(_dgammaI_U2U2D2)
  GET_FIELD_UNUSED(_dgammaI_U2U2D1)
  GET_FIELD_UNUSED(_dgammaI_U0U2D2)
  GET_FIELD_UNUSED(_dgammaI_U0U0D2)
  GET_FIELD_UNUSED(_dgammaI_U0U0D1)
  GET_FIELD_UNUSED(_dgammaI_U0U0D0)
  GET_FIELD_UNUSED(_dgammaI_U1U1D2)
  GET_FIELD_UNUSED(_dgammaI_U1U1D1)
  GET_FIELD_UNUSED(_dgammaI_U1U1D0)
  GET_FIELD_UNUSED(_dgammaI_U1U2D1)
  GET_FIELD_UNUSED(_dgammaI_U1U2D0)
  GET_FIELD_UNUSED(_dgammaI_U0U2D1)
  GET_FIELD_UNUSED(_dgammaI_U1U2D2)
  GET_FIELD(_Gamma_U2D1D1)
  GET_FIELD(_Gamma_U2D1D2)
  GET_FIELD(_Gamma_U0D1D1)
  GET_FIELD(_Gamma_U2D0D2)
  GET_FIELD(_Gamma_U2D2D2)
  GET_FIELD(_Gamma_U0D1D2)
  GET_FIELD(_Gamma_U0D0D2)
  GET_FIELD(_Gamma_U0D0D1)
  GET_FIELD(_Gamma_U0D0D0)
  GET_FIELD(_Gamma_U1D2D2)
  GET_FIELD(_Gamma_U2D0D1)
  GET_FIELD(_Gamma_U0D2D2)
  GET_FIELD(_Gamma_U2D0D0)
  GET_FIELD(_Gamma_U1D0D2)
  GET_FIELD(_Gamma_U1D1D2)
  GET_FIELD(_Gamma_U1D0D0)
  GET_FIELD(_Gamma_U1D0D1)
  GET_FIELD(_Gamma_U1D1D1)
  GET_FIELD(_E)
  GET_FIELD(_J_U0)
  GET_FIELD(_J_U1)
  GET_FIELD(_J_U2)
  GET_FIELD(K)
  GET_FIELD(dK_D2)
  GET_FIELD(dK_D1)
  GET_FIELD(dK_D0)
  GET_FIELD(_R)


  for(ijk = 0; ijk < nn; ++ijk)
  {
  double psim4 = 
pow(psi[ijk], -4);

  double psim6 = 
pow(psi[ijk], -6);

  double J_U2 = 
_J_U2[ijk]*psim6;

  double J_U0 = 
_J_U0[ijk]*psim6;

  double J_U1 = 
_J_U1[ijk]*psim6;

  double E = 
_E[ijk]*psim6;

  double dLnpsi_D0 = 
dpsi_D0[ijk]/psi[ijk];

  double dLnpsi_D1 = 
dpsi_D1[ijk]/psi[ijk];

  double dLnpsi_D2 = 
dpsi_D2[ijk]/psi[ijk];

  double DDpsi = 
-_Gamma_U0D0D0[ijk]*_gammaI_U0U0[ijk]*dpsi_D0[ijk] - 2.0*
_Gamma_U0D0D1[ijk]*_gammaI_U0U1[ijk]*dpsi_D0[ijk] - 2.0*
_Gamma_U0D0D2[ijk]*_gammaI_U0U2[ijk]*dpsi_D0[ijk] - _Gamma_U0D1D1[ijk]*
_gammaI_U1U1[ijk]*dpsi_D0[ijk] - 2.0*_Gamma_U0D1D2[ijk]*
_gammaI_U1U2[ijk]*dpsi_D0[ijk] - _Gamma_U0D2D2[ijk]*_gammaI_U2U2[ijk]*
dpsi_D0[ijk] - _Gamma_U1D0D0[ijk]*_gammaI_U0U0[ijk]*dpsi_D1[ijk] - 2.0*
_Gamma_U1D0D1[ijk]*_gammaI_U0U1[ijk]*dpsi_D1[ijk] - 2.0*
_Gamma_U1D0D2[ijk]*_gammaI_U0U2[ijk]*dpsi_D1[ijk] - _Gamma_U1D1D1[ijk]*
_gammaI_U1U1[ijk]*dpsi_D1[ijk] - 2.0*_Gamma_U1D1D2[ijk]*
_gammaI_U1U2[ijk]*dpsi_D1[ijk] - _Gamma_U1D2D2[ijk]*_gammaI_U2U2[ijk]*
dpsi_D1[ijk] - _Gamma_U2D0D0[ijk]*_gammaI_U0U0[ijk]*dpsi_D2[ijk] - 2.0*
_Gamma_U2D0D1[ijk]*_gammaI_U0U1[ijk]*dpsi_D2[ijk] - 2.0*
_Gamma_U2D0D2[ijk]*_gammaI_U0U2[ijk]*dpsi_D2[ijk] - _Gamma_U2D1D1[ijk]*
_gammaI_U1U1[ijk]*dpsi_D2[ijk] - 2.0*_Gamma_U2D1D2[ijk]*
_gammaI_U1U2[ijk]*dpsi_D2[ijk] - _Gamma_U2D2D2[ijk]*_gammaI_U2U2[ijk]*
dpsi_D2[ijk] + _gammaI_U0U0[ijk]*ddpsi_D0D0[ijk] + 2.0*
_gammaI_U0U1[ijk]*ddpsi_D0D1[ijk] + 2.0*_gammaI_U0U2[ijk]*
ddpsi_D0D2[ijk] + _gammaI_U1U1[ijk]*ddpsi_D1D1[ijk] + 2.0*
_gammaI_U1U2[ijk]*ddpsi_D1D2[ijk] + _gammaI_U2U2[ijk]*
ddpsi_D2D2[ijk];

  double R = 
-8*DDpsi*psim4/psi[ijk] + _R[ijk]*psim4;

  double Kbar_U0U0 = 
(1.0/3.0)*K[ijk]*_gammaI_U0U0[ijk] + _A_UiUj_U0U0[ijk]*
psim6;

  double Kbar_U0U1 = 
(1.0/3.0)*K[ijk]*_gammaI_U0U1[ijk] + _A_UiUj_U0U1[ijk]*
psim6;

  double Kbar_U0U2 = 
(1.0/3.0)*K[ijk]*_gammaI_U0U2[ijk] + _A_UiUj_U0U2[ijk]*
psim6;

  double Kbar_U2U2 = 
(1.0/3.0)*K[ijk]*_gammaI_U2U2[ijk] + _A_UiUj_U2U2[ijk]*
psim6;

  double Kbar_U1U1 = 
(1.0/3.0)*K[ijk]*_gammaI_U1U1[ijk] + _A_UiUj_U1U1[ijk]*
psim6;

  double Kbar_U1U2 = 
(1.0/3.0)*K[ijk]*_gammaI_U1U2[ijk] + _A_UiUj_U1U2[ijk]*
psim6;

  double KijKij = 
pow(Kbar_U0U0, 2)*pow(_gamma_D0D0[ijk], 2) + 4.0*Kbar_U0U0*Kbar_U0U1*
_gamma_D0D0[ijk]*_gamma_D0D1[ijk] + 4.0*Kbar_U0U0*Kbar_U0U2*
_gamma_D0D0[ijk]*_gamma_D0D2[ijk] + 2.0*Kbar_U0U0*Kbar_U1U1*
pow(_gamma_D0D1[ijk], 2) + 4.0*Kbar_U0U0*Kbar_U1U2*_gamma_D0D1[ijk]*
_gamma_D0D2[ijk] + 2.0*Kbar_U0U0*Kbar_U2U2*pow(_gamma_D0D2[ijk], 2) +
2.0*pow(Kbar_U0U1, 2)*_gamma_D0D0[ijk]*_gamma_D1D1[ijk] + 2.0*
pow(Kbar_U0U1, 2)*pow(_gamma_D0D1[ijk], 2) + 4.0*Kbar_U0U1*Kbar_U0U2*
_gamma_D0D0[ijk]*_gamma_D1D2[ijk] + 4.0*Kbar_U0U1*Kbar_U0U2*
_gamma_D0D1[ijk]*_gamma_D0D2[ijk] + 4.0*Kbar_U0U1*Kbar_U1U1*
_gamma_D0D1[ijk]*_gamma_D1D1[ijk] + 4.0*Kbar_U0U1*Kbar_U1U2*
_gamma_D0D1[ijk]*_gamma_D1D2[ijk] + 4.0*Kbar_U0U1*Kbar_U1U2*
_gamma_D0D2[ijk]*_gamma_D1D1[ijk] + 4.0*Kbar_U0U1*Kbar_U2U2*
_gamma_D0D2[ijk]*_gamma_D1D2[ijk] + 2.0*pow(Kbar_U0U2, 2)*
_gamma_D0D0[ijk]*_gamma_D2D2[ijk] + 2.0*pow(Kbar_U0U2, 2)*
pow(_gamma_D0D2[ijk], 2) + 4.0*Kbar_U0U2*Kbar_U1U1*_gamma_D0D1[ijk]*
_gamma_D1D2[ijk] + 4.0*Kbar_U0U2*Kbar_U1U2*_gamma_D0D1[ijk]*
_gamma_D2D2[ijk] + 4.0*Kbar_U0U2*Kbar_U1U2*_gamma_D0D2[ijk]*
_gamma_D1D2[ijk] + 4.0*Kbar_U0U2*Kbar_U2U2*_gamma_D0D2[ijk]*
_gamma_D2D2[ijk] + pow(Kbar_U1U1, 2)*pow(_gamma_D1D1[ijk], 2) + 4.0*
Kbar_U1U1*Kbar_U1U2*_gamma_D1D1[ijk]*_gamma_D1D2[ijk] + 2.0*Kbar_U1U1*
Kbar_U2U2*pow(_gamma_D1D2[ijk], 2) + 2.0*pow(Kbar_U1U2, 2)*
_gamma_D1D1[ijk]*_gamma_D2D2[ijk] + 2.0*pow(Kbar_U1U2, 2)*
pow(_gamma_D1D2[ijk], 2) + 4.0*Kbar_U1U2*Kbar_U2U2*_gamma_D1D2[ijk]*
_gamma_D2D2[ijk] + pow(Kbar_U2U2, 2)*pow(_gamma_D2D2[ijk], 2);

  double Ham_Constraint = 
-16*M_PI*E + pow(K[ijk], 2) - KijKij + R;

  double c_U2U2U2 = 
-2.0*_gammaI_U0U2[ijk]*_gamma_D2D2[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U1U2[ijk]*_gamma_D2D2[ijk]*dLnpsi_D1 - 2.0*_gammaI_U2U2[ijk]*
_gamma_D2D2[ijk]*dLnpsi_D2 + 4.0*dLnpsi_D2;

  double c_U0U0U1 = 
-2.0*_gammaI_U0U0[ijk]*_gamma_D0D1[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U0U1[ijk]*_gamma_D0D1[ijk]*dLnpsi_D1 - 2.0*_gammaI_U0U2[ijk]*
_gamma_D0D1[ijk]*dLnpsi_D2 + 2.0*dLnpsi_D1;

  double c_U0U0U0 = 
-2.0*_gammaI_U0U0[ijk]*_gamma_D0D0[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U0U1[ijk]*_gamma_D0D0[ijk]*dLnpsi_D1 - 2.0*_gammaI_U0U2[ijk]*
_gamma_D0D0[ijk]*dLnpsi_D2 + 4.0*dLnpsi_D0;

  double c_U1U0U2 = 
-2.0*_gamma_D1D2[ijk]*(_gammaI_U0U0[ijk]*dLnpsi_D0 + _gammaI_U0U1[ijk]*
dLnpsi_D1 + _gammaI_U0U2[ijk]*dLnpsi_D2);

  double c_U0U0U2 = 
-2.0*_gammaI_U0U0[ijk]*_gamma_D0D2[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U0U1[ijk]*_gamma_D0D2[ijk]*dLnpsi_D1 - 2.0*_gammaI_U0U2[ijk]*
_gamma_D0D2[ijk]*dLnpsi_D2 + 2.0*dLnpsi_D2;

  double c_U0U2U2 = 
-2.0*_gammaI_U0U2[ijk]*_gamma_D0D2[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U1U2[ijk]*_gamma_D0D2[ijk]*dLnpsi_D1 - 2.0*_gammaI_U2U2[ijk]*
_gamma_D0D2[ijk]*dLnpsi_D2 + 2.0*dLnpsi_D0;

  double c_U2U0U1 = 
-2.0*_gamma_D1D2[ijk]*(_gammaI_U0U0[ijk]*dLnpsi_D0 + _gammaI_U0U1[ijk]*
dLnpsi_D1 + _gammaI_U0U2[ijk]*dLnpsi_D2);

  double c_U2U0U0 = 
-2.0*_gammaI_U0U0[ijk]*_gamma_D0D2[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U0U1[ijk]*_gamma_D0D2[ijk]*dLnpsi_D1 - 2.0*_gammaI_U0U2[ijk]*
_gamma_D0D2[ijk]*dLnpsi_D2 + 2.0*dLnpsi_D2;

  double c_U1U1U1 = 
-2.0*_gammaI_U0U1[ijk]*_gamma_D1D1[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U1U1[ijk]*_gamma_D1D1[ijk]*dLnpsi_D1 - 2.0*_gammaI_U1U2[ijk]*
_gamma_D1D1[ijk]*dLnpsi_D2 + 4.0*dLnpsi_D1;

  double c_U1U2U2 = 
-2.0*_gammaI_U0U2[ijk]*_gamma_D1D2[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U1U2[ijk]*_gamma_D1D2[ijk]*dLnpsi_D1 - 2.0*_gammaI_U2U2[ijk]*
_gamma_D1D2[ijk]*dLnpsi_D2 + 2.0*dLnpsi_D1;

  double c_U0U1U1 = 
-2.0*_gammaI_U0U1[ijk]*_gamma_D0D1[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U1U1[ijk]*_gamma_D0D1[ijk]*dLnpsi_D1 - 2.0*_gammaI_U1U2[ijk]*
_gamma_D0D1[ijk]*dLnpsi_D2 + 2.0*dLnpsi_D0;

  double c_U0U1U2 = 
-2.0*_gamma_D0D2[ijk]*(_gammaI_U0U1[ijk]*dLnpsi_D0 + _gammaI_U1U1[ijk]*
dLnpsi_D1 + _gammaI_U1U2[ijk]*dLnpsi_D2);

  double c_U1U0U1 = 
-2.0*_gamma_D1D1[ijk]*(_gammaI_U0U0[ijk]*dLnpsi_D0 + _gammaI_U0U1[ijk]*
dLnpsi_D1 + _gammaI_U0U2[ijk]*dLnpsi_D2);

  double c_U2U1U2 = 
-2.0*_gamma_D2D2[ijk]*(_gammaI_U0U1[ijk]*dLnpsi_D0 + _gammaI_U1U1[ijk]*
dLnpsi_D1 + _gammaI_U1U2[ijk]*dLnpsi_D2);

  double c_U1U0U0 = 
-2.0*_gammaI_U0U0[ijk]*_gamma_D0D1[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U0U1[ijk]*_gamma_D0D1[ijk]*dLnpsi_D1 - 2.0*_gammaI_U0U2[ijk]*
_gamma_D0D1[ijk]*dLnpsi_D2 + 2.0*dLnpsi_D1;

  double c_U2U1U1 = 
-2.0*_gammaI_U0U1[ijk]*_gamma_D1D2[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U1U1[ijk]*_gamma_D1D2[ijk]*dLnpsi_D1 - 2.0*_gammaI_U1U2[ijk]*
_gamma_D1D2[ijk]*dLnpsi_D2 + 2.0*dLnpsi_D2;

  double c_U1U1U2 = 
-2.0*_gammaI_U0U1[ijk]*_gamma_D1D2[ijk]*dLnpsi_D0 - 2.0*
_gammaI_U1U1[ijk]*_gamma_D1D2[ijk]*dLnpsi_D1 - 2.0*_gammaI_U1U2[ijk]*
_gamma_D1D2[ijk]*dLnpsi_D2 + 2.0*dLnpsi_D2;

  double c_U2U0U2 = 
-2.0*_gamma_D2D2[ijk]*(_gammaI_U0U0[ijk]*dLnpsi_D0 + _gammaI_U0U1[ijk]*
dLnpsi_D1 + _gammaI_U0U2[ijk]*dLnpsi_D2);

  double djKj_U0 = 
(1.0/3.0)*psim4*(K[ijk]*(_dgammaI_U0U0D0[ijk] + _dgammaI_U0U1D1[ijk] + 
_dgammaI_U0U2D2[ijk]) - 4.0*K[ijk]*(_gammaI_U0U0[ijk]*dLnpsi_D0 + 
_gammaI_U0U1[ijk]*dLnpsi_D1 + _gammaI_U0U2[ijk]*dLnpsi_D2) + 
_gammaI_U0U0[ijk]*dK_D0[ijk] + _gammaI_U0U1[ijk]*dK_D1[ijk] + 
_gammaI_U0U2[ijk]*dK_D2[ijk] - 3*psim6*(10.0*_A_UiUj_U0U0[ijk]*
dLnpsi_D0 + 10.0*_A_UiUj_U0U1[ijk]*dLnpsi_D1 + 10.0*_A_UiUj_U0U2[ijk]*
dLnpsi_D2 - _dA_UiUj_U0U0D0[ijk] - _dA_UiUj_U0U1D1[ijk] - 
_dA_UiUj_U0U2D2[ijk]));

  double djKj_U1 = 
(1.0/3.0)*psim4*(K[ijk]*(_dgammaI_U0U1D0[ijk] + _dgammaI_U1U1D1[ijk] + 
_dgammaI_U1U2D2[ijk]) - 4.0*K[ijk]*(_gammaI_U0U1[ijk]*dLnpsi_D0 + 
_gammaI_U1U1[ijk]*dLnpsi_D1 + _gammaI_U1U2[ijk]*dLnpsi_D2) + 
_gammaI_U0U1[ijk]*dK_D0[ijk] + _gammaI_U1U1[ijk]*dK_D1[ijk] + 
_gammaI_U1U2[ijk]*dK_D2[ijk] - 3*psim6*(10.0*_A_UiUj_U0U1[ijk]*
dLnpsi_D0 + 10.0*_A_UiUj_U1U1[ijk]*dLnpsi_D1 + 10.0*_A_UiUj_U1U2[ijk]*
dLnpsi_D2 - _dA_UiUj_U0U1D0[ijk] - _dA_UiUj_U1U1D1[ijk] - 
_dA_UiUj_U1U2D2[ijk]));

  double djKj_U2 = 
(1.0/3.0)*psim4*(K[ijk]*(_dgammaI_U0U2D0[ijk] + _dgammaI_U1U2D1[ijk] + 
_dgammaI_U2U2D2[ijk]) - 4.0*K[ijk]*(_gammaI_U0U2[ijk]*dLnpsi_D0 + 
_gammaI_U1U2[ijk]*dLnpsi_D1 + _gammaI_U2U2[ijk]*dLnpsi_D2) + 
_gammaI_U0U2[ijk]*dK_D0[ijk] + _gammaI_U1U2[ijk]*dK_D1[ijk] + 
_gammaI_U2U2[ijk]*dK_D2[ijk] - 3*psim6*(10.0*_A_UiUj_U0U2[ijk]*
dLnpsi_D0 + 10.0*_A_UiUj_U1U2[ijk]*dLnpsi_D1 + 10.0*_A_UiUj_U2U2[ijk]*
dLnpsi_D2 - _dA_UiUj_U0U2D0[ijk] - _dA_UiUj_U1U2D1[ijk] - 
_dA_UiUj_U2U2D2[ijk]));

  double GammaKbar_U2 = 
Kbar_U0U0*_Gamma_U2D0D0[ijk] + 2.0*Kbar_U0U1*_Gamma_U2D0D1[ijk] + 
Kbar_U0U2*_Gamma_U0D0D0[ijk] + Kbar_U0U2*_Gamma_U1D0D1[ijk] + 3.0*
Kbar_U0U2*_Gamma_U2D0D2[ijk] + Kbar_U1U1*_Gamma_U2D1D1[ijk] + 
Kbar_U1U2*_Gamma_U0D0D1[ijk] + Kbar_U1U2*_Gamma_U1D1D1[ijk] + 3.0*
Kbar_U1U2*_Gamma_U2D1D2[ijk] + Kbar_U2U2*_Gamma_U0D0D2[ijk] + 
Kbar_U2U2*_Gamma_U1D1D2[ijk] + 2.0*Kbar_U2U2*_Gamma_U2D2D2[ijk];

  double GammaKbar_U1 = 
Kbar_U0U0*_Gamma_U1D0D0[ijk] + Kbar_U0U1*_Gamma_U0D0D0[ijk] + 3.0*
Kbar_U0U1*_Gamma_U1D0D1[ijk] + Kbar_U0U1*_Gamma_U2D0D2[ijk] + 2.0*
Kbar_U0U2*_Gamma_U1D0D2[ijk] + Kbar_U1U1*_Gamma_U0D0D1[ijk] + 2.0*
Kbar_U1U1*_Gamma_U1D1D1[ijk] + Kbar_U1U1*_Gamma_U2D1D2[ijk] + 
Kbar_U1U2*_Gamma_U0D0D2[ijk] + 3.0*Kbar_U1U2*_Gamma_U1D1D2[ijk] + 
Kbar_U1U2*_Gamma_U2D2D2[ijk] + Kbar_U2U2*_Gamma_U1D2D2[ijk];

  double GammaKbar_U0 = 
2.0*Kbar_U0U0*_Gamma_U0D0D0[ijk] + Kbar_U0U0*_Gamma_U1D0D1[ijk] + 
Kbar_U0U0*_Gamma_U2D0D2[ijk] + 3.0*Kbar_U0U1*_Gamma_U0D0D1[ijk] + 
Kbar_U0U1*_Gamma_U1D1D1[ijk] + Kbar_U0U1*_Gamma_U2D1D2[ijk] + 3.0*
Kbar_U0U2*_Gamma_U0D0D2[ijk] + Kbar_U0U2*_Gamma_U1D1D2[ijk] + 
Kbar_U0U2*_Gamma_U2D2D2[ijk] + Kbar_U1U1*_Gamma_U0D1D1[ijk] + 2.0*
Kbar_U1U2*_Gamma_U0D1D2[ijk] + Kbar_U2U2*_Gamma_U0D2D2[ijk];

  double DbarjKj_U2 = 
GammaKbar_U2*psim4 + djKj_U2;

  double DbarjKj_U0 = 
GammaKbar_U0*psim4 + djKj_U0;

  double DbarjKj_U1 = 
GammaKbar_U1*psim4 + djKj_U1;

  double CKbar_U2 = 
Kbar_U0U0*c_U2U0U0 + 2.0*Kbar_U0U1*c_U2U0U1 + Kbar_U0U2*c_U0U0U0 + 
Kbar_U0U2*c_U1U0U1 + 3.0*Kbar_U0U2*c_U2U0U2 + Kbar_U1U1*c_U2U1U1 + 
Kbar_U1U2*c_U0U0U1 + Kbar_U1U2*c_U1U1U1 + 3.0*Kbar_U1U2*c_U2U1U2 + 
Kbar_U2U2*c_U0U0U2 + Kbar_U2U2*c_U1U1U2 + 2.0*Kbar_U2U2*
c_U2U2U2;

  double CKbar_U1 = 
Kbar_U0U0*c_U1U0U0 + Kbar_U0U1*c_U0U0U0 + 3.0*Kbar_U0U1*c_U1U0U1 + 
Kbar_U0U1*c_U2U0U2 + 2.0*Kbar_U0U2*c_U1U0U2 + Kbar_U1U1*c_U0U0U1 + 2.0*
Kbar_U1U1*c_U1U1U1 + Kbar_U1U1*c_U2U1U2 + Kbar_U1U2*c_U0U0U2 + 3.0*
Kbar_U1U2*c_U1U1U2 + Kbar_U1U2*c_U2U2U2 + Kbar_U2U2*
c_U1U2U2;

  double CKbar_U0 = 
2.0*Kbar_U0U0*c_U0U0U0 + Kbar_U0U0*c_U1U0U1 + Kbar_U0U0*c_U2U0U2 + 3.0*
Kbar_U0U1*c_U0U0U1 + Kbar_U0U1*c_U1U1U1 + Kbar_U0U1*c_U2U1U2 + 3.0*
Kbar_U0U2*c_U0U0U2 + Kbar_U0U2*c_U1U1U2 + Kbar_U0U2*c_U2U2U2 + 
Kbar_U1U1*c_U0U1U1 + 2.0*Kbar_U1U2*c_U0U1U2 + Kbar_U2U2*
c_U0U2U2;

  double Dk_U0 = 
CKbar_U0*psim4 + DbarjKj_U0;

  double Dk_U1 = 
CKbar_U1*psim4 + DbarjKj_U1;

  double Dk_U2 = 
CKbar_U2*psim4 + DbarjKj_U2;

  double Mom_constraint_U2 = 
Dk_U2 - 8*M_PI*J_U2 - psim4*(_gammaI_U0U2[ijk]*dK_D0[ijk] + 
_gammaI_U1U2[ijk]*dK_D1[ijk] + _gammaI_U2U2[ijk]*dK_D2[ijk]);

  double Mom_constraint_U0 = 
Dk_U0 - 8*M_PI*J_U0 - psim4*(_gammaI_U0U0[ijk]*dK_D0[ijk] + 
_gammaI_U0U1[ijk]*dK_D1[ijk] + _gammaI_U0U2[ijk]*dK_D2[ijk]);

  double Mom_constraint_U1 = 
Dk_U1 - 8*M_PI*J_U1 - psim4*(_gammaI_U0U1[ijk]*dK_D0[ijk] + 
_gammaI_U1U1[ijk]*dK_D1[ijk] + _gammaI_U1U2[ijk]*dK_D2[ijk]);


  /* populating: */
  mom_constraint_1st_U1[ijk] = Mom_constraint_U1;
  mom_constraint_1st_U0[ijk] = Mom_constraint_U0;
  mom_constraint_1st_U2[ijk] = Mom_constraint_U2;
  ham_constraint_1st[ijk] = Ham_Constraint;
  }
  }
  DECLARE_FIELD(_dgammaI_U0U0D1)
  DECLARE_FIELD(_dgammaI_U0U0D0)
  DECLARE_FIELD(_dgammaI_U2U2D2)
  DECLARE_FIELD(_dgammaI_U0U0D2)
  DECLARE_FIELD(_dgammaI_U0U2D1)
  DECLARE_FIELD(_dgammaI_U1U1D0)
  DECLARE_FIELD(_dgammaI_U1U1D2)
  DECLARE_FIELD(_dgammaI_U2U2D0)
  DECLARE_FIELD(_dgammaI_U2U2D1)
  DECLARE_FIELD(_dgammaI_U0U1D0)
  DECLARE_FIELD(_dgammaI_U0U1D1)
  DECLARE_FIELD(_dgammaI_U0U1D2)
  DECLARE_FIELD(_dgammaI_U0U2D0)
  DECLARE_FIELD(_dgammaI_U1U1D1)
  DECLARE_FIELD(_dgammaI_U1U2D1)
  DECLARE_FIELD(_dgammaI_U1U2D2)
  DECLARE_FIELD(_dgammaI_U1U2D0)
  DECLARE_FIELD(_dgammaI_U0U2D2)

  REMOVE_FIELD(_dgammaI_U0U0D1)
  REMOVE_FIELD(_dgammaI_U0U0D0)
  REMOVE_FIELD(_dgammaI_U2U2D2)
  REMOVE_FIELD(_dgammaI_U0U0D2)
  REMOVE_FIELD(_dgammaI_U0U2D1)
  REMOVE_FIELD(_dgammaI_U1U1D0)
  REMOVE_FIELD(_dgammaI_U1U1D2)
  REMOVE_FIELD(_dgammaI_U2U2D0)
  REMOVE_FIELD(_dgammaI_U2U2D1)
  REMOVE_FIELD(_dgammaI_U0U1D0)
  REMOVE_FIELD(_dgammaI_U0U1D1)
  REMOVE_FIELD(_dgammaI_U0U1D2)
  REMOVE_FIELD(_dgammaI_U0U2D0)
  REMOVE_FIELD(_dgammaI_U1U1D1)
  REMOVE_FIELD(_dgammaI_U1U2D1)
  REMOVE_FIELD(_dgammaI_U1U2D2)
  REMOVE_FIELD(_dgammaI_U1U2D0)
  REMOVE_FIELD(_dgammaI_U0U2D2)
  }
}
