/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"
#include "maths_equation_solvings_lib.h"
#include "bbn_XCTS_equations_lib.h"



void *bbn_jacobian_eq_Beta_U2(void *vp1,void *vp2)
{
  DDM_SCHUR_JACOBIAN_EQ_DECLARE
  unsigned ijk,lmn;/* for Jacobian entries J[ijk][lmn] */
  const double kd[2]   = {0.,1.};/* Kronecker delta */

  /* declaring: */
  JACOBIAN_DERIVATIVE(JB0_D1)
  JACOBIAN_DERIVATIVE(JB0_D0)
  JACOBIAN_DERIVATIVE(JB0_D2)
  JACOBIAN_DERIVATIVE(JJB0_D1D1)
  JACOBIAN_DERIVATIVE(JJB0_D1D2)
  JACOBIAN_DERIVATIVE(JJB0_D2D2)
  JACOBIAN_DERIVATIVE(JJB0_D0D0)
  JACOBIAN_DERIVATIVE(JJB0_D0D1)
  JACOBIAN_DERIVATIVE(JJB0_D0D2)
  READ_v(psi)
  READ_v_UNUSED(dpsi_D0)
  READ_v_UNUSED(dpsi_D1)
  READ_v_UNUSED(dpsi_D2)
  READ_v(eta)
  READ_v_UNUSED(deta_D0)
  READ_v_UNUSED(deta_D1)
  READ_v_UNUSED(deta_D2)
  READ_v_UNUSED(_gammaI_U0U2)
  READ_v_UNUSED(_gammaI_U0U0)
  READ_v_UNUSED(_gammaI_U0U1)
  READ_v_UNUSED(_gammaI_U1U2)
  READ_v_UNUSED(_gammaI_U1U1)
  READ_v_UNUSED(_gammaI_U2U2)
  READ_v_UNUSED(_Gamma_U2D1D1)
  READ_v_UNUSED(_Gamma_U2D1D2)
  READ_v_UNUSED(_Gamma_U0D1D1)
  READ_v_UNUSED(_Gamma_U2D0D2)
  READ_v_UNUSED(_Gamma_U2D2D2)
  READ_v_UNUSED(_Gamma_U0D1D2)
  READ_v_UNUSED(_Gamma_U0D0D2)
  READ_v_UNUSED(_Gamma_U0D0D1)
  READ_v_UNUSED(_Gamma_U0D0D0)
  READ_v_UNUSED(_Gamma_U1D2D2)
  READ_v_UNUSED(_Gamma_U2D0D1)
  READ_v_UNUSED(_Gamma_U0D2D2)
  READ_v_UNUSED(_Gamma_U2D0D0)
  READ_v_UNUSED(_Gamma_U1D0D2)
  READ_v_UNUSED(_Gamma_U1D1D2)
  READ_v_UNUSED(_Gamma_U1D0D0)
  READ_v_UNUSED(_Gamma_U1D0D1)
  READ_v_UNUSED(_Gamma_U1D1D1)
  READ_v_UNUSED(_dGamma_U2D2D2D2)
  READ_v_UNUSED(_dGamma_U2D2D2D0)
  READ_v_UNUSED(_dGamma_U2D2D2D1)
  READ_v_UNUSED(_dGamma_U2D0D0D2)
  READ_v_UNUSED(_dGamma_U1D1D2D2)
  READ_v_UNUSED(_dGamma_U2D0D0D0)
  READ_v_UNUSED(_dGamma_U1D1D2D0)
  READ_v_UNUSED(_dGamma_U1D1D2D1)
  READ_v_UNUSED(_dGamma_U2D1D1D0)
  READ_v_UNUSED(_dGamma_U2D0D0D1)
  READ_v_UNUSED(_dGamma_U2D0D2D1)
  READ_v_UNUSED(_dGamma_U1D0D1D0)
  READ_v_UNUSED(_dGamma_U1D0D1D1)
  READ_v_UNUSED(_dGamma_U1D0D1D2)
  READ_v_UNUSED(_dGamma_U1D2D2D1)
  READ_v_UNUSED(_dGamma_U1D0D0D1)
  READ_v_UNUSED(_dGamma_U1D0D0D0)
  READ_v_UNUSED(_dGamma_U1D0D0D2)
  READ_v_UNUSED(_dGamma_U0D1D2D2)
  READ_v_UNUSED(_dGamma_U0D1D2D1)
  READ_v_UNUSED(_dGamma_U0D1D2D0)
  READ_v_UNUSED(_dGamma_U2D0D2D0)
  READ_v_UNUSED(_dGamma_U1D0D2D2)
  READ_v_UNUSED(_dGamma_U1D0D2D1)
  READ_v_UNUSED(_dGamma_U1D0D2D0)
  READ_v_UNUSED(_dGamma_U2D1D1D2)
  READ_v_UNUSED(_dGamma_U2D0D2D2)
  READ_v_UNUSED(_dGamma_U0D0D1D0)
  READ_v_UNUSED(_dGamma_U1D2D2D0)
  READ_v_UNUSED(_dGamma_U2D1D2D1)
  READ_v_UNUSED(_dGamma_U2D0D1D2)
  READ_v_UNUSED(_dGamma_U2D0D1D1)
  READ_v_UNUSED(_dGamma_U2D0D1D0)
  READ_v_UNUSED(_dGamma_U2D1D2D2)
  READ_v_UNUSED(_dGamma_U0D1D1D0)
  READ_v_UNUSED(_dGamma_U0D1D1D1)
  READ_v_UNUSED(_dGamma_U0D1D1D2)
  READ_v_UNUSED(_dGamma_U1D2D2D2)
  READ_v_UNUSED(_dGamma_U1D1D1D1)
  READ_v_UNUSED(_dGamma_U1D1D1D0)
  READ_v_UNUSED(_dGamma_U1D1D1D2)
  READ_v_UNUSED(_dGamma_U0D0D1D1)
  READ_v_UNUSED(_dGamma_U0D0D2D2)
  READ_v_UNUSED(_dGamma_U0D0D2D0)
  READ_v_UNUSED(_dGamma_U0D0D2D1)
  READ_v_UNUSED(_dGamma_U2D1D2D0)
  READ_v_UNUSED(_dGamma_U0D0D0D0)
  READ_v_UNUSED(_dGamma_U0D0D0D1)
  READ_v_UNUSED(_dGamma_U0D0D0D2)
  READ_v_UNUSED(_dGamma_U2D1D1D1)
  READ_v_UNUSED(_dGamma_U0D2D2D0)
  READ_v_UNUSED(_dGamma_U0D2D2D1)
  READ_v_UNUSED(_dGamma_U0D2D2D2)
  READ_v_UNUSED(_dGamma_U0D0D1D2)


  DDM_SCHUR_JACOBIAN_EQ_Bpart_OPEN

  double dLnOf_alpha_B_U1 = 
deta_D1[ijk]/eta[ijk] - 7*dpsi_D1[ijk]/psi[ijk];

  double dLnOf_alpha_B_U0 = 
deta_D0[ijk]/eta[ijk] - 7*dpsi_D0[ijk]/psi[ijk];

  double dLnOf_alpha_B_U2 = 
deta_D2[ijk]/eta[ijk] - 7*dpsi_D2[ijk]/psi[ijk];



  double t1_B_U2 = 
_gammaI_U0U0[ijk]*(JJB0_D0D0(j_JJB0_D0D0,ijk,lmn) + 
_dGamma_U2D0D2D0[ijk]*kd[ijk==lmn]) + _gammaI_U0U1[ijk]*
(JJB0_D0D1(j_JJB0_D0D1,ijk,lmn) + _dGamma_U2D0D2D1[ijk]*kd[ijk==lmn]) + 
_gammaI_U0U1[ijk]*(JJB0_D0D1(j_JJB0_D0D1,ijk,lmn) + 
_dGamma_U2D1D2D0[ijk]*kd[ijk==lmn]) + _gammaI_U0U2[ijk]*
(JJB0_D0D2(j_JJB0_D0D2,ijk,lmn) + _dGamma_U2D0D2D2[ijk]*kd[ijk==lmn]) + 
_gammaI_U0U2[ijk]*(JJB0_D0D2(j_JJB0_D0D2,ijk,lmn) + 
_dGamma_U2D2D2D0[ijk]*kd[ijk==lmn]) + _gammaI_U1U1[ijk]*
(JJB0_D1D1(j_JJB0_D1D1,ijk,lmn) + _dGamma_U2D1D2D1[ijk]*kd[ijk==lmn]) + 
_gammaI_U1U2[ijk]*(JJB0_D1D2(j_JJB0_D1D2,ijk,lmn) + 
_dGamma_U2D1D2D2[ijk]*kd[ijk==lmn]) + _gammaI_U1U2[ijk]*
(JJB0_D1D2(j_JJB0_D1D2,ijk,lmn) + _dGamma_U2D2D2D1[ijk]*kd[ijk==lmn]) + 
_gammaI_U2U2[ijk]*(JJB0_D2D2(j_JJB0_D2D2,ijk,lmn) + 
_dGamma_U2D2D2D2[ijk]*kd[ijk==lmn]);



  double t2_B_U2 = 
2.0*JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U2D0D2[ijk]*_gammaI_U0U0[ijk] + 
2.0*JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U2D1D2[ijk]*_gammaI_U1U1[ijk] + 
2.0*JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D2D2[ijk]*_gammaI_U2U2[ijk] + 
2.0*_gammaI_U0U1[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U2D1D2[ijk] + 
JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U2D0D2[ijk]) + 2.0*_gammaI_U0U2[ijk]*
(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U2D2D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*
_Gamma_U2D0D2[ijk]) + 2.0*_gammaI_U1U2[ijk]*(JB0_D1(j_JB0_D1,ijk,lmn)*
_Gamma_U2D2D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D1D2[ijk]);

  double t3_B_U2 = 
kd[ijk==lmn]*(_Gamma_U0D0D2[ijk]*_Gamma_U2D0D0[ijk]*_gammaI_U0U0[ijk] + 
_Gamma_U0D0D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U0U1[ijk] + 
_Gamma_U0D0D2[ijk]*_Gamma_U2D0D2[ijk]*_gammaI_U0U2[ijk] + 
_Gamma_U0D1D2[ijk]*_Gamma_U2D0D0[ijk]*_gammaI_U0U1[ijk] + 
_Gamma_U0D1D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U1U1[ijk] + 
_Gamma_U0D1D2[ijk]*_Gamma_U2D0D2[ijk]*_gammaI_U1U2[ijk] + 
_Gamma_U0D2D2[ijk]*_Gamma_U2D0D0[ijk]*_gammaI_U0U2[ijk] + 
_Gamma_U0D2D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U1U2[ijk] + 
_Gamma_U0D2D2[ijk]*_Gamma_U2D0D2[ijk]*_gammaI_U2U2[ijk] + 
_Gamma_U1D0D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U0U0[ijk] + 
_Gamma_U1D0D2[ijk]*_Gamma_U2D1D1[ijk]*_gammaI_U0U1[ijk] + 
_Gamma_U1D0D2[ijk]*_Gamma_U2D1D2[ijk]*_gammaI_U0U2[ijk] + 
_Gamma_U1D1D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U0U1[ijk] + 
_Gamma_U1D1D2[ijk]*_Gamma_U2D1D1[ijk]*_gammaI_U1U1[ijk] + 
_Gamma_U1D1D2[ijk]*_Gamma_U2D1D2[ijk]*_gammaI_U1U2[ijk] + 
_Gamma_U1D2D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U0U2[ijk] + 
_Gamma_U1D2D2[ijk]*_Gamma_U2D1D1[ijk]*_gammaI_U1U2[ijk] + 
_Gamma_U1D2D2[ijk]*_Gamma_U2D1D2[ijk]*_gammaI_U2U2[ijk] + 
pow(_Gamma_U2D0D2[ijk], 2)*_gammaI_U0U0[ijk] + 2.0*_Gamma_U2D0D2[ijk]*
_Gamma_U2D1D2[ijk]*_gammaI_U0U1[ijk] + 2.0*_Gamma_U2D0D2[ijk]*
_Gamma_U2D2D2[ijk]*_gammaI_U0U2[ijk] + pow(_Gamma_U2D1D2[ijk], 2)*
_gammaI_U1U1[ijk] + 2.0*_Gamma_U2D1D2[ijk]*_Gamma_U2D2D2[ijk]*
_gammaI_U1U2[ijk] + pow(_Gamma_U2D2D2[ijk], 2)*_gammaI_U2U2[ijk]);



  double t4_B_U2 = 
-_gammaI_U0U0[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U0D0D0[ijk] + 
JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D0D0[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*
_Gamma_U2D0D0[ijk] + kd[ijk==lmn]*(_Gamma_U0D0D0[ijk]*
_Gamma_U2D0D2[ijk] + _Gamma_U1D0D0[ijk]*_Gamma_U2D1D2[ijk] + 
_Gamma_U2D0D0[ijk]*_Gamma_U2D2D2[ijk])) - 2.0*_gammaI_U0U1[ijk]*
(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U0D0D1[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*
_Gamma_U1D0D1[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D0D1[ijk] + 
kd[ijk==lmn]*(_Gamma_U0D0D1[ijk]*_Gamma_U2D0D2[ijk] + 
_Gamma_U1D0D1[ijk]*_Gamma_U2D1D2[ijk] + _Gamma_U2D0D1[ijk]*
_Gamma_U2D2D2[ijk])) - 2.0*_gammaI_U0U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D0D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D0D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D0D2[ijk] + kd[ijk==lmn]*
(_Gamma_U0D0D2[ijk]*_Gamma_U2D0D2[ijk] + _Gamma_U1D0D2[ijk]*
_Gamma_U2D1D2[ijk] + _Gamma_U2D0D2[ijk]*_Gamma_U2D2D2[ijk])) - 
_gammaI_U1U1[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U0D1D1[ijk] + 
JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D1D1[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*
_Gamma_U2D1D1[ijk] + kd[ijk==lmn]*(_Gamma_U0D1D1[ijk]*
_Gamma_U2D0D2[ijk] + _Gamma_U1D1D1[ijk]*_Gamma_U2D1D2[ijk] + 
_Gamma_U2D1D1[ijk]*_Gamma_U2D2D2[ijk])) - 2.0*_gammaI_U1U2[ijk]*
(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U0D1D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*
_Gamma_U1D1D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D1D2[ijk] + 
kd[ijk==lmn]*(_Gamma_U0D1D2[ijk]*_Gamma_U2D0D2[ijk] + 
_Gamma_U1D1D2[ijk]*_Gamma_U2D1D2[ijk] + _Gamma_U2D1D2[ijk]*
_Gamma_U2D2D2[ijk])) - _gammaI_U2U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D2D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D2D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D2D2[ijk] + kd[ijk==lmn]*
(_Gamma_U0D2D2[ijk]*_Gamma_U2D0D2[ijk] + _Gamma_U1D2D2[ijk]*
_Gamma_U2D1D2[ijk] + pow(_Gamma_U2D2D2[ijk], 2)));





  double t5_B_U2 = 
0.33333333333333331*_gammaI_U0U2[ijk]*(JJB0_D0D2(j_JJB0_D0D2,ijk,lmn) + 
kd[ijk==lmn]*(_dGamma_U0D0D2D0[ijk] + _dGamma_U1D1D2D0[ijk] + 
_dGamma_U2D2D2D0[ijk])) + 0.33333333333333331*_gammaI_U1U2[ijk]*
(JJB0_D1D2(j_JJB0_D1D2,ijk,lmn) + kd[ijk==lmn]*(_dGamma_U0D0D2D1[ijk] + 
_dGamma_U1D1D2D1[ijk] + _dGamma_U2D2D2D1[ijk])) + 0.33333333333333331*
_gammaI_U2U2[ijk]*(JJB0_D2D2(j_JJB0_D2D2,ijk,lmn) + kd[ijk==lmn]*
(_dGamma_U0D0D2D2[ijk] + _dGamma_U1D1D2D2[ijk] + _dGamma_U2D2D2D2[ijk]));



  double t6_B_U2 = 
0.33333333333333331*_gammaI_U0U2[ijk]*(2.0*JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D0D2[ijk] + JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U1D1D2[ijk] + 
JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U2D2D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*
_Gamma_U1D0D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D0D2[ijk]) + 
0.33333333333333331*_gammaI_U1U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D1D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U0D0D2[ijk] + 2.0*
JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D1D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*
_Gamma_U2D2D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D1D2[ijk]) + 
0.33333333333333331*_gammaI_U2U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D2D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D2D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U0D0D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*
_Gamma_U1D1D2[ijk] + 2.0*JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D2D2[ijk]);

  double t7_B_U2 = 
kd[ijk==lmn]*(0.33333333333333331*_Gamma_U0D0D0[ijk]*
_Gamma_U0D0D2[ijk]*_gammaI_U0U2[ijk] + 0.33333333333333331*
_Gamma_U0D0D1[ijk]*_Gamma_U0D0D2[ijk]*_gammaI_U1U2[ijk] + 
0.33333333333333331*_Gamma_U0D0D1[ijk]*_Gamma_U1D0D2[ijk]*
_gammaI_U0U2[ijk] + 0.33333333333333331*pow(_Gamma_U0D0D2[ijk], 2)*
_gammaI_U2U2[ijk] + 0.33333333333333331*_Gamma_U0D0D2[ijk]*
_Gamma_U2D0D2[ijk]*_gammaI_U0U2[ijk] + 0.33333333333333331*
_Gamma_U0D1D1[ijk]*_Gamma_U1D0D2[ijk]*_gammaI_U1U2[ijk] + 
0.33333333333333331*_Gamma_U0D1D2[ijk]*_Gamma_U1D0D0[ijk]*
_gammaI_U0U2[ijk] + 0.33333333333333331*_Gamma_U0D1D2[ijk]*
_Gamma_U1D0D1[ijk]*_gammaI_U1U2[ijk] + 0.66666666666666663*
_Gamma_U0D1D2[ijk]*_Gamma_U1D0D2[ijk]*_gammaI_U2U2[ijk] + 
0.33333333333333331*_Gamma_U0D1D2[ijk]*_Gamma_U2D0D2[ijk]*
_gammaI_U1U2[ijk] + 0.33333333333333331*_Gamma_U0D2D2[ijk]*
_Gamma_U2D0D0[ijk]*_gammaI_U0U2[ijk] + 0.33333333333333331*
_Gamma_U0D2D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U1U2[ijk] + 
0.66666666666666663*_Gamma_U0D2D2[ijk]*_Gamma_U2D0D2[ijk]*
_gammaI_U2U2[ijk] + 0.33333333333333331*_Gamma_U1D0D1[ijk]*
_Gamma_U1D1D2[ijk]*_gammaI_U0U2[ijk] + 0.33333333333333331*
_Gamma_U1D0D2[ijk]*_Gamma_U2D1D2[ijk]*_gammaI_U0U2[ijk] + 
0.33333333333333331*_Gamma_U1D1D1[ijk]*_Gamma_U1D1D2[ijk]*
_gammaI_U1U2[ijk] + 0.33333333333333331*pow(_Gamma_U1D1D2[ijk], 2)*
_gammaI_U2U2[ijk] + 0.33333333333333331*_Gamma_U1D1D2[ijk]*
_Gamma_U2D1D2[ijk]*_gammaI_U1U2[ijk] + 0.33333333333333331*
_Gamma_U1D2D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U0U2[ijk] + 
0.33333333333333331*_Gamma_U1D2D2[ijk]*_Gamma_U2D1D1[ijk]*
_gammaI_U1U2[ijk] + 0.66666666666666663*_Gamma_U1D2D2[ijk]*
_Gamma_U2D1D2[ijk]*_gammaI_U2U2[ijk] + 0.33333333333333331*
_Gamma_U2D0D2[ijk]*_Gamma_U2D2D2[ijk]*_gammaI_U0U2[ijk] + 
0.33333333333333331*_Gamma_U2D1D2[ijk]*_Gamma_U2D2D2[ijk]*
_gammaI_U1U2[ijk] + 0.33333333333333331*pow(_Gamma_U2D2D2[ijk], 2)*
_gammaI_U2U2[ijk]);



  double t8_B_U2 = 
-0.33333333333333331*_gammaI_U0U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D0D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D0D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D0D2[ijk] + kd[ijk==lmn]*
(_Gamma_U0D0D0[ijk]*_Gamma_U0D0D2[ijk] + _Gamma_U0D0D1[ijk]*
_Gamma_U1D0D2[ijk] + _Gamma_U0D0D2[ijk]*_Gamma_U2D0D2[ijk] + 
_Gamma_U0D1D2[ijk]*_Gamma_U1D0D0[ijk] + _Gamma_U0D2D2[ijk]*
_Gamma_U2D0D0[ijk] + _Gamma_U1D0D1[ijk]*_Gamma_U1D1D2[ijk] + 
_Gamma_U1D0D2[ijk]*_Gamma_U2D1D2[ijk] + _Gamma_U1D2D2[ijk]*
_Gamma_U2D0D1[ijk] + _Gamma_U2D0D2[ijk]*_Gamma_U2D2D2[ijk])) - 
0.33333333333333331*_gammaI_U1U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D1D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D1D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D1D2[ijk] + kd[ijk==lmn]*
(_Gamma_U0D0D1[ijk]*_Gamma_U0D0D2[ijk] + _Gamma_U0D1D1[ijk]*
_Gamma_U1D0D2[ijk] + _Gamma_U0D1D2[ijk]*_Gamma_U1D0D1[ijk] + 
_Gamma_U0D1D2[ijk]*_Gamma_U2D0D2[ijk] + _Gamma_U0D2D2[ijk]*
_Gamma_U2D0D1[ijk] + _Gamma_U1D1D1[ijk]*_Gamma_U1D1D2[ijk] + 
_Gamma_U1D1D2[ijk]*_Gamma_U2D1D2[ijk] + _Gamma_U1D2D2[ijk]*
_Gamma_U2D1D1[ijk] + _Gamma_U2D1D2[ijk]*_Gamma_U2D2D2[ijk])) - 
0.33333333333333331*_gammaI_U2U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D2D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D2D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D2D2[ijk] + kd[ijk==lmn]*
(pow(_Gamma_U0D0D2[ijk], 2) + 2.0*_Gamma_U0D1D2[ijk]*
_Gamma_U1D0D2[ijk] + 2.0*_Gamma_U0D2D2[ijk]*_Gamma_U2D0D2[ijk] + 
pow(_Gamma_U1D1D2[ijk], 2) + 2.0*_Gamma_U1D2D2[ijk]*
_Gamma_U2D1D2[ijk] + pow(_Gamma_U2D2D2[ijk], 2)));





  double t10_B_U2 = 
-dLnOf_alpha_B_U0*(_Gamma_U0D0D2[ijk]*_gammaI_U0U2[ijk]*kd[ijk==lmn] + 
_Gamma_U0D1D2[ijk]*_gammaI_U1U2[ijk]*kd[ijk==lmn] + _Gamma_U0D2D2[ijk]*
_gammaI_U2U2[ijk]*kd[ijk==lmn] + _gammaI_U0U0[ijk]*
(JB0_D0(j_JB0_D0,ijk,lmn) + _Gamma_U2D0D2[ijk]*kd[ijk==lmn]) + 
_gammaI_U0U1[ijk]*(JB0_D1(j_JB0_D1,ijk,lmn) + _Gamma_U2D1D2[ijk]*
kd[ijk==lmn]) + _gammaI_U0U2[ijk]*(JB0_D2(j_JB0_D2,ijk,lmn) + 
_Gamma_U2D2D2[ijk]*kd[ijk==lmn]) - 0.66666666666666663*
_gammaI_U0U2[ijk]*(JB0_D2(j_JB0_D2,ijk,lmn) + kd[ijk==lmn]*
(_Gamma_U0D0D2[ijk] + _Gamma_U1D1D2[ijk] + _Gamma_U2D2D2[ijk]))) - 
dLnOf_alpha_B_U1*(_Gamma_U1D0D2[ijk]*_gammaI_U0U2[ijk]*kd[ijk==lmn] + 
_Gamma_U1D1D2[ijk]*_gammaI_U1U2[ijk]*kd[ijk==lmn] + _Gamma_U1D2D2[ijk]*
_gammaI_U2U2[ijk]*kd[ijk==lmn] + _gammaI_U0U1[ijk]*
(JB0_D0(j_JB0_D0,ijk,lmn) + _Gamma_U2D0D2[ijk]*kd[ijk==lmn]) + 
_gammaI_U1U1[ijk]*(JB0_D1(j_JB0_D1,ijk,lmn) + _Gamma_U2D1D2[ijk]*
kd[ijk==lmn]) + _gammaI_U1U2[ijk]*(JB0_D2(j_JB0_D2,ijk,lmn) + 
_Gamma_U2D2D2[ijk]*kd[ijk==lmn]) - 0.66666666666666663*
_gammaI_U1U2[ijk]*(JB0_D2(j_JB0_D2,ijk,lmn) + kd[ijk==lmn]*
(_Gamma_U0D0D2[ijk] + _Gamma_U1D1D2[ijk] + _Gamma_U2D2D2[ijk]))) - 
dLnOf_alpha_B_U2*(2.0*_gammaI_U0U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn) + 
_Gamma_U2D0D2[ijk]*kd[ijk==lmn]) + 2.0*_gammaI_U1U2[ijk]*
(JB0_D1(j_JB0_D1,ijk,lmn) + _Gamma_U2D1D2[ijk]*kd[ijk==lmn]) + 2.0*
_gammaI_U2U2[ijk]*(JB0_D2(j_JB0_D2,ijk,lmn) + _Gamma_U2D2D2[ijk]*
kd[ijk==lmn]) - 0.66666666666666663*_gammaI_U2U2[ijk]*
(JB0_D2(j_JB0_D2,ijk,lmn) + kd[ijk==lmn]*(_Gamma_U0D0D2[ijk] + 
_Gamma_U1D1D2[ijk] + _Gamma_U2D2D2[ijk])));

  double Bpart_U2 = 
t10_B_U2 + t1_B_U2 + t2_B_U2 + t3_B_U2 + t4_B_U2 + t5_B_U2 + t6_B_U2 + 
t7_B_U2 + t8_B_U2;



  B[i][j] = Bpart_U2;

  DDM_SCHUR_JACOBIAN_EQ_Bpart_CLOSE

  DDM_SCHUR_JACOBIAN_EQ_Epart_OPEN

  double dLnOf_alpha_E_U0 = 
deta_D0[ijk]/eta[ijk] - 7*dpsi_D0[ijk]/psi[ijk];

  double dLnOf_alpha_E_U1 = 
deta_D1[ijk]/eta[ijk] - 7*dpsi_D1[ijk]/psi[ijk];

  double dLnOf_alpha_E_U2 = 
deta_D2[ijk]/eta[ijk] - 7*dpsi_D2[ijk]/psi[ijk];



  double t1_E_U2 = 
_gammaI_U0U0[ijk]*(JJB0_D0D0(j_JJB0_D0D0,ijk,lmn) + 
_dGamma_U2D0D2D0[ijk]*kd[ijk==lmn]) + _gammaI_U0U1[ijk]*
(JJB0_D0D1(j_JJB0_D0D1,ijk,lmn) + _dGamma_U2D0D2D1[ijk]*kd[ijk==lmn]) + 
_gammaI_U0U1[ijk]*(JJB0_D0D1(j_JJB0_D0D1,ijk,lmn) + 
_dGamma_U2D1D2D0[ijk]*kd[ijk==lmn]) + _gammaI_U0U2[ijk]*
(JJB0_D0D2(j_JJB0_D0D2,ijk,lmn) + _dGamma_U2D0D2D2[ijk]*kd[ijk==lmn]) + 
_gammaI_U0U2[ijk]*(JJB0_D0D2(j_JJB0_D0D2,ijk,lmn) + 
_dGamma_U2D2D2D0[ijk]*kd[ijk==lmn]) + _gammaI_U1U1[ijk]*
(JJB0_D1D1(j_JJB0_D1D1,ijk,lmn) + _dGamma_U2D1D2D1[ijk]*kd[ijk==lmn]) + 
_gammaI_U1U2[ijk]*(JJB0_D1D2(j_JJB0_D1D2,ijk,lmn) + 
_dGamma_U2D1D2D2[ijk]*kd[ijk==lmn]) + _gammaI_U1U2[ijk]*
(JJB0_D1D2(j_JJB0_D1D2,ijk,lmn) + _dGamma_U2D2D2D1[ijk]*kd[ijk==lmn]) + 
_gammaI_U2U2[ijk]*(JJB0_D2D2(j_JJB0_D2D2,ijk,lmn) + 
_dGamma_U2D2D2D2[ijk]*kd[ijk==lmn]);



  double t2_E_U2 = 
2.0*JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U2D0D2[ijk]*_gammaI_U0U0[ijk] + 
2.0*JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U2D1D2[ijk]*_gammaI_U1U1[ijk] + 
2.0*JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D2D2[ijk]*_gammaI_U2U2[ijk] + 
2.0*_gammaI_U0U1[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U2D1D2[ijk] + 
JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U2D0D2[ijk]) + 2.0*_gammaI_U0U2[ijk]*
(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U2D2D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*
_Gamma_U2D0D2[ijk]) + 2.0*_gammaI_U1U2[ijk]*(JB0_D1(j_JB0_D1,ijk,lmn)*
_Gamma_U2D2D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D1D2[ijk]);

  double t3_E_U2 = 
kd[ijk==lmn]*(_Gamma_U0D0D2[ijk]*_Gamma_U2D0D0[ijk]*_gammaI_U0U0[ijk] + 
_Gamma_U0D0D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U0U1[ijk] + 
_Gamma_U0D0D2[ijk]*_Gamma_U2D0D2[ijk]*_gammaI_U0U2[ijk] + 
_Gamma_U0D1D2[ijk]*_Gamma_U2D0D0[ijk]*_gammaI_U0U1[ijk] + 
_Gamma_U0D1D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U1U1[ijk] + 
_Gamma_U0D1D2[ijk]*_Gamma_U2D0D2[ijk]*_gammaI_U1U2[ijk] + 
_Gamma_U0D2D2[ijk]*_Gamma_U2D0D0[ijk]*_gammaI_U0U2[ijk] + 
_Gamma_U0D2D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U1U2[ijk] + 
_Gamma_U0D2D2[ijk]*_Gamma_U2D0D2[ijk]*_gammaI_U2U2[ijk] + 
_Gamma_U1D0D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U0U0[ijk] + 
_Gamma_U1D0D2[ijk]*_Gamma_U2D1D1[ijk]*_gammaI_U0U1[ijk] + 
_Gamma_U1D0D2[ijk]*_Gamma_U2D1D2[ijk]*_gammaI_U0U2[ijk] + 
_Gamma_U1D1D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U0U1[ijk] + 
_Gamma_U1D1D2[ijk]*_Gamma_U2D1D1[ijk]*_gammaI_U1U1[ijk] + 
_Gamma_U1D1D2[ijk]*_Gamma_U2D1D2[ijk]*_gammaI_U1U2[ijk] + 
_Gamma_U1D2D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U0U2[ijk] + 
_Gamma_U1D2D2[ijk]*_Gamma_U2D1D1[ijk]*_gammaI_U1U2[ijk] + 
_Gamma_U1D2D2[ijk]*_Gamma_U2D1D2[ijk]*_gammaI_U2U2[ijk] + 
pow(_Gamma_U2D0D2[ijk], 2)*_gammaI_U0U0[ijk] + 2.0*_Gamma_U2D0D2[ijk]*
_Gamma_U2D1D2[ijk]*_gammaI_U0U1[ijk] + 2.0*_Gamma_U2D0D2[ijk]*
_Gamma_U2D2D2[ijk]*_gammaI_U0U2[ijk] + pow(_Gamma_U2D1D2[ijk], 2)*
_gammaI_U1U1[ijk] + 2.0*_Gamma_U2D1D2[ijk]*_Gamma_U2D2D2[ijk]*
_gammaI_U1U2[ijk] + pow(_Gamma_U2D2D2[ijk], 2)*_gammaI_U2U2[ijk]);



  double t4_E_U2 = 
-_gammaI_U0U0[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U0D0D0[ijk] + 
JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D0D0[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*
_Gamma_U2D0D0[ijk] + kd[ijk==lmn]*(_Gamma_U0D0D0[ijk]*
_Gamma_U2D0D2[ijk] + _Gamma_U1D0D0[ijk]*_Gamma_U2D1D2[ijk] + 
_Gamma_U2D0D0[ijk]*_Gamma_U2D2D2[ijk])) - 2.0*_gammaI_U0U1[ijk]*
(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U0D0D1[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*
_Gamma_U1D0D1[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D0D1[ijk] + 
kd[ijk==lmn]*(_Gamma_U0D0D1[ijk]*_Gamma_U2D0D2[ijk] + 
_Gamma_U1D0D1[ijk]*_Gamma_U2D1D2[ijk] + _Gamma_U2D0D1[ijk]*
_Gamma_U2D2D2[ijk])) - 2.0*_gammaI_U0U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D0D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D0D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D0D2[ijk] + kd[ijk==lmn]*
(_Gamma_U0D0D2[ijk]*_Gamma_U2D0D2[ijk] + _Gamma_U1D0D2[ijk]*
_Gamma_U2D1D2[ijk] + _Gamma_U2D0D2[ijk]*_Gamma_U2D2D2[ijk])) - 
_gammaI_U1U1[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U0D1D1[ijk] + 
JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D1D1[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*
_Gamma_U2D1D1[ijk] + kd[ijk==lmn]*(_Gamma_U0D1D1[ijk]*
_Gamma_U2D0D2[ijk] + _Gamma_U1D1D1[ijk]*_Gamma_U2D1D2[ijk] + 
_Gamma_U2D1D1[ijk]*_Gamma_U2D2D2[ijk])) - 2.0*_gammaI_U1U2[ijk]*
(JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U0D1D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*
_Gamma_U1D1D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D1D2[ijk] + 
kd[ijk==lmn]*(_Gamma_U0D1D2[ijk]*_Gamma_U2D0D2[ijk] + 
_Gamma_U1D1D2[ijk]*_Gamma_U2D1D2[ijk] + _Gamma_U2D1D2[ijk]*
_Gamma_U2D2D2[ijk])) - _gammaI_U2U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D2D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D2D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D2D2[ijk] + kd[ijk==lmn]*
(_Gamma_U0D2D2[ijk]*_Gamma_U2D0D2[ijk] + _Gamma_U1D2D2[ijk]*
_Gamma_U2D1D2[ijk] + pow(_Gamma_U2D2D2[ijk], 2)));





  double t5_E_U2 = 
0.33333333333333331*_gammaI_U0U2[ijk]*(JJB0_D0D2(j_JJB0_D0D2,ijk,lmn) + 
kd[ijk==lmn]*(_dGamma_U0D0D2D0[ijk] + _dGamma_U1D1D2D0[ijk] + 
_dGamma_U2D2D2D0[ijk])) + 0.33333333333333331*_gammaI_U1U2[ijk]*
(JJB0_D1D2(j_JJB0_D1D2,ijk,lmn) + kd[ijk==lmn]*(_dGamma_U0D0D2D1[ijk] + 
_dGamma_U1D1D2D1[ijk] + _dGamma_U2D2D2D1[ijk])) + 0.33333333333333331*
_gammaI_U2U2[ijk]*(JJB0_D2D2(j_JJB0_D2D2,ijk,lmn) + kd[ijk==lmn]*
(_dGamma_U0D0D2D2[ijk] + _dGamma_U1D1D2D2[ijk] + _dGamma_U2D2D2D2[ijk]));



  double t6_E_U2 = 
0.33333333333333331*_gammaI_U0U2[ijk]*(2.0*JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D0D2[ijk] + JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U1D1D2[ijk] + 
JB0_D0(j_JB0_D0,ijk,lmn)*_Gamma_U2D2D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*
_Gamma_U1D0D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D0D2[ijk]) + 
0.33333333333333331*_gammaI_U1U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D1D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U0D0D2[ijk] + 2.0*
JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D1D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*
_Gamma_U2D2D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D1D2[ijk]) + 
0.33333333333333331*_gammaI_U2U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D2D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D2D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U0D0D2[ijk] + JB0_D2(j_JB0_D2,ijk,lmn)*
_Gamma_U1D1D2[ijk] + 2.0*JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D2D2[ijk]);

  double t7_E_U2 = 
kd[ijk==lmn]*(0.33333333333333331*_Gamma_U0D0D0[ijk]*
_Gamma_U0D0D2[ijk]*_gammaI_U0U2[ijk] + 0.33333333333333331*
_Gamma_U0D0D1[ijk]*_Gamma_U0D0D2[ijk]*_gammaI_U1U2[ijk] + 
0.33333333333333331*_Gamma_U0D0D1[ijk]*_Gamma_U1D0D2[ijk]*
_gammaI_U0U2[ijk] + 0.33333333333333331*pow(_Gamma_U0D0D2[ijk], 2)*
_gammaI_U2U2[ijk] + 0.33333333333333331*_Gamma_U0D0D2[ijk]*
_Gamma_U2D0D2[ijk]*_gammaI_U0U2[ijk] + 0.33333333333333331*
_Gamma_U0D1D1[ijk]*_Gamma_U1D0D2[ijk]*_gammaI_U1U2[ijk] + 
0.33333333333333331*_Gamma_U0D1D2[ijk]*_Gamma_U1D0D0[ijk]*
_gammaI_U0U2[ijk] + 0.33333333333333331*_Gamma_U0D1D2[ijk]*
_Gamma_U1D0D1[ijk]*_gammaI_U1U2[ijk] + 0.66666666666666663*
_Gamma_U0D1D2[ijk]*_Gamma_U1D0D2[ijk]*_gammaI_U2U2[ijk] + 
0.33333333333333331*_Gamma_U0D1D2[ijk]*_Gamma_U2D0D2[ijk]*
_gammaI_U1U2[ijk] + 0.33333333333333331*_Gamma_U0D2D2[ijk]*
_Gamma_U2D0D0[ijk]*_gammaI_U0U2[ijk] + 0.33333333333333331*
_Gamma_U0D2D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U1U2[ijk] + 
0.66666666666666663*_Gamma_U0D2D2[ijk]*_Gamma_U2D0D2[ijk]*
_gammaI_U2U2[ijk] + 0.33333333333333331*_Gamma_U1D0D1[ijk]*
_Gamma_U1D1D2[ijk]*_gammaI_U0U2[ijk] + 0.33333333333333331*
_Gamma_U1D0D2[ijk]*_Gamma_U2D1D2[ijk]*_gammaI_U0U2[ijk] + 
0.33333333333333331*_Gamma_U1D1D1[ijk]*_Gamma_U1D1D2[ijk]*
_gammaI_U1U2[ijk] + 0.33333333333333331*pow(_Gamma_U1D1D2[ijk], 2)*
_gammaI_U2U2[ijk] + 0.33333333333333331*_Gamma_U1D1D2[ijk]*
_Gamma_U2D1D2[ijk]*_gammaI_U1U2[ijk] + 0.33333333333333331*
_Gamma_U1D2D2[ijk]*_Gamma_U2D0D1[ijk]*_gammaI_U0U2[ijk] + 
0.33333333333333331*_Gamma_U1D2D2[ijk]*_Gamma_U2D1D1[ijk]*
_gammaI_U1U2[ijk] + 0.66666666666666663*_Gamma_U1D2D2[ijk]*
_Gamma_U2D1D2[ijk]*_gammaI_U2U2[ijk] + 0.33333333333333331*
_Gamma_U2D0D2[ijk]*_Gamma_U2D2D2[ijk]*_gammaI_U0U2[ijk] + 
0.33333333333333331*_Gamma_U2D1D2[ijk]*_Gamma_U2D2D2[ijk]*
_gammaI_U1U2[ijk] + 0.33333333333333331*pow(_Gamma_U2D2D2[ijk], 2)*
_gammaI_U2U2[ijk]);



  double t8_E_U2 = 
-0.33333333333333331*_gammaI_U0U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D0D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D0D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D0D2[ijk] + kd[ijk==lmn]*
(_Gamma_U0D0D0[ijk]*_Gamma_U0D0D2[ijk] + _Gamma_U0D0D1[ijk]*
_Gamma_U1D0D2[ijk] + _Gamma_U0D0D2[ijk]*_Gamma_U2D0D2[ijk] + 
_Gamma_U0D1D2[ijk]*_Gamma_U1D0D0[ijk] + _Gamma_U0D2D2[ijk]*
_Gamma_U2D0D0[ijk] + _Gamma_U1D0D1[ijk]*_Gamma_U1D1D2[ijk] + 
_Gamma_U1D0D2[ijk]*_Gamma_U2D1D2[ijk] + _Gamma_U1D2D2[ijk]*
_Gamma_U2D0D1[ijk] + _Gamma_U2D0D2[ijk]*_Gamma_U2D2D2[ijk])) - 
0.33333333333333331*_gammaI_U1U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D1D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D1D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D1D2[ijk] + kd[ijk==lmn]*
(_Gamma_U0D0D1[ijk]*_Gamma_U0D0D2[ijk] + _Gamma_U0D1D1[ijk]*
_Gamma_U1D0D2[ijk] + _Gamma_U0D1D2[ijk]*_Gamma_U1D0D1[ijk] + 
_Gamma_U0D1D2[ijk]*_Gamma_U2D0D2[ijk] + _Gamma_U0D2D2[ijk]*
_Gamma_U2D0D1[ijk] + _Gamma_U1D1D1[ijk]*_Gamma_U1D1D2[ijk] + 
_Gamma_U1D1D2[ijk]*_Gamma_U2D1D2[ijk] + _Gamma_U1D2D2[ijk]*
_Gamma_U2D1D1[ijk] + _Gamma_U2D1D2[ijk]*_Gamma_U2D2D2[ijk])) - 
0.33333333333333331*_gammaI_U2U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn)*
_Gamma_U0D2D2[ijk] + JB0_D1(j_JB0_D1,ijk,lmn)*_Gamma_U1D2D2[ijk] + 
JB0_D2(j_JB0_D2,ijk,lmn)*_Gamma_U2D2D2[ijk] + kd[ijk==lmn]*
(pow(_Gamma_U0D0D2[ijk], 2) + 2.0*_Gamma_U0D1D2[ijk]*
_Gamma_U1D0D2[ijk] + 2.0*_Gamma_U0D2D2[ijk]*_Gamma_U2D0D2[ijk] + 
pow(_Gamma_U1D1D2[ijk], 2) + 2.0*_Gamma_U1D2D2[ijk]*
_Gamma_U2D1D2[ijk] + pow(_Gamma_U2D2D2[ijk], 2)));





  double t10_E_U2 = 
-dLnOf_alpha_E_U0*(_Gamma_U0D0D2[ijk]*_gammaI_U0U2[ijk]*kd[ijk==lmn] + 
_Gamma_U0D1D2[ijk]*_gammaI_U1U2[ijk]*kd[ijk==lmn] + _Gamma_U0D2D2[ijk]*
_gammaI_U2U2[ijk]*kd[ijk==lmn] + _gammaI_U0U0[ijk]*
(JB0_D0(j_JB0_D0,ijk,lmn) + _Gamma_U2D0D2[ijk]*kd[ijk==lmn]) + 
_gammaI_U0U1[ijk]*(JB0_D1(j_JB0_D1,ijk,lmn) + _Gamma_U2D1D2[ijk]*
kd[ijk==lmn]) + _gammaI_U0U2[ijk]*(JB0_D2(j_JB0_D2,ijk,lmn) + 
_Gamma_U2D2D2[ijk]*kd[ijk==lmn]) - 0.66666666666666663*
_gammaI_U0U2[ijk]*(JB0_D2(j_JB0_D2,ijk,lmn) + kd[ijk==lmn]*
(_Gamma_U0D0D2[ijk] + _Gamma_U1D1D2[ijk] + _Gamma_U2D2D2[ijk]))) - 
dLnOf_alpha_E_U1*(_Gamma_U1D0D2[ijk]*_gammaI_U0U2[ijk]*kd[ijk==lmn] + 
_Gamma_U1D1D2[ijk]*_gammaI_U1U2[ijk]*kd[ijk==lmn] + _Gamma_U1D2D2[ijk]*
_gammaI_U2U2[ijk]*kd[ijk==lmn] + _gammaI_U0U1[ijk]*
(JB0_D0(j_JB0_D0,ijk,lmn) + _Gamma_U2D0D2[ijk]*kd[ijk==lmn]) + 
_gammaI_U1U1[ijk]*(JB0_D1(j_JB0_D1,ijk,lmn) + _Gamma_U2D1D2[ijk]*
kd[ijk==lmn]) + _gammaI_U1U2[ijk]*(JB0_D2(j_JB0_D2,ijk,lmn) + 
_Gamma_U2D2D2[ijk]*kd[ijk==lmn]) - 0.66666666666666663*
_gammaI_U1U2[ijk]*(JB0_D2(j_JB0_D2,ijk,lmn) + kd[ijk==lmn]*
(_Gamma_U0D0D2[ijk] + _Gamma_U1D1D2[ijk] + _Gamma_U2D2D2[ijk]))) - 
dLnOf_alpha_E_U2*(2.0*_gammaI_U0U2[ijk]*(JB0_D0(j_JB0_D0,ijk,lmn) + 
_Gamma_U2D0D2[ijk]*kd[ijk==lmn]) + 2.0*_gammaI_U1U2[ijk]*
(JB0_D1(j_JB0_D1,ijk,lmn) + _Gamma_U2D1D2[ijk]*kd[ijk==lmn]) + 2.0*
_gammaI_U2U2[ijk]*(JB0_D2(j_JB0_D2,ijk,lmn) + _Gamma_U2D2D2[ijk]*
kd[ijk==lmn]) - 0.66666666666666663*_gammaI_U2U2[ijk]*
(JB0_D2(j_JB0_D2,ijk,lmn) + kd[ijk==lmn]*(_Gamma_U0D0D2[ijk] + 
_Gamma_U1D1D2[ijk] + _Gamma_U2D2D2[ijk])));

  double Epart_U2 = 
t10_E_U2 + t1_E_U2 + t2_E_U2 + t3_E_U2 + t4_E_U2 + t5_E_U2 + t6_E_U2 + 
t7_E_U2 + t8_E_U2;



  E_Trans[j][i] = Epart_U2;

  DDM_SCHUR_JACOBIAN_EQ_Epart_CLOSE

  return 0;
}
