/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "bbn_headers.h"


#define add_field_and_get_field(name) ADD_FIELD(name) PREP_FIELD(name)
#define add_field_NoMem_and_declare_field(name) ADD_FIELD_NoMem(name)\
                                      Field_T *const f##name = patch->pool[Ind(#name)];
void bbn_update_psi10A_UiUj(Patch_T *const patch)
{

  /* declaring: */
  PREP_FIELD(_A_UiUj_U2U2)
  PREP_FIELD(_A_UiUj_U1U2)
  PREP_FIELD(_A_UiUj_U1U1)
  PREP_FIELD(_A_UiUj_U0U2)
  PREP_FIELD(_A_UiUj_U0U1)
  PREP_FIELD(_A_UiUj_U0U0)
  PREP_FIELD(_dA_UiUj_U2U2D2)
  PREP_FIELD(_dA_UiUj_U2U2D0)
  PREP_FIELD(_dA_UiUj_U2U2D1)
  PREP_FIELD(_dA_UiUj_U1U1D2)
  PREP_FIELD(_dA_UiUj_U1U1D0)
  PREP_FIELD(_dA_UiUj_U1U1D1)
  PREP_FIELD(_dA_UiUj_U0U0D2)
  PREP_FIELD(_dA_UiUj_U0U0D0)
  PREP_FIELD(_dA_UiUj_U0U0D1)
  PREP_FIELD(_dA_UiUj_U0U1D2)
  PREP_FIELD(_dA_UiUj_U0U1D1)
  PREP_FIELD(_dA_UiUj_U0U1D0)
  PREP_FIELD(_dA_UiUj_U1U2D1)
  PREP_FIELD(_dA_UiUj_U1U2D0)
  PREP_FIELD(_dA_UiUj_U1U2D2)
  PREP_FIELD(_dA_UiUj_U0U2D0)
  PREP_FIELD(_dA_UiUj_U0U2D1)
  PREP_FIELD(_dA_UiUj_U0U2D2)
  PREP_FIELD(_Aij2)
  GET_FIELD(Beta_U1)
  GET_FIELD(Beta_U0)
  GET_FIELD(Beta_U2)
  GET_FIELD(dBeta_U2D2)
  GET_FIELD(dBeta_U2D0)
  GET_FIELD(dBeta_U2D1)
  GET_FIELD(dBeta_U0D0)
  GET_FIELD(dBeta_U1D1)
  GET_FIELD(dBeta_U0D1)
  GET_FIELD(dBeta_U0D2)
  GET_FIELD(dBeta_U1D2)
  GET_FIELD(dBeta_U1D0)
  GET_FIELD(psi)
  GET_FIELD(dpsi_D0)
  GET_FIELD(dpsi_D1)
  GET_FIELD(dpsi_D2)
  GET_FIELD(eta)
  GET_FIELD(deta_D0)
  GET_FIELD(deta_D1)
  GET_FIELD(deta_D2)
  GET_FIELD(_gamma_D2D2)
  GET_FIELD(_gamma_D0D2)
  GET_FIELD(_gamma_D0D0)
  GET_FIELD(_gamma_D0D1)
  GET_FIELD(_gamma_D1D2)
  GET_FIELD(_gamma_D1D1)
  GET_FIELD(_gammaI_U0U2)
  GET_FIELD(_gammaI_U0U0)
  GET_FIELD(_gammaI_U0U1)
  GET_FIELD(_gammaI_U1U2)
  GET_FIELD(_gammaI_U1U1)
  GET_FIELD(_gammaI_U2U2)
  add_field_and_prep_field(_LBij_U0U1)
  add_field_and_prep_field(_LBij_U0U0)
  add_field_and_prep_field(_LBij_U0U2)
  add_field_and_prep_field(_LBij_U1U1)
  add_field_and_prep_field(_LBij_U1U2)
  add_field_and_prep_field(_LBij_U2U2)
  GET_FIELD(_Gamma_U2D1D1)
  GET_FIELD(_Gamma_U2D1D2)
  GET_FIELD(_Gamma_U0D1D1)
  GET_FIELD(_Gamma_U2D0D2)
  GET_FIELD(_Gamma_U2D2D2)
  GET_FIELD(_Gamma_U0D1D2)
  GET_FIELD(_Gamma_U0D0D2)
  GET_FIELD(_Gamma_U0D0D1)
  GET_FIELD(_Gamma_U0D0D0)
  GET_FIELD(_Gamma_U1D2D2)
  GET_FIELD(_Gamma_U2D0D1)
  GET_FIELD(_Gamma_U0D2D2)
  GET_FIELD(_Gamma_U2D0D0)
  GET_FIELD(_Gamma_U1D0D2)
  GET_FIELD(_Gamma_U1D1D2)
  GET_FIELD(_Gamma_U1D0D0)
  GET_FIELD(_Gamma_U1D0D1)
  GET_FIELD(_Gamma_U1D1D1)


    unsigned nn = patch->nn;
    unsigned ijk;
    for(ijk = 0; ijk < nn; ++ijk)
    {
    double psi7 = 
pow(psi[ijk], 7);

    double _DB_UU_U1U2 = 
_gammaI_U0U1[ijk]*(Beta_U0[ijk]*_Gamma_U2D0D0[ijk] + Beta_U1[ijk]*
_Gamma_U2D0D1[ijk] + Beta_U2[ijk]*_Gamma_U2D0D2[ijk] + 
dBeta_U2D0[ijk]) + _gammaI_U1U1[ijk]*(Beta_U0[ijk]*_Gamma_U2D0D1[ijk] + 
Beta_U1[ijk]*_Gamma_U2D1D1[ijk] + Beta_U2[ijk]*_Gamma_U2D1D2[ijk] + 
dBeta_U2D1[ijk]) + _gammaI_U1U2[ijk]*(Beta_U0[ijk]*_Gamma_U2D0D2[ijk] + 
Beta_U1[ijk]*_Gamma_U2D1D2[ijk] + Beta_U2[ijk]*_Gamma_U2D2D2[ijk] + 
dBeta_U2D2[ijk]);

    double _DB_UU_U1U1 = 
_gammaI_U0U1[ijk]*(Beta_U0[ijk]*_Gamma_U1D0D0[ijk] + Beta_U1[ijk]*
_Gamma_U1D0D1[ijk] + Beta_U2[ijk]*_Gamma_U1D0D2[ijk] + 
dBeta_U1D0[ijk]) + _gammaI_U1U1[ijk]*(Beta_U0[ijk]*_Gamma_U1D0D1[ijk] + 
Beta_U1[ijk]*_Gamma_U1D1D1[ijk] + Beta_U2[ijk]*_Gamma_U1D1D2[ijk] + 
dBeta_U1D1[ijk]) + _gammaI_U1U2[ijk]*(Beta_U0[ijk]*_Gamma_U1D0D2[ijk] + 
Beta_U1[ijk]*_Gamma_U1D1D2[ijk] + Beta_U2[ijk]*_Gamma_U1D2D2[ijk] + 
dBeta_U1D2[ijk]);

    double _DB_UU_U1U0 = 
_gammaI_U0U1[ijk]*(Beta_U0[ijk]*_Gamma_U0D0D0[ijk] + Beta_U1[ijk]*
_Gamma_U0D0D1[ijk] + Beta_U2[ijk]*_Gamma_U0D0D2[ijk] + 
dBeta_U0D0[ijk]) + _gammaI_U1U1[ijk]*(Beta_U0[ijk]*_Gamma_U0D0D1[ijk] + 
Beta_U1[ijk]*_Gamma_U0D1D1[ijk] + Beta_U2[ijk]*_Gamma_U0D1D2[ijk] + 
dBeta_U0D1[ijk]) + _gammaI_U1U2[ijk]*(Beta_U0[ijk]*_Gamma_U0D0D2[ijk] + 
Beta_U1[ijk]*_Gamma_U0D1D2[ijk] + Beta_U2[ijk]*_Gamma_U0D2D2[ijk] + 
dBeta_U0D2[ijk]);

    double _DB_UU_U0U2 = 
_gammaI_U0U0[ijk]*(Beta_U0[ijk]*_Gamma_U2D0D0[ijk] + Beta_U1[ijk]*
_Gamma_U2D0D1[ijk] + Beta_U2[ijk]*_Gamma_U2D0D2[ijk] + 
dBeta_U2D0[ijk]) + _gammaI_U0U1[ijk]*(Beta_U0[ijk]*_Gamma_U2D0D1[ijk] + 
Beta_U1[ijk]*_Gamma_U2D1D1[ijk] + Beta_U2[ijk]*_Gamma_U2D1D2[ijk] + 
dBeta_U2D1[ijk]) + _gammaI_U0U2[ijk]*(Beta_U0[ijk]*_Gamma_U2D0D2[ijk] + 
Beta_U1[ijk]*_Gamma_U2D1D2[ijk] + Beta_U2[ijk]*_Gamma_U2D2D2[ijk] + 
dBeta_U2D2[ijk]);

    double _DB_UU_U0U0 = 
_gammaI_U0U0[ijk]*(Beta_U0[ijk]*_Gamma_U0D0D0[ijk] + Beta_U1[ijk]*
_Gamma_U0D0D1[ijk] + Beta_U2[ijk]*_Gamma_U0D0D2[ijk] + 
dBeta_U0D0[ijk]) + _gammaI_U0U1[ijk]*(Beta_U0[ijk]*_Gamma_U0D0D1[ijk] + 
Beta_U1[ijk]*_Gamma_U0D1D1[ijk] + Beta_U2[ijk]*_Gamma_U0D1D2[ijk] + 
dBeta_U0D1[ijk]) + _gammaI_U0U2[ijk]*(Beta_U0[ijk]*_Gamma_U0D0D2[ijk] + 
Beta_U1[ijk]*_Gamma_U0D1D2[ijk] + Beta_U2[ijk]*_Gamma_U0D2D2[ijk] + 
dBeta_U0D2[ijk]);

    double _DB_UU_U0U1 = 
_gammaI_U0U0[ijk]*(Beta_U0[ijk]*_Gamma_U1D0D0[ijk] + Beta_U1[ijk]*
_Gamma_U1D0D1[ijk] + Beta_U2[ijk]*_Gamma_U1D0D2[ijk] + 
dBeta_U1D0[ijk]) + _gammaI_U0U1[ijk]*(Beta_U0[ijk]*_Gamma_U1D0D1[ijk] + 
Beta_U1[ijk]*_Gamma_U1D1D1[ijk] + Beta_U2[ijk]*_Gamma_U1D1D2[ijk] + 
dBeta_U1D1[ijk]) + _gammaI_U0U2[ijk]*(Beta_U0[ijk]*_Gamma_U1D0D2[ijk] + 
Beta_U1[ijk]*_Gamma_U1D1D2[ijk] + Beta_U2[ijk]*_Gamma_U1D2D2[ijk] + 
dBeta_U1D2[ijk]);

    double _DB_UU_U2U0 = 
_gammaI_U0U2[ijk]*(Beta_U0[ijk]*_Gamma_U0D0D0[ijk] + Beta_U1[ijk]*
_Gamma_U0D0D1[ijk] + Beta_U2[ijk]*_Gamma_U0D0D2[ijk] + 
dBeta_U0D0[ijk]) + _gammaI_U1U2[ijk]*(Beta_U0[ijk]*_Gamma_U0D0D1[ijk] + 
Beta_U1[ijk]*_Gamma_U0D1D1[ijk] + Beta_U2[ijk]*_Gamma_U0D1D2[ijk] + 
dBeta_U0D1[ijk]) + _gammaI_U2U2[ijk]*(Beta_U0[ijk]*_Gamma_U0D0D2[ijk] + 
Beta_U1[ijk]*_Gamma_U0D1D2[ijk] + Beta_U2[ijk]*_Gamma_U0D2D2[ijk] + 
dBeta_U0D2[ijk]);

    double _DB_UU_U2U1 = 
_gammaI_U0U2[ijk]*(Beta_U0[ijk]*_Gamma_U1D0D0[ijk] + Beta_U1[ijk]*
_Gamma_U1D0D1[ijk] + Beta_U2[ijk]*_Gamma_U1D0D2[ijk] + 
dBeta_U1D0[ijk]) + _gammaI_U1U2[ijk]*(Beta_U0[ijk]*_Gamma_U1D0D1[ijk] + 
Beta_U1[ijk]*_Gamma_U1D1D1[ijk] + Beta_U2[ijk]*_Gamma_U1D1D2[ijk] + 
dBeta_U1D1[ijk]) + _gammaI_U2U2[ijk]*(Beta_U0[ijk]*_Gamma_U1D0D2[ijk] + 
Beta_U1[ijk]*_Gamma_U1D1D2[ijk] + Beta_U2[ijk]*_Gamma_U1D2D2[ijk] + 
dBeta_U1D2[ijk]);

    double _DB_UU_U2U2 = 
_gammaI_U0U2[ijk]*(Beta_U0[ijk]*_Gamma_U2D0D0[ijk] + Beta_U1[ijk]*
_Gamma_U2D0D1[ijk] + Beta_U2[ijk]*_Gamma_U2D0D2[ijk] + 
dBeta_U2D0[ijk]) + _gammaI_U1U2[ijk]*(Beta_U0[ijk]*_Gamma_U2D0D1[ijk] + 
Beta_U1[ijk]*_Gamma_U2D1D1[ijk] + Beta_U2[ijk]*_Gamma_U2D1D2[ijk] + 
dBeta_U2D1[ijk]) + _gammaI_U2U2[ijk]*(Beta_U0[ijk]*_Gamma_U2D0D2[ijk] + 
Beta_U1[ijk]*_Gamma_U2D1D2[ijk] + Beta_U2[ijk]*_Gamma_U2D2D2[ijk] + 
dBeta_U2D2[ijk]);

    double _LV_UU_U0U2 = 
-0.66666666666666663*_DB_UU_U0U0*_gammaI_U0U2[ijk]*_gamma_D0D0[ijk] - 
0.66666666666666663*_DB_UU_U0U1*_gammaI_U0U2[ijk]*_gamma_D0D1[ijk] - 
0.66666666666666663*_DB_UU_U0U2*_gammaI_U0U2[ijk]*_gamma_D0D2[ijk] + 
_DB_UU_U0U2 - 0.66666666666666663*_DB_UU_U1U0*_gammaI_U0U2[ijk]*
_gamma_D0D1[ijk] - 0.66666666666666663*_DB_UU_U1U1*_gammaI_U0U2[ijk]*
_gamma_D1D1[ijk] - 0.66666666666666663*_DB_UU_U1U2*_gammaI_U0U2[ijk]*
_gamma_D1D2[ijk] - 0.66666666666666663*_DB_UU_U2U0*_gammaI_U0U2[ijk]*
_gamma_D0D2[ijk] + _DB_UU_U2U0 - 0.66666666666666663*_DB_UU_U2U1*
_gammaI_U0U2[ijk]*_gamma_D1D2[ijk] - 0.66666666666666663*_DB_UU_U2U2*
_gammaI_U0U2[ijk]*_gamma_D2D2[ijk];

    double _LV_UU_U0U0 = 
-0.66666666666666663*_DB_UU_U0U0*_gammaI_U0U0[ijk]*_gamma_D0D0[ijk] + 
2*_DB_UU_U0U0 - 0.66666666666666663*_DB_UU_U0U1*_gammaI_U0U0[ijk]*
_gamma_D0D1[ijk] - 0.66666666666666663*_DB_UU_U0U2*_gammaI_U0U0[ijk]*
_gamma_D0D2[ijk] - 0.66666666666666663*_DB_UU_U1U0*_gammaI_U0U0[ijk]*
_gamma_D0D1[ijk] - 0.66666666666666663*_DB_UU_U1U1*_gammaI_U0U0[ijk]*
_gamma_D1D1[ijk] - 0.66666666666666663*_DB_UU_U1U2*_gammaI_U0U0[ijk]*
_gamma_D1D2[ijk] - 0.66666666666666663*_DB_UU_U2U0*_gammaI_U0U0[ijk]*
_gamma_D0D2[ijk] - 0.66666666666666663*_DB_UU_U2U1*_gammaI_U0U0[ijk]*
_gamma_D1D2[ijk] - 0.66666666666666663*_DB_UU_U2U2*_gammaI_U0U0[ijk]*
_gamma_D2D2[ijk];

    double _LV_UU_U0U1 = 
-0.66666666666666663*_DB_UU_U0U0*_gammaI_U0U1[ijk]*_gamma_D0D0[ijk] - 
0.66666666666666663*_DB_UU_U0U1*_gammaI_U0U1[ijk]*_gamma_D0D1[ijk] + 
_DB_UU_U0U1 - 0.66666666666666663*_DB_UU_U0U2*_gammaI_U0U1[ijk]*
_gamma_D0D2[ijk] - 0.66666666666666663*_DB_UU_U1U0*_gammaI_U0U1[ijk]*
_gamma_D0D1[ijk] + _DB_UU_U1U0 - 0.66666666666666663*_DB_UU_U1U1*
_gammaI_U0U1[ijk]*_gamma_D1D1[ijk] - 0.66666666666666663*_DB_UU_U1U2*
_gammaI_U0U1[ijk]*_gamma_D1D2[ijk] - 0.66666666666666663*_DB_UU_U2U0*
_gammaI_U0U1[ijk]*_gamma_D0D2[ijk] - 0.66666666666666663*_DB_UU_U2U1*
_gammaI_U0U1[ijk]*_gamma_D1D2[ijk] - 0.66666666666666663*_DB_UU_U2U2*
_gammaI_U0U1[ijk]*_gamma_D2D2[ijk];

    double _LV_UU_U2U2 = 
-0.66666666666666663*_DB_UU_U0U0*_gammaI_U2U2[ijk]*_gamma_D0D0[ijk] - 
0.66666666666666663*_DB_UU_U0U1*_gammaI_U2U2[ijk]*_gamma_D0D1[ijk] - 
0.66666666666666663*_DB_UU_U0U2*_gammaI_U2U2[ijk]*_gamma_D0D2[ijk] - 
0.66666666666666663*_DB_UU_U1U0*_gammaI_U2U2[ijk]*_gamma_D0D1[ijk] - 
0.66666666666666663*_DB_UU_U1U1*_gammaI_U2U2[ijk]*_gamma_D1D1[ijk] - 
0.66666666666666663*_DB_UU_U1U2*_gammaI_U2U2[ijk]*_gamma_D1D2[ijk] - 
0.66666666666666663*_DB_UU_U2U0*_gammaI_U2U2[ijk]*_gamma_D0D2[ijk] - 
0.66666666666666663*_DB_UU_U2U1*_gammaI_U2U2[ijk]*_gamma_D1D2[ijk] - 
0.66666666666666663*_DB_UU_U2U2*_gammaI_U2U2[ijk]*_gamma_D2D2[ijk] + 2*
_DB_UU_U2U2;

    double _LV_UU_U1U2 = 
-0.66666666666666663*_DB_UU_U0U0*_gammaI_U1U2[ijk]*_gamma_D0D0[ijk] - 
0.66666666666666663*_DB_UU_U0U1*_gammaI_U1U2[ijk]*_gamma_D0D1[ijk] - 
0.66666666666666663*_DB_UU_U0U2*_gammaI_U1U2[ijk]*_gamma_D0D2[ijk] - 
0.66666666666666663*_DB_UU_U1U0*_gammaI_U1U2[ijk]*_gamma_D0D1[ijk] - 
0.66666666666666663*_DB_UU_U1U1*_gammaI_U1U2[ijk]*_gamma_D1D1[ijk] - 
0.66666666666666663*_DB_UU_U1U2*_gammaI_U1U2[ijk]*_gamma_D1D2[ijk] + 
_DB_UU_U1U2 - 0.66666666666666663*_DB_UU_U2U0*_gammaI_U1U2[ijk]*
_gamma_D0D2[ijk] - 0.66666666666666663*_DB_UU_U2U1*_gammaI_U1U2[ijk]*
_gamma_D1D2[ijk] + _DB_UU_U2U1 - 0.66666666666666663*_DB_UU_U2U2*
_gammaI_U1U2[ijk]*_gamma_D2D2[ijk];

    double _LV_UU_U1U1 = 
-0.66666666666666663*_DB_UU_U0U0*_gammaI_U1U1[ijk]*_gamma_D0D0[ijk] - 
0.66666666666666663*_DB_UU_U0U1*_gammaI_U1U1[ijk]*_gamma_D0D1[ijk] - 
0.66666666666666663*_DB_UU_U0U2*_gammaI_U1U1[ijk]*_gamma_D0D2[ijk] - 
0.66666666666666663*_DB_UU_U1U0*_gammaI_U1U1[ijk]*_gamma_D0D1[ijk] - 
0.66666666666666663*_DB_UU_U1U1*_gammaI_U1U1[ijk]*_gamma_D1D1[ijk] + 2*
_DB_UU_U1U1 - 0.66666666666666663*_DB_UU_U1U2*_gammaI_U1U1[ijk]*
_gamma_D1D2[ijk] - 0.66666666666666663*_DB_UU_U2U0*_gammaI_U1U1[ijk]*
_gamma_D0D2[ijk] - 0.66666666666666663*_DB_UU_U2U1*_gammaI_U1U1[ijk]*
_gamma_D1D2[ijk] - 0.66666666666666663*_DB_UU_U2U2*_gammaI_U1U1[ijk]*
_gamma_D2D2[ijk];

    double _A_UUij_U2U2 = 
(1.0/2.0)*_LV_UU_U2U2*psi7/eta[ijk];

    double _A_UUij_U1U2 = 
(1.0/2.0)*_LV_UU_U1U2*psi7/eta[ijk];

    double _A_UUij_U1U1 = 
(1.0/2.0)*_LV_UU_U1U1*psi7/eta[ijk];

    double _A_UUij_U0U2 = 
(1.0/2.0)*_LV_UU_U0U2*psi7/eta[ijk];

    double _A_UUij_U0U1 = 
(1.0/2.0)*_LV_UU_U0U1*psi7/eta[ijk];

    double _A_UUij_U0U0 = 
(1.0/2.0)*_LV_UU_U0U0*psi7/eta[ijk];

    double _AijAij = 
pow(_A_UUij_U0U0, 2)*pow(_gamma_D0D0[ijk], 2) + 4.0*_A_UUij_U0U0*
_A_UUij_U0U1*_gamma_D0D0[ijk]*_gamma_D0D1[ijk] + 4.0*_A_UUij_U0U0*
_A_UUij_U0U2*_gamma_D0D0[ijk]*_gamma_D0D2[ijk] + 2.0*_A_UUij_U0U0*
_A_UUij_U1U1*pow(_gamma_D0D1[ijk], 2) + 4.0*_A_UUij_U0U0*_A_UUij_U1U2*
_gamma_D0D1[ijk]*_gamma_D0D2[ijk] + 2.0*_A_UUij_U0U0*_A_UUij_U2U2*
pow(_gamma_D0D2[ijk], 2) + 2.0*pow(_A_UUij_U0U1, 2)*_gamma_D0D0[ijk]*
_gamma_D1D1[ijk] + 2.0*pow(_A_UUij_U0U1, 2)*pow(_gamma_D0D1[ijk], 2) +
4.0*_A_UUij_U0U1*_A_UUij_U0U2*_gamma_D0D0[ijk]*_gamma_D1D2[ijk] + 4.0*
_A_UUij_U0U1*_A_UUij_U0U2*_gamma_D0D1[ijk]*_gamma_D0D2[ijk] + 4.0*
_A_UUij_U0U1*_A_UUij_U1U1*_gamma_D0D1[ijk]*_gamma_D1D1[ijk] + 4.0*
_A_UUij_U0U1*_A_UUij_U1U2*_gamma_D0D1[ijk]*_gamma_D1D2[ijk] + 4.0*
_A_UUij_U0U1*_A_UUij_U1U2*_gamma_D0D2[ijk]*_gamma_D1D1[ijk] + 4.0*
_A_UUij_U0U1*_A_UUij_U2U2*_gamma_D0D2[ijk]*_gamma_D1D2[ijk] + 2.0*
pow(_A_UUij_U0U2, 2)*_gamma_D0D0[ijk]*_gamma_D2D2[ijk] + 2.0*
pow(_A_UUij_U0U2, 2)*pow(_gamma_D0D2[ijk], 2) + 4.0*_A_UUij_U0U2*
_A_UUij_U1U1*_gamma_D0D1[ijk]*_gamma_D1D2[ijk] + 4.0*_A_UUij_U0U2*
_A_UUij_U1U2*_gamma_D0D1[ijk]*_gamma_D2D2[ijk] + 4.0*_A_UUij_U0U2*
_A_UUij_U1U2*_gamma_D0D2[ijk]*_gamma_D1D2[ijk] + 4.0*_A_UUij_U0U2*
_A_UUij_U2U2*_gamma_D0D2[ijk]*_gamma_D2D2[ijk] + pow(_A_UUij_U1U1, 2)*
pow(_gamma_D1D1[ijk], 2) + 4.0*_A_UUij_U1U1*_A_UUij_U1U2*
_gamma_D1D1[ijk]*_gamma_D1D2[ijk] + 2.0*_A_UUij_U1U1*_A_UUij_U2U2*
pow(_gamma_D1D2[ijk], 2) + 2.0*pow(_A_UUij_U1U2, 2)*_gamma_D1D1[ijk]*
_gamma_D2D2[ijk] + 2.0*pow(_A_UUij_U1U2, 2)*pow(_gamma_D1D2[ijk], 2) +
4.0*_A_UUij_U1U2*_A_UUij_U2U2*_gamma_D1D2[ijk]*_gamma_D2D2[ijk] +
pow(_A_UUij_U2U2, 2)*pow(_gamma_D2D2[ijk], 2);


    /* populating: */
    _A_UiUj_U2U2[ijk] = _A_UUij_U2U2;
    _A_UiUj_U1U2[ijk] = _A_UUij_U1U2;
    _A_UiUj_U1U1[ijk] = _A_UUij_U1U1;
    _A_UiUj_U0U2[ijk] = _A_UUij_U0U2;
    _A_UiUj_U0U1[ijk] = _A_UUij_U0U1;
    _A_UiUj_U0U0[ijk] = _A_UUij_U0U0;

    /* populating: */
    _LBij_U0U1[ijk] = _LV_UU_U0U1;
    _LBij_U0U0[ijk] = _LV_UU_U0U0;
    _LBij_U0U2[ijk] = _LV_UU_U0U2;
    _LBij_U1U1[ijk] = _LV_UU_U1U1;
    _LBij_U1U2[ijk] = _LV_UU_U1U2;
    _LBij_U2U2[ijk] = _LV_UU_U2U2;
    _Aij2[ijk] = _AijAij;
    }/*end of for(ijk = 0; ijk < nn; ++ijk)*/
  add_field_NoMem_and_declare_field(_dLBij_U2U2D2)
  add_field_NoMem_and_declare_field(_dLBij_U2U2D0)
  add_field_NoMem_and_declare_field(_dLBij_U2U2D1)
  add_field_NoMem_and_declare_field(_dLBij_U1U1D2)
  add_field_NoMem_and_declare_field(_dLBij_U1U1D0)
  add_field_NoMem_and_declare_field(_dLBij_U1U1D1)
  add_field_NoMem_and_declare_field(_dLBij_U0U0D2)
  add_field_NoMem_and_declare_field(_dLBij_U0U0D0)
  add_field_NoMem_and_declare_field(_dLBij_U0U0D1)
  add_field_NoMem_and_declare_field(_dLBij_U0U1D2)
  add_field_NoMem_and_declare_field(_dLBij_U0U1D1)
  add_field_NoMem_and_declare_field(_dLBij_U0U1D0)
  add_field_NoMem_and_declare_field(_dLBij_U1U2D1)
  add_field_NoMem_and_declare_field(_dLBij_U1U2D0)
  add_field_NoMem_and_declare_field(_dLBij_U1U2D2)
  add_field_NoMem_and_declare_field(_dLBij_U0U2D0)
  add_field_NoMem_and_declare_field(_dLBij_U0U2D1)
  add_field_NoMem_and_declare_field(_dLBij_U0U2D2)
  Field_T *f_LBij_U2U2 = patch->pool[Ind("_LBij_U2U2")];
  Field_T *f_LBij_U1U2 = patch->pool[Ind("_LBij_U1U2")];
  Field_T *f_LBij_U1U1 = patch->pool[Ind("_LBij_U1U1")];
  Field_T *f_LBij_U0U2 = patch->pool[Ind("_LBij_U0U2")];
  Field_T *f_LBij_U0U1 = patch->pool[Ind("_LBij_U0U1")];
  Field_T *f_LBij_U0U0 = patch->pool[Ind("_LBij_U0U0")];
  f_dLBij_U2U2D2->v = Partial_Derivative(f_LBij_U2U2,"z");
  f_dLBij_U2U2D0->v = Partial_Derivative(f_LBij_U2U2,"x");
  f_dLBij_U2U2D1->v = Partial_Derivative(f_LBij_U2U2,"y");
  f_dLBij_U1U1D2->v = Partial_Derivative(f_LBij_U1U1,"z");
  f_dLBij_U1U1D0->v = Partial_Derivative(f_LBij_U1U1,"x");
  f_dLBij_U1U1D1->v = Partial_Derivative(f_LBij_U1U1,"y");
  f_dLBij_U0U0D2->v = Partial_Derivative(f_LBij_U0U0,"z");
  f_dLBij_U0U0D0->v = Partial_Derivative(f_LBij_U0U0,"x");
  f_dLBij_U0U0D1->v = Partial_Derivative(f_LBij_U0U0,"y");
  f_dLBij_U0U1D2->v = Partial_Derivative(f_LBij_U0U1,"z");
  f_dLBij_U0U1D1->v = Partial_Derivative(f_LBij_U0U1,"y");
  f_dLBij_U0U1D0->v = Partial_Derivative(f_LBij_U0U1,"x");
  f_dLBij_U1U2D1->v = Partial_Derivative(f_LBij_U1U2,"y");
  f_dLBij_U1U2D0->v = Partial_Derivative(f_LBij_U1U2,"x");
  f_dLBij_U1U2D2->v = Partial_Derivative(f_LBij_U1U2,"z");
  f_dLBij_U0U2D0->v = Partial_Derivative(f_LBij_U0U2,"x");
  f_dLBij_U0U2D1->v = Partial_Derivative(f_LBij_U0U2,"y");
  f_dLBij_U0U2D2->v = Partial_Derivative(f_LBij_U0U2,"z");
  GET_FIELD(_dLBij_U2U2D2)
  GET_FIELD(_dLBij_U2U2D0)
  GET_FIELD(_dLBij_U2U2D1)
  GET_FIELD(_dLBij_U1U1D2)
  GET_FIELD(_dLBij_U1U1D0)
  GET_FIELD(_dLBij_U1U1D1)
  GET_FIELD(_dLBij_U0U0D2)
  GET_FIELD(_dLBij_U0U0D0)
  GET_FIELD(_dLBij_U0U0D1)
  GET_FIELD(_dLBij_U0U1D2)
  GET_FIELD(_dLBij_U0U1D1)
  GET_FIELD(_dLBij_U0U1D0)
  GET_FIELD(_dLBij_U1U2D1)
  GET_FIELD(_dLBij_U1U2D0)
  GET_FIELD(_dLBij_U1U2D2)
  GET_FIELD(_dLBij_U0U2D0)
  GET_FIELD(_dLBij_U0U2D1)
  GET_FIELD(_dLBij_U0U2D2)
    for(ijk = 0; ijk < nn; ++ijk)
    {
    double psi7_ = 
pow(psi[ijk], 7);

    double dLnOf_alpha__U2 = 
deta_D2[ijk]/eta[ijk] - 7*dpsi_D2[ijk]/psi[ijk];

    double dLnOf_alpha__U0 = 
deta_D0[ijk]/eta[ijk] - 7*dpsi_D0[ijk]/psi[ijk];

    double dLnOf_alpha__U1 = 
deta_D1[ijk]/eta[ijk] - 7*dpsi_D1[ijk]/psi[ijk];

    double dlAij_U0U1D2 = 
-1.0/2.0*psi7_*(_LBij_U0U1[ijk]*dLnOf_alpha__U2 - _dLBij_U0U1D2[ijk])/
eta[ijk];

    double dlAij_U0U0D2 = 
-1.0/2.0*psi7_*(_LBij_U0U0[ijk]*dLnOf_alpha__U2 - _dLBij_U0U0D2[ijk])/
eta[ijk];

    double dlAij_U0U0D1 = 
-1.0/2.0*psi7_*(_LBij_U0U0[ijk]*dLnOf_alpha__U1 - _dLBij_U0U0D1[ijk])/
eta[ijk];

    double dlAij_U0U1D1 = 
-1.0/2.0*psi7_*(_LBij_U0U1[ijk]*dLnOf_alpha__U1 - _dLBij_U0U1D1[ijk])/
eta[ijk];

    double dlAij_U0U0D0 = 
-1.0/2.0*psi7_*(_LBij_U0U0[ijk]*dLnOf_alpha__U0 - _dLBij_U0U0D0[ijk])/
eta[ijk];

    double dlAij_U1U2D0 = 
-1.0/2.0*psi7_*(_LBij_U1U2[ijk]*dLnOf_alpha__U0 - _dLBij_U1U2D0[ijk])/
eta[ijk];

    double dlAij_U0U1D0 = 
-1.0/2.0*psi7_*(_LBij_U0U1[ijk]*dLnOf_alpha__U0 - _dLBij_U0U1D0[ijk])/
eta[ijk];

    double dlAij_U1U2D2 = 
-1.0/2.0*psi7_*(_LBij_U1U2[ijk]*dLnOf_alpha__U2 - _dLBij_U1U2D2[ijk])/
eta[ijk];

    double dlAij_U1U2D1 = 
-1.0/2.0*psi7_*(_LBij_U1U2[ijk]*dLnOf_alpha__U1 - _dLBij_U1U2D1[ijk])/
eta[ijk];

    double dlAij_U0U2D1 = 
-1.0/2.0*psi7_*(_LBij_U0U2[ijk]*dLnOf_alpha__U1 - _dLBij_U0U2D1[ijk])/
eta[ijk];

    double dlAij_U0U2D0 = 
-1.0/2.0*psi7_*(_LBij_U0U2[ijk]*dLnOf_alpha__U0 - _dLBij_U0U2D0[ijk])/
eta[ijk];

    double dlAij_U0U2D2 = 
-1.0/2.0*psi7_*(_LBij_U0U2[ijk]*dLnOf_alpha__U2 - _dLBij_U0U2D2[ijk])/
eta[ijk];

    double dlAij_U2U2D2 = 
-1.0/2.0*psi7_*(_LBij_U2U2[ijk]*dLnOf_alpha__U2 - _dLBij_U2U2D2[ijk])/
eta[ijk];

    double dlAij_U1U1D2 = 
-1.0/2.0*psi7_*(_LBij_U1U1[ijk]*dLnOf_alpha__U2 - _dLBij_U1U1D2[ijk])/
eta[ijk];

    double dlAij_U1U1D1 = 
-1.0/2.0*psi7_*(_LBij_U1U1[ijk]*dLnOf_alpha__U1 - _dLBij_U1U1D1[ijk])/
eta[ijk];

    double dlAij_U1U1D0 = 
-1.0/2.0*psi7_*(_LBij_U1U1[ijk]*dLnOf_alpha__U0 - _dLBij_U1U1D0[ijk])/
eta[ijk];

    double dlAij_U2U2D0 = 
-1.0/2.0*psi7_*(_LBij_U2U2[ijk]*dLnOf_alpha__U0 - _dLBij_U2U2D0[ijk])/
eta[ijk];

    double dlAij_U2U2D1 = 
-1.0/2.0*psi7_*(_LBij_U2U2[ijk]*dLnOf_alpha__U1 - _dLBij_U2U2D1[ijk])/
eta[ijk];


    /* populating: */
    _dA_UiUj_U2U2D2[ijk] = dlAij_U2U2D2;
    _dA_UiUj_U2U2D0[ijk] = dlAij_U2U2D0;
    _dA_UiUj_U2U2D1[ijk] = dlAij_U2U2D1;
    _dA_UiUj_U1U1D2[ijk] = dlAij_U1U1D2;
    _dA_UiUj_U1U1D0[ijk] = dlAij_U1U1D0;
    _dA_UiUj_U1U1D1[ijk] = dlAij_U1U1D1;
    _dA_UiUj_U0U0D2[ijk] = dlAij_U0U0D2;
    _dA_UiUj_U0U0D0[ijk] = dlAij_U0U0D0;
    _dA_UiUj_U0U0D1[ijk] = dlAij_U0U0D1;
    _dA_UiUj_U0U1D2[ijk] = dlAij_U0U1D2;
    _dA_UiUj_U0U1D1[ijk] = dlAij_U0U1D1;
    _dA_UiUj_U0U1D0[ijk] = dlAij_U0U1D0;
    _dA_UiUj_U1U2D1[ijk] = dlAij_U1U2D1;
    _dA_UiUj_U1U2D0[ijk] = dlAij_U1U2D0;
    _dA_UiUj_U1U2D2[ijk] = dlAij_U1U2D2;
    _dA_UiUj_U0U2D0[ijk] = dlAij_U0U2D0;
    _dA_UiUj_U0U2D1[ijk] = dlAij_U0U2D1;
    _dA_UiUj_U0U2D2[ijk] = dlAij_U0U2D2;
    }
  REMOVE_FIELD(f_LBij_U0U1)
  REMOVE_FIELD(f_LBij_U0U0)
  REMOVE_FIELD(f_LBij_U0U2)
  REMOVE_FIELD(f_LBij_U1U1)
  REMOVE_FIELD(f_LBij_U1U2)
  REMOVE_FIELD(f_LBij_U2U2)
  REMOVE_FIELD(f_dLBij_U2U2D2)
  REMOVE_FIELD(f_dLBij_U2U2D0)
  REMOVE_FIELD(f_dLBij_U2U2D1)
  REMOVE_FIELD(f_dLBij_U1U1D2)
  REMOVE_FIELD(f_dLBij_U1U1D0)
  REMOVE_FIELD(f_dLBij_U1U1D1)
  REMOVE_FIELD(f_dLBij_U0U0D2)
  REMOVE_FIELD(f_dLBij_U0U0D0)
  REMOVE_FIELD(f_dLBij_U0U0D1)
  REMOVE_FIELD(f_dLBij_U0U1D2)
  REMOVE_FIELD(f_dLBij_U0U1D1)
  REMOVE_FIELD(f_dLBij_U0U1D0)
  REMOVE_FIELD(f_dLBij_U1U2D1)
  REMOVE_FIELD(f_dLBij_U1U2D0)
  REMOVE_FIELD(f_dLBij_U1U2D2)
  REMOVE_FIELD(f_dLBij_U0U2D0)
  REMOVE_FIELD(f_dLBij_U0U2D1)
  REMOVE_FIELD(f_dLBij_U0U2D2)
}
