/*
  These C codes generated by Cpi version 2.0
  Copyright (C) 2019-2020 Alireza Rashti.
*/


#include "bbn_headers.h"


void bbn_free_date_dGammaConf(Patch_T *const patch);
void bbn_free_date_dGammaConf(Patch_T *const patch)
{
  bbn_free_data_dg_analytic(patch,bbn_ks_read_analytic,patch);
  bbn_free_data_ddg_analytic(patch,bbn_ks_read_analytic,patch);


  /* declaring: */
  READ_v(_gammaI_U0U2)
  READ_v(_gammaI_U0U0)
  READ_v(_gammaI_U0U1)
  READ_v(_gammaI_U1U2)
  READ_v(_gammaI_U1U1)
  READ_v(_gammaI_U2U2)
  READ_v(_dgamma_D0D0D1)
  READ_v(_dgamma_D0D0D0)
  READ_v(_dgamma_D2D2D2)
  READ_v(_dgamma_D0D0D2)
  READ_v(_dgamma_D0D2D1)
  READ_v(_dgamma_D1D1D0)
  READ_v(_dgamma_D1D1D2)
  READ_v(_dgamma_D2D2D0)
  READ_v(_dgamma_D2D2D1)
  READ_v(_dgamma_D0D1D0)
  READ_v(_dgamma_D0D1D1)
  READ_v(_dgamma_D0D1D2)
  READ_v(_dgamma_D0D2D0)
  READ_v(_dgamma_D1D1D1)
  READ_v(_dgamma_D1D2D1)
  READ_v(_dgamma_D1D2D2)
  READ_v(_dgamma_D1D2D0)
  READ_v(_dgamma_D0D2D2)
  READ_v(_ddgamma_D0D1D1D0)
  READ_v(_ddgamma_D0D1D1D1)
  READ_v(_ddgamma_D0D1D1D2)
  READ_v(_ddgamma_D2D2D1D2)
  READ_v(_ddgamma_D2D2D0D2)
  READ_v(_ddgamma_D1D2D0D2)
  READ_v(_ddgamma_D1D2D0D1)
  READ_v(_ddgamma_D1D2D0D0)
  READ_v(_ddgamma_D1D1D0D0)
  READ_v(_ddgamma_D1D2D2D1)
  READ_v(_ddgamma_D1D2D2D0)
  READ_v(_ddgamma_D2D2D1D0)
  READ_v(_ddgamma_D1D1D0D1)
  READ_v(_ddgamma_D2D2D0D0)
  READ_v(_ddgamma_D2D2D2D2)
  READ_v(_ddgamma_D2D2D2D0)
  READ_v(_ddgamma_D2D2D2D1)
  READ_v(_ddgamma_D0D1D2D2)
  READ_v(_ddgamma_D0D1D2D1)
  READ_v(_ddgamma_D0D1D2D0)
  READ_v(_ddgamma_D1D2D1D2)
  READ_v(_ddgamma_D1D2D2D2)
  READ_v(_ddgamma_D0D1D0D1)
  READ_v(_ddgamma_D0D1D0D0)
  READ_v(_ddgamma_D0D1D0D2)
  READ_v(_ddgamma_D0D0D1D1)
  READ_v(_ddgamma_D0D0D1D0)
  READ_v(_ddgamma_D1D1D0D2)
  READ_v(_ddgamma_D0D0D1D2)
  READ_v(_ddgamma_D0D2D0D2)
  READ_v(_ddgamma_D0D0D0D0)
  READ_v(_ddgamma_D0D0D0D1)
  READ_v(_ddgamma_D0D2D0D0)
  READ_v(_ddgamma_D0D2D0D1)
  READ_v(_ddgamma_D1D1D2D2)
  READ_v(_ddgamma_D0D0D0D2)
  READ_v(_ddgamma_D1D1D2D0)
  READ_v(_ddgamma_D1D1D2D1)
  READ_v(_ddgamma_D0D0D2D2)
  READ_v(_ddgamma_D2D2D0D1)
  READ_v(_ddgamma_D0D0D2D0)
  READ_v(_ddgamma_D0D0D2D1)
  READ_v(_ddgamma_D1D1D1D1)
  READ_v(_ddgamma_D0D2D1D2)
  READ_v(_ddgamma_D0D2D1D1)
  READ_v(_ddgamma_D0D2D1D0)
  READ_v(_ddgamma_D1D1D1D0)
  READ_v(_ddgamma_D1D2D1D0)
  READ_v(_ddgamma_D1D2D1D1)
  READ_v(_ddgamma_D2D2D1D1)
  READ_v(_ddgamma_D0D2D2D0)
  READ_v(_ddgamma_D0D2D2D1)
  READ_v(_ddgamma_D0D2D2D2)
  READ_v(_ddgamma_D1D1D1D2)
  REALLOC_v_WRITE_v(_dGamma_U2D2D2D2)
  REALLOC_v_WRITE_v(_dGamma_U2D2D2D0)
  REALLOC_v_WRITE_v(_dGamma_U2D2D2D1)
  REALLOC_v_WRITE_v(_dGamma_U2D0D0D2)
  REALLOC_v_WRITE_v(_dGamma_U1D1D2D2)
  REALLOC_v_WRITE_v(_dGamma_U2D0D0D0)
  REALLOC_v_WRITE_v(_dGamma_U1D1D2D0)
  REALLOC_v_WRITE_v(_dGamma_U1D1D2D1)
  REALLOC_v_WRITE_v(_dGamma_U2D1D1D0)
  REALLOC_v_WRITE_v(_dGamma_U2D0D0D1)
  REALLOC_v_WRITE_v(_dGamma_U2D0D2D1)
  REALLOC_v_WRITE_v(_dGamma_U1D0D1D0)
  REALLOC_v_WRITE_v(_dGamma_U1D0D1D1)
  REALLOC_v_WRITE_v(_dGamma_U1D0D1D2)
  REALLOC_v_WRITE_v(_dGamma_U1D2D2D1)
  REALLOC_v_WRITE_v(_dGamma_U1D0D0D1)
  REALLOC_v_WRITE_v(_dGamma_U1D0D0D0)
  REALLOC_v_WRITE_v(_dGamma_U1D0D0D2)
  REALLOC_v_WRITE_v(_dGamma_U0D1D2D2)
  REALLOC_v_WRITE_v(_dGamma_U0D1D2D1)
  REALLOC_v_WRITE_v(_dGamma_U0D1D2D0)
  REALLOC_v_WRITE_v(_dGamma_U2D0D2D0)
  REALLOC_v_WRITE_v(_dGamma_U1D0D2D2)
  REALLOC_v_WRITE_v(_dGamma_U1D0D2D1)
  REALLOC_v_WRITE_v(_dGamma_U1D0D2D0)
  REALLOC_v_WRITE_v(_dGamma_U2D1D1D2)
  REALLOC_v_WRITE_v(_dGamma_U2D0D2D2)
  REALLOC_v_WRITE_v(_dGamma_U0D0D1D0)
  REALLOC_v_WRITE_v(_dGamma_U1D2D2D0)
  REALLOC_v_WRITE_v(_dGamma_U2D1D2D1)
  REALLOC_v_WRITE_v(_dGamma_U2D0D1D2)
  REALLOC_v_WRITE_v(_dGamma_U2D0D1D1)
  REALLOC_v_WRITE_v(_dGamma_U2D0D1D0)
  REALLOC_v_WRITE_v(_dGamma_U2D1D2D2)
  REALLOC_v_WRITE_v(_dGamma_U0D1D1D0)
  REALLOC_v_WRITE_v(_dGamma_U0D1D1D1)
  REALLOC_v_WRITE_v(_dGamma_U0D1D1D2)
  REALLOC_v_WRITE_v(_dGamma_U1D2D2D2)
  REALLOC_v_WRITE_v(_dGamma_U1D1D1D1)
  REALLOC_v_WRITE_v(_dGamma_U1D1D1D0)
  REALLOC_v_WRITE_v(_dGamma_U1D1D1D2)
  REALLOC_v_WRITE_v(_dGamma_U0D0D1D1)
  REALLOC_v_WRITE_v(_dGamma_U0D0D2D2)
  REALLOC_v_WRITE_v(_dGamma_U0D0D2D0)
  REALLOC_v_WRITE_v(_dGamma_U0D0D2D1)
  REALLOC_v_WRITE_v(_dGamma_U2D1D2D0)
  REALLOC_v_WRITE_v(_dGamma_U0D0D0D0)
  REALLOC_v_WRITE_v(_dGamma_U0D0D0D1)
  REALLOC_v_WRITE_v(_dGamma_U0D0D0D2)
  REALLOC_v_WRITE_v(_dGamma_U2D1D1D1)
  REALLOC_v_WRITE_v(_dGamma_U0D2D2D0)
  REALLOC_v_WRITE_v(_dGamma_U0D2D2D1)
  REALLOC_v_WRITE_v(_dGamma_U0D2D2D2)
  REALLOC_v_WRITE_v(_dGamma_U0D0D1D2)


  const unsigned nn = patch->nn;
  unsigned ijk;
  for(ijk = 0; ijk < nn; ++ijk)
  {
  double dgI_U0U1D0 = 
-_dgamma_D0D0D0[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U1[ijk] - 
_dgamma_D0D1D0[ijk]*_gammaI_U0U0[ijk]*_gammaI_U1U1[ijk] - 
_dgamma_D0D1D0[ijk]*pow(_gammaI_U0U1[ijk], 2) - _dgamma_D0D2D0[ijk]*
_gammaI_U0U0[ijk]*_gammaI_U1U2[ijk] - _dgamma_D0D2D0[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - _dgamma_D1D1D0[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U1U1[ijk] - _dgamma_D1D2D0[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - _dgamma_D1D2D0[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U1U1[ijk] - _dgamma_D2D2D0[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk];

  double dgI_U0U1D1 = 
-_dgamma_D0D0D1[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U1[ijk] - 
_dgamma_D0D1D1[ijk]*_gammaI_U0U0[ijk]*_gammaI_U1U1[ijk] - 
_dgamma_D0D1D1[ijk]*pow(_gammaI_U0U1[ijk], 2) - _dgamma_D0D2D1[ijk]*
_gammaI_U0U0[ijk]*_gammaI_U1U2[ijk] - _dgamma_D0D2D1[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - _dgamma_D1D1D1[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U1U1[ijk] - _dgamma_D1D2D1[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - _dgamma_D1D2D1[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U1U1[ijk] - _dgamma_D2D2D1[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk];

  double dgI_U0U1D2 = 
-_dgamma_D0D0D2[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U1[ijk] - 
_dgamma_D0D1D2[ijk]*_gammaI_U0U0[ijk]*_gammaI_U1U1[ijk] - 
_dgamma_D0D1D2[ijk]*pow(_gammaI_U0U1[ijk], 2) - _dgamma_D0D2D2[ijk]*
_gammaI_U0U0[ijk]*_gammaI_U1U2[ijk] - _dgamma_D0D2D2[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - _dgamma_D1D1D2[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U1U1[ijk] - _dgamma_D1D2D2[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - _dgamma_D1D2D2[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U1U1[ijk] - _dgamma_D2D2D2[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk];

  double dgI_U0U2D0 = 
-_dgamma_D0D0D0[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D0D1D0[ijk]*_gammaI_U0U0[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D0D1D0[ijk]*_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D0D2D0[ijk]*_gammaI_U0U0[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D0D2D0[ijk]*pow(_gammaI_U0U2[ijk], 2) - _dgamma_D1D1D0[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - _dgamma_D1D2D0[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U2U2[ijk] - _dgamma_D1D2D0[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk] - _dgamma_D2D2D0[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U2U2[ijk];

  double dgI_U2U2D1 = 
-_dgamma_D0D0D1[ijk]*pow(_gammaI_U0U2[ijk], 2) - 2.0*
_dgamma_D0D1D1[ijk]*_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk] - 2.0*
_dgamma_D0D2D1[ijk]*_gammaI_U0U2[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D1D1D1[ijk]*pow(_gammaI_U1U2[ijk], 2) - 2.0*
_dgamma_D1D2D1[ijk]*_gammaI_U1U2[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D2D2D1[ijk]*pow(_gammaI_U2U2[ijk], 2);

  double dgI_U2U2D0 = 
-_dgamma_D0D0D0[ijk]*pow(_gammaI_U0U2[ijk], 2) - 2.0*
_dgamma_D0D1D0[ijk]*_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk] - 2.0*
_dgamma_D0D2D0[ijk]*_gammaI_U0U2[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D1D1D0[ijk]*pow(_gammaI_U1U2[ijk], 2) - 2.0*
_dgamma_D1D2D0[ijk]*_gammaI_U1U2[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D2D2D0[ijk]*pow(_gammaI_U2U2[ijk], 2);

  double dgI_U0U2D2 = 
-_dgamma_D0D0D2[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D0D1D2[ijk]*_gammaI_U0U0[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D0D1D2[ijk]*_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D0D2D2[ijk]*_gammaI_U0U0[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D0D2D2[ijk]*pow(_gammaI_U0U2[ijk], 2) - _dgamma_D1D1D2[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - _dgamma_D1D2D2[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U2U2[ijk] - _dgamma_D1D2D2[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk] - _dgamma_D2D2D2[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U2U2[ijk];

  double dgI_U2U2D2 = 
-_dgamma_D0D0D2[ijk]*pow(_gammaI_U0U2[ijk], 2) - 2.0*
_dgamma_D0D1D2[ijk]*_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk] - 2.0*
_dgamma_D0D2D2[ijk]*_gammaI_U0U2[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D1D1D2[ijk]*pow(_gammaI_U1U2[ijk], 2) - 2.0*
_dgamma_D1D2D2[ijk]*_gammaI_U1U2[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D2D2D2[ijk]*pow(_gammaI_U2U2[ijk], 2);

  double dgI_U0U2D1 = 
-_dgamma_D0D0D1[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D0D1D1[ijk]*_gammaI_U0U0[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D0D1D1[ijk]*_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D0D2D1[ijk]*_gammaI_U0U0[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D0D2D1[ijk]*pow(_gammaI_U0U2[ijk], 2) - _dgamma_D1D1D1[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - _dgamma_D1D2D1[ijk]*
_gammaI_U0U1[ijk]*_gammaI_U2U2[ijk] - _dgamma_D1D2D1[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk] - _dgamma_D2D2D1[ijk]*
_gammaI_U0U2[ijk]*_gammaI_U2U2[ijk];

  double dgI_U0U0D1 = 
-_dgamma_D0D0D1[ijk]*pow(_gammaI_U0U0[ijk], 2) - 2.0*
_dgamma_D0D1D1[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U1[ijk] - 2.0*
_dgamma_D0D2D1[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D1D1D1[ijk]*pow(_gammaI_U0U1[ijk], 2) - 2.0*
_dgamma_D1D2D1[ijk]*_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D2D2D1[ijk]*pow(_gammaI_U0U2[ijk], 2);

  double dgI_U0U0D0 = 
-_dgamma_D0D0D0[ijk]*pow(_gammaI_U0U0[ijk], 2) - 2.0*
_dgamma_D0D1D0[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U1[ijk] - 2.0*
_dgamma_D0D2D0[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D1D1D0[ijk]*pow(_gammaI_U0U1[ijk], 2) - 2.0*
_dgamma_D1D2D0[ijk]*_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D2D2D0[ijk]*pow(_gammaI_U0U2[ijk], 2);

  double dgI_U0U0D2 = 
-_dgamma_D0D0D2[ijk]*pow(_gammaI_U0U0[ijk], 2) - 2.0*
_dgamma_D0D1D2[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U1[ijk] - 2.0*
_dgamma_D0D2D2[ijk]*_gammaI_U0U0[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D1D1D2[ijk]*pow(_gammaI_U0U1[ijk], 2) - 2.0*
_dgamma_D1D2D2[ijk]*_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D2D2D2[ijk]*pow(_gammaI_U0U2[ijk], 2);

  double dgI_U1U2D2 = 
-_dgamma_D0D0D2[ijk]*_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D0D1D2[ijk]*_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D0D1D2[ijk]*_gammaI_U0U2[ijk]*_gammaI_U1U1[ijk] - 
_dgamma_D0D2D2[ijk]*_gammaI_U0U1[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D0D2D2[ijk]*_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D1D1D2[ijk]*_gammaI_U1U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D1D2D2[ijk]*_gammaI_U1U1[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D1D2D2[ijk]*pow(_gammaI_U1U2[ijk], 2) - _dgamma_D2D2D2[ijk]*
_gammaI_U1U2[ijk]*_gammaI_U2U2[ijk];

  double dgI_U1U2D0 = 
-_dgamma_D0D0D0[ijk]*_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D0D1D0[ijk]*_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D0D1D0[ijk]*_gammaI_U0U2[ijk]*_gammaI_U1U1[ijk] - 
_dgamma_D0D2D0[ijk]*_gammaI_U0U1[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D0D2D0[ijk]*_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D1D1D0[ijk]*_gammaI_U1U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D1D2D0[ijk]*_gammaI_U1U1[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D1D2D0[ijk]*pow(_gammaI_U1U2[ijk], 2) - _dgamma_D2D2D0[ijk]*
_gammaI_U1U2[ijk]*_gammaI_U2U2[ijk];

  double dgI_U1U2D1 = 
-_dgamma_D0D0D1[ijk]*_gammaI_U0U1[ijk]*_gammaI_U0U2[ijk] - 
_dgamma_D0D1D1[ijk]*_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D0D1D1[ijk]*_gammaI_U0U2[ijk]*_gammaI_U1U1[ijk] - 
_dgamma_D0D2D1[ijk]*_gammaI_U0U1[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D0D2D1[ijk]*_gammaI_U0U2[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D1D1D1[ijk]*_gammaI_U1U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D1D2D1[ijk]*_gammaI_U1U1[ijk]*_gammaI_U2U2[ijk] - 
_dgamma_D1D2D1[ijk]*pow(_gammaI_U1U2[ijk], 2) - _dgamma_D2D2D1[ijk]*
_gammaI_U1U2[ijk]*_gammaI_U2U2[ijk];

  double dgI_U1U1D1 = 
-_dgamma_D0D0D1[ijk]*pow(_gammaI_U0U1[ijk], 2) - 2.0*
_dgamma_D0D1D1[ijk]*_gammaI_U0U1[ijk]*_gammaI_U1U1[ijk] - 2.0*
_dgamma_D0D2D1[ijk]*_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D1D1D1[ijk]*pow(_gammaI_U1U1[ijk], 2) - 2.0*
_dgamma_D1D2D1[ijk]*_gammaI_U1U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D2D2D1[ijk]*pow(_gammaI_U1U2[ijk], 2);

  double dgI_U1U1D0 = 
-_dgamma_D0D0D0[ijk]*pow(_gammaI_U0U1[ijk], 2) - 2.0*
_dgamma_D0D1D0[ijk]*_gammaI_U0U1[ijk]*_gammaI_U1U1[ijk] - 2.0*
_dgamma_D0D2D0[ijk]*_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D1D1D0[ijk]*pow(_gammaI_U1U1[ijk], 2) - 2.0*
_dgamma_D1D2D0[ijk]*_gammaI_U1U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D2D2D0[ijk]*pow(_gammaI_U1U2[ijk], 2);

  double dgI_U1U1D2 = 
-_dgamma_D0D0D2[ijk]*pow(_gammaI_U0U1[ijk], 2) - 2.0*
_dgamma_D0D1D2[ijk]*_gammaI_U0U1[ijk]*_gammaI_U1U1[ijk] - 2.0*
_dgamma_D0D2D2[ijk]*_gammaI_U0U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D1D1D2[ijk]*pow(_gammaI_U1U1[ijk], 2) - 2.0*
_dgamma_D1D2D2[ijk]*_gammaI_U1U1[ijk]*_gammaI_U1U2[ijk] - 
_dgamma_D2D2D2[ijk]*pow(_gammaI_U1U2[ijk], 2);

  double dGamma_U1D0D1D2 = 
0.5*_ddgamma_D0D0D1D2[ijk]*_gammaI_U0U1[ijk] + 0.5*
_ddgamma_D1D1D0D2[ijk]*_gammaI_U1U1[ijk] + 0.5*_dgamma_D0D0D1[ijk]*
dgI_U0U1D2 + 0.5*_dgamma_D1D1D0[ijk]*dgI_U1U1D2 + 0.5*
_gammaI_U1U2[ijk]*(-_ddgamma_D0D1D2D2[ijk] + _ddgamma_D0D2D1D2[ijk] + 
_ddgamma_D1D2D0D2[ijk]) + 0.5*dgI_U1U2D2*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U1D2D2D2 = 
0.5*_ddgamma_D2D2D2D2[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D2D2D2[ijk]*
dgI_U1U2D2 + 0.5*_gammaI_U0U1[ijk]*(2*_ddgamma_D0D2D2D2[ijk] - 
_ddgamma_D2D2D0D2[ijk]) + 0.5*_gammaI_U1U1[ijk]*(2*
_ddgamma_D1D2D2D2[ijk] - _ddgamma_D2D2D1D2[ijk]) + 0.5*dgI_U0U1D2*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*dgI_U1U1D2*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

  double dGamma_U1D0D1D0 = 
0.5*_ddgamma_D0D0D1D0[ijk]*_gammaI_U0U1[ijk] + 0.5*
_ddgamma_D1D1D0D0[ijk]*_gammaI_U1U1[ijk] + 0.5*_dgamma_D0D0D1[ijk]*
dgI_U0U1D0 + 0.5*_dgamma_D1D1D0[ijk]*dgI_U1U1D0 + 0.5*
_gammaI_U1U2[ijk]*(-_ddgamma_D0D1D2D0[ijk] + _ddgamma_D0D2D1D0[ijk] + 
_ddgamma_D1D2D0D0[ijk]) + 0.5*dgI_U1U2D0*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U1D0D1D1 = 
0.5*_ddgamma_D0D0D1D1[ijk]*_gammaI_U0U1[ijk] + 0.5*
_ddgamma_D1D1D0D1[ijk]*_gammaI_U1U1[ijk] + 0.5*_dgamma_D0D0D1[ijk]*
dgI_U0U1D1 + 0.5*_dgamma_D1D1D0[ijk]*dgI_U1U1D1 + 0.5*
_gammaI_U1U2[ijk]*(-_ddgamma_D0D1D2D1[ijk] + _ddgamma_D0D2D1D1[ijk] + 
_ddgamma_D1D2D0D1[ijk]) + 0.5*dgI_U1U2D1*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U0D0D2D1 = 
0.5*_ddgamma_D0D0D2D1[ijk]*_gammaI_U0U0[ijk] + 0.5*
_ddgamma_D2D2D0D1[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D0D0D2[ijk]*
dgI_U0U0D1 + 0.5*_dgamma_D2D2D0[ijk]*dgI_U0U2D1 + 0.5*
_gammaI_U0U1[ijk]*(_ddgamma_D0D1D2D1[ijk] - _ddgamma_D0D2D1D1[ijk] + 
_ddgamma_D1D2D0D1[ijk]) + 0.5*dgI_U0U1D1*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U1D0D0D2 = 
0.5*_ddgamma_D0D0D0D2[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D0D0D0[ijk]*
dgI_U0U1D2 - 0.5*_gammaI_U1U1[ijk]*(_ddgamma_D0D0D1D2[ijk] - 2*
_ddgamma_D0D1D0D2[ijk]) - 0.5*_gammaI_U1U2[ijk]*(_ddgamma_D0D0D2D2[ijk] - 
2*_ddgamma_D0D2D0D2[ijk]) - 0.5*dgI_U1U1D2*(_dgamma_D0D0D1[ijk] - 2*
_dgamma_D0D1D0[ijk]) - 0.5*dgI_U1U2D2*(_dgamma_D0D0D2[ijk] - 2*
_dgamma_D0D2D0[ijk]);

  double dGamma_U1D0D0D1 = 
0.5*_ddgamma_D0D0D0D1[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D0D0D0[ijk]*
dgI_U0U1D1 - 0.5*_gammaI_U1U1[ijk]*(_ddgamma_D0D0D1D1[ijk] - 2*
_ddgamma_D0D1D0D1[ijk]) - 0.5*_gammaI_U1U2[ijk]*(_ddgamma_D0D0D2D1[ijk] - 
2*_ddgamma_D0D2D0D1[ijk]) - 0.5*dgI_U1U1D1*(_dgamma_D0D0D1[ijk] - 2*
_dgamma_D0D1D0[ijk]) - 0.5*dgI_U1U2D1*(_dgamma_D0D0D2[ijk] - 2*
_dgamma_D0D2D0[ijk]);

  double dGamma_U1D0D0D0 = 
0.5*_ddgamma_D0D0D0D0[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D0D0D0[ijk]*
dgI_U0U1D0 - 0.5*_gammaI_U1U1[ijk]*(_ddgamma_D0D0D1D0[ijk] - 2*
_ddgamma_D0D1D0D0[ijk]) - 0.5*_gammaI_U1U2[ijk]*(_ddgamma_D0D0D2D0[ijk] - 
2*_ddgamma_D0D2D0D0[ijk]) - 0.5*dgI_U1U1D0*(_dgamma_D0D0D1[ijk] - 2*
_dgamma_D0D1D0[ijk]) - 0.5*dgI_U1U2D0*(_dgamma_D0D0D2[ijk] - 2*
_dgamma_D0D2D0[ijk]);

  double dGamma_U1D2D2D1 = 
0.5*_ddgamma_D2D2D2D1[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D2D2D2[ijk]*
dgI_U1U2D1 + 0.5*_gammaI_U0U1[ijk]*(2*_ddgamma_D0D2D2D1[ijk] - 
_ddgamma_D2D2D0D1[ijk]) + 0.5*_gammaI_U1U1[ijk]*(2*
_ddgamma_D1D2D2D1[ijk] - _ddgamma_D2D2D1D1[ijk]) + 0.5*dgI_U0U1D1*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*dgI_U1U1D1*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

  double dGamma_U1D0D2D1 = 
0.5*_ddgamma_D0D0D2D1[ijk]*_gammaI_U0U1[ijk] + 0.5*
_ddgamma_D2D2D0D1[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D0D0D2[ijk]*
dgI_U0U1D1 + 0.5*_dgamma_D2D2D0[ijk]*dgI_U1U2D1 + 0.5*
_gammaI_U1U1[ijk]*(_ddgamma_D0D1D2D1[ijk] - _ddgamma_D0D2D1D1[ijk] + 
_ddgamma_D1D2D0D1[ijk]) + 0.5*dgI_U1U1D1*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U1D0D2D0 = 
0.5*_ddgamma_D0D0D2D0[ijk]*_gammaI_U0U1[ijk] + 0.5*
_ddgamma_D2D2D0D0[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D0D0D2[ijk]*
dgI_U0U1D0 + 0.5*_dgamma_D2D2D0[ijk]*dgI_U1U2D0 + 0.5*
_gammaI_U1U1[ijk]*(_ddgamma_D0D1D2D0[ijk] - _ddgamma_D0D2D1D0[ijk] + 
_ddgamma_D1D2D0D0[ijk]) + 0.5*dgI_U1U1D0*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U1D0D2D2 = 
0.5*_ddgamma_D0D0D2D2[ijk]*_gammaI_U0U1[ijk] + 0.5*
_ddgamma_D2D2D0D2[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D0D0D2[ijk]*
dgI_U0U1D2 + 0.5*_dgamma_D2D2D0[ijk]*dgI_U1U2D2 + 0.5*
_gammaI_U1U1[ijk]*(_ddgamma_D0D1D2D2[ijk] - _ddgamma_D0D2D1D2[ijk] + 
_ddgamma_D1D2D0D2[ijk]) + 0.5*dgI_U1U1D2*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U0D1D1D2 = 
0.5*_ddgamma_D1D1D1D2[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D1D1D1[ijk]*
dgI_U0U1D2 + 0.5*_gammaI_U0U0[ijk]*(2*_ddgamma_D0D1D1D2[ijk] - 
_ddgamma_D1D1D0D2[ijk]) - 0.5*_gammaI_U0U2[ijk]*(_ddgamma_D1D1D2D2[ijk] - 
2*_ddgamma_D1D2D1D2[ijk]) + 0.5*dgI_U0U0D2*(2*_dgamma_D0D1D1[ijk] - 
_dgamma_D1D1D0[ijk]) - 0.5*dgI_U0U2D2*(_dgamma_D1D1D2[ijk] - 2*
_dgamma_D1D2D1[ijk]);

  double dGamma_U0D1D1D0 = 
0.5*_ddgamma_D1D1D1D0[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D1D1D1[ijk]*
dgI_U0U1D0 + 0.5*_gammaI_U0U0[ijk]*(2*_ddgamma_D0D1D1D0[ijk] - 
_ddgamma_D1D1D0D0[ijk]) - 0.5*_gammaI_U0U2[ijk]*(_ddgamma_D1D1D2D0[ijk] - 
2*_ddgamma_D1D2D1D0[ijk]) + 0.5*dgI_U0U0D0*(2*_dgamma_D0D1D1[ijk] - 
_dgamma_D1D1D0[ijk]) - 0.5*dgI_U0U2D0*(_dgamma_D1D1D2[ijk] - 2*
_dgamma_D1D2D1[ijk]);

  double dGamma_U0D1D1D1 = 
0.5*_ddgamma_D1D1D1D1[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D1D1D1[ijk]*
dgI_U0U1D1 + 0.5*_gammaI_U0U0[ijk]*(2*_ddgamma_D0D1D1D1[ijk] - 
_ddgamma_D1D1D0D1[ijk]) - 0.5*_gammaI_U0U2[ijk]*(_ddgamma_D1D1D2D1[ijk] - 
2*_ddgamma_D1D2D1D1[ijk]) + 0.5*dgI_U0U0D1*(2*_dgamma_D0D1D1[ijk] - 
_dgamma_D1D1D0[ijk]) - 0.5*dgI_U0U2D1*(_dgamma_D1D1D2[ijk] - 2*
_dgamma_D1D2D1[ijk]);

  double dGamma_U0D1D2D1 = 
0.5*_ddgamma_D1D1D2D1[ijk]*_gammaI_U0U1[ijk] + 0.5*
_ddgamma_D2D2D1D1[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D1D1D2[ijk]*
dgI_U0U1D1 + 0.5*_dgamma_D2D2D1[ijk]*dgI_U0U2D1 + 0.5*
_gammaI_U0U0[ijk]*(_ddgamma_D0D1D2D1[ijk] + _ddgamma_D0D2D1D1[ijk] - 
_ddgamma_D1D2D0D1[ijk]) + 0.5*dgI_U0U0D1*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);

  double dGamma_U0D1D2D0 = 
0.5*_ddgamma_D1D1D2D0[ijk]*_gammaI_U0U1[ijk] + 0.5*
_ddgamma_D2D2D1D0[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D1D1D2[ijk]*
dgI_U0U1D0 + 0.5*_dgamma_D2D2D1[ijk]*dgI_U0U2D0 + 0.5*
_gammaI_U0U0[ijk]*(_ddgamma_D0D1D2D0[ijk] + _ddgamma_D0D2D1D0[ijk] - 
_ddgamma_D1D2D0D0[ijk]) + 0.5*dgI_U0U0D0*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);

  double dGamma_U2D1D1D0 = 
0.5*_ddgamma_D1D1D1D0[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D1D1D1[ijk]*
dgI_U1U2D0 + 0.5*_gammaI_U0U2[ijk]*(2*_ddgamma_D0D1D1D0[ijk] - 
_ddgamma_D1D1D0D0[ijk]) - 0.5*_gammaI_U2U2[ijk]*(_ddgamma_D1D1D2D0[ijk] - 
2*_ddgamma_D1D2D1D0[ijk]) + 0.5*dgI_U0U2D0*(2*_dgamma_D0D1D1[ijk] - 
_dgamma_D1D1D0[ijk]) - 0.5*dgI_U2U2D0*(_dgamma_D1D1D2[ijk] - 2*
_dgamma_D1D2D1[ijk]);

  double dGamma_U0D1D2D2 = 
0.5*_ddgamma_D1D1D2D2[ijk]*_gammaI_U0U1[ijk] + 0.5*
_ddgamma_D2D2D1D2[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D1D1D2[ijk]*
dgI_U0U1D2 + 0.5*_dgamma_D2D2D1[ijk]*dgI_U0U2D2 + 0.5*
_gammaI_U0U0[ijk]*(_ddgamma_D0D1D2D2[ijk] + _ddgamma_D0D2D1D2[ijk] - 
_ddgamma_D1D2D0D2[ijk]) + 0.5*dgI_U0U0D2*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);

  double dGamma_U2D2D2D0 = 
0.5*_ddgamma_D2D2D2D0[ijk]*_gammaI_U2U2[ijk] + 0.5*_dgamma_D2D2D2[ijk]*
dgI_U2U2D0 + 0.5*_gammaI_U0U2[ijk]*(2*_ddgamma_D0D2D2D0[ijk] - 
_ddgamma_D2D2D0D0[ijk]) + 0.5*_gammaI_U1U2[ijk]*(2*
_ddgamma_D1D2D2D0[ijk] - _ddgamma_D2D2D1D0[ijk]) + 0.5*dgI_U0U2D0*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*dgI_U1U2D0*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

  double dGamma_U2D2D2D1 = 
0.5*_ddgamma_D2D2D2D1[ijk]*_gammaI_U2U2[ijk] + 0.5*_dgamma_D2D2D2[ijk]*
dgI_U2U2D1 + 0.5*_gammaI_U0U2[ijk]*(2*_ddgamma_D0D2D2D1[ijk] - 
_ddgamma_D2D2D0D1[ijk]) + 0.5*_gammaI_U1U2[ijk]*(2*
_ddgamma_D1D2D2D1[ijk] - _ddgamma_D2D2D1D1[ijk]) + 0.5*dgI_U0U2D1*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*dgI_U1U2D1*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

  double dGamma_U2D2D2D2 = 
0.5*_ddgamma_D2D2D2D2[ijk]*_gammaI_U2U2[ijk] + 0.5*_dgamma_D2D2D2[ijk]*
dgI_U2U2D2 + 0.5*_gammaI_U0U2[ijk]*(2*_ddgamma_D0D2D2D2[ijk] - 
_ddgamma_D2D2D0D2[ijk]) + 0.5*_gammaI_U1U2[ijk]*(2*
_ddgamma_D1D2D2D2[ijk] - _ddgamma_D2D2D1D2[ijk]) + 0.5*dgI_U0U2D2*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*dgI_U1U2D2*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

  double dGamma_U1D2D2D0 = 
0.5*_ddgamma_D2D2D2D0[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D2D2D2[ijk]*
dgI_U1U2D0 + 0.5*_gammaI_U0U1[ijk]*(2*_ddgamma_D0D2D2D0[ijk] - 
_ddgamma_D2D2D0D0[ijk]) + 0.5*_gammaI_U1U1[ijk]*(2*
_ddgamma_D1D2D2D0[ijk] - _ddgamma_D2D2D1D0[ijk]) + 0.5*dgI_U0U1D0*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*dgI_U1U1D0*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

  double dGamma_U2D0D2D0 = 
0.5*_ddgamma_D0D0D2D0[ijk]*_gammaI_U0U2[ijk] + 0.5*
_ddgamma_D2D2D0D0[ijk]*_gammaI_U2U2[ijk] + 0.5*_dgamma_D0D0D2[ijk]*
dgI_U0U2D0 + 0.5*_dgamma_D2D2D0[ijk]*dgI_U2U2D0 + 0.5*
_gammaI_U1U2[ijk]*(_ddgamma_D0D1D2D0[ijk] - _ddgamma_D0D2D1D0[ijk] + 
_ddgamma_D1D2D0D0[ijk]) + 0.5*dgI_U1U2D0*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U0D0D2D0 = 
0.5*_ddgamma_D0D0D2D0[ijk]*_gammaI_U0U0[ijk] + 0.5*
_ddgamma_D2D2D0D0[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D0D0D2[ijk]*
dgI_U0U0D0 + 0.5*_dgamma_D2D2D0[ijk]*dgI_U0U2D0 + 0.5*
_gammaI_U0U1[ijk]*(_ddgamma_D0D1D2D0[ijk] - _ddgamma_D0D2D1D0[ijk] + 
_ddgamma_D1D2D0D0[ijk]) + 0.5*dgI_U0U1D0*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U2D0D0D1 = 
0.5*_ddgamma_D0D0D0D1[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D0D0D0[ijk]*
dgI_U0U2D1 - 0.5*_gammaI_U1U2[ijk]*(_ddgamma_D0D0D1D1[ijk] - 2*
_ddgamma_D0D1D0D1[ijk]) - 0.5*_gammaI_U2U2[ijk]*(_ddgamma_D0D0D2D1[ijk] - 
2*_ddgamma_D0D2D0D1[ijk]) - 0.5*dgI_U1U2D1*(_dgamma_D0D0D1[ijk] - 2*
_dgamma_D0D1D0[ijk]) - 0.5*dgI_U2U2D1*(_dgamma_D0D0D2[ijk] - 2*
_dgamma_D0D2D0[ijk]);

  double dGamma_U0D0D2D2 = 
0.5*_ddgamma_D0D0D2D2[ijk]*_gammaI_U0U0[ijk] + 0.5*
_ddgamma_D2D2D0D2[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D0D0D2[ijk]*
dgI_U0U0D2 + 0.5*_dgamma_D2D2D0[ijk]*dgI_U0U2D2 + 0.5*
_gammaI_U0U1[ijk]*(_ddgamma_D0D1D2D2[ijk] - _ddgamma_D0D2D1D2[ijk] + 
_ddgamma_D1D2D0D2[ijk]) + 0.5*dgI_U0U1D2*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U1D1D1D2 = 
0.5*_ddgamma_D1D1D1D2[ijk]*_gammaI_U1U1[ijk] + 0.5*_dgamma_D1D1D1[ijk]*
dgI_U1U1D2 + 0.5*_gammaI_U0U1[ijk]*(2*_ddgamma_D0D1D1D2[ijk] - 
_ddgamma_D1D1D0D2[ijk]) - 0.5*_gammaI_U1U2[ijk]*(_ddgamma_D1D1D2D2[ijk] - 
2*_ddgamma_D1D2D1D2[ijk]) + 0.5*dgI_U0U1D2*(2*_dgamma_D0D1D1[ijk] - 
_dgamma_D1D1D0[ijk]) - 0.5*dgI_U1U2D2*(_dgamma_D1D1D2[ijk] - 2*
_dgamma_D1D2D1[ijk]);

  double dGamma_U1D1D2D0 = 
0.5*_ddgamma_D1D1D2D0[ijk]*_gammaI_U1U1[ijk] + 0.5*
_ddgamma_D2D2D1D0[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D1D1D2[ijk]*
dgI_U1U1D0 + 0.5*_dgamma_D2D2D1[ijk]*dgI_U1U2D0 + 0.5*
_gammaI_U0U1[ijk]*(_ddgamma_D0D1D2D0[ijk] + _ddgamma_D0D2D1D0[ijk] - 
_ddgamma_D1D2D0D0[ijk]) + 0.5*dgI_U0U1D0*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);

  double dGamma_U1D1D2D1 = 
0.5*_ddgamma_D1D1D2D1[ijk]*_gammaI_U1U1[ijk] + 0.5*
_ddgamma_D2D2D1D1[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D1D1D2[ijk]*
dgI_U1U1D1 + 0.5*_dgamma_D2D2D1[ijk]*dgI_U1U2D1 + 0.5*
_gammaI_U0U1[ijk]*(_ddgamma_D0D1D2D1[ijk] + _ddgamma_D0D2D1D1[ijk] - 
_ddgamma_D1D2D0D1[ijk]) + 0.5*dgI_U0U1D1*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);

  double dGamma_U1D1D2D2 = 
0.5*_ddgamma_D1D1D2D2[ijk]*_gammaI_U1U1[ijk] + 0.5*
_ddgamma_D2D2D1D2[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D1D1D2[ijk]*
dgI_U1U1D2 + 0.5*_dgamma_D2D2D1[ijk]*dgI_U1U2D2 + 0.5*
_gammaI_U0U1[ijk]*(_ddgamma_D0D1D2D2[ijk] + _ddgamma_D0D2D1D2[ijk] - 
_ddgamma_D1D2D0D2[ijk]) + 0.5*dgI_U0U1D2*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);

  double dGamma_U0D2D2D0 = 
0.5*_ddgamma_D2D2D2D0[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D2D2D2[ijk]*
dgI_U0U2D0 + 0.5*_gammaI_U0U0[ijk]*(2*_ddgamma_D0D2D2D0[ijk] - 
_ddgamma_D2D2D0D0[ijk]) + 0.5*_gammaI_U0U1[ijk]*(2*
_ddgamma_D1D2D2D0[ijk] - _ddgamma_D2D2D1D0[ijk]) + 0.5*dgI_U0U0D0*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*dgI_U0U1D0*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

  double dGamma_U2D0D2D2 = 
0.5*_ddgamma_D0D0D2D2[ijk]*_gammaI_U0U2[ijk] + 0.5*
_ddgamma_D2D2D0D2[ijk]*_gammaI_U2U2[ijk] + 0.5*_dgamma_D0D0D2[ijk]*
dgI_U0U2D2 + 0.5*_dgamma_D2D2D0[ijk]*dgI_U2U2D2 + 0.5*
_gammaI_U1U2[ijk]*(_ddgamma_D0D1D2D2[ijk] - _ddgamma_D0D2D1D2[ijk] + 
_ddgamma_D1D2D0D2[ijk]) + 0.5*dgI_U1U2D2*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U2D1D1D1 = 
0.5*_ddgamma_D1D1D1D1[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D1D1D1[ijk]*
dgI_U1U2D1 + 0.5*_gammaI_U0U2[ijk]*(2*_ddgamma_D0D1D1D1[ijk] - 
_ddgamma_D1D1D0D1[ijk]) - 0.5*_gammaI_U2U2[ijk]*(_ddgamma_D1D1D2D1[ijk] - 
2*_ddgamma_D1D2D1D1[ijk]) + 0.5*dgI_U0U2D1*(2*_dgamma_D0D1D1[ijk] - 
_dgamma_D1D1D0[ijk]) - 0.5*dgI_U2U2D1*(_dgamma_D1D1D2[ijk] - 2*
_dgamma_D1D2D1[ijk]);

  double dGamma_U2D1D1D2 = 
0.5*_ddgamma_D1D1D1D2[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D1D1D1[ijk]*
dgI_U1U2D2 + 0.5*_gammaI_U0U2[ijk]*(2*_ddgamma_D0D1D1D2[ijk] - 
_ddgamma_D1D1D0D2[ijk]) - 0.5*_gammaI_U2U2[ijk]*(_ddgamma_D1D1D2D2[ijk] - 
2*_ddgamma_D1D2D1D2[ijk]) + 0.5*dgI_U0U2D2*(2*_dgamma_D0D1D1[ijk] - 
_dgamma_D1D1D0[ijk]) - 0.5*dgI_U2U2D2*(_dgamma_D1D1D2[ijk] - 2*
_dgamma_D1D2D1[ijk]);

  double dGamma_U0D0D0D1 = 
0.5*_ddgamma_D0D0D0D1[ijk]*_gammaI_U0U0[ijk] + 0.5*_dgamma_D0D0D0[ijk]*
dgI_U0U0D1 - 0.5*_gammaI_U0U1[ijk]*(_ddgamma_D0D0D1D1[ijk] - 2*
_ddgamma_D0D1D0D1[ijk]) - 0.5*_gammaI_U0U2[ijk]*(_ddgamma_D0D0D2D1[ijk] - 
2*_ddgamma_D0D2D0D1[ijk]) - 0.5*dgI_U0U1D1*(_dgamma_D0D0D1[ijk] - 2*
_dgamma_D0D1D0[ijk]) - 0.5*dgI_U0U2D1*(_dgamma_D0D0D2[ijk] - 2*
_dgamma_D0D2D0[ijk]);

  double dGamma_U0D0D0D2 = 
0.5*_ddgamma_D0D0D0D2[ijk]*_gammaI_U0U0[ijk] + 0.5*_dgamma_D0D0D0[ijk]*
dgI_U0U0D2 - 0.5*_gammaI_U0U1[ijk]*(_ddgamma_D0D0D1D2[ijk] - 2*
_ddgamma_D0D1D0D2[ijk]) - 0.5*_gammaI_U0U2[ijk]*(_ddgamma_D0D0D2D2[ijk] - 
2*_ddgamma_D0D2D0D2[ijk]) - 0.5*dgI_U0U1D2*(_dgamma_D0D0D1[ijk] - 2*
_dgamma_D0D1D0[ijk]) - 0.5*dgI_U0U2D2*(_dgamma_D0D0D2[ijk] - 2*
_dgamma_D0D2D0[ijk]);

  double dGamma_U0D0D1D2 = 
0.5*_ddgamma_D0D0D1D2[ijk]*_gammaI_U0U0[ijk] + 0.5*
_ddgamma_D1D1D0D2[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D0D0D1[ijk]*
dgI_U0U0D2 + 0.5*_dgamma_D1D1D0[ijk]*dgI_U0U1D2 + 0.5*
_gammaI_U0U2[ijk]*(-_ddgamma_D0D1D2D2[ijk] + _ddgamma_D0D2D1D2[ijk] + 
_ddgamma_D1D2D0D2[ijk]) + 0.5*dgI_U0U2D2*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U0D0D1D1 = 
0.5*_ddgamma_D0D0D1D1[ijk]*_gammaI_U0U0[ijk] + 0.5*
_ddgamma_D1D1D0D1[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D0D0D1[ijk]*
dgI_U0U0D1 + 0.5*_dgamma_D1D1D0[ijk]*dgI_U0U1D1 + 0.5*
_gammaI_U0U2[ijk]*(-_ddgamma_D0D1D2D1[ijk] + _ddgamma_D0D2D1D1[ijk] + 
_ddgamma_D1D2D0D1[ijk]) + 0.5*dgI_U0U2D1*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U0D0D1D0 = 
0.5*_ddgamma_D0D0D1D0[ijk]*_gammaI_U0U0[ijk] + 0.5*
_ddgamma_D1D1D0D0[ijk]*_gammaI_U0U1[ijk] + 0.5*_dgamma_D0D0D1[ijk]*
dgI_U0U0D0 + 0.5*_dgamma_D1D1D0[ijk]*dgI_U0U1D0 + 0.5*
_gammaI_U0U2[ijk]*(-_ddgamma_D0D1D2D0[ijk] + _ddgamma_D0D2D1D0[ijk] + 
_ddgamma_D1D2D0D0[ijk]) + 0.5*dgI_U0U2D0*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U0D2D2D2 = 
0.5*_ddgamma_D2D2D2D2[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D2D2D2[ijk]*
dgI_U0U2D2 + 0.5*_gammaI_U0U0[ijk]*(2*_ddgamma_D0D2D2D2[ijk] - 
_ddgamma_D2D2D0D2[ijk]) + 0.5*_gammaI_U0U1[ijk]*(2*
_ddgamma_D1D2D2D2[ijk] - _ddgamma_D2D2D1D2[ijk]) + 0.5*dgI_U0U0D2*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*dgI_U0U1D2*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

  double dGamma_U2D0D1D0 = 
0.5*_ddgamma_D0D0D1D0[ijk]*_gammaI_U0U2[ijk] + 0.5*
_ddgamma_D1D1D0D0[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D0D0D1[ijk]*
dgI_U0U2D0 + 0.5*_dgamma_D1D1D0[ijk]*dgI_U1U2D0 + 0.5*
_gammaI_U2U2[ijk]*(-_ddgamma_D0D1D2D0[ijk] + _ddgamma_D0D2D1D0[ijk] + 
_ddgamma_D1D2D0D0[ijk]) + 0.5*dgI_U2U2D0*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U1D1D1D1 = 
0.5*_ddgamma_D1D1D1D1[ijk]*_gammaI_U1U1[ijk] + 0.5*_dgamma_D1D1D1[ijk]*
dgI_U1U1D1 + 0.5*_gammaI_U0U1[ijk]*(2*_ddgamma_D0D1D1D1[ijk] - 
_ddgamma_D1D1D0D1[ijk]) - 0.5*_gammaI_U1U2[ijk]*(_ddgamma_D1D1D2D1[ijk] - 
2*_ddgamma_D1D2D1D1[ijk]) + 0.5*dgI_U0U1D1*(2*_dgamma_D0D1D1[ijk] - 
_dgamma_D1D1D0[ijk]) - 0.5*dgI_U1U2D1*(_dgamma_D1D1D2[ijk] - 2*
_dgamma_D1D2D1[ijk]);

  double dGamma_U2D0D1D2 = 
0.5*_ddgamma_D0D0D1D2[ijk]*_gammaI_U0U2[ijk] + 0.5*
_ddgamma_D1D1D0D2[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D0D0D1[ijk]*
dgI_U0U2D2 + 0.5*_dgamma_D1D1D0[ijk]*dgI_U1U2D2 + 0.5*
_gammaI_U2U2[ijk]*(-_ddgamma_D0D1D2D2[ijk] + _ddgamma_D0D2D1D2[ijk] + 
_ddgamma_D1D2D0D2[ijk]) + 0.5*dgI_U2U2D2*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U2D0D0D2 = 
0.5*_ddgamma_D0D0D0D2[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D0D0D0[ijk]*
dgI_U0U2D2 - 0.5*_gammaI_U1U2[ijk]*(_ddgamma_D0D0D1D2[ijk] - 2*
_ddgamma_D0D1D0D2[ijk]) - 0.5*_gammaI_U2U2[ijk]*(_ddgamma_D0D0D2D2[ijk] - 
2*_ddgamma_D0D2D0D2[ijk]) - 0.5*dgI_U1U2D2*(_dgamma_D0D0D1[ijk] - 2*
_dgamma_D0D1D0[ijk]) - 0.5*dgI_U2U2D2*(_dgamma_D0D0D2[ijk] - 2*
_dgamma_D0D2D0[ijk]);

  double dGamma_U2D1D2D2 = 
0.5*_ddgamma_D1D1D2D2[ijk]*_gammaI_U1U2[ijk] + 0.5*
_ddgamma_D2D2D1D2[ijk]*_gammaI_U2U2[ijk] + 0.5*_dgamma_D1D1D2[ijk]*
dgI_U1U2D2 + 0.5*_dgamma_D2D2D1[ijk]*dgI_U2U2D2 + 0.5*
_gammaI_U0U2[ijk]*(_ddgamma_D0D1D2D2[ijk] + _ddgamma_D0D2D1D2[ijk] - 
_ddgamma_D1D2D0D2[ijk]) + 0.5*dgI_U0U2D2*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);

  double dGamma_U2D0D1D1 = 
0.5*_ddgamma_D0D0D1D1[ijk]*_gammaI_U0U2[ijk] + 0.5*
_ddgamma_D1D1D0D1[ijk]*_gammaI_U1U2[ijk] + 0.5*_dgamma_D0D0D1[ijk]*
dgI_U0U2D1 + 0.5*_dgamma_D1D1D0[ijk]*dgI_U1U2D1 + 0.5*
_gammaI_U2U2[ijk]*(-_ddgamma_D0D1D2D1[ijk] + _ddgamma_D0D2D1D1[ijk] + 
_ddgamma_D1D2D0D1[ijk]) + 0.5*dgI_U2U2D1*(-_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U2D1D2D0 = 
0.5*_ddgamma_D1D1D2D0[ijk]*_gammaI_U1U2[ijk] + 0.5*
_ddgamma_D2D2D1D0[ijk]*_gammaI_U2U2[ijk] + 0.5*_dgamma_D1D1D2[ijk]*
dgI_U1U2D0 + 0.5*_dgamma_D2D2D1[ijk]*dgI_U2U2D0 + 0.5*
_gammaI_U0U2[ijk]*(_ddgamma_D0D1D2D0[ijk] + _ddgamma_D0D2D1D0[ijk] - 
_ddgamma_D1D2D0D0[ijk]) + 0.5*dgI_U0U2D0*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);

  double dGamma_U0D0D0D0 = 
0.5*_ddgamma_D0D0D0D0[ijk]*_gammaI_U0U0[ijk] + 0.5*_dgamma_D0D0D0[ijk]*
dgI_U0U0D0 - 0.5*_gammaI_U0U1[ijk]*(_ddgamma_D0D0D1D0[ijk] - 2*
_ddgamma_D0D1D0D0[ijk]) - 0.5*_gammaI_U0U2[ijk]*(_ddgamma_D0D0D2D0[ijk] - 
2*_ddgamma_D0D2D0D0[ijk]) - 0.5*dgI_U0U1D0*(_dgamma_D0D0D1[ijk] - 2*
_dgamma_D0D1D0[ijk]) - 0.5*dgI_U0U2D0*(_dgamma_D0D0D2[ijk] - 2*
_dgamma_D0D2D0[ijk]);

  double dGamma_U0D2D2D1 = 
0.5*_ddgamma_D2D2D2D1[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D2D2D2[ijk]*
dgI_U0U2D1 + 0.5*_gammaI_U0U0[ijk]*(2*_ddgamma_D0D2D2D1[ijk] - 
_ddgamma_D2D2D0D1[ijk]) + 0.5*_gammaI_U0U1[ijk]*(2*
_ddgamma_D1D2D2D1[ijk] - _ddgamma_D2D2D1D1[ijk]) + 0.5*dgI_U0U0D1*(2*
_dgamma_D0D2D2[ijk] - _dgamma_D2D2D0[ijk]) + 0.5*dgI_U0U1D1*(2*
_dgamma_D1D2D2[ijk] - _dgamma_D2D2D1[ijk]);

  double dGamma_U2D0D2D1 = 
0.5*_ddgamma_D0D0D2D1[ijk]*_gammaI_U0U2[ijk] + 0.5*
_ddgamma_D2D2D0D1[ijk]*_gammaI_U2U2[ijk] + 0.5*_dgamma_D0D0D2[ijk]*
dgI_U0U2D1 + 0.5*_dgamma_D2D2D0[ijk]*dgI_U2U2D1 + 0.5*
_gammaI_U1U2[ijk]*(_ddgamma_D0D1D2D1[ijk] - _ddgamma_D0D2D1D1[ijk] + 
_ddgamma_D1D2D0D1[ijk]) + 0.5*dgI_U1U2D1*(_dgamma_D0D1D2[ijk] - 
_dgamma_D0D2D1[ijk] + _dgamma_D1D2D0[ijk]);

  double dGamma_U1D1D1D0 = 
0.5*_ddgamma_D1D1D1D0[ijk]*_gammaI_U1U1[ijk] + 0.5*_dgamma_D1D1D1[ijk]*
dgI_U1U1D0 + 0.5*_gammaI_U0U1[ijk]*(2*_ddgamma_D0D1D1D0[ijk] - 
_ddgamma_D1D1D0D0[ijk]) - 0.5*_gammaI_U1U2[ijk]*(_ddgamma_D1D1D2D0[ijk] - 
2*_ddgamma_D1D2D1D0[ijk]) + 0.5*dgI_U0U1D0*(2*_dgamma_D0D1D1[ijk] - 
_dgamma_D1D1D0[ijk]) - 0.5*dgI_U1U2D0*(_dgamma_D1D1D2[ijk] - 2*
_dgamma_D1D2D1[ijk]);

  double dGamma_U2D0D0D0 = 
0.5*_ddgamma_D0D0D0D0[ijk]*_gammaI_U0U2[ijk] + 0.5*_dgamma_D0D0D0[ijk]*
dgI_U0U2D0 - 0.5*_gammaI_U1U2[ijk]*(_ddgamma_D0D0D1D0[ijk] - 2*
_ddgamma_D0D1D0D0[ijk]) - 0.5*_gammaI_U2U2[ijk]*(_ddgamma_D0D0D2D0[ijk] - 
2*_ddgamma_D0D2D0D0[ijk]) - 0.5*dgI_U1U2D0*(_dgamma_D0D0D1[ijk] - 2*
_dgamma_D0D1D0[ijk]) - 0.5*dgI_U2U2D0*(_dgamma_D0D0D2[ijk] - 2*
_dgamma_D0D2D0[ijk]);

  double dGamma_U2D1D2D1 = 
0.5*_ddgamma_D1D1D2D1[ijk]*_gammaI_U1U2[ijk] + 0.5*
_ddgamma_D2D2D1D1[ijk]*_gammaI_U2U2[ijk] + 0.5*_dgamma_D1D1D2[ijk]*
dgI_U1U2D1 + 0.5*_dgamma_D2D2D1[ijk]*dgI_U2U2D1 + 0.5*
_gammaI_U0U2[ijk]*(_ddgamma_D0D1D2D1[ijk] + _ddgamma_D0D2D1D1[ijk] - 
_ddgamma_D1D2D0D1[ijk]) + 0.5*dgI_U0U2D1*(_dgamma_D0D1D2[ijk] + 
_dgamma_D0D2D1[ijk] - _dgamma_D1D2D0[ijk]);


  /* populating: */
  _dGamma_U2D2D2D2[ijk] = dGamma_U2D2D2D2;
  _dGamma_U2D2D2D0[ijk] = dGamma_U2D2D2D0;
  _dGamma_U2D2D2D1[ijk] = dGamma_U2D2D2D1;
  _dGamma_U2D0D0D2[ijk] = dGamma_U2D0D0D2;
  _dGamma_U1D1D2D2[ijk] = dGamma_U1D1D2D2;
  _dGamma_U2D0D0D0[ijk] = dGamma_U2D0D0D0;
  _dGamma_U1D1D2D0[ijk] = dGamma_U1D1D2D0;
  _dGamma_U1D1D2D1[ijk] = dGamma_U1D1D2D1;
  _dGamma_U2D1D1D0[ijk] = dGamma_U2D1D1D0;
  _dGamma_U2D0D0D1[ijk] = dGamma_U2D0D0D1;
  _dGamma_U2D0D2D1[ijk] = dGamma_U2D0D2D1;
  _dGamma_U1D0D1D0[ijk] = dGamma_U1D0D1D0;
  _dGamma_U1D0D1D1[ijk] = dGamma_U1D0D1D1;
  _dGamma_U1D0D1D2[ijk] = dGamma_U1D0D1D2;
  _dGamma_U1D2D2D1[ijk] = dGamma_U1D2D2D1;
  _dGamma_U1D0D0D1[ijk] = dGamma_U1D0D0D1;
  _dGamma_U1D0D0D0[ijk] = dGamma_U1D0D0D0;
  _dGamma_U1D0D0D2[ijk] = dGamma_U1D0D0D2;
  _dGamma_U0D1D2D2[ijk] = dGamma_U0D1D2D2;
  _dGamma_U0D1D2D1[ijk] = dGamma_U0D1D2D1;
  _dGamma_U0D1D2D0[ijk] = dGamma_U0D1D2D0;
  _dGamma_U2D0D2D0[ijk] = dGamma_U2D0D2D0;
  _dGamma_U1D0D2D2[ijk] = dGamma_U1D0D2D2;
  _dGamma_U1D0D2D1[ijk] = dGamma_U1D0D2D1;
  _dGamma_U1D0D2D0[ijk] = dGamma_U1D0D2D0;
  _dGamma_U2D1D1D2[ijk] = dGamma_U2D1D1D2;
  _dGamma_U2D0D2D2[ijk] = dGamma_U2D0D2D2;
  _dGamma_U0D0D1D0[ijk] = dGamma_U0D0D1D0;
  _dGamma_U1D2D2D0[ijk] = dGamma_U1D2D2D0;
  _dGamma_U2D1D2D1[ijk] = dGamma_U2D1D2D1;
  _dGamma_U2D0D1D2[ijk] = dGamma_U2D0D1D2;
  _dGamma_U2D0D1D1[ijk] = dGamma_U2D0D1D1;
  _dGamma_U2D0D1D0[ijk] = dGamma_U2D0D1D0;
  _dGamma_U2D1D2D2[ijk] = dGamma_U2D1D2D2;
  _dGamma_U0D1D1D0[ijk] = dGamma_U0D1D1D0;
  _dGamma_U0D1D1D1[ijk] = dGamma_U0D1D1D1;
  _dGamma_U0D1D1D2[ijk] = dGamma_U0D1D1D2;
  _dGamma_U1D2D2D2[ijk] = dGamma_U1D2D2D2;
  _dGamma_U1D1D1D1[ijk] = dGamma_U1D1D1D1;
  _dGamma_U1D1D1D0[ijk] = dGamma_U1D1D1D0;
  _dGamma_U1D1D1D2[ijk] = dGamma_U1D1D1D2;
  _dGamma_U0D0D1D1[ijk] = dGamma_U0D0D1D1;
  _dGamma_U0D0D2D2[ijk] = dGamma_U0D0D2D2;
  _dGamma_U0D0D2D0[ijk] = dGamma_U0D0D2D0;
  _dGamma_U0D0D2D1[ijk] = dGamma_U0D0D2D1;
  _dGamma_U2D1D2D0[ijk] = dGamma_U2D1D2D0;
  _dGamma_U0D0D0D0[ijk] = dGamma_U0D0D0D0;
  _dGamma_U0D0D0D1[ijk] = dGamma_U0D0D0D1;
  _dGamma_U0D0D0D2[ijk] = dGamma_U0D0D0D2;
  _dGamma_U2D1D1D1[ijk] = dGamma_U2D1D1D1;
  _dGamma_U0D2D2D0[ijk] = dGamma_U0D2D2D0;
  _dGamma_U0D2D2D1[ijk] = dGamma_U0D2D2D1;
  _dGamma_U0D2D2D2[ijk] = dGamma_U0D2D2D2;
  _dGamma_U0D0D1D2[ijk] = dGamma_U0D0D1D2;
  }

  bbn_rm_1st_2nd_derivatives_conformal_metric(patch);

}
