/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "sns_headers.h"
#include "maths_equation_solvings_lib.h"
#include "sns_XCTS_equations_lib.h"


void *sns_eq_Beta_U1(void *vp1,void *vp2)
{
  DDM_SCHUR_EQ_DECLARE
  unsigned ijk;/* node index */

  /* declaring: */
  GET_FIELD_UNUSED(_A_UiUj_U2U2)
  GET_FIELD_UNUSED(_A_UiUj_U1U2)
  GET_FIELD_UNUSED(_A_UiUj_U1U1)
  GET_FIELD_UNUSED(_A_UiUj_U0U2)
  GET_FIELD_UNUSED(_A_UiUj_U0U1)
  GET_FIELD_UNUSED(_A_UiUj_U0U0)
  GET_FIELD_UNUSED(_dA_UiUj_U2U2D2)
  GET_FIELD_UNUSED(_dA_UiUj_U2U2D0)
  GET_FIELD_UNUSED(_dA_UiUj_U2U2D1)
  GET_FIELD_UNUSED(_dA_UiUj_U1U1D2)
  GET_FIELD_UNUSED(_dA_UiUj_U1U1D0)
  GET_FIELD_UNUSED(_dA_UiUj_U1U1D1)
  GET_FIELD_UNUSED(_dA_UiUj_U0U0D2)
  GET_FIELD_UNUSED(_dA_UiUj_U0U0D0)
  GET_FIELD_UNUSED(_dA_UiUj_U0U0D1)
  GET_FIELD_UNUSED(_dA_UiUj_U0U1D2)
  GET_FIELD_UNUSED(_dA_UiUj_U0U1D1)
  GET_FIELD_UNUSED(_dA_UiUj_U0U1D0)
  GET_FIELD_UNUSED(_dA_UiUj_U1U2D1)
  GET_FIELD_UNUSED(_dA_UiUj_U1U2D0)
  GET_FIELD_UNUSED(_dA_UiUj_U1U2D2)
  GET_FIELD_UNUSED(_dA_UiUj_U0U2D0)
  GET_FIELD_UNUSED(_dA_UiUj_U0U2D1)
  GET_FIELD_UNUSED(_dA_UiUj_U0U2D2)
  GET_FIELD(psi)
  GET_FIELD(dK_D2)
  GET_FIELD(dK_D1)
  GET_FIELD(dK_D0)
  GET_FIELD_UNUSED(_gammaI_U0U2)
  GET_FIELD_UNUSED(_gammaI_U0U0)
  GET_FIELD_UNUSED(_gammaI_U0U1)
  GET_FIELD_UNUSED(_gammaI_U1U2)
  GET_FIELD_UNUSED(_gammaI_U1U1)
  GET_FIELD_UNUSED(_gammaI_U2U2)
  GET_FIELD_UNUSED(_Gamma_U2D1D1)
  GET_FIELD_UNUSED(_Gamma_U2D1D2)
  GET_FIELD_UNUSED(_Gamma_U0D1D1)
  GET_FIELD_UNUSED(_Gamma_U2D0D2)
  GET_FIELD_UNUSED(_Gamma_U2D2D2)
  GET_FIELD_UNUSED(_Gamma_U0D1D2)
  GET_FIELD_UNUSED(_Gamma_U0D0D2)
  GET_FIELD_UNUSED(_Gamma_U0D0D1)
  GET_FIELD_UNUSED(_Gamma_U0D0D0)
  GET_FIELD_UNUSED(_Gamma_U1D2D2)
  GET_FIELD_UNUSED(_Gamma_U2D0D1)
  GET_FIELD_UNUSED(_Gamma_U0D2D2)
  GET_FIELD_UNUSED(_Gamma_U2D0D0)
  GET_FIELD_UNUSED(_Gamma_U1D0D2)
  GET_FIELD_UNUSED(_Gamma_U1D1D2)
  GET_FIELD_UNUSED(_Gamma_U1D0D0)
  GET_FIELD_UNUSED(_Gamma_U1D0D1)
  GET_FIELD_UNUSED(_Gamma_U1D1D1)
  GET_FIELD_UNUSED(_J_U0)
  GET_FIELD_UNUSED(_J_U1)
  GET_FIELD_UNUSED(_J_U2)


  DDM_SCHUR_EQ_OPEN

  double F_eq_U1 = 
_A_UiUj_U0U0[ijk]*_Gamma_U1D0D0[ijk] + _A_UiUj_U0U1[ijk]*
_Gamma_U0D0D0[ijk] + 3.0*_A_UiUj_U0U1[ijk]*_Gamma_U1D0D1[ijk] + 
_A_UiUj_U0U1[ijk]*_Gamma_U2D0D2[ijk] + 2.0*_A_UiUj_U0U2[ijk]*
_Gamma_U1D0D2[ijk] + _A_UiUj_U1U1[ijk]*_Gamma_U0D0D1[ijk] + 2.0*
_A_UiUj_U1U1[ijk]*_Gamma_U1D1D1[ijk] + _A_UiUj_U1U1[ijk]*
_Gamma_U2D1D2[ijk] + _A_UiUj_U1U2[ijk]*_Gamma_U0D0D2[ijk] + 3.0*
_A_UiUj_U1U2[ijk]*_Gamma_U1D1D2[ijk] + _A_UiUj_U1U2[ijk]*
_Gamma_U2D2D2[ijk] + _A_UiUj_U2U2[ijk]*_Gamma_U1D2D2[ijk] - 8*M_PI*
_J_U1[ijk]*pow(psi[ijk], 4) + _dA_UiUj_U0U1D0[ijk] + 
_dA_UiUj_U1U1D1[ijk] + _dA_UiUj_U1U2D2[ijk] - 0.66666666666666663*
pow(psi[ijk], 6)*(_gammaI_U0U1[ijk]*dK_D0[ijk] + _gammaI_U1U1[ijk]*
dK_D1[ijk] + _gammaI_U1U2[ijk]*dK_D2[ijk]);

  F[n] = F_eq_U1;

  DDM_SCHUR_EQ_CLOSE

  return 0;
}
