/*
  These C codes generated by Cpi version 1.0
  Copyright (C) 2019 Alireza Rashti.
*/


#include "sns_headers.h"
#include "maths_equation_solvings_lib.h"
#include "sns_XCTS_equations_lib.h"


void *sns_jacobian_eq_phi(void *vp1,void *vp2)
{
  DDM_SCHUR_JACOBIAN_EQ_DECLARE
  unsigned ijk,lmn;/* for Jacobian entries J[ijk][lmn] */

  /* declaring: */
  JACOBIAN_DERIVATIVE(Jphi_D1)
  JACOBIAN_DERIVATIVE(Jphi_D0)
  JACOBIAN_DERIVATIVE(Jphi_D2)
  JACOBIAN_DERIVATIVE(JJphi_D1D2)
  JACOBIAN_DERIVATIVE(JJphi_D1D1)
  JACOBIAN_DERIVATIVE(JJphi_D0D2)
  JACOBIAN_DERIVATIVE(JJphi_D0D0)
  JACOBIAN_DERIVATIVE(JJphi_D0D1)
  JACOBIAN_DERIVATIVE(JJphi_D2D2)
  GET_FIELD_IF_IN_NS(enthalpy)
  GET_FIELD_IF_IN_NS(denthalpy_D2)
  GET_FIELD_IF_IN_NS(denthalpy_D0)
  GET_FIELD_IF_IN_NS(denthalpy_D1)
  GET_FIELD_IF_IN_NS(rho0)
  GET_FIELD_IF_IN_NS(drho0_D2)
  GET_FIELD_IF_IN_NS(drho0_D0)
  GET_FIELD_IF_IN_NS(drho0_D1)
  GET_FIELD(eta)
  GET_FIELD(deta_D0)
  GET_FIELD(deta_D1)
  GET_FIELD(deta_D2)
  GET_FIELD(psi)
  GET_FIELD(dpsi_D0)
  GET_FIELD(dpsi_D1)
  GET_FIELD(dpsi_D2)
  GET_FIELD(_gammaI_U0U2)
  GET_FIELD(_gammaI_U0U0)
  GET_FIELD(_gammaI_U0U1)
  GET_FIELD(_gammaI_U1U2)
  GET_FIELD(_gammaI_U1U1)
  GET_FIELD(_gammaI_U2U2)
  GET_FIELD(_Gamma_U2D1D1)
  GET_FIELD(_Gamma_U2D1D2)
  GET_FIELD(_Gamma_U0D1D1)
  GET_FIELD(_Gamma_U2D0D2)
  GET_FIELD(_Gamma_U2D2D2)
  GET_FIELD(_Gamma_U0D1D2)
  GET_FIELD(_Gamma_U0D0D2)
  GET_FIELD(_Gamma_U0D0D1)
  GET_FIELD(_Gamma_U0D0D0)
  GET_FIELD(_Gamma_U1D2D2)
  GET_FIELD(_Gamma_U2D0D1)
  GET_FIELD(_Gamma_U0D2D2)
  GET_FIELD(_Gamma_U2D0D0)
  GET_FIELD(_Gamma_U1D0D2)
  GET_FIELD(_Gamma_U1D1D2)
  GET_FIELD(_Gamma_U1D0D0)
  GET_FIELD(_Gamma_U1D0D1)
  GET_FIELD(_Gamma_U1D1D1)


  B[0][0] = 1;
  for (i = 1; i < Ni; ++i)
  {
    ijk = node[i];
    for (j = 0; j < Nj; ++j)
    {
      lmn = node[j];
      double dLn_of_alpha_b_U1 = 
deta_D1[ijk]/eta[ijk] - dpsi_D1[ijk]/psi[ijk];

      double dLn_of_alpha_b_U0 = 
deta_D0[ijk]/eta[ijk] - dpsi_D0[ijk]/psi[ijk];

      double dLn_of_alpha_b_U2 = 
deta_D2[ijk]/eta[ijk] - dpsi_D2[ijk]/psi[ijk];

      double dLn_of_enthalpy_b_U2 = 
denthalpy_D2[ijk]/enthalpy[ijk];

      double dLn_of_enthalpy_b_U1 = 
denthalpy_D1[ijk]/enthalpy[ijk];

      double dLn_of_enthalpy_b_U0 = 
denthalpy_D0[ijk]/enthalpy[ijk];

      double dLns0_b_U2 = 
drho0_D2[ijk] + rho0[ijk]*(dLn_of_alpha_b_U2 - dLn_of_enthalpy_b_U2);

      double dLns0_b_U0 = 
drho0_D0[ijk] + rho0[ijk]*(dLn_of_alpha_b_U0 - dLn_of_enthalpy_b_U0);

      double dLns0_b_U1 = 
drho0_D1[ijk] + rho0[ijk]*(dLn_of_alpha_b_U1 - dLn_of_enthalpy_b_U1);

      double t1_b = 
1.0*(Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U0[ijk]*dLns0_b_U0 +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U1[ijk]*dLns0_b_U1 +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U2[ijk]*dLns0_b_U2 +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U0U1[ijk]*dLns0_b_U0 +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U1U1[ijk]*dLns0_b_U1 +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U1U2[ijk]*dLns0_b_U2 +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U0U2[ijk]*dLns0_b_U0 +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U1U2[ijk]*dLns0_b_U1 +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U2U2[ijk]*dLns0_b_U2)/
pow(psi[ijk], 4);

      double t2_b = 
2.0*(Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U0[ijk]*dpsi_D0[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U1[ijk]*dpsi_D1[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U2[ijk]*dpsi_D2[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U0U1[ijk]*dpsi_D0[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U1U1[ijk]*dpsi_D1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U1U2[ijk]*dpsi_D2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U0U2[ijk]*dpsi_D0[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U1U2[ijk]*dpsi_D1[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U2U2[ijk]*dpsi_D2[ijk])/
pow(psi[ijk], 5);

      double t3_b = 
-(_gammaI_U0U0[ijk]*(-JJphi_D0D0(j_JJphi_D0D0,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D0D0[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D0D0[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D0D0[ijk]) +
2.0*_gammaI_U0U1[ijk]*(-JJphi_D0D1(j_JJphi_D0D1,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D0D1[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D0D1[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D0D1[ijk]) +
2.0*_gammaI_U0U2[ijk]*(-JJphi_D0D2(j_JJphi_D0D2,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D0D2[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D0D2[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D0D2[ijk]) +
_gammaI_U1U1[ijk]*(-JJphi_D1D1(j_JJphi_D1D1,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D1D1[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D1D1[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D1D1[ijk]) +
2.0*_gammaI_U1U2[ijk]*(-JJphi_D1D2(j_JJphi_D1D2,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D1D2[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D1D2[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D1D2[ijk]) +
_gammaI_U2U2[ijk]*(-JJphi_D2D2(j_JJphi_D2D2,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D2D2[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D2D2[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D2D2[ijk]))/
pow(psi[ijk], 4);

      double Bpart = 
rho0[ijk]*(t2_b + t3_b) + t1_b;

  B[i][j] = Bpart;

  DDM_SCHUR_JACOBIAN_EQ_Bpart_CLOSE

 if (S->NI)
 {
    E_Trans = S->E_Trans->reg->A;
    for (k = K0; k < Nk; ++k)
    {
      lmn = node[k];
      j = k-K0;
      for (i = 1; i < Ni; ++i)
      {
        ijk = node[i];
        double dLn_of_alpha_e_U0 = 
deta_D0[ijk]/eta[ijk] - dpsi_D0[ijk]/psi[ijk];

        double dLn_of_alpha_e_U1 = 
deta_D1[ijk]/eta[ijk] - dpsi_D1[ijk]/psi[ijk];

        double dLn_of_alpha_e_U2 = 
deta_D2[ijk]/eta[ijk] - dpsi_D2[ijk]/psi[ijk];

        double dLn_of_enthalpy_e_U2 = 
denthalpy_D2[ijk]/enthalpy[ijk];

        double dLn_of_enthalpy_e_U0 = 
denthalpy_D0[ijk]/enthalpy[ijk];

        double dLn_of_enthalpy_e_U1 = 
denthalpy_D1[ijk]/enthalpy[ijk];

        double dLns0_e_U2 = 
drho0_D2[ijk] + rho0[ijk]*(dLn_of_alpha_e_U2 - dLn_of_enthalpy_e_U2);

        double dLns0_e_U1 = 
drho0_D1[ijk] + rho0[ijk]*(dLn_of_alpha_e_U1 - dLn_of_enthalpy_e_U1);

        double dLns0_e_U0 = 
drho0_D0[ijk] + rho0[ijk]*(dLn_of_alpha_e_U0 - dLn_of_enthalpy_e_U0);

        double t1_e = 
1.0*(Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U0[ijk]*dLns0_e_U0 +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U1[ijk]*dLns0_e_U1 +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U2[ijk]*dLns0_e_U2 +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U0U1[ijk]*dLns0_e_U0 +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U1U1[ijk]*dLns0_e_U1 +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U1U2[ijk]*dLns0_e_U2 +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U0U2[ijk]*dLns0_e_U0 +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U1U2[ijk]*dLns0_e_U1 +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U2U2[ijk]*dLns0_e_U2)/
pow(psi[ijk], 4);

        double t2_e = 
2.0*(Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U0[ijk]*dpsi_D0[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U1[ijk]*dpsi_D1[ijk] +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_gammaI_U0U2[ijk]*dpsi_D2[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U0U1[ijk]*dpsi_D0[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U1U1[ijk]*dpsi_D1[ijk] +
Jphi_D1(j_Jphi_D1,ijk,lmn)*_gammaI_U1U2[ijk]*dpsi_D2[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U0U2[ijk]*dpsi_D0[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U1U2[ijk]*dpsi_D1[ijk] +
Jphi_D2(j_Jphi_D2,ijk,lmn)*_gammaI_U2U2[ijk]*dpsi_D2[ijk])/
pow(psi[ijk], 5);

        double t3_e = 
-(_gammaI_U0U0[ijk]*(-JJphi_D0D0(j_JJphi_D0D0,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D0D0[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D0D0[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D0D0[ijk]) +
2.0*_gammaI_U0U1[ijk]*(-JJphi_D0D1(j_JJphi_D0D1,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D0D1[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D0D1[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D0D1[ijk]) +
2.0*_gammaI_U0U2[ijk]*(-JJphi_D0D2(j_JJphi_D0D2,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D0D2[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D0D2[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D0D2[ijk]) +
_gammaI_U1U1[ijk]*(-JJphi_D1D1(j_JJphi_D1D1,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D1D1[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D1D1[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D1D1[ijk]) +
2.0*_gammaI_U1U2[ijk]*(-JJphi_D1D2(j_JJphi_D1D2,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D1D2[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D1D2[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D1D2[ijk]) +
_gammaI_U2U2[ijk]*(-JJphi_D2D2(j_JJphi_D2D2,ijk,lmn) +
Jphi_D0(j_Jphi_D0,ijk,lmn)*_Gamma_U0D2D2[ijk] + Jphi_D1(j_Jphi_D1,ijk,lmn)*
_Gamma_U1D2D2[ijk] + Jphi_D2(j_Jphi_D2,ijk,lmn)*_Gamma_U2D2D2[ijk]))/
pow(psi[ijk], 4);

        double Epart = 
rho0[ijk]*(t2_e + t3_e) + t1_e;

  E_Trans[j][i] = Epart;

  DDM_SCHUR_JACOBIAN_EQ_Epart_CLOSE

  return 0;
}
